define("Sage/UI/Forms/nls/ru/FormFromSData", {
    "addText": "Добавить",
    "deleteText": "Удалить",
    "saveText": "Сохранить",
    "cancelText": "Отмена",
    "editText": "Редактировать",
    "helpText": "Справка",
    "yesText": "Да",
    "noText": "Нет",
    "okText": "OК",
    "newPickList": "Новый список выбора",
    "items": "Элементы списка выбора",
    "number": "Заказ",
    "enterValue": "Ввести значение",
    "lblMore": "Еще",
    "picklistAlreadyExists": "Picklist \"${0}\" уже существует.",
    "messageOnSave": "Список выбора \"${0}\" сохранен. Продолжите добавление или изменение информации в поле.",
    "permissionsToView": "Отсутствуют права для просмотра.",
    "required": "Требуется вход",
    "allowMultiples": "Разрешить множественный выбор",
    "valueMustExist": "Текст должен совпадать с элементом списка",
    "alphaSorted": "Отсортировано по алфавиту",
    "noneEditable": "Пользователи не могут редактировать элементы"
});