define(
"dojo/cldr/nls/pt-pt/currency", //begin v1.x content
{
	"COP_displayName": "Peso colombiano",
	"CZK_displayName": "Coroa checa",
	"TND_displayName": "Dinar tunisino",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dólar jamaicano",
	"PHP_displayName": "Peso filipino",
	"ALL_displayName": "Lek albanês",
	"USD_symbol": "US$",
	"LBP_displayName": "Libra libanesa",
	"VND_displayName": "Dong vietnamita",
	"LYD_displayName": "Dinar líbio",
	"RON_displayName": "Leu romeno",
	"MKD_displayName": "Dinar macedónio",
	"SEK_displayName": "Coroa sueca",
	"CNY_displayName": "Yuan chinês",
	"IDR_displayName": "Rupia indonésia",
	"ILS_displayName": "Sheqel novo israelita",
	"YER_displayName": "Rial iemenita",
	"TJS_displayName": "Somoni do Tajaquistão",
	"TTD_displayName": "Dólar de Trindade e Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira turca",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham dos Emirados Árabes Unidos",
	"KZT_displayName": "Tenge do Cazaquistão",
	"BHD_displayName": "Dinar baremita",
	"RUB_displayName": "Rublo russo",
	"NZD_displayName": "Dólar neozelandês",
	"IQD_displayName": "Dinar iraquiano",
	"TMT_displayName": "Manat do Turcomenistão",
	"INR_symbol": "₹",
	"KGS_displayName": "Som do Quirguistão",
	"KWD_displayName": "Dinar kuwaitiano",
	"AFN_displayName": "Afegani do Afeganistão",
	"ARS_displayName": "Peso argentino",
	"MAD_displayName": "Dirham marroquino",
	"BAM_displayName": "Marco bósnio-herzegóvino conversível",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Dólar bruneíno",
	"SGD_displayName": "Dólar de Singapura",
	"MVR_displayName": "Rupia das Ilhas Maldivas",
	"MXN_displayName": "Peso mexicano",
	"DZD_displayName": "Dinar argelino",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar jordaniano",
	"PEN_displayName": "Novo sol peruano",
	"GTQ_displayName": "Quetzal da Guatemala",
	"BYR_displayName": "Rublo bielorusso",
	"CAD_displayName": "Dólar canadiano",
	"BZD_displayName": "Dólar belizense",
	"CLP_displayName": "Peso chileno",
	"XOF_displayName": "Franco CFA de BCEAO",
	"NOK_displayName": "Coroa norueguesa",
	"DOP_displayName": "Peso dominicano",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won sul-coreano",
	"USD_displayName": "Dólar dos Estados Unidos",
	"UYU_displayName": "Peso uruguaio",
	"UZS_displayName": "Som do Uzbequistão",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial do Qatar",
	"SAR_displayName": "Rial saudita",
	"SYP_displayName": "Libra síria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Libra egípcia",
	"AMD_displayName": "Dram arménio",
	"GBP_displayName": "Libra esterlina britânica",
	"HUF_displayName": "Forint húngaro",
	"ISK_displayName": "Coroa islandesa",
	"IRR_displayName": "Rial iraniano",
	"OMR_displayName": "Rial de Omã",
	"TWD_displayName": "Novo dólar taiwanês",
	"PAB_displayName": "Balboa panamenho",
	"UAH_displayName": "Hryvnia da Ucrânia",
	"ETB_displayName": "Birr etíope",
	"PLN_displayName": "Zloti polaco",
	"VEF_displayName": "Bolívar venezuelano",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Real brasileiro",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dólar de Hong Kong",
	"NIO_displayName": "Córdoba Ouro nicaraguano",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupia nepalesa",
	"PKR_displayName": "Rupia paquistanesa",
	"TWD_symbol": "NT$",
	"UZS_symbol": "UZS",
	"GEL_displayName": "Lari georgiano",
	"AZN_displayName": "Manat do Azerbaijão",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit malaio",
	"DKK_displayName": "Coroa dinamarquesa",
	"THB_displayName": "Baht da Tailândia",
	"BRL_symbol": "R$",
	"JPY_displayName": "Iene japonês",
	"KES_displayName": "Xelim queniano",
	"KHR_displayName": "Riel cambojano",
	"PYG_displayName": "Guarani paraguaio",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupia do Sri Lanka",
	"BGN_displayName": "Lev búlgaro",
	"BDT_displayName": "Taka de Bangladesh",
	"MOP_displayName": "Pataca de Macau",
	"HNL_displayName": "Lempira das Honduras",
	"RWF_displayName": "Franco ruandês",
	"CHF_displayName": "Franco suíço",
	"CRC_displayName": "Colon costa-riquenho",
	"INR_displayName": "Rupia indiana",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand sul-africano",
	"AUD_displayName": "Dólar australiano",
	"LAK_displayName": "Kip de Laos",
	"MNT_displayName": "Tugrik da Mongólia",
	"RSD_displayName": "Dinar sérvio",
	"HRK_displayName": "Kuna croata"
}
//end v1.x content
);