define("Sage/MainView/Contact/nls/zh-cn/ContactSearchForDuplicates", {
    "svAccount_Caption": "客户:",
    "svCompany_Caption": "公司:",
    "svEmail_Caption": "电子邮件:",
    "svName_Caption": "名称:",
    "svTitle_Caption": "标题:",
    "svType_Caption": "类型:",
    "svSubType_Caption": "子类型:",
    "svAccMgr_Caption": "客户经理:",
    "svHomePhone_Caption": "住宅电话:",
    "svWorkPhone_Caption": "单位电话:",
    "svMobilePhone_Caption": "移动电话:",
    "svStatus_Caption": "状态:",
    "svWebAddress_Caption": "网站:",
    "svEntityAccount_Caption": "客户",
    "svEntityLead_Caption": "销售线索",
    "svEntityContact_Contact": "联系人",
    "svTollFree_Caption": "免费电话:",
    "svIndustry_Caption": "行业:",
    "svDivision_Caption": "分部:",
    "svMainPhone_Caption": "主要电话:",
    "LeadSummaryView_Title": "摘要视图 - 销售线索",
    "ContactSummaryView_Title": "摘要视图 - 联系人",
    "AccountSummaryView_Title": "摘要视图 - 客户",
    "closeText": "关闭",
    "errorLoadingSummaryView": "加载摘要视图时出现错误: ${0}"
});