define(
"dojo/cldr/nls/de/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbianischer Peso",
	"CZK_displayName": "Tschechische Krone",
	"TND_displayName": "Tunesischer Dinar",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaika-Dollar",
	"PHP_displayName": "Philippinischer Peso",
	"ALL_displayName": "Albanischer Lek",
	"USD_symbol": "$",
	"LBP_displayName": "Libanesisches Pfund",
	"VND_displayName": "Vietnamesischer Dong",
	"LYD_displayName": "Libyscher Dinar",
	"RON_displayName": "Rumänischer Leu",
	"MKD_displayName": "Mazedonischer Denar",
	"SEK_displayName": "Schwedische Krone",
	"CNY_displayName": "Renminbi Yuan",
	"IDR_displayName": "Indonesische Rupiah",
	"ILS_displayName": "Israelischer Neuer Schekel",
	"YER_displayName": "Jemen-Rial",
	"TJS_displayName": "Tadschikistan-Somoni",
	"TTD_displayName": "Trinidad und Tobago-Dollar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Türkische Lira",
	"EUR_displayName": "Euro",
	"AED_displayName": "VAE-Dirham",
	"KZT_displayName": "Kasachischer Tenge",
	"BHD_displayName": "Bahrain-Dinar",
	"RUB_displayName": "Russischer Rubel",
	"NZD_displayName": "Neuseeland-Dollar",
	"IQD_displayName": "Irakischer Dinar",
	"TMT_displayName": "Turkmenistan-Manat",
	"ZWL_displayName": "Simbabwe-Dollar (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgisischer Som",
	"KWD_displayName": "Kuwait-Dinar",
	"AFN_displayName": "Afghanischer Afghani",
	"ARS_displayName": "Argentinischer Peso",
	"MAD_displayName": "Marokkanischer Dirham",
	"BAM_displayName": "Bosnien und Herzegowina Konvertierbare Mark",
	"BOB_displayName": "Bolivanischer Boliviano",
	"BND_displayName": "Brunei-Dollar",
	"SGD_displayName": "Singapur-Dollar",
	"MVR_displayName": "Malediven-Rupie",
	"MXN_displayName": "Mexikanischer Peso",
	"DZD_displayName": "Algerischer Dinar",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Jordanischer Dinar",
	"PEN_displayName": "Peruanischer Neuer Sol",
	"GTQ_displayName": "Guatemaltekischer Quetzal",
	"BYR_displayName": "Belarus-Rubel",
	"CAD_displayName": "Kanadischer Dollar",
	"BZD_displayName": "Belize-Dollar",
	"CLP_displayName": "Chilenischer Peso",
	"XOF_displayName": "CFA-Franc (BCEAO)",
	"NOK_displayName": "Norwegische Krone",
	"DOP_displayName": "Dominikanischer Peso",
	"JPY_symbol": "¥",
	"KRW_displayName": "Südkoreanischer Won",
	"USD_displayName": "US-Dollar",
	"UYU_displayName": "Uruguayischer Peso",
	"UZS_displayName": "Usbekistan-Sum",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Katar-Riyal",
	"SAR_displayName": "Saudi-Rial",
	"SYP_displayName": "Syrisches Pfund",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Ägyptisches Pfund",
	"AMD_displayName": "Armenischer Dram",
	"GBP_displayName": "Britisches Pfund Sterling",
	"HUF_displayName": "Ungarischer Forint",
	"CSD_displayName": "Serbischer Dinar (2002–2006)",
	"ISK_displayName": "Isländische Krone",
	"IRR_displayName": "Iranischer Rial",
	"OMR_displayName": "Omanischer Rial",
	"TWD_displayName": "Neuer Taiwan-Dollar",
	"PAB_displayName": "Panamaischer Balboa",
	"UAH_displayName": "Ukrainische Hrywnja",
	"ETB_displayName": "Äthiopischer Birr",
	"PLN_displayName": "Polnischer Złoty",
	"VEF_displayName": "Venezolanischer Bolívar",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Brasilianischer Real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hongkong-Dollar",
	"NIO_displayName": "Nicaragua-Cordoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepalesische Rupie",
	"PKR_displayName": "Pakistanische Rupie",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Georgischer Lari",
	"AZN_displayName": "Aserbaidschan-Manat",
	"GBP_symbol": "£",
	"MYR_displayName": "Malaysischer Ringgit",
	"DKK_displayName": "Dänische Krone",
	"THB_displayName": "Thailändischer Baht",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japanischer Yen",
	"KES_displayName": "Kenia-Schilling",
	"KHR_displayName": "Kambodschanischer Riel",
	"PYG_displayName": "Paraguayischer Guaraní",
	"VND_symbol": "₫",
	"LKR_displayName": "Sri-Lanka-Rupie",
	"BGN_displayName": "Bulgarischer Lew",
	"BDT_displayName": "Bangladesch-Taka",
	"MOP_displayName": "Macao-Pataca",
	"HNL_displayName": "Honduras-Lempira",
	"RWF_displayName": "Ruanda-Franc",
	"CHF_displayName": "Schweizer Franken",
	"CRC_displayName": "Costa-Rica-Colón",
	"INR_displayName": "Indische Rupie",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Südafrikanischer Rand",
	"AUD_displayName": "Australischer Dollar",
	"LAK_displayName": "Laotischer Kip",
	"MNT_displayName": "Mongolischer Tögrög",
	"RSD_displayName": "Serbischer Dinar",
	"HRK_displayName": "Kroatischer Kuna"
}
//end v1.x content
);