define(
"dojo/cldr/nls/bn/currency", //begin v1.x content
{
	"COP_displayName": "কলোম্বিয়ান পেসো",
	"CZK_displayName": "চেকোস্লোভাক কোরুনা",
	"TND_displayName": "তিউনেশিয়ান দিনার",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "জ্যামাইকান ডলার",
	"PHP_displayName": "ফিলিপাইন পেসো",
	"ALL_displayName": "আলবেনিয়ান লেক",
	"USD_symbol": "US$",
	"LBP_displayName": "লেবানিজ পাউন্ড",
	"VND_displayName": "ভিয়েতনামি ডঙ্গ",
	"LYD_displayName": "লিবিয়ান ডলার",
	"RON_displayName": "রুমানিয়া লেয়ু",
	"MKD_displayName": "ম্যাসেডোনিয়ান দিনার",
	"SEK_displayName": "সুইডিশ ক্রোনা",
	"CNY_displayName": "চীনা য়ুয়ান রেন্মিন্বি",
	"IDR_displayName": "ইন্দোনেশিয়ান রুপিয়াহ",
	"ILS_displayName": "ইস্রাইলি নতুন শেকেল",
	"YER_displayName": "ইয়েমেনি রিয়াল",
	"TJS_displayName": "তাজিকিস্তান সোমোনি",
	"TTD_displayName": "ত্রিনিদাদ এবং টোবাগো ডলার",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "তুর্কি লিরা",
	"EUR_displayName": "ইউরো",
	"AED_displayName": "সংযুক্ত আরব আমিরাত দিরহাম",
	"KZT_displayName": "কাজাক্সটান টেঙ্গে",
	"BHD_displayName": "বাহরাইনি দিনার",
	"RUB_displayName": "রাশিয়ান রুবেল",
	"NZD_displayName": "নিউজিল্যান্ড ডলার",
	"IQD_displayName": "ইরাকি দিনার",
	"TMT_displayName": "তুর্কমেনিস্তান নতুন মানত",
	"ZWL_displayName": "জিম্বাবুয়ে ডলার (২০০৯)",
	"INR_symbol": "₹",
	"KGS_displayName": "কিরগিজস্তান সোম",
	"KWD_displayName": "কুয়েতি দিনার",
	"AFN_displayName": "আফগানি",
	"ARS_displayName": "আর্জেন্টিনা পেসো",
	"MAD_displayName": "মোরোক্কান দিরহাম",
	"BAM_displayName": "বসনিয়া এবং হার্জেগোভিনা মার্ক",
	"BOB_displayName": "বলিভিয়ানো",
	"BND_displayName": "ব্রুনেই ডলার",
	"SGD_displayName": "সিঙ্গাপুর ডলার",
	"MVR_displayName": "মালদিভিয়ান রুফিয়া",
	"MXN_displayName": "ম্যাক্সিকান পেসো",
	"DZD_displayName": "আলজেরীয় দিনার",
	"MXN_symbol": "MX$",
	"JOD_displayName": "জর্ডানিয়ান দিনার",
	"PEN_displayName": "পেরুভিয়ান সোল নুয়েভো",
	"GTQ_displayName": "গুয়াতেমালা কুয়েৎজাল",
	"BYR_displayName": "বেলারুশিয়ান রুবেল",
	"CAD_displayName": "কানাডিয়ান ডলার",
	"BZD_displayName": "বেলিজ ডলার",
	"CLP_displayName": "চিলি পেসো",
	"XOF_displayName": "সিএফএ ফ্র্যাঙ্ক বিসিইএও",
	"NOK_displayName": "নরওয়ে ক্রৌন",
	"DOP_displayName": "ডোমিনিকান পেসো",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "দক্ষিণ কোরিয়ান ওন",
	"USD_displayName": "মার্কিন ডলার",
	"UYU_displayName": "উরুগুয়ে পেসো",
	"UZS_displayName": "উজবেকিস্তানি সোম",
	"XOF_symbol": "CFA",
	"QAR_displayName": "কাতার রিয়্যাল",
	"SAR_displayName": "সৌদি রিয়্যাল",
	"SYP_displayName": "সিরিয়ান পাউন্ড",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "মিশরীয় পাউন্ড",
	"AMD_displayName": "আরমেনিয়ান দ্রাম",
	"GBP_displayName": "ব্রিটিশ পাউন্ড স্টার্লিং",
	"HUF_displayName": "হাঙ্গেরিয়ান ফোরিন্ট",
	"CSD_displayName": "প্রাচীন সারবিয়ান দিনার",
	"ISK_displayName": "আইসল্যান্ড ক্রৌন",
	"IRR_displayName": "ইরানিয়ান রিয়াল",
	"OMR_displayName": "ওমানি রিয়াল",
	"TWD_displayName": "নূতন তাইওয়ান ক্যারাবিয়ান ডলার",
	"BDT_symbol": "৳",
	"PAB_displayName": "পানামা বেলবোয়া",
	"UAH_displayName": "ইউক্রেইন হৃভনিয়া",
	"ETB_displayName": "ইথিওপিয়ান বির",
	"PLN_displayName": "পোলিশ জ্লোটি",
	"VEF_displayName": "ভেনিজুয়েলীয় বলিভার",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ব্রাজিলিয়ান রিয়েল",
	"HKD_symbol": "HK$",
	"HKD_displayName": "হংকং ডলার",
	"NIO_displayName": "নিকারাগুয়ান কর্ডোবা",
	"THB_symbol": "฿",
	"NPR_displayName": "নেপালি রুপি",
	"PKR_displayName": "পাকিস্তানি রুপি",
	"TWD_symbol": "NT$",
	"GEL_displayName": "জর্জিয়ান লারি",
	"AZN_displayName": "আজারবাইজান মানাত",
	"GBP_symbol": "£",
	"MYR_displayName": "মালয়েশিয়ান রিঙ্গিৎ",
	"DKK_displayName": "ড্যানিশ ক্রৌন",
	"THB_displayName": "থাই বাত",
	"BRL_symbol": "R$",
	"JPY_displayName": "জাপানিজ ইয়েন",
	"KES_displayName": "কেনিয়ান শিলিং",
	"KHR_displayName": "কম্বোডিয়ান রিয়েল",
	"PYG_displayName": "প্যারগুয়ান",
	"VND_symbol": "₫",
	"LKR_displayName": "শ্রীলঙ্কান রুপি",
	"BGN_displayName": "বুলগেরীয় নিউ লেভ",
	"BDT_displayName": "বাংলাদেশী টাকা",
	"HNL_displayName": "হন্ডুরাস লেম্পিরা",
	"MOP_displayName": "ম্যাক্যাও পাটাকা",
	"RWF_displayName": "রুয়ান্ডান ফ্রাঙ্ক",
	"CHF_displayName": "সুইস ফ্রাঙ্ক",
	"CRC_displayName": "কোস্টা রিকা কোলোন",
	"INR_displayName": "ভারতীয় রুপি",
	"KRW_symbol": "₩",
	"ZAR_displayName": "দক্ষিণ আফ্রিকান রেন্ড",
	"AUD_displayName": "অস্ট্রেলিয়ান ডলার",
	"LAK_displayName": "লেউশান কিপ",
	"MNT_displayName": "মঙ্গোলিয়ান তুগরিক",
	"RSD_displayName": "সারবিয়ান দিনার",
	"HRK_displayName": "ক্রোয়েশিয়ান কুনা"
}
//end v1.x content
);