define("Sage/Groups/nls/it/GroupManager", {
    "ConfirmDeleteMessage": "Eliminare il gruppo corrente?",
    "ConfirmDeleteFmtMessage": "Eliminare il gruppo ${0}?",
    "InvalidSortStringMessage": "Errore: stringa ordinamento non valida- ",
    "InvalidConditionStringMessage": "Errore: stringa condizione non valida - ",
    "InvalidLayoutConditionStringMessage": "Errore: stringa layout non valida - ",
    "noneSelectedTitle": "Nessun record selezionato",
    "noneSelectedPromptFmt": "Nessun record selezionato. Sarà aggiunto l'intero gruppo, ${0} record. Continuare?",
    "noneSelectedRemovePromptFmt": "Nessun record selezionato. Sarà rimosso l'intero gruppo, ${0} record. Continuare?",
    "noRecordsInGroup": "Non ci sono record che devono essere selezionati da questo gruppo.",
    "newGroupTitle": "Aggiungi record al nuovo gruppo",
    "newGroupNamePrompt": "${0} il record selezionato verrà aggiunto a questo nuovo gruppo.<br><br>Nome gruppo:<br>${1}",
    "newGroupRePrompt": "&nbsp;&nbsp;<i>Inserire un nome di gruppo.</i>",
    "invalidCharMsg": "Il nome non può contenere: / \\ : * ? \" <> | o '",
    "groupNameText": "Nome gruppo:",
    "saveLookupDlgTitle": "Salva risultati ricerca come nuovo gruppo",
    "yesCaption": "Sì",
    "noCaption": "No",
    "cancelCaption": "Annulla",
    "okCaption": "OK",
    "LOCALSTORE_NAMESPACE": "SageGroups",
    "exportToExcel": "Questo metodo non è più utilizzato, vedere Sage.TaskPane.CommonTasksTasklet.exportToExcel.",
    "createAdHocGroupJob_Description": "Gruppo: ${0}",
    "createAdHocGroupJob_Title": "Creazione in corso",
    "createAdHocGroupJobError": "Si è verificato un errore durante la creazione del gruppo: ${0}",
    "createAdHocGroupJobProcessingJobMsg": "È possibile attendere il completamento o chiudere la finestra del messaggio. Una volta completato il gruppo, l'utente riceverà una notifica."
});