define(
"dojo/cldr/nls/he/currency", //begin v1.x content
{
	"COP_displayName": "פזו קולומביאני",
	"CZK_displayName": "קורונה צ׳כית",
	"TND_displayName": "דינר טוניסאי",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "דולר ג׳מאיקני",
	"PHP_displayName": "פזו פיליפיני",
	"ALL_displayName": "לק אלבני",
	"USD_symbol": "US$",
	"LBP_displayName": "לירה לבנונית",
	"VND_displayName": "דונג וייטנאמי",
	"LYD_displayName": "דינר לובי",
	"RON_displayName": "לאו רומני חדש",
	"MKD_displayName": "דינר מקדוני",
	"SEK_displayName": "כתר שוודי",
	"CNY_displayName": "יואן רנמינבי סיני",
	"IDR_displayName": "רופיה אינדונזית",
	"ILS_displayName": "ש״ח",
	"YER_displayName": "ריאל תימני",
	"TJS_displayName": "סומוני טג׳קיסטני",
	"TTD_displayName": "דולר טרינידדי",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "לירה טורקית חדשה",
	"EUR_displayName": "אירו",
	"AED_displayName": "דירהם של איחוד הנסיכויות הערביות",
	"KZT_displayName": "טנגה קזחסטני",
	"BHD_displayName": "דינר בחרייני",
	"RUB_displayName": "רובל",
	"NZD_displayName": "דולר ניו זילנדי",
	"IQD_displayName": "דינר עירקי",
	"TMT_displayName": "מנאט טורקמני",
	"INR_symbol": "₹",
	"KGS_displayName": "סום קירגיזי",
	"KWD_displayName": "דינר כוויתי",
	"AFN_displayName": "אפגני אפגני",
	"ARS_displayName": "פזו ארגנטינאי",
	"MAD_displayName": "דירהם מרוקאי",
	"BAM_displayName": "מארק בר המרה של בוסניה־הרצגובינה",
	"BOB_displayName": "בוליביאנו",
	"BND_displayName": "דולר ברוניי",
	"SGD_displayName": "דולר סינגפורי",
	"MVR_displayName": "רופיה מלדיבית",
	"MXN_displayName": "פזו מקסיקני",
	"DZD_displayName": "דינר אלג׳ירי",
	"MXN_symbol": "MX$",
	"JOD_displayName": "דינר ירדני",
	"PEN_displayName": "סול פרואני חדש",
	"GTQ_displayName": "קצל גואטמלי",
	"BYR_displayName": "רובל בלרוסי",
	"CAD_displayName": "דולר קנדי",
	"BZD_displayName": "דולר בליזי",
	"CLP_displayName": "פזו צ׳ילאני",
	"XOF_displayName": "פרנק CFA BCEAO",
	"NOK_displayName": "כתר נורבגי",
	"DOP_displayName": "פזו דומיניקני",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "וון דרום קוראני",
	"USD_displayName": "דולר אמריקאי",
	"UYU_displayName": "פזו אורוגוואי",
	"UZS_displayName": "סום אוזבקי",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ריאל קטארי",
	"SAR_displayName": "ריאל סעודי",
	"SYP_displayName": "לירה סורית",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "לירה מיצרית",
	"AMD_displayName": "דראם ארמני",
	"GBP_displayName": "לירה שטרלינג",
	"HUF_displayName": "פורינט הונגרי",
	"CSD_displayName": "דינר סרבי ישן",
	"ISK_displayName": "קרונה איסלנדית",
	"IRR_displayName": "ריאל איראני",
	"OMR_displayName": "ריאל עומאני",
	"TWD_displayName": "דולר טייוואני חדש",
	"PAB_displayName": "בלבואה פנמי",
	"UAH_displayName": "גריבנה אוקראיני",
	"ETB_displayName": "ביר אתיופי",
	"PLN_displayName": "זלוטי פולני",
	"VEF_displayName": "בוליבר ונצואלי",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ריאל ברזילאי",
	"HKD_symbol": "HK$",
	"HKD_displayName": "דולר הונג קונגי",
	"NIO_displayName": "קורדובה ניקראגי",
	"THB_symbol": "฿",
	"NPR_displayName": "רופי נפאלי",
	"PKR_displayName": "רופי פקיסטני",
	"TWD_symbol": "NT$",
	"GEL_displayName": "לרי גאורגי",
	"AZN_displayName": "מאנאט אזרביג׳ני",
	"GBP_symbol": "£",
	"MYR_displayName": "רינגיט מלזי",
	"DKK_displayName": "כתר דני",
	"THB_displayName": "בהט תאילנדי",
	"BRL_symbol": "R$",
	"JPY_displayName": "ין יפני",
	"KES_displayName": "שילינג קנייאתי",
	"KHR_displayName": "ריל קמבודי",
	"PYG_displayName": "גוורני פראגוואי",
	"VND_symbol": "₫",
	"LKR_displayName": "רופי סרי לנקי",
	"BGN_displayName": "לב בולגרי",
	"BDT_displayName": "טאקה בנגלדשי",
	"MOP_displayName": "פטקה של מקאו",
	"HNL_displayName": "למפירה הונדורי",
	"RWF_displayName": "פרנק רואנדי",
	"CHF_displayName": "פרנק שוויצרי",
	"CRC_displayName": "קולון קוסטה־ריקני",
	"INR_displayName": "רופי הודית",
	"KRW_symbol": "₩",
	"ZAR_displayName": "ראנד דרום אפריקאי",
	"AUD_displayName": "דולר אוסטרלי",
	"LAK_displayName": "קיפ לאי",
	"MNT_displayName": "טוגריק מונגולי",
	"RSD_displayName": "דינר סרבי",
	"HRK_displayName": "קונה קרואטי"
}
//end v1.x content
);