define(
"dojo/cldr/nls/gl/currency", //begin v1.x content
{
	"COP_displayName": "Peso colombiano",
	"CZK_displayName": "Coroa checa",
	"TND_displayName": "Dinar tunesino",
	"EUR_symbol": "€",
	"CAD_symbol": "$CA",
	"JMD_displayName": "Dólar xamaicano",
	"PHP_displayName": "Peso filipino",
	"ALL_displayName": "Lek albanés",
	"USD_symbol": "$",
	"LBP_displayName": "Libra libanesa",
	"VND_displayName": "Dong vietnamita",
	"LYD_displayName": "Dinar libio",
	"RON_displayName": "Leu romanés",
	"MKD_displayName": "Dinar macedonio",
	"SEK_displayName": "Coroa sueca",
	"CNY_displayName": "Iuán chinés",
	"IDR_displayName": "Rupia indonesia",
	"ILS_displayName": "Novo shequel israelí",
	"YER_displayName": "Rial iemení",
	"TJS_displayName": "Somoni taxico",
	"TTD_displayName": "Dólar de Trinidade e Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira turca",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham dos Emiratos Árabes Unidos",
	"KZT_displayName": "Tenge casaco",
	"BHD_displayName": "Dinar de Baréin",
	"RUB_displayName": "Rublo ruso",
	"NZD_displayName": "Dólar neozelandés",
	"IQD_displayName": "Dinar iraquí",
	"TMT_displayName": "Manat turcomano",
	"INR_symbol": "₹",
	"KGS_displayName": "Som quirguizo",
	"KWD_displayName": "Dinar kuwaití",
	"AFN_displayName": "Afgani afgano",
	"ARS_displayName": "Peso arxentino",
	"MAD_displayName": "Dirham marroquí",
	"BAM_displayName": "Marco convertible de Bosnia e Hercegovina",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Dólar de Brunei",
	"SGD_displayName": "Dólar de Singapur",
	"MVR_displayName": "Rupia maldiva",
	"MXN_displayName": "Peso mexicano",
	"MXN_symbol": "$MX",
	"DZD_displayName": "Dinar alxeriano",
	"JOD_displayName": "Dinar xordano",
	"PEN_displayName": "Sol novo peruano",
	"GTQ_displayName": "Quetzal guatemalteco",
	"BYR_displayName": "Rublo bielorruso",
	"CAD_displayName": "Dólar canadiano",
	"BZD_displayName": "Dólar beliceño",
	"CLP_displayName": "Peso chileno",
	"XOF_displayName": "Franco CFA BCEAO",
	"NOK_displayName": "Coroa norueguesa",
	"DOP_displayName": "Peso dominicano",
	"JPY_symbol": "¥JP",
	"KRW_displayName": "Won surcoreano",
	"USD_displayName": "Dólar estadounidense",
	"UYU_displayName": "Peso uruguaio",
	"UZS_displayName": "Som usbeco",
	"QAR_displayName": "Rial qatarí",
	"SAR_displayName": "Rial saudita",
	"SYP_displayName": "Libra siria",
	"EGP_displayName": "Libra exipcia",
	"AMD_displayName": "Dram armenio",
	"GBP_displayName": "Libra esterlina",
	"HUF_displayName": "Florín húngaro",
	"ISK_displayName": "Coroa islandesa",
	"IRR_displayName": "Rial iraniano",
	"OMR_displayName": "Rial omaní",
	"TWD_displayName": "Novo dólar taiwanés",
	"PAB_displayName": "Balboa panameño",
	"UAH_displayName": "Grivna ucraína",
	"ETB_displayName": "Birr etíope",
	"PLN_displayName": "Zloty polaco",
	"VEF_displayName": "Bolívar venezolano",
	"BRL_displayName": "Real brasileiro",
	"HKD_symbol": "$HK",
	"HKD_displayName": "Dólar de Hong Kong",
	"NIO_displayName": "Córdoba de ouro nicaragüense",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupia nepalesa",
	"PKR_displayName": "Rupia paquistaní",
	"GEL_displayName": "Lari xeorxiano",
	"AZN_displayName": "Manat acerbaixano",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit malaio",
	"DKK_displayName": "Coroa dinamarquesa",
	"THB_displayName": "Baht tailandés",
	"JPY_displayName": "Ien xaponés",
	"KES_displayName": "Chelín kenyano",
	"KHR_displayName": "Riel camboxano",
	"PYG_displayName": "Guaraní paraguaio",
	"LKR_displayName": "Rupia de Sri Lanka",
	"BGN_displayName": "Lev búlgaro",
	"BDT_displayName": "Taka de Bangladesh",
	"MOP_displayName": "Pataca de Macau",
	"HNL_displayName": "Lempira hondureño",
	"RWF_displayName": "Franco ruandés",
	"CHF_displayName": "Franco suízo",
	"CRC_displayName": "Colón costarricense",
	"INR_displayName": "Rupia india",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand sudafricano",
	"AUD_displayName": "Dólar australiano",
	"LAK_displayName": "Kip laosiano",
	"MNT_displayName": "Tugrik mongol",
	"RSD_displayName": "Dinar serbio",
	"HRK_displayName": "Kuna croata"
}
//end v1.x content
);