define("Sage/MainView/ActivityMgr/nls/it/RecurringEditor", {
    "activityOccurrsText": "Questa attività ricorre...",
    "onceText": "Una volta",
    "dailyText": "Ogni giorno",
    "weeklyText": "Ogni settimana",
    "monthlyText": "Ogni mese",
    "yearlyText": "Ogni anno",
    "occursOnceText": "Questa attività si verifica solo una volta",
    "everyText": "Ogni",
    "daysText": "Giorno/i",
    "daysAfterText": "Giorno/i dopo il completamento",
    "startRecurringText": "Inizio ricorrenza: ",
    "endAfterText": "Termina dopo",
    "endOnText": "Fine ricorrenza:",
    "occurrencesText": "occorrenze",
    "weeksOnText": "Settimana/e il:",
    "monText": "Lunedì",
    "tueText": "Martedì",
    "wedText": "Mercoledì",
    "thurText": "Giovedì",
    "friText": "Venerdì",
    "satText": "Sabato",
    "sunText": "Domenica",
    "weeksAfterText": "Settimana/e dopo il completamento",
    "monthsOnText": "Giorno del/dei mese/i",
    "monthsOnTheText": "Mese/i il",
    "monthsAfterText": "Mese/i dopo completamento",
    "firstText": "1°",
    "secondText": "2°",
    "thirdText": "3°",
    "fourthText": "4°",
    "lastText": "ultimo",
    "yearsOnText": "Anno/i il",
    "yearsAfterText": "Anno/i dopo il completamento",
    "janText": "Gennaio",
    "febText": "Febbraio",
    "marText": "Marzo",
    "aprText": "Aprile",
    "mayText": "Maggio",
    "junText": "Giugno",
    "julText": "Luglio",
    "augText": "Agosto",
    "sepText": "Settembre",
    "octText": "Ottobre",
    "novText": "Novembre",
    "decText": "Dicembre",
    "theText": "Il",
    "inText": "in"
});