define("Sage/MainView/Contact/nls/it/ContactSearchForDuplicates", {
    "svAccount_Caption": "Azienda:",
    "svCompany_Caption": "Società:",
    "svEmail_Caption": "E-mail:",
    "svName_Caption": "Nome:",
    "svTitle_Caption": "Titolo:",
    "svType_Caption": "Tipo:",
    "svSubType_Caption": "Sottotipo",
    "svAccMgr_Caption": "Acct mgr:",
    "svHomePhone_Caption": "Telefono abitazione:",
    "svWorkPhone_Caption": "Telefono ufficio:",
    "svMobilePhone_Caption": "Cellulare:",
    "svStatus_Caption": "Stato:",
    "svWebAddress_Caption": "Web:",
    "svEntityAccount_Caption": "Azienda",
    "svEntityLead_Caption": "Lead",
    "svEntityContact_Contact": "Contatto",
    "svTollFree_Caption": "Numero verde:",
    "svIndustry_Caption": "Settore:",
    "svDivision_Caption": "Divisione:",
    "svMainPhone_Caption": "Telefono principale:",
    "LeadSummaryView_Title": "Vista di riepilogo - Lead",
    "ContactSummaryView_Title": "Vista di riepilogo - Contatto",
    "AccountSummaryView_Title": "Vista di riepilogo - Azienda",
    "closeText": "Chiudi",
    "errorLoadingSummaryView": "Si è verificato un errore durante il caricamento della vista di riepilogo: ${0}"
});