define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/en/AddEditDialog", {
        // Add/Edit labels
        lblFilter: "Filter",
        lblMetric: "Metric",
        lblFilters: "Filters",
        lblMetrics: "Metrics",
        lblDistinct: "Distinct",
        lblRange: "Range",
        lblUserLookup: "User Lookup",
        lblAdd: "Add",
        lblEdit: "Edit",
        lblRemove: "Remove",
        lblHelp: 'Help',
        lblFilterName: "Filter Name",
        lblMetricName: "Metric Name",
        lblDisplayName: "Display Name",
        lblName: "Name",
        lblDisplay: "Display",
        lblCalculated: "Calculated",
        lblCalculation: "Calculation",
        lblDescription: "Description",
        lblFieldsName: "Fields Name",
        lblCalculatedFieldsName: "Calculated Fields Name",
        lblFilterDp: "Fields",
        lblTypeDp: "Type",
        lblCharacter: "Characters",
        lblFrom: "From",
        lblTo: "To",
        lblOperators: "Operators",
        lblAggregation: "Aggregations",
        lblTypeSpecificContentBox: "Type Specific Content Box",
        lblSaveButton: "OK",
        lblCancelButton: "Cancel",
        DateDiffCheckerValue: "Date Difference Metric",
        InvalidFilterName: "Invalid filter name",
        InvalidRangeName: "Invalid range name",
        RequiredFilterName: "Filter name is required",
        RequiredRangeName: "Range name is required",
        FieldMustBeANumber: "Character field must be integer",
        SelectAnItem: "Please select an item",
        ItemRequired: "Item required",
        ItemInvalid: "Item invalid",
        LowerMustBeLessThanUpper: "Lower value must be less than upper value.",
        InvalidSpecialDateValue: "Invalid special date placeholder value.",
        defaultRangeRowValue: "Enter a value",
        totalRecordCountLabel: "Total Records: ${0}",
        lblNew: "New",
        lblExisting: "Existing",
        lblExistingCalc: "Existing Calculated Field",
        validNameMsg: "A valid entry starts with a capital letter and <br> can contain alphanumeric values and underscores.",
      
    propertyName: 'Name',
    displayName: 'Display',
    dataTypeId: 'Type',
    dataTypeData: 'Type Attributes',
    length: 'Length',
    scale: 'Scale',
    precision: 'Precision',
    isIncluded: 'Included',
    isReadOnly: 'Read Only',
    displayCategory: 'Display Category',
    sdata: 'Sdata',
    bulkAction: 'Bulk Action',
    canBulkUpdate: 'Can Bulk Update',
    canImport: 'Import',
    canMatch: 'Match',
    generate: 'Generate',
    audited: 'Audited',
    //errors
    notUniqueFor: 'is not unique for',
    notUnique: 'is not unique',
    nlsCode: 'NLS Code',
    nlsName: 'NLS Name',
    showTranslations: 'Show translations',
    hideTranslations: 'Hide translations',
    standardIds: 'Standard Ids',
    others: 'Others',
    SelectField: 'Please select a field !',
    SelectOneField: 'Please select only one field !',
    parent: 'Parent Entity and Join Field',
    child: 'Child Entity and Join Field',
    cardinality: 'Relationship',
    cascade: 'Cascade',
    includeParent: 'Include parent relationship property in the child entity',
    includeChild: 'Include child relationship property in the parent entity',
    existingRelaton: 'This relationship already exists !'
   
});