define("Sage/MainView/EntityMgr/EntityWizard/nls/fr/_EntityWizardDialog", {
    "lblNewEntityWizard": "Assistant Nouvelle entité",
    "lblCreateEntity": "Créer une entité",
    "lblCreateEntityFromTable": "Créer une nouvelle entité à partir d'une table",
    "lblEntityName": "Nom",
    "lblDisplayName": "Affichage",
    "lblPackage": "Package",
    "lblEntityUsed": "Le nom de l'entité est déjà utilisé !",
    "lblNext": "Suivant",
    "lblCancel": "Annuler",
    "lblBack": "Précédent",
    "lblEnterProperties": "Entrer des champs",
    "lblAddNewProperty": "Cliquez sur le bouton ajouter (+) pour ajouter de nouveaux champs à l'entité",
    "lblPropertyName": "Nom du champ",
    "lblDataType": "Type de données",
    "lblLength": "Longueur",
    "lblSure": "Etes-vous sûr ?",
    "lblThisStepCreateEntity": "L'exécution de cette étape permet de créer des entités et le schéma nécessaire",
    "lblEntity": "Entité",
    "lblProperties": "Champs",
    "lblStatus": "Etat",
    "lblSuccess": "Opération réussie",
    "lblSuccessMsg": "Opération réussie, entité créée avec succès.",
    "lblError": "Erreur",
    "lblFailed": "Echec",
    "lblErrorMsg": "Erreur, échec de la création de l'entité !",
    "lblFinish": "Terminer",
    "lblInvalidEntry": "Pour être valide, l'entrée doit commencer par une lettre majuscule. Elle peut contenir des valeurs alphanumériques et des traits de soulignement.",
    "lblRequired": "Obligatoire",
    "lblErrorRelation": "Erreur lors de la création de relation avec",
    "lblRelationship": "Relation principale",
    "lblSelectEntity": "Sélectionnez si cette entité a une relation principale avec une autre entité",
    "lblExistingEntity": "Lier à une entité existante",
    "lblRelatedEntity": "Entité liée",
    "lblRelationType": "Type lié",
    "addFieldDialogTitle": "Ajouter un champ",
    "editFieldDialogTitle": "Modifier le champ",
    "noDeleteSysProps": "Impossible de supprimer les propriétés système",
    "noEditSysProps": "Impossible de modifier les propriétés système",
    "NoRecordsSelected": "Aucun enregistrement n'est sélectionné.",
    "lblNullable": "Est nullable",
    "CreateUser": "Créé par",
    "CreateDate": "Date de création",
    "ModifyUser": "Modifié par",
    "ModifyDate": "Date de modification"
});