define("Sage/UI/nls/BulkUpdateWidget", {
    root: {
        dlgBulkActionUpdate_Title: 'Bulk Action Update',
        pageLoading_Caption: 'Loading property options...',
        header_Caption: 'Select a property you would like to update.',
        header_NoPropertiesEnabled: 'The ${0} entity is enabled for bulk updates, however, there are no properties that have been enabled. Please contact your system administrator for more information',
        errorRequestPropertyOptions: 'An error occurred reading meta data for ${0} entity. ${1}',
        errorEntityNotSupported: "The ${0} entity does not support bulk updates",
        update_Property_Caption: 'Update:',
        addProperty_Tooltip: 'Add Property',
        removeProperty_Tooltip: 'Remove Property',
        no_Caption: 'No',
        yes_Caption: 'Yes',
        days_Caption: 'days',
        moveOut_Caption: 'Move',
        moveTo_Caption: 'To',
        moveDate_Backward: 'Backward',
        moveDate_Forward: 'Forward',
        update_To_Caption: 'To:',
        lookupHeaderText: 'Lookup ${0}',
        lookupNameColText: 'Name',
        lookupTitleColText: 'Title',
        lookupDepartmentColText: 'Department',
        lookupRegionColText: 'Region',
        lookupTypeColText: 'Type',
        lookupDescriptionColText: 'Description',
        btnOK_Caption: 'OK',
        btnCancel_Caption: 'Cancel',
        errorUnspecifiedValue: 'Please specify a value before continuing or remove the invalid row.',
        errorRequestingJobMgr: 'An error occurred performing update: ${0}',
        selectOption_Caption: 'Select an option...',
        updateRecords_Caption: 'Updating Selected Records',
        chkScheduleJob_Caption: 'Schedule this update to occur at a specific date/time.',
        lookup_Caption: 'Lookup',
        job_Description: 'Bulk Update Error(s) Occurred',
        errorDuplicateValue: 'Property already selected',
        errorInvalidPropertyType: 'Property type \'${0}\' is not supported for bulk updates.',
        calculatedField: 'Calculated Field',
        standardId: 'Standard Id',
        unknownPropertyType: 'Unknown'
    },
    "de": true,
    "en": true,
    "fr": true,
    "it": true,
    "ru": true
});
