define(
"dojo/cldr/nls/it/currency", //begin v1.x content
{
	"COP_displayName": "Peso Colombiano",
	"CZK_displayName": "Corona Ceca",
	"TND_displayName": "Dinaro Tunisino",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dollaro Giamaicano",
	"PHP_displayName": "Peso delle Filippine",
	"ALL_displayName": "Lek Albanese",
	"USD_symbol": "US$",
	"LBP_displayName": "Sterlina Libanese",
	"VND_displayName": "Dong Vietnamita",
	"LYD_displayName": "Dinaro Libico",
	"RON_displayName": "Leu Rumeno",
	"MKD_displayName": "Dinaro Macedone",
	"SEK_displayName": "Corona Svedese",
	"CNY_displayName": "Renmimbi Cinese",
	"IDR_displayName": "Rupia Indonesiana",
	"ILS_displayName": "Nuovo Shequel Israeliano",
	"YER_displayName": "Rial dello Yemen",
	"TJS_displayName": "Somoni del Tajikistan",
	"TTD_displayName": "Dollaro di Trinidad e Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Nuova Lira Turca",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham degli Emirati Arabi Uniti",
	"KZT_displayName": "Tenge Kazaco",
	"BHD_displayName": "Dinaro del Bahraini",
	"RUB_displayName": "Rublo Russo",
	"NZD_displayName": "Dollaro Neozelandese",
	"IQD_displayName": "Dinaro Iracheno",
	"TMT_displayName": "Manat Turkmeno",
	"ZWL_displayName": "Dollaro Zimbabwiano (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Som Kirghiso",
	"KWD_displayName": "Dinaro Kuwaitiano",
	"AFN_displayName": "Afghani",
	"ARS_displayName": "Peso Argentino",
	"MAD_displayName": "Dirham Marocchino",
	"BAM_displayName": "Marco Conv. Bosnia-Erzegovina",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Dollaro del Brunei",
	"SGD_displayName": "Dollaro di Singapore",
	"MVR_displayName": "Rufiyaa delle Maldive",
	"MXN_displayName": "Peso Messicano",
	"DZD_displayName": "Dinaro Algerino",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinaro Giordano",
	"PEN_displayName": "Sol Nuevo Peruviano",
	"GTQ_displayName": "Quetzal Guatemalteco",
	"BYR_displayName": "Rublo Bielorussia",
	"CAD_displayName": "Dollaro Canadese",
	"BZD_displayName": "Dollaro del Belize",
	"CLP_displayName": "Peso Cileno",
	"XOF_displayName": "Franco CFA BCEAO",
	"NOK_displayName": "Corona Norvegese",
	"DOP_displayName": "Peso Dominicano",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won Sudcoreano",
	"USD_displayName": "Dollaro Statunitense",
	"UYU_displayName": "Peso Uruguaiano",
	"UZS_displayName": "Sum dell’Uzbekistan",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial del Qatar",
	"SAR_displayName": "Ryal Saudita",
	"SYP_displayName": "Sterlina Siriana",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Sterlina Egiziana",
	"AMD_displayName": "Dram Armeno",
	"GBP_displayName": "Sterlina Inglese",
	"HUF_displayName": "Fiorino Ungherese",
	"CSD_displayName": "Antico Dinaro Serbo",
	"ISK_displayName": "Corona Islandese",
	"IRR_displayName": "Rial Iraniano",
	"OMR_displayName": "Rial dell'Oman",
	"TWD_displayName": "Nuovo dollaro taiwanese",
	"PAB_displayName": "Balboa di Panama",
	"UAH_displayName": "Grivnia Ucraina",
	"ETB_displayName": "Birr Etiopico",
	"PLN_displayName": "Zloty Polacco",
	"VEF_displayName": "Bolívar Venezuelano",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Real Brasiliano",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dollaro di Hong Kong",
	"NIO_displayName": "Córdoba Nicaraguense",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupia Nepalese",
	"PKR_displayName": "Rupia del Pakistan",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari Georgiano",
	"AZN_displayName": "Manat Azero",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit della Malesia",
	"DKK_displayName": "Corona Danese",
	"THB_displayName": "Baht Tailandese",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yen Giapponese",
	"KES_displayName": "Scellino Keniota",
	"KHR_displayName": "Riel Cambogiano",
	"PYG_displayName": "Guaraní del Paraguay",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupia di Sri Lanka",
	"BGN_displayName": "Nuovo Lev Bulgaro",
	"BDT_displayName": "Taka Bangladese",
	"MOP_displayName": "Pataca di Macao",
	"HNL_displayName": "Lempira Honduregna",
	"RWF_displayName": "Franco Ruandese",
	"CHF_displayName": "Franco Svizzero",
	"CRC_displayName": "Colón Costaricano",
	"INR_displayName": "Rupia Indiana",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand Sudafricano",
	"AUD_displayName": "Dollaro Australiano",
	"LAK_displayName": "Kip Laotiano",
	"MNT_displayName": "Tugrik Mongolo",
	"RSD_displayName": "Dinaro Serbo",
	"HRK_displayName": "Kuna Croata"
}
//end v1.x content
);