define("Sage/UI/Filters/nls/ru/CheckBoxFilter", {
    "loadingText": "Загрузка...",
    "moreText": "Редактировать элементы",
    "clearText": "Очистить",
    "emptyText": "(пусто)",
    "nullText": "(нуль)",
    "ofText": "/",
    "filterHasMetric": "Имеет метрику",
    "filterHasFilter": "Имеет фильтр",
    "filteroptionYesterday": "Вчера",
    "filteroptionToday": "Сегодня",
    "filteroptionThisWeek": "Эта неделя",
    "filteroptionThisMonth": "Этот месяц",
    "filteroptionThisQuarter": "Этот квартал",
    "filteroptionThisYear": "Этот год",
    "filteroptionLastWeek": "Прошлая неделя",
    "filteroptionLastMonth": "Прошлый месяц",
    "filteroptionLastQuarter": "Прошлый квартал",
    "filteroptionLastYear": "Прошлый год",
    "filteroptionWeektoStart": "С начала недели",
    "filteroptionMonthtoStart": "С начала месяца",
    "filteroptionQtrtoStart": "С начала квартала",
    "filteroptionYeartoStart": "С начала года",
    "filteroptionOlder": "Раньше",
    "filteroption0To999": "от 0 до 999",
    "filteroption1000To9999": "от 1000 до 9999",
    "filteroption10000To99999": "от 10 000 до 99 999",
    "filteroption100000To499999": "от 100 000 до 499 999",
    "filteroption500000To999999": "от 500 000 до 999 999",
    "filteroption1000000AndHigher": "1 000 000 и выше",
    "filteroptionT": "T"
});