define("Sage/MainView/EntityMgr/nls/de/_BaseEntityDetailContent", {
    "FilterTabTitle": "Filter",
    "MetricTabTitle": "Kennzahlen",
    "PropertyTabTitle": "Felder",
    "CalcFieldTabTitle": "Berechnete Felder",
    "EntityTabTitle": "Entitäten",
    "RelationTabTitle": "Beziehungen",
    "dialogTitleAddField": "Feld zu ${0}-Entität hinzufügen",
    "dialogTitleAddFilter": "Filter zu ${0}-Entität hinzufügen",
    "dialogTitleAddMetric": "Kennzahl zu ${0}-Entität hinzufügen",
    "dialogTitleAddRelationship": "Beziehung zu ${0}-Entität hinzufügen",
    "editDialogTitle": "${0} in ${1}-Entität bearbeiten",
    "FilterDialogTitle": "Filter",
    "MetricDialogTitle": "Kennzahl",
    "PropertyDialogTitle": "Feld",
    "RelationDialogTitle": "Beziehung",
    "FilterGridColumnFilter": "Filtername",
    "MetricGridColumnMetric": "Kennzahlname",
    "FilterGridColumnDisplay": "Anzeigename",
    "FilterGridColumnProperty": "Feld",
    "FilterGridColumnType": "Kennzahl oder Filter",
    "FilterGridColumnIsMetric": "Im Cockpit",
    "FilterGridColumnLastUpdated": "Zuletzt geändert",
    "FilterGridColumnDetails": "Typ",
    "FilterGridDetailsDistinctFilter": "Eindeutig",
    "FilterGridDetailsDateDiffMetricFilter": "Kennzahl \"Datumsdifferenz\"",
    "FilterGridDetailsRangeFilter": "Bereich",
    "FilterGridDetailsMetricFilter": "Kennzahl",
    "FilterGridDetailsUserLookupFilter": "Benutzersuche",
    "FilterGridDetailsLookupFilter": "Suchen",
    "FilterGridDetailsCustom": "Benutzerdefiniert",
    "GridHelp": "Hilfe",
    "FilterGridAdd": "Filter hinzufügen",
    "FilterGridRemove": "Filter entfernen",
    "FilterGridEdit": "Filter bearbeiten",
    "MetricGridAdd": "Kennzahl hinzufügen",
    "MetricGridRemove": "Kennzahl entfernen",
    "MetricGridEdit": "Kennzahl bearbeiten",
    "PropertyGridAdd": "Feld hinzufügen",
    "PropertyGridRemove": "Feld entfernen",
    "PropertyGridEdit": "Feld bearbeiten",
    "CalculatedGridAdd": "Berechnetes Feld hinzufügen",
    "CalculatedGridRemove": "Berechnetes Feld entfernen",
    "CalculatedGridEdit": "Berechnetes Feld bearbeiten",
    "lblFilterName": "Filtername",
    "lblDisplayName": "Anzeigename",
    "lblFilterDp": "Felder",
    "lblTypeDp": "Typ",
    "lblCharacter": "Zeichen",
    "lblTypeSpecificContentBox": "Typspezifischer Inhaltsbereich",
    "lblSaveButton": "Speichern",
    "lblCancelButton": "Abbrechen",
    "lblOkButton": "OK",
    "lblWarning": "Wählen Sie ein Element aus.",
    "confirmDeleteFmtTxt": "Möchten Sie diese Elemente wirklich löschen? (Anzahl der Elemente: ${0})",
    "filtersFor": "Filter für",
    "metricsFor": "Kennzahlen für",
    "propertyFor": "Felder für",
    "calculatedFor": "Berechnete Felder für",
    "defaultRangeRowValue": "Wert eingeben",
    "customSql": "Benutzerdefinierter SQL-Befehl",
    "displayName": "Anzeigename",
    "lower": "Unterer",
    "rangeId": "Bereichs-ID",
    "rangeName": "Bereichsname",
    "upper": "Obergrenze",
    "SUM": "Summe",
    "Contains": "Enthält",
    "StartsWith": "Beginnt mit",
    "EndsWith": "Endet mit",
    "LessThan": "Kleiner als",
    "GreaterThan": "Größer als",
    "LessThanEqual": "Kleiner gleich",
    "GreaterThanEqual": "Größer gleich",
    "Equal": "Gleich",
    "NotEqual": "Ist ungleich",
    "COUNT": "Anzahl",
    "AVG": "Durchschnitt",
    "MIN": "Minimum",
    "MAX": "Maximalwert",
    "totalRecordCountLabel": "Datensätze gesamt: ${0}",
    "propertyName": "Name",
    "Description": "Beschreibung",
    "propertyType": "Typ",
    "included": "Enthalten",
    "calculatedFields": "Berechnet",
    "generate": "Erstellen",
    "key": "Schlüssel",
    "relationFor": "Beziehung für",
    "childEntity": "Untergeordnet",
    "childProperty": "Feld des untergeordneten Elements",
    "parentEntity": "Übergeordnet",
    "parentProperty": "Feld des übergeordneten Elements",
    "editable": "Bearbeitbar",
    "cardinality": "Kardinalität",
    "relationship": "Beziehung",
    "parentImport": "Übergeordnetes Element importieren",
    "parentMatch": "Übergeordnetes Element abgleichen",
    "parentAudit": "Übergeordnetes Element überwachen",
    "parentIncluded": "Übergeordnetes eingeschlossen",
    "childImport": "Untergeordnetes Element importieren",
    "childMatch": "Untergeordnetes Element abgleichen",
    "childAudit": "Untergeordnetes Element überwachen",
    "childIncluded": "Untergeordnetes eingeschlossen",
    "text": "Text",
    "memo": "Memo",
    "unicodeText": "unicode-Text",
    "unicodeMemo": "unicode-Memo",
    "integer": "Ganzzahl",
    "double": "Double",
    "single": "Single",
    "decimal": "dezimal",
    "short": "kurz",
    "standardId": "Standard-ID",
    "trueFalse": "Wahr/Falsch",
    "yesNo": "Ja/Nein",
    "boolean": "boolesch",
    "dateTime": "Datum/Uhrzeit",
    "email": "E-Mail",
    "phone": "Telefon",
    "pickList": "Auswahlliste",
    "owner": "Zugriffsberechtigter",
    "lookup": "Suchen",
    "dependencyLookup": "Abhängigkeitensuche",
    "char": "Zeichen",
    "enum_": "Enum",
    "guid": "guid",
    "byte": "Byte",
    "binary": "binär",
    "url": "URL",
    "string": "Zeichenfolge",
    "number": "Zahl",
    "notUniqueFor": "ist nicht eindeutig für",
    "lblPluralName": "Name im Plural anzeigen",
    "lblTitle": "Titel",
    "IsExtension": "Ist Erweiterung",
    "AdvOptions": "Erweiterte Optionen",
    "lblImport": "Importieren",
    "lblMatch": "Abgleichen",
    "lblBulkUpdate": "Massenaktualisierung",
    "lblAudited": "Überwacht",
    "lblPut": "PUT",
    "lblPost": "POST",
    "lblDelete": "Löschen",
    "lblHistory": "Historie nachverfolgen in",
    "metricNotEditable": "Diese Kennzahl kann nicht bearbeitet werden."
});