define("Sage/MainView/EntityMgr/nls/de/EntityListPanelConfig", {
    "colNameEntityName": "Name",
    "colNameType": "Typ",
    "colNameTable": "Tabelle",
    "colNameCreateUser": "Angelegt von",
    "colNameCreateDate": "Erstellungsdatum",
    "colNameLastExecutionDate": "Letzte Ausführung",
    "colNameLastExecutionUser": "Letzte Ausführung durch",
    "colNameModifyUser": "Geändert von",
    "colNameModifyDate": "Änderungsdatum",
    "colNameEntityDisplayName": "Anzeigename",
    "colNameEntityTableName": "Tabelle",
    "colNamePropertyCount": "Eigenschaftenanzahl",
    "colNameFilterCount": "Filteranzahl",
    "colNameMetricCount": "Kennzahlanzahl",
    "colNamePackage": "Paket",
    "owner": "Zugriffsberechtigter",
    "assignTo": "Zuweisen zu",
    "newACI": "Neuer Bereich/Neue Kategorie/Neues Problem",
    "insertACI": "Bereich/Kategorie/Problem einfügen",
    "autoAssign": "Automatische Zuweisung",
    "areaCatIssue": "Bereich/Kategorie/Problem",
    "lookupACI": "Bereich/Kategorie/Problem suchen",
    "displayName": "Anzeigename",
    "displayPluralName": "Name im Plural anzeigen",
    "Title": "Titel",
    "IsExtension": "IsExtension",
    "Audited": "Überwacht",
    "OK": "OK",
    "Cancel": "Abbrechen"
});