define("Sage/UI/nls/en/AddressFormatConditionWidget", {
	trueText: 'True',
	falseText: 'False',
	networkText: 'Network',
	remoteText: 'Remote',
	webText: 'Web',
	webViewerText: 'Web Viewer',
	concurrentText: 'Concurrent',
	retiredText: 'Retired',
	templateText: 'Template',
	addonText: 'Addon',
	adminText: 'Admin',
	userText: 'User',
	teamText: 'Team',
	departmentText: 'Department',
	systemText: 'System',
    displayDuplicatesError: '*Duplicates are not allowed. Please correct.',
	Text: 'TEXT',
	Space: 'space',
	_propertyLabel: 'Property',
	_seperatorLabel: 'Separated by'
});
