define(
"dojo/cldr/nls/pt/currency", //begin v1.x content
{
	"COP_displayName": "Peso colombiano",
	"CZK_displayName": "Coroa checa",
	"TND_displayName": "Dinar tunisiano",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dólar jamaicano",
	"PHP_displayName": "Peso filipino",
	"ALL_displayName": "Lek Albanês",
	"USD_symbol": "US$",
	"LBP_displayName": "Libra libanesa",
	"VND_displayName": "Dong vietnamita",
	"LYD_displayName": "Dinar líbio",
	"RON_displayName": "Leu romeno",
	"MKD_displayName": "Dinar macedônio",
	"SEK_displayName": "Coroa sueca",
	"CNY_displayName": "Yuan chinês",
	"IDR_displayName": "Rupia indonésia",
	"ILS_displayName": "Sheqel Novo israelita",
	"YER_displayName": "Rial iemenita",
	"TJS_displayName": "Somoni tadjique",
	"TTD_displayName": "Dólar de Trinidad e Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira turca",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirém dos Emirados Árabes Unidos",
	"KZT_displayName": "Tenge cazaque",
	"BHD_displayName": "Dinar bareinita",
	"RUB_displayName": "Rublo russo",
	"NZD_displayName": "Dólar da Nova Zelândia",
	"IQD_displayName": "Dinar iraquiano",
	"TMT_displayName": "Manat do Turcomenistão",
	"ZWL_displayName": "Dólar do Zimbábue (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Som quirguiz",
	"KWD_displayName": "Dinar coveitiano",
	"AFN_displayName": "Afegane afegão",
	"ARS_displayName": "Peso argentino",
	"MAD_displayName": "Dirrã marroquino",
	"BAM_displayName": "Marco bósnio-herzegovino conversível",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Dólar do Brunei",
	"SGD_displayName": "Dólar de Cingapura",
	"MVR_displayName": "Rupia maldiva",
	"MXN_displayName": "Peso mexicano",
	"DZD_displayName": "Dinar argelino",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar jordaniano",
	"PEN_displayName": "Novo sol peruano",
	"GTQ_displayName": "Quetzal guatemalense",
	"BYR_displayName": "Rublo bielorrusso",
	"CAD_displayName": "Dólar canadense",
	"BZD_displayName": "Dólar do Belize",
	"CLP_displayName": "Peso chileno",
	"XOF_displayName": "Franco CFA BCEAO",
	"NOK_displayName": "Coroa norueguesa",
	"DOP_displayName": "Peso dominicano",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won sul-coreano",
	"USD_displayName": "Dólar norte-americano",
	"UYU_displayName": "Peso uruguaio",
	"UZS_displayName": "Som uzbeque",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial catariano",
	"SAR_displayName": "Rial saudita",
	"SYP_displayName": "Libra síria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Libra egípcia",
	"AMD_displayName": "Dram armênio",
	"GBP_displayName": "Libra esterlina britânica",
	"HUF_displayName": "Forinte húngaro",
	"CSD_displayName": "Dinar sérvio (2002–2006)",
	"ISK_displayName": "Coroa islandesa",
	"IRR_displayName": "Rial iraniano",
	"OMR_displayName": "Rial omanense",
	"TWD_displayName": "Novo dólar taiwanês",
	"PAB_displayName": "Balboa panamenha",
	"UAH_displayName": "Hryvnia ucraniano",
	"ETB_displayName": "Birr etíope",
	"PLN_displayName": "Zloti polonês",
	"VEF_displayName": "Bolívar venezuelano",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Real brasileiro",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dólar de Hong Kong",
	"NIO_displayName": "Córdoba nicaraguense",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupia nepalesa",
	"PKR_displayName": "Rupia paquistanesa",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari georgiano",
	"AZN_displayName": "Manat azeri",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit malaio",
	"DKK_displayName": "Coroa dinamarquesa",
	"THB_displayName": "Baht tailandês",
	"BRL_symbol": "R$",
	"JPY_displayName": "Iene japonês",
	"KES_displayName": "Xelim queniano",
	"KHR_displayName": "Riel cambojano",
	"PYG_displayName": "Guarani paraguaio",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupia ceilandesa",
	"BGN_displayName": "Lev búlgaro",
	"BDT_displayName": "Taka bengalesa",
	"MOP_displayName": "Pataca macaense",
	"HNL_displayName": "Lempira hondurenha",
	"RWF_displayName": "Franco ruandês",
	"CHF_displayName": "Franco suíço",
	"CRC_displayName": "Colón costarriquenho",
	"INR_displayName": "Rupia indiana",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand sul-africano",
	"AUD_displayName": "Dólar australiano",
	"LAK_displayName": "Kip de Laos",
	"MNT_displayName": "Tugrik mongol",
	"RSD_displayName": "Dinar sérvio",
	"HRK_displayName": "Kuna croata"
}
//end v1.x content
);