define(
"dojo/cldr/nls/si/currency", //begin v1.x content
{
	"COP_displayName": "කොලොම්බියානු පෙසෝ",
	"CZK_displayName": "චෙක් රිපබ්ලික් කොරූනා",
	"TND_displayName": "ටියුනීසියානු ඩිනාර්",
	"PHP_displayName": "පිලිපීන පෙසෝ",
	"JMD_displayName": "ජැමෙයිකානු ඩොලර්",
	"LKR_symbol": "රු.",
	"ALL_displayName": "ඇල්බේනියානු ලෙක්",
	"LBP_displayName": "ලෙබනන පවුම්",
	"VND_displayName": "වියට්නාම ඩොන්",
	"LYD_displayName": "ලිබියානු ඩිනාර්",
	"RON_displayName": "රොමේනියානු ලෙව්",
	"MKD_displayName": "මැසඩෝනියානු ඩිනාර්",
	"SEK_displayName": "ස්වෙඩිෂ් ක්රෝනා",
	"CNY_displayName": "චීන යුආන්",
	"IDR_displayName": "ඉන්දුනීසියානු රුපියා",
	"ILS_displayName": "ඊශ්රායල නව ශෙකල්",
	"YER_displayName": "යේමන රියාල්",
	"TJS_displayName": "තජිකිස්ථාන සමොනි",
	"TTD_displayName": "ට්රිනිඩෑඩ් සහ ටොබෑගෝ ඩොලර්",
	"TRY_displayName": "තුර්කි ලිරා",
	"EUR_displayName": "යුරෝ",
	"AED_displayName": "එක්සත් අරාබි එමිරේට්ස් ඩිරාම්",
	"KZT_displayName": "කසකස්ථාන ටෙන්ග",
	"BHD_displayName": "බහරේන් ඩිනාර්",
	"RUB_displayName": "රුසියන් රූබල්",
	"NZD_displayName": "නවසීලන්ත ඩොලර්",
	"IQD_displayName": "ඉරාක ඩිනාර්",
	"TMT_displayName": "තක්මෙනිස්ථාන මනාට්",
	"KGS_displayName": "කිරිගිස්ථාන සම්",
	"KWD_displayName": "කුවේට් ඩිනාර්",
	"AFN_displayName": "ඇෆ්ගනිථාන ඇෆ්ගනි",
	"ARS_displayName": "ආර්ජන්ටිනා පෙසෝ",
	"MAD_displayName": "මොරොක්කෝ ඩිර්හැම්",
	"BAM_displayName": "බොස්නියා හර්සගොවීනා පරිවර්ත්ය මාර්ක්",
	"BOB_displayName": "බොලිවියානු බොලිවියානෝ",
	"BND_displayName": "බෘනායි ඩොලර්",
	"SGD_displayName": "සිංගප්පූරු ඩොලර්",
	"MVR_displayName": "මාලදිවයින් රුෆියා",
	"MXN_displayName": "මෙක්සිකානු ඩොලර්",
	"DZD_displayName": "ඇල්ගේරියානු ඩිනාර්",
	"JOD_displayName": "ජෝර්දාන් ඩිනාර්",
	"PEN_displayName": "පේරු නියුවෝ සොල්",
	"GTQ_displayName": "ගෝතමාලානු ක්වෙට්සල්",
	"BYR_displayName": "බෙලරූස් රූබල්",
	"CAD_displayName": "කැනේඩියානු ඩොලර්",
	"BZD_displayName": "බෙලීස් ඩොලර්",
	"CLP_displayName": "චිලි පැසෝ",
	"XOF_displayName": "CFA ෆ්රෑන්ක් BCEAO",
	"NOK_displayName": "නොර්වීජියන් ක්රෝන්",
	"DOP_displayName": "ඩොමිනිකානු පෙසෝ",
	"KRW_displayName": "දකුණු කොරියානු වොන්",
	"USD_displayName": "ඇමරිකානු ඩොලර්",
	"UYU_displayName": "උරුගුවේ පෙසෝ",
	"UZS_displayName": "උස්බෙකිස්ථාන සම්",
	"QAR_displayName": "කටාර් රියාල්",
	"SAR_displayName": "සවුදි රියාල්",
	"SYP_displayName": "සිරියානු පවුම්",
	"EGP_displayName": "ඊජිප්තු පවුම්",
	"AMD_displayName": "ආර්මේනියානු ඩ්රෑම්",
	"GBP_displayName": "බ්රිතාන්ය ස්ටර්ලින් පවුම්",
	"HUF_displayName": "හංගේරියානු ෆරින්ට්",
	"ISK_displayName": "අයිස්ලන්තික ක්රෝනා",
	"IRR_displayName": "ඉරාන රියාල්",
	"OMR_displayName": "ඕමාන් රියාල්",
	"TWD_displayName": "නව තායිවාන ඩොලර්",
	"PAB_displayName": "පැනමා බැල්බෝ",
	"UAH_displayName": "යුක්රේන හ්රිව්නියා",
	"ETB_displayName": "ඉතියෝපියානු බීර්",
	"PLN_displayName": "පොලිෂ් ස්ලොටි",
	"VEF_displayName": "වෙනිසියුලානු බොලිවර්",
	"BRL_displayName": "බ්රසීල රියල්",
	"HKD_displayName": "හොංකොං ඩොලර්",
	"NIO_displayName": "නිකරගුවානු කොඩෝබා",
	"NPR_displayName": "නේපාල රුපියල්",
	"PKR_displayName": "පාකිස්ථාන රුපියල්",
	"GEL_displayName": "ජෝජියානු ලැරී",
	"AZN_displayName": "අසර්බයිජානු මනාට්",
	"MYR_displayName": "මැලේසියානු රින්ගිට්",
	"DKK_displayName": "ඩැනිෂ් ක්රෝන්",
	"THB_displayName": "තායි බාත්",
	"JPY_displayName": "ජපන් යෙන්",
	"KES_displayName": "කෙන්යානු ශිලිං",
	"KHR_displayName": "කාම්බෝජ රියේල්",
	"PYG_displayName": "පැරගුවේ ගුවරානි",
	"LKR_displayName": "ශ්රී ලංකා රුපියල",
	"BGN_displayName": "බල්ගේරියානු ලිව්",
	"BDT_displayName": "බංග්ලාදේශ් ටකා",
	"MOP_displayName": "මැකනීස් පටකා",
	"HNL_displayName": "හොන්ඩුරානු ලෙම්පිරා",
	"RWF_displayName": "රුවන්ඩා ෆ්රෑන්ක්",
	"CHF_displayName": "ස්විස් ෆ්රෑන්ක්",
	"CRC_displayName": "කොස්ට රිකා කොලෝන්",
	"INR_displayName": "ඉන්දියානු රුපියල්",
	"ZAR_displayName": "දකුණු අප්රිකානු රැන්ඩ්",
	"AUD_displayName": "ඔස්ට්රේලියානු ඩොලර්",
	"LAK_displayName": "ලාඕස් කිප්",
	"MNT_displayName": "මොන්ගෝලියානු ටග්රික්",
	"RSD_displayName": "සර්බියානු ඩිනාර්",
	"HRK_displayName": "ක්රොඒෂියානු කූනා"
}
//end v1.x content
);