define(
"dojo/cldr/nls/ms/currency", //begin v1.x content
{
	"COP_displayName": "Peso Colombia",
	"CZK_displayName": "Koruna Republik Czech",
	"TND_displayName": "Dinar Tunisia",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dolar Jamaica",
	"PHP_displayName": "Peso Filipina",
	"ALL_displayName": "Lek Albania",
	"USD_symbol": "US$",
	"LBP_displayName": "Paun Lubnan",
	"VND_displayName": "Dong Vietnam",
	"LYD_displayName": "Dinar Libya",
	"RON_displayName": "Leu Romania",
	"MKD_displayName": "Denar Macedonia",
	"SEK_displayName": "Krona Sweden",
	"CNY_displayName": "Yuan Cina",
	"IDR_displayName": "Rupiah Indonesia",
	"ILS_displayName": "Sheqel Baru Israel",
	"YER_displayName": "Rial Yaman",
	"TJS_displayName": "Somoni Tajikistan",
	"TTD_displayName": "Dolar Trinidad dan Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira Turki",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham Emiriah Arab Bersatu",
	"KZT_displayName": "Tenge Kazakhstan",
	"BHD_displayName": "Dinar Bahrain",
	"RUB_displayName": "Ruble Rusia",
	"NZD_displayName": "Dolar New Zealand",
	"IQD_displayName": "Dinar Iraq",
	"TMT_displayName": "Manat Turkmenistan",
	"INR_symbol": "₹",
	"KGS_displayName": "Som Kyrgystani",
	"KWD_displayName": "Dinar Kuwait",
	"AFN_displayName": "Afghani Afghanistan",
	"ARS_displayName": "Peso Argentina",
	"MAD_displayName": "Dirham Maghribi",
	"BAM_displayName": "Mark Boleh Tukar Bosnia-Herzegovina",
	"BOB_displayName": "Boliviano Bolivia",
	"BND_displayName": "Dolar Brunei",
	"SGD_displayName": "Dolar Singapura",
	"MVR_displayName": "Rufiyaa Maldives",
	"MXN_displayName": "Peso Mexico",
	"DZD_displayName": "Dinar Algeria",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar Jordan",
	"PEN_displayName": "Nuevo Sol Peru",
	"GTQ_displayName": "Quetzal Guatemala",
	"BYR_displayName": "Ruble Belarus",
	"CAD_displayName": "Dolar Kanada",
	"BZD_displayName": "Dolar Belize",
	"CLP_displayName": "Peso Chile",
	"XOF_displayName": "Franc CFA BCEAO",
	"NOK_displayName": "Krone Norway",
	"DOP_displayName": "Peso Dominican",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won Korea Selatan",
	"USD_displayName": "Dolar AS",
	"UZS_displayName": "Som Uzbekistan",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial Qatar",
	"SAR_displayName": "Riyal Saudi",
	"SYP_displayName": "Paun Syria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Paun Mesir",
	"AMD_displayName": "Dram Armenia",
	"GBP_displayName": "Paun Sterling British",
	"HUF_displayName": "Forint Hungary",
	"ISK_displayName": "Krona Iceland",
	"IRR_displayName": "Rial Iran",
	"OMR_displayName": "Rial Oman",
	"TWD_displayName": "Dolar Taiwan Baru",
	"PAB_displayName": "Balboa Panama",
	"UAH_displayName": "Hryvnia Ukraine",
	"ETB_displayName": "Birr Ethiopia",
	"PLN_displayName": "Zloty Poland",
	"VEF_displayName": "Bolivar Venezuela",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Real Brazil",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dolar Hong Kong",
	"NIO_displayName": "Cordoba Nicaragua",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupee Nepal",
	"PKR_displayName": "Rupee Pakistan",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari Georgia",
	"AZN_displayName": "Manat Azerbaijan",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit Malaysia",
	"DKK_displayName": "Krone Denmark",
	"THB_displayName": "Baht Thai",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yen Jepun",
	"KES_displayName": "Syiling Kenya",
	"KHR_displayName": "Riel Kemboja",
	"PYG_displayName": "Guarani Paraguay",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupee Sri Lanka",
	"BGN_displayName": "Lev Bulgaria",
	"BDT_displayName": "Taka Bangladesh",
	"MOP_displayName": "Pataca Macau",
	"HNL_displayName": "Lempira Honduras",
	"RWF_displayName": "Franc Rwanda",
	"CHF_displayName": "Franc Switzerland",
	"CRC_displayName": "Colon Costa Rica",
	"INR_displayName": "Rupee India",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand Afrika Selatan",
	"MYR_symbol": "RM",
	"AUD_displayName": "Dolar Australia",
	"LAK_displayName": "Kip Laos",
	"MNT_displayName": "Tugrik Mongolia",
	"RSD_displayName": "Dinar Serbia",
	"HRK_displayName": "Kuna Croatia"
}
//end v1.x content
);