define(
"dojo/cldr/nls/tr/currency", //begin v1.x content
{
	"COP_displayName": "Kolombiya Pesosu",
	"CZK_displayName": "Çek Cumhuriyeti Korunası",
	"TND_displayName": "Tunus Dinarı",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaika Doları",
	"PHP_displayName": "Filipinler Pesosu",
	"ALL_displayName": "Arnavutluk Leki",
	"USD_symbol": "$",
	"LBP_displayName": "Lübnan Lirası",
	"VND_displayName": "Vietnam Dongu",
	"LYD_displayName": "Libya Dinarı",
	"RON_displayName": "Romen Leyi",
	"MKD_displayName": "Makedonya Dinarı",
	"SEK_displayName": "İsveç Kronu",
	"CNY_displayName": "Çin Yuanı",
	"IDR_displayName": "Endonezya Rupiahı",
	"ILS_displayName": "Yeni İsrail Şekeli",
	"YER_displayName": "Yemen Riyali",
	"TJS_displayName": "Tacikistan Somonisi",
	"TTD_displayName": "Trinidad ve Tobago Doları",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Türk Lirası",
	"EUR_displayName": "Euro",
	"AED_displayName": "Birleşik Arap Emirlikleri Dirhemi",
	"KZT_displayName": "Kazakistan Tengesi",
	"BHD_displayName": "Bahreyn Dinarı",
	"RUB_displayName": "Rus Rublesi",
	"NZD_displayName": "Yeni Zelanda Doları",
	"IQD_displayName": "Irak Dinarı",
	"TMT_displayName": "Türkmenistan Manatı",
	"ZWL_displayName": "Zimbabve Doları (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kırgızistan Somu",
	"KWD_displayName": "Kuveyt Dinarı",
	"TRY_symbol": "₺",
	"AFN_displayName": "Afganistan Afganisi",
	"ARS_displayName": "Arjantin Pesosu",
	"MAD_displayName": "Fas Dirhemi",
	"BAM_displayName": "Konvertibl Bosna Hersek Markı",
	"BOB_displayName": "Bolivya Bolivyanosu",
	"BND_displayName": "Brunei Doları",
	"SGD_displayName": "Singapur Doları",
	"MVR_displayName": "Maldiv Rufiyaası",
	"MXN_displayName": "Meksika Pesosu",
	"DZD_displayName": "Cezayir Dinarı",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Ürdün Dinarı",
	"PEN_displayName": "Peru Nuevo Solü",
	"GTQ_displayName": "Guatemala Quetzalı",
	"BYR_displayName": "Beyaz Rusya Rublesi",
	"CAD_displayName": "Kanada Doları",
	"BZD_displayName": "Belize Doları",
	"CLP_displayName": "Şili Pesosu",
	"XOF_displayName": "CFA Frangı BCEAO",
	"NOK_displayName": "Norveç Kronu",
	"TRY_pattern": "¤#,##0.00",
	"DOP_displayName": "Dominik Pesosu",
	"JPY_symbol": "¥",
	"KRW_displayName": "Güney Kore Wonu",
	"USD_displayName": "ABD Doları",
	"UYU_displayName": "Uruguay Pesosu",
	"UZS_displayName": "Özbekistan Somu",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Katar Riyali",
	"SAR_displayName": "Suudi Arabistan Riyali",
	"SYP_displayName": "Suriye Lirası",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Mısır Lirası",
	"AMD_displayName": "Ermenistan Dramı",
	"GBP_displayName": "İngiliz Sterlini",
	"HUF_displayName": "Macar Forinti",
	"CSD_displayName": "Eski Sırbistan Dinarı",
	"ISK_displayName": "İzlanda Kronu",
	"IRR_displayName": "İran Riyali",
	"OMR_displayName": "Umman Riyali",
	"TWD_displayName": "Yeni Tayvan Doları",
	"PAB_displayName": "Panama Balboası",
	"UAH_displayName": "Ukrayna Grivnası",
	"ETB_displayName": "Etiyopya Birri",
	"PLN_displayName": "Polonya Zlotisi",
	"VEF_displayName": "Venezuela Bolivarı",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Brezilya Reali",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hong Kong Doları",
	"NIO_displayName": "Nikaragua Kordobası",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepal Rupisi",
	"PKR_displayName": "Pakistan Rupisi",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Gürcistan Larisi",
	"AZN_displayName": "Azerbaycan Manatı",
	"GBP_symbol": "£",
	"MYR_displayName": "Malezya Ringgiti",
	"DKK_displayName": "Danimarka Kronu",
	"THB_displayName": "Tayland Bahtı",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japon Yeni",
	"KES_displayName": "Kenya Şilini",
	"KHR_displayName": "Kamboçya Rieli",
	"PYG_displayName": "Paraguay Guaranisi",
	"VND_symbol": "₫",
	"LKR_displayName": "Sri Lanka Rupisi",
	"BGN_displayName": "Bulgar Levası",
	"BDT_displayName": "Bangladeş Takası",
	"MOP_displayName": "Makao Patakası",
	"HNL_displayName": "Honduras Lempirası",
	"RWF_displayName": "Ruanda Frangı",
	"CHF_displayName": "İsviçre Frangı",
	"CRC_displayName": "Kosta Rika Kolonu",
	"INR_displayName": "Hindistan Rupisi",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Güney Afrika Randı",
	"AUD_displayName": "Avustralya Doları",
	"LAK_displayName": "Laos Kipi",
	"MNT_displayName": "Moğolistan Tugriki",
	"RSD_displayName": "Sırp Dinarı",
	"HRK_displayName": "Hırvatistan Kunası"
}
//end v1.x content
);