define("Sage/Utility/nls/ru/Activity", {
    "ToDo": "Дело",
    "PhoneCall": "Звонок",
    "Meeting": "Встреча",
    "Personal": "Личное действие",
    "Literature": "Литература",
    "Fax": "Факс",
    "Letter": "Письмо",
    "Note": "Заметка",
    "Email": "Электронная почта",
    "Document": "Документ",
    "DatabaseChange": "Изменение базы данных",
    "Event": "Событие",
    "ScheduledEvent": "Запланированное событие",
    "Contact": "Контакт",
    "Lead": "Заинтересованное лицо",
    "New": "Новый",
    "Change": "Изменить",
    "Deleted": "Удалено",
    "Confirm": "Подтвердить",
    "Decline": "Отклонить",
    "Unknown": "Неизвестно",
    "Leader": "Организатор",
    "Complete": "Завершить",
    "confirmTypeChanged": "Изменено",
    "confirmTypeConfirmed": "Подтверждено",
    "confirmTypeDeleted": "Удалено",
    "timelessText": "без указания времени"
});