define("Sage/Reporting/nls/zh-tw/Enumerations", {
    "txtGroup": "群組",
    "txtDateRange": "日期範圍",
    "txtUser": "使用者",
    "txtQuery": "查詢",
    "txtIsGreaterThan": "大於",
    "txtIsLessThan": "小於",
    "txtIsInTheRange": "在範圍內",
    "txtIsAfter": "晚於",
    "txtIsBefore": "早於",
    "txtContains": "包含",
    "txtStartsWith": "開始於",
    "txtEndsWith": "結束於",
    "txtIs": "是",
    "txtIsNot": "不是",
    "txtOnDemand": "隨需",
    "txtScheduled": "已安排",
    "txtCrystalReport": "Crystal 報告",
    "txtExportToFileReportType": "匯出至檔案",
    "txtUnknownReportType": "不明",
    "txtNoFormat": "沒有格式",
    "txtPdf": "PDF",
    "txtExcel": "Excel",
    "txtExcelDataOnly": "Excel-資料",
    "txtCsv": "CSV",
    "txtWord": "Word",
    "txtXml": "XML"
});