define(
"dojo/cldr/nls/lv/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbijas peso",
	"CZK_displayName": "Čehijas krona",
	"TND_displayName": "Tunisijas dinārs",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaikas dolārs",
	"PHP_displayName": "Filipīnu peso",
	"ALL_displayName": "Albānijas leks",
	"USD_symbol": "$",
	"LBP_displayName": "Libānas mārciņa",
	"VND_displayName": "Vjetnamas dongi",
	"LYD_displayName": "Lībijas dinārs",
	"RON_displayName": "Rumānijas leja",
	"MKD_displayName": "Maķedonijas denārs",
	"SEK_displayName": "Zviedrijas krona",
	"CNY_displayName": "Ķīnas juaņs",
	"IDR_displayName": "Indonēzijas rūpija",
	"ILS_displayName": "Izraēlas šekelis",
	"YER_displayName": "Jemenas riāls",
	"TJS_displayName": "Tadžikistānas somons",
	"TTD_displayName": "Trinidādas un Tobāgo dolārs",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Turcijas jaunā lira",
	"EUR_displayName": "eiro",
	"AED_displayName": "Apvienoto Arābu Emirātu dirhēms",
	"KZT_displayName": "Kazahstānas tenge",
	"BHD_displayName": "Bahreinas dinārs",
	"RUB_displayName": "Krievijas rublis",
	"NZD_displayName": "Jaunzēlandes dolārs",
	"IQD_displayName": "Irākas dinārs",
	"TMT_displayName": "Turkmenistānas jaunais manats",
	"ZWL_displayName": "Zimbabves dolārs (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgizstānas soms",
	"KWD_displayName": "Kuveitas dinārs",
	"AFN_displayName": "Afganistānas afgāns",
	"ARS_displayName": "Argentīnas peso",
	"MAD_displayName": "Marokas dirhēms",
	"BAM_displayName": "Bosnijas un Hercogovinas marka",
	"BOB_displayName": "Bolīvijas boliviano",
	"BND_displayName": "Brunejas dolārs",
	"SGD_displayName": "Singapūras dolārs",
	"MVR_displayName": "Maldīvijas rūfija",
	"MXN_displayName": "Meksikas peso",
	"DZD_displayName": "Alžīrijas dinārs",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Jordānas dinārs",
	"PEN_displayName": "Peru jaunais sols",
	"GTQ_displayName": "Gvatemalas ketsals",
	"BYR_displayName": "Baltkrievijas rubelis",
	"CAD_displayName": "Kanādas dolārs",
	"BZD_displayName": "Belizas dolārs",
	"CLP_displayName": "Čīles peso",
	"XOF_displayName": "Rietumāfrikas CFA franks",
	"NOK_displayName": "Norvēģijas krona",
	"DOP_displayName": "Dominikānas peso",
	"JPY_symbol": "¥",
	"KRW_displayName": "Dienvidkorejas vona",
	"USD_displayName": "ASV dolārs",
	"UYU_displayName": "Urugvajas peso",
	"UZS_displayName": "Uzbekistānas sums",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Kataras riāls",
	"SAR_displayName": "Saūda riāls",
	"SYP_displayName": "Sīrijas mārciņa",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Ēģiptes mārciņa",
	"AMD_displayName": "Armēnijas drams",
	"GBP_displayName": "Lielbritānijas sterliņu mārciņa",
	"HUF_displayName": "Ungārijas forints",
	"ISK_displayName": "Īslandes krona",
	"IRR_displayName": "Irānas riāls",
	"OMR_displayName": "Omānas riāls",
	"TWD_displayName": "Taivānas jaunais dolārs",
	"PAB_displayName": "Panamas balboa",
	"UAH_displayName": "Ukrainas grivna",
	"ETB_displayName": "Etiopijas birs",
	"PLN_displayName": "Polijas zlots",
	"VEF_displayName": "Venecuēlas bolivārs",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Brazīlijas reāls",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Honkongas dolārs",
	"NIO_displayName": "Nikaragvas kordoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepālas rūpija",
	"PKR_displayName": "Pakistānas rūpija",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Gruzijas lari",
	"AZN_displayName": "Azerbaidžānas manats",
	"GBP_symbol": "£",
	"MYR_displayName": "Malaizijas ringits",
	"DKK_displayName": "Dānijas krona",
	"THB_displayName": "Taizemes bāts",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japānas jena",
	"KES_displayName": "Kenijas šiliņš",
	"KHR_displayName": "Kambodžas riels",
	"PYG_displayName": "Paragvajas guarani",
	"VND_symbol": "₫",
	"LKR_displayName": "Šrilankas rūpija",
	"BGN_displayName": "Bulgārijas leva",
	"BDT_displayName": "Bangladešas taka",
	"MOP_displayName": "Makao pataka",
	"HNL_displayName": "Hondurasas lempīra",
	"RWF_displayName": "Ruandas franks",
	"CHF_displayName": "Šveices franks",
	"CRC_displayName": "Kostarikas kolons",
	"INR_displayName": "Indijas rūpija",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Dienvidāfrikas rands",
	"AUD_displayName": "Austrālijas dolārs",
	"LAK_displayName": "Laosas kips",
	"MNT_displayName": "Mongolijas tugriks",
	"RSD_displayName": "Serbijas dinārs",
	"HRK_displayName": "Horvātijas kuna"
}
//end v1.x content
);