define(
"dojo/cldr/nls/bs-cyrl/currency", //begin v1.x content
{
	"COP_displayName": "Колумбијски пезо",
	"CZK_displayName": "Чешка круна",
	"TND_displayName": "Тунизијски долар",
	"JMD_displayName": "Јамајски долар",
	"PHP_displayName": "Филипински пезо",
	"ALL_displayName": "Албански лек",
	"LBP_displayName": "Лебанска фунта",
	"VND_displayName": "Вијетнамски донг",
	"LYD_displayName": "Либијски динар",
	"RON_displayName": "Румунски леу",
	"MKD_displayName": "Македонски денар",
	"SEK_displayName": "Шведска круна",
	"CNY_displayName": "Кинески јуан ренминби",
	"IDR_displayName": "Индонезијска рупиа",
	"ILS_displayName": "Израелски нови шекел",
	"YER_displayName": "Јеменски риал",
	"TJS_displayName": "Таљихистански сомони",
	"TTD_displayName": "Тринидад тобагошки долар",
	"TRY_displayName": "Турска лира",
	"EUR_displayName": "Евро",
	"AED_displayName": "Уједињени арапски емирати дирхам",
	"KZT_displayName": "Казахстански тенџ",
	"BHD_displayName": "Бахреински динар",
	"RUB_displayName": "Руска рубља",
	"NZD_displayName": "Новозеландски долар",
	"IQD_displayName": "Ирачки динар",
	"TMT_displayName": "Туркменистански манат",
	"ZWL_displayName": "Зимбабвеански долар (2009)",
	"KGS_displayName": "Киргистански сом",
	"KWD_displayName": "Кувајтски динар",
	"TRY_symbol": "Тл",
	"AFN_displayName": "Авганистански авган",
	"ARS_displayName": "аргентински пезо",
	"PLN_symbol": "зл",
	"MAD_displayName": "Марокански дирхам",
	"BAM_displayName": "Конвертибилна марка",
	"BOB_displayName": "Боливијски Боливиано",
	"BND_displayName": "Брунејски долар",
	"SGD_displayName": "Сингапурски долар",
	"MVR_displayName": "Малдивијска руфија",
	"MXN_displayName": "Мексички пезо",
	"DZD_displayName": "Алжирски динар",
	"BAM_symbol": "КМ",
	"JOD_displayName": "Јордански динар",
	"PEN_displayName": "Перуански нуево сол",
	"GTQ_displayName": "Гватемалски квецал",
	"BYR_displayName": "Белоруска рубља",
	"CAD_displayName": "Канадски долар",
	"BZD_displayName": "Белизе долар",
	"CLP_displayName": "Чилеански пезо",
	"XOF_displayName": "CFA франак BCEAO",
	"NOK_displayName": "Норвешка круна",
	"DOP_displayName": "Доминикански пезо",
	"JPY_symbol": "¥",
	"KRW_displayName": "Јужнокорејски Вон",
	"USD_displayName": "Амерички долар",
	"UYU_displayName": "Уругвајски пезо",
	"UZS_displayName": "Узбекистански сом",
	"QAR_displayName": "Катаршки ријал",
	"SAR_displayName": "Саудијски ријал",
	"SYP_displayName": "Сиријска фунта",
	"EGP_displayName": "Египатска фунта",
	"AMD_displayName": "Јерменски драм",
	"GBP_displayName": "Британска фунта стерлинга",
	"HUF_displayName": "Мађарска форинта",
	"CSD_displayName": "Стари српски динар",
	"ISK_displayName": "Исландска круна",
	"RSD_symbol": "дин.",
	"IRR_displayName": "Ирански риал",
	"OMR_displayName": "Омански ријал",
	"TWD_displayName": "Нови тајвански долар",
	"PAB_displayName": "Панамска балбоа",
	"UAH_displayName": "Украјинска хривња",
	"ETB_displayName": "етиопијски бир",
	"PLN_displayName": "Пољски злот",
	"VEF_displayName": "Венецуелански боливар",
	"BRL_displayName": "Бразилски Реал",
	"HKD_displayName": "Хонгконшки долар",
	"NIO_displayName": "Никарагванска златна кордоба",
	"NPR_displayName": "Непалски рупи",
	"PKR_displayName": "Пакистански рупи",
	"GEL_displayName": "Грузијски лари",
	"AZN_displayName": "Азербејџански манат",
	"MYR_displayName": "Малезијски ринггит",
	"DKK_displayName": "Данска круна",
	"THB_displayName": "Таи бахт",
	"JPY_displayName": "Јапански јен",
	"KES_displayName": "Кенијски шилинг",
	"KHR_displayName": "Камбоџијски риел",
	"PYG_displayName": "Парагвајски гуарни",
	"LKR_displayName": "Шриланкански рупи",
	"BGN_displayName": "Бугарски лев",
	"BDT_displayName": "Бангладешка така",
	"MOP_displayName": "Маканишка патака",
	"HNL_displayName": "Хондурашка лемпира",
	"RWF_displayName": "Руандански франак",
	"CHF_displayName": "Швајцарски франак",
	"CRC_displayName": "Костарикански колон",
	"INR_displayName": "Индијски Рупи",
	"ZAR_displayName": "Јужно-афрички ранд",
	"AUD_displayName": "Аустралијски долар",
	"LAK_displayName": "Лаошки кип",
	"CZK_symbol": "Кч",
	"MNT_displayName": "Монголски тугрик",
	"RSD_displayName": "Српски динар",
	"HRK_displayName": "Хрватска куна"
}
//end v1.x content
);