define(
"dojo/cldr/nls/nb/currency", //begin v1.x content
{
	"COP_displayName": "colombianske pesos",
	"CZK_displayName": "tsjekkiske koruna",
	"TND_displayName": "tunisiske dinarer",
	"EUR_symbol": "€",
	"CAD_symbol": "CAD",
	"JMD_displayName": "jamaikanske dollar",
	"PHP_displayName": "filippinske pesos",
	"ALL_displayName": "albanske lek",
	"USD_symbol": "USD",
	"LBP_displayName": "libanesiske pund",
	"VND_displayName": "vietnamesiske dong",
	"LYD_displayName": "libyske dinarer",
	"RON_displayName": "rumenske leu",
	"MKD_displayName": "makedonske denarer",
	"SEK_displayName": "svenske kroner",
	"CNY_displayName": "kinesiske yuan",
	"IDR_displayName": "indonesiske rupier",
	"ILS_displayName": "nye israelske shekler",
	"YER_displayName": "jemenittiske rialer",
	"TJS_displayName": "tadsjikiske somoni",
	"TTD_displayName": "trinidadiske dollar",
	"CNY_symbol": "CNY",
	"TRY_displayName": "tyrkiske lire",
	"EUR_displayName": "euro",
	"AED_displayName": "emiratarabiske dirham",
	"KZT_displayName": "kasakhstanske tenge",
	"BHD_displayName": "bahrainske dinarer",
	"RUB_displayName": "russiske rubler",
	"NZD_displayName": "newzealandske dollar",
	"IQD_displayName": "irakske dinarer",
	"TMT_displayName": "turkmenske manat",
	"ZWL_displayName": "zimbabwisk dollar (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "kirgisiske som",
	"KWD_displayName": "kuwaitiske dinarer",
	"AFN_displayName": "afghansk afghani",
	"ARS_displayName": "argentinske pesos",
	"MAD_displayName": "marokkanske dirham",
	"BAM_displayName": "bosnisk-hercegovinske konvertible mark",
	"BOB_displayName": "bolivianske boliviano",
	"BND_displayName": "bruneiske dollar",
	"SGD_displayName": "singaporske dollar",
	"MVR_displayName": "maldiviske rufiyaa",
	"MXN_displayName": "meksikanske pesos",
	"DZD_displayName": "algeriske dinarer",
	"MXN_symbol": "MXN",
	"JOD_displayName": "jordanske dinarer",
	"PEN_displayName": "peruanske nuevo sol",
	"GTQ_displayName": "guatemalanske quetzal",
	"BYR_displayName": "hviterussiske rubler",
	"CAD_displayName": "kanadiske dollar",
	"BZD_displayName": "beliziske dollar",
	"CLP_displayName": "chilenske pesos",
	"NOK_symbol": "kr",
	"XOF_displayName": "vestafrikanske CFA-franc",
	"NOK_displayName": "norske kroner",
	"DOP_displayName": "dominikanske pesos",
	"JPY_symbol": "JPY",
	"KRW_displayName": "sørkoreanske won",
	"USD_displayName": "amerikanske dollar",
	"UYU_displayName": "uruguayanske pesos",
	"UZS_displayName": "usbekiske som",
	"XOF_symbol": "CFA",
	"QAR_displayName": "qatarske rialer",
	"SAR_displayName": "saudiarabiske riyaler",
	"SYP_displayName": "syriske pund",
	"NZD_symbol": "NZD",
	"EGP_displayName": "egyptiske pund",
	"AMD_displayName": "armenske dram",
	"GBP_displayName": "britiske pund sterling",
	"HUF_displayName": "ungarske forinter",
	"CSD_displayName": "serbiske dinarer (2002–2006)",
	"ISK_displayName": "islandske kroner",
	"IRR_displayName": "iranske rialer",
	"OMR_displayName": "omanske rialer",
	"TWD_displayName": "nye taiwanske dollar",
	"PAB_displayName": "panamanske balboa",
	"UAH_displayName": "ukrainske hryvnia",
	"ETB_displayName": "etiopiske birr",
	"PLN_displayName": "polske zloty",
	"VEF_displayName": "venezuelanske bolivar",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "brasilianske real",
	"HKD_symbol": "HKD",
	"HKD_displayName": "Hongkong-dollar",
	"NIO_displayName": "nicaraguanske córdoba",
	"THB_symbol": "THB",
	"NPR_displayName": "nepalske rupier",
	"PKR_displayName": "pakistanske rupier",
	"TWD_symbol": "TWD",
	"GEL_displayName": "georgiske lari",
	"AZN_displayName": "aserbajdsjanske manat",
	"GBP_symbol": "£",
	"MYR_displayName": "malaysiske ringgit",
	"DKK_displayName": "danske kroner",
	"THB_displayName": "thailandske baht",
	"BRL_symbol": "BRL",
	"JPY_displayName": "japanske yen",
	"KES_displayName": "kenyanske shilling",
	"KHR_displayName": "kambodsjanske riel",
	"PYG_displayName": "paraguayanske guarani",
	"VND_symbol": "VND",
	"LKR_displayName": "srilankiske rupier",
	"BGN_displayName": "bulgarske lev",
	"BDT_displayName": "bangladeshiske taka",
	"MOP_displayName": "makaoiske pataca",
	"HNL_displayName": "honduranske lempira",
	"RWF_displayName": "rwandiske franc",
	"CHF_displayName": "sveitsiske franc",
	"CRC_displayName": "costaricanske colón",
	"INR_displayName": "indiske rupier",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "sørafrikanske rand",
	"AUD_displayName": "australske dollar",
	"LAK_displayName": "laotiske kip",
	"MNT_displayName": "mongolske tugrik",
	"RSD_displayName": "serbiske dinarer",
	"HRK_displayName": "kroatiske kuna"
}
//end v1.x content
);