define("Sage/UI/Filters/nls/zh-tw/CheckBoxFilter", {
    "loadingText": "載入中...",
    "moreText": "編輯項目",
    "clearText": "清除",
    "emptyText": "(空白)",
    "nullText": "(Null)",
    "ofText": "/",
    "filterHasMetric": "有計量",
    "filterHasFilter": "有篩選",
    "filteroptionYesterday": "昨天",
    "filteroptionToday": "今天",
    "filteroptionThisWeek": "本週",
    "filteroptionThisMonth": "本月",
    "filteroptionThisQuarter": "本季",
    "filteroptionThisYear": "今年",
    "filteroptionLastWeek": "上週",
    "filteroptionLastMonth": "上個月",
    "filteroptionLastQuarter": "上一季",
    "filteroptionLastYear": "去年",
    "filteroptionWeektoStart": "週初至今",
    "filteroptionMonthtoStart": "月初至今",
    "filteroptionQtrtoStart": "季初至今",
    "filteroptionYeartoStart": "年初至今",
    "filteroptionOlder": "較舊的",
    "filteroption0To999": "0 到 999",
    "filteroption1000To9999": "1000 到 9999",
    "filteroption10000To99999": "10,000 到 99,999",
    "filteroption100000To499999": "100,000 到 499,999",
    "filteroption500000To999999": "500,000 到 999,999",
    "filteroption1000000AndHigher": "1,000,000 和更高",
    "filteroptionT": "T"
});