define(
"dojo/cldr/nls/is/currency", //begin v1.x content
{
	"COP_displayName": "Kólumbískur pesi",
	"CZK_displayName": "Tékknesk króna",
	"TND_displayName": "Túniskur denari",
	"CAD_symbol": "CAD",
	"JMD_displayName": "Jamaískur dalur",
	"PHP_displayName": "Filippseyskur pesi",
	"ALL_displayName": "Albanskt lek",
	"USD_symbol": "USD",
	"LBP_displayName": "Líbanskt pund",
	"VND_displayName": "Víetnamskt dong",
	"LYD_displayName": "Líbískur denari",
	"RON_displayName": "Rúmenskt lei",
	"MKD_displayName": "Makedónskur denari",
	"SEK_displayName": "Sænsk króna",
	"CNY_displayName": "Kínverskt júan",
	"IDR_displayName": "Indónesísk rúpía",
	"ILS_displayName": "Nýr ísraelskur sikill",
	"YER_displayName": "Jemenskt ríal",
	"TJS_displayName": "Tadsjikskur sómóni",
	"TTD_displayName": "Trínidad og Tóbagó-dalur",
	"TRY_displayName": "Tyrknesk líra",
	"EUR_displayName": "Evra",
	"AED_displayName": "Arabískt dírham",
	"KZT_displayName": "Kasakst tengi",
	"ISK_symbol": "kr",
	"BHD_displayName": "Bareinskur denari",
	"RUB_displayName": "Rússnesk rúbla",
	"NZD_displayName": "Nýsjálenskur dalur",
	"IQD_displayName": "Írakskur denari",
	"TMT_displayName": "Túrkmenskt manat",
	"KGS_displayName": "Kirgiskt som",
	"KWD_displayName": "Kúveiskur denari",
	"AFN_displayName": "Afgani",
	"ARS_displayName": "Argentínskur pesi",
	"MAD_displayName": "Marokkóskt dírham",
	"BAM_displayName": "Skiptanlegt Bosníu og Hersegóvínu-mark",
	"BOB_displayName": "Bólivíani",
	"BND_displayName": "Brúneiskur dalur",
	"SGD_displayName": "Singapúrskur dalur",
	"MVR_displayName": "Maldíveysk rúpía",
	"MXN_displayName": "Mexíkóskur pesi",
	"MXN_symbol": "MXN",
	"DZD_displayName": "Alsírskur denari",
	"JOD_displayName": "Jórdanskur denari",
	"PEN_displayName": "Perúskt sól",
	"GTQ_displayName": "Gvatemalskt kvesal",
	"BYR_displayName": "Hvítrússnesk rúbla",
	"CAD_displayName": "Kanadískur dalur",
	"BZD_displayName": "Belískur dalur",
	"CLP_displayName": "Síleskur pesi",
	"XOF_displayName": "Vesturafrískur franki",
	"NOK_displayName": "Norsk króna",
	"DOP_displayName": "Dóminískur pesi",
	"KRW_displayName": "Suðurkóreskt vonn",
	"USD_displayName": "Bandaríkjadalur",
	"UYU_displayName": "Úrúgvæskur pesi",
	"UZS_displayName": "Úsbekskt súm",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Katarskt ríal",
	"SAR_displayName": "Sádiarabískt ríal",
	"SYP_displayName": "Sýrlenskt pund",
	"EGP_displayName": "Egypskt pund",
	"AMD_displayName": "Armenskt dramm",
	"GBP_displayName": "Sterlingspund",
	"HUF_displayName": "Ungversk fórinta",
	"ISK_displayName": "Íslensk króna",
	"IRR_displayName": "Íranskt ríal",
	"OMR_displayName": "Ómanskt ríal",
	"TWD_displayName": "Taívanskur dalur",
	"PAB_displayName": "Balbói",
	"UAH_displayName": "Úkraínsk hrinja",
	"ETB_displayName": "Eþíópískt birr",
	"PLN_displayName": "Pólskt slot",
	"VEF_displayName": "Venesúelskur bólívari",
	"BRL_displayName": "Brasilískt ríal",
	"HKD_displayName": "Hong Kong-dalur",
	"NIO_displayName": "Níkarögsk kordóva",
	"NPR_displayName": "Nepölsk rúpía",
	"PKR_displayName": "Pakistönsk rúpía",
	"GEL_displayName": "Georgískur lari",
	"AZN_displayName": "Aserskt manat",
	"MYR_displayName": "Malasískt ringit",
	"DKK_displayName": "Dönsk króna",
	"THB_displayName": "Taílenskt bat",
	"JPY_displayName": "Japanskt jen",
	"KES_displayName": "Kenískur skildingur",
	"KHR_displayName": "Kambódískt ríal",
	"PYG_displayName": "Paragvæskt gvaraní",
	"LKR_displayName": "Srílönsk rúpía",
	"BGN_displayName": "Búlgarskt lef",
	"BDT_displayName": "Bangladessk taka",
	"MOP_displayName": "Makaópataka",
	"HNL_displayName": "Hondúrsk lempíra",
	"RWF_displayName": "Rúandskur franki",
	"CHF_displayName": "Svissneskur franki",
	"CRC_displayName": "Kostarískt kólon",
	"INR_displayName": "Indversk rúpía",
	"ZAR_displayName": "Suðurafrískt rand",
	"AUD_displayName": "Ástralskur dalur",
	"LAK_displayName": "Laoskt kip",
	"MNT_displayName": "Mongólskur túríkur",
	"RSD_displayName": "Serbneskur denari",
	"HRK_displayName": "Króatísk kúna"
}
//end v1.x content
);