define(
"dojo/cldr/nls/zu/currency", //begin v1.x content
{
	"COP_displayName": "i-Colombian Peso",
	"CZK_displayName": "i-Czech Republic Koruna",
	"TND_displayName": "i-Tunisian Dinar",
	"PHP_displayName": "i-Philippine Peso",
	"JMD_displayName": "i-Jamaican Dollar",
	"ALL_displayName": "i-Albanian Lek",
	"LBP_displayName": "i-Lebanese Pound",
	"VND_displayName": "i-Vietnamese Dong",
	"LYD_displayName": "i-Libyan Dinar",
	"RON_displayName": "I-Romanian Leu",
	"MKD_displayName": "i-Macedonian Denar",
	"SEK_displayName": "i-Swedish Krona",
	"CNY_displayName": "i-Chinese Yuan",
	"IDR_displayName": "i-Indonesian Rupiah",
	"ILS_displayName": "i-Israeli New Sheqel",
	"YER_displayName": "i-Yemeni Rial",
	"TJS_displayName": "i-Tajikistani Somoni",
	"TTD_displayName": "Idola lase-Trinidad nase-Tobago",
	"TRY_displayName": "i-Turkish Lira",
	"EUR_displayName": "i-Euro",
	"AED_displayName": "i-Dirham yase-United Arab Emirates",
	"KZT_displayName": "i-Kazakhstani Tenge",
	"BHD_displayName": "i-Bahraini Dinar",
	"RUB_displayName": "i-Russian Ruble",
	"NZD_displayName": "i-New Zealand Dollar",
	"IQD_displayName": "i-Iraqi Dinar",
	"TMT_displayName": "i-Turkmenistani Manat",
	"KGS_displayName": "i-Kyrgystani Som",
	"KWD_displayName": "i-Kuwaiti Dinar",
	"AFN_displayName": "i-Afghan Afghani",
	"ARS_displayName": "i-Argentina Peso",
	"MAD_displayName": "i-Moroccan Dirham",
	"BAM_displayName": "i-Bosnia-Herzegovina Convertible Mark",
	"BOB_displayName": "i-Bolivian Boliviano",
	"BND_displayName": "i-Brunei Dollar",
	"SGD_displayName": "i-Singapore Dollar",
	"MVR_displayName": "i-Maldivian Rufiyana",
	"MXN_displayName": "i-Mexican Peso",
	"ZAR_symbol": "R",
	"DZD_displayName": "i-Algerian Dinar",
	"JOD_displayName": "i-Jordanian Dinar",
	"PEN_displayName": "i-Peruvian Nuevo Sol",
	"GTQ_displayName": "i-Guatemalan Quetzal",
	"BYR_displayName": "i-Belarusian Ruble",
	"CAD_displayName": "i-Candian Dollar",
	"BZD_displayName": "i-Belize Dollar",
	"CLP_displayName": "i-Chilean Peso",
	"XOF_displayName": "i-CFA Franc BCEAO",
	"NOK_displayName": "i-Norwegian Krone",
	"DOP_displayName": "i-Dominican Peso",
	"KRW_displayName": "i-South Korean Won",
	"USD_displayName": "i-US Dollar",
	"UYU_displayName": "i-Uruguayan Peso",
	"UZS_displayName": "i-Uzbekistan Som",
	"QAR_displayName": "i-Qatari Rial",
	"SAR_displayName": "i-Saudi Riyal",
	"SYP_displayName": "i-Syrian Pound",
	"EGP_displayName": "i-Egyptian Pound",
	"AMD_displayName": "i-Armenian Dram",
	"GBP_displayName": "i-British Pound Sterling",
	"HUF_displayName": "i-Hungarian Forint",
	"ISK_displayName": "i-Icelandic Króna",
	"IRR_displayName": "i-Iranian Rial",
	"OMR_displayName": "i-Omani Rial",
	"TWD_displayName": "i-New Taiwan Dollar",
	"PAB_displayName": "i-Panamanian Balboa",
	"UAH_displayName": "i-Ukrainian Hryvnia",
	"ETB_displayName": "i-Ethopian Birr",
	"PLN_displayName": "i-Polish Zloty",
	"VEF_displayName": "i-Venezuelan Bolívar",
	"BRL_displayName": "i-Brazilian Real",
	"HKD_displayName": "i-Hong Kong Dollar",
	"NIO_displayName": "i-Nicaraguan Córdoba",
	"NPR_displayName": "i-Nepalese Rupee",
	"PKR_displayName": "i-Pakistani Rupee",
	"GEL_displayName": "i-Georgian Lari",
	"AZN_displayName": "i-Azerbaijani Manat",
	"MYR_displayName": "i-Malaysian Ringgit",
	"DKK_displayName": "i-Danish Krone",
	"THB_displayName": "i-Thai Baht",
	"JPY_displayName": "i-Japanese Yen",
	"KES_displayName": "i-Kenyan Shilling",
	"KHR_displayName": "i-Cambodian Riel",
	"PYG_displayName": "i-Paraguayan Guarani",
	"LKR_displayName": "i-Sri Lankan Rupee",
	"BGN_displayName": "i-Bulgarian Lev",
	"BDT_displayName": "i-Bangladeshi Taka",
	"MOP_displayName": "i-Macanese Pataca",
	"HNL_displayName": "i-Honduran Lempira",
	"RWF_displayName": "i-Rwandan Franc",
	"CHF_displayName": "i-Swiss Franc",
	"CRC_displayName": "i-Costa Rican Colón",
	"INR_displayName": "i-Indian Rupee",
	"ZAR_displayName": "i-South African Rand",
	"AUD_displayName": "i-Austrilian Dollar",
	"LAK_displayName": "i-Laotian Kip",
	"MNT_displayName": "i-Mongolian Tugrik",
	"RSD_displayName": "i-Serbian Dinar",
	"HRK_displayName": "i-Croatian Kuna"
}
//end v1.x content
);