define("Sage/MainView/ReportMgr/Crystal/nls/zh-cn/_ParameterEditorBase", {
    "txtPleaseSpecifyValue": "请指定值。",
    "lblAvailableValues_Caption": "可用值:",
    "lblSelectedValues_Caption": "所选值:",
    "lblEnterValue_Caption": "输入值:",
    "btnOK_Caption": "确定",
    "txtTheValueMustBeBetween": "值长度必须在 {0} 和 {1} 个字符之间。",
    "txtTheMinimumLengthForThisField": "此字段的最小长度为 {0}。",
    "txtTheMaximumLengthForThisField": "此字段的最大长度为 {0}。",
    "txtPleaseSpecifyNumberBetween": "请指定 {0} 和 {1} 之间的数字值。",
    "txtPleaseSpecifyNumberLesser": "请指定小于或等于 {0} 的数字值。",
    "txtPleaseSpecifyNumberGreater": "请指定大于或等于 {0} 的数字值。",
    "txtNoLowerValue": "无下限值",
    "txtNoUpperValue": "无上限值",
    "txtIncludeThisValue": "包含该值",
    "txtFrom": "自:",
    "txtTo": "至:",
    "txtPleaseSpecifyFromValue": "请指定开始范围值",
    "txtPleaseSpecifyToValue": "请指定结束范围值",
    "txtPleaseSpecifyDateBetween": "请指定介于 {0} 和 {1} 之间的日期值。",
    "txtPleaseSpecifyDateLesser": "请指定小于或等于 {0} 的日期值。",
    "txtPleaseSpecifyDateGreater": "请指定大于或等于 {0} 的日期值。",
    "txtFromMustBeLessThanOrEqualToTo": "开始范围值必须小于或等于结束范围值。",
    "txtStartOfRange": "范围开始时间:",
    "txtEndOfRange": "范围结束时间:",
    "txtAddRange": "添加范围",
    "lblSelectValue_Caption": "选择值:",
    "lblOrValue_Caption": "或"
});