define("Sage/MainView/EntityMgr/nls/ru/_BaseEntityDetailContent", {
    "FilterTabTitle": "Фильтры",
    "MetricTabTitle": "Метрики",
    "PropertyTabTitle": "Поля",
    "CalcFieldTabTitle": "Вычисляемые поля",
    "EntityTabTitle": "Сущности",
    "RelationTabTitle": "Отношения",
    "dialogTitleAddField": "Добавить поле в сущность \"${0}\"",
    "dialogTitleAddFilter": "Добавить фильтр в сущность \"${0}\"",
    "dialogTitleAddMetric": "Добавить метрику в сущность \"${0}\"",
    "dialogTitleAddRelationship": "Добавить отношение в сущность \"${0}\"",
    "editDialogTitle": "Редактировать \"${0}\" в сущности \"${1}\"",
    "FilterDialogTitle": "Фильтр",
    "MetricDialogTitle": "Метрика",
    "PropertyDialogTitle": "Поле",
    "RelationDialogTitle": "Отношение",
    "FilterGridColumnFilter": "Имя фильтра",
    "MetricGridColumnMetric": "Имя метрики",
    "FilterGridColumnDisplay": "Отображаемое имя",
    "FilterGridColumnProperty": "Поле",
    "FilterGridColumnType": "Метрика или фильтр",
    "FilterGridColumnIsMetric": "В личном кабинете",
    "FilterGridColumnLastUpdated": "Последнее изменение",
    "FilterGridColumnDetails": "Тип",
    "FilterGridDetailsDistinctFilter": "Уникальный",
    "FilterGridDetailsDateDiffMetricFilter": "Разность между датами метрики",
    "FilterGridDetailsRangeFilter": "Диапазон",
    "FilterGridDetailsMetricFilter": "Метрика",
    "FilterGridDetailsUserLookupFilter": "Поиск пользователя",
    "FilterGridDetailsLookupFilter": "Поиск",
    "FilterGridDetailsCustom": "Пользовательский",
    "GridHelp": "Справка",
    "FilterGridAdd": "Добавить фильтр",
    "FilterGridRemove": "Удалить фильтр",
    "FilterGridEdit": "Редактировать фильтр",
    "MetricGridAdd": "Добавить метрику",
    "MetricGridRemove": "Удалить метрику",
    "MetricGridEdit": "Редактировать метрику",
    "PropertyGridAdd": "Добавить поле",
    "PropertyGridRemove": "Удалить поле",
    "PropertyGridEdit": "Редактировать поле",
    "CalculatedGridAdd": "Добавить вычисляемое поле",
    "CalculatedGridRemove": "Удалить вычисляемое поле",
    "CalculatedGridEdit": "Редактировать вычисляемое поле",
    "lblFilterName": "Имя фильтра",
    "lblDisplayName": "Отображаемое имя",
    "lblFilterDp": "Поля",
    "lblTypeDp": "Тип",
    "lblCharacter": "Символы",
    "lblTypeSpecificContentBox": "Поле данных с учетом типа",
    "lblSaveButton": "Сохранить",
    "lblCancelButton": "Отмена",
    "lblOkButton": "OК",
    "lblWarning": "Выберите элемент.",
    "confirmDeleteFmtTxt": "Действительно удалить эти элементы (${0})?",
    "filtersFor": "Фильтры для",
    "metricsFor": "Метрики для",
    "propertyFor": "Поля для",
    "calculatedFor": "Вычисляемые поля для",
    "defaultRangeRowValue": "Введите значение",
    "customSql": "Пользовательский SQL",
    "displayName": "Отображаемое имя",
    "lower": "Нижнее",
    "rangeId": "ИД диапазона",
    "rangeName": "Имя диапазона",
    "upper": "Верхний",
    "SUM": "Итого (сумма)",
    "Contains": "Содержит",
    "StartsWith": "Начинается с",
    "EndsWith": "Заканчивается на",
    "LessThan": "Меньше",
    "GreaterThan": "Больше",
    "LessThanEqual": "Меньше или равно",
    "GreaterThanEqual": "Больше или равно",
    "Equal": "Равно",
    "NotEqual": "Не равно",
    "COUNT": "Количество",
    "AVG": "Среднее",
    "MIN": "Минимальное значение",
    "MAX": "Максимальное значение",
    "totalRecordCountLabel": "Всего записей: ${0}",
    "propertyName": "Имя",
    "Description": "Описание",
    "propertyType": "Тип",
    "included": "Включено",
    "calculatedFields": "Рассчитано",
    "generate": "Сгенерировать",
    "key": "Ключ",
    "relationFor": "Отношение для",
    "childEntity": "Дочерний элемент",
    "childProperty": "Поле дочернего элемента",
    "parentEntity": "Родительский элемент",
    "parentProperty": "Поле родительского элемента",
    "editable": "Редактируемый",
    "cardinality": "Мощность",
    "relationship": "Отношение",
    "parentImport": "Импорт родительского элемента",
    "parentMatch": "Совпадение родительского элемента",
    "parentAudit": "Аудит родительского элемента",
    "parentIncluded": "Включая родительский элемент",
    "childImport": "Импорт дочернего элемента",
    "childMatch": "Совпадение дочернего элемента",
    "childAudit": "Аудит дочернего элемента",
    "childIncluded": "Включая дочерний элемент",
    "text": "текст",
    "memo": "заметка",
    "unicodeText": "Текст unicode",
    "unicodeMemo": "Заметка unicode",
    "integer": "целое число",
    "double": "двойное",
    "single": "одинарное",
    "decimal": "десятичное",
    "short": "короткое",
    "standardId": "стандартный ИД",
    "trueFalse": "истина/ложь",
    "yesNo": "да/нет",
    "boolean": "логическое значение",
    "dateTime": "дата/время",
    "email": "электронная почта",
    "phone": "телефон",
    "pickList": "список выбора",
    "owner": "владелец",
    "lookup": "поиск",
    "dependencyLookup": "поиск зависимости",
    "char": "символ",
    "enum_": "перечисление",
    "guid": "guid",
    "byte": "байт",
    "binary": "двоичный",
    "url": "URL-адрес",
    "string": "строка",
    "number": "число",
    "notUniqueFor": "не уникально для",
    "lblPluralName": "Отображение имени во множественном числе",
    "lblTitle": "Название",
    "IsExtension": "Является расширением",
    "AdvOptions": "Дополнительные параметры",
    "lblImport": "Импорт",
    "lblMatch": "Соответствие",
    "lblBulkUpdate": "Массовое обновление",
    "lblAudited": "Аудит выполнен",
    "lblPut": "Разместить",
    "lblPost": "Опубликовать",
    "lblDelete": "Удалить",
    "lblHistory": "Отслеживать историю до",
    "metricNotEditable": "Изменение этой метрики невозможно."
});