define("Sage/UI/Dashboard/nls/it/WidgetDefinition", {
    "defaultWidgetText": "Modificare impostazioni dei widget",
    "settingsText": "Impostazioni",
    "viewGroupText": "Visualizza gruppo",
    "Bar_Chart": "Grafico a barre",
    "Column_Chart": "Grafico a colonne",
    "Group_List": "Elenco gruppi",
    "Pie_Chart": "Grafico a torta",
    "Funnel_Chart": "Grafico a imbuto",
    "Line_Chart": "Grafico a linee",
    "SData_Feed": "Feed SData",
    "Web_Feed": "Feed Web",
    "Website": "Sito Web",
    "Default": "Predefinito",
    "Links": "Collegamenti",
    "Recently_Viewed": "Visualizzati di recente",
    "Todays_Activities": "Attività di oggi",
    "Today_s_Activities": "Attività di oggi",
    "Welcome": "Benvenuto",
    "Closing_Opportunities": "Chiusura opportunità",
    "Quick_Actions": "Azioni rapide",
    "Do_You_Know___": "Sai che...",
    "All_Leads": "Tutti i lead",
    "My_Notes": "Note personali",
    "Open_Opportunities": "Opportunità aperte",
    "My_Top_Opportunities": "Migliori opportunità personali",
    "My_Pipeline": "Pipeline personale",
    "Recent_Lead_Creation_History": "Cronologia creazione lead recente",
    "My_Activity_trend": "Tendenza attività personali",
    "My_Completed_Activities_by_Type": "Attività personali completate per tipo",
    "Active_Campaigns": "Campagne attive",
    "All_Open_Opportunities": "Tutte le opportunità aperte",
    "Top_Opportunities": "Migliori opportunità",
    "Open_Defect_Distribution": "Distribuzione difetti aperti",
    "My_Dashboard": "Dashboard personale",
    "Sales": "Vendite",
    "Group_List_Description": "Visualizza un elenco di record raggruppati per entità. Ad esempio, un gruppo di campagne attive.",
    "Welcome_Description": "Visualizza un'introduzione a Saleslogix con un collegamento all'argomento della guida Introduzione alla parte Web di Saleslogix.",
    "Line_Chart_Description": "Visualizza i dati sotto forma di punti di dati connessi da una linea. Utile quando i dati rappresentano molti gruppi di categorie.",
    "Bar_Chart_Description": "Visualizza i dati sotto forma di barre orizzontali. Utile nel confronto dei dati.",
    "Column_Chart_Description": "Visualizza i dati sotto forma di barre verticali raggruppate per categoria. Utile per mostrare le modifiche ai dati in un determinato periodo di tempo o per illustrare confronti tra dati.",
    "Funnel_Chart_Description": "Visualizza i dati sotto forma di imbuto con proporzioni progressive. Il dato viene rappresentato come porzione del 100% e non ci sono assi.",
    "Pie_Chart_Description": "Visualizza i dati come porzioni dell'intero. Ciascun valore è calcolato come percentuale del totale. Questo grafico non ha assi.",
    "Recently_Viewed_Description": "Visualizza i collegamenti ai record visitati di recente con un'icona che identifica il tipo di record stesso. Ad esempio, Azienda o Contatto.",
    "Todays_Activities_Description": "Visualizza i collegamenti alle attività di oggi.",
    "Links_Description": "Visualizza i collegamenti creati, ad esempio a una vista dettagli in Saleslogix o a un sito Web esterno.",
    "SData_Feed_Description": "Visualizza un feed Web utilizzando feed SData (Sage Data). Ad esempio, un feed dell'integrazione contabilità o del database Saleslogix.",
    "Web_Feed_Description": "Visualizza informazioni su feed RSS o Atom.",
    "Website_Description": "Visualizza un sito Web scelto dall'utente."
});