define("Sage/UI/Forms/nls/fr/FormFromSData", {
    "addText": "Ajouter",
    "deleteText": "Supprimer",
    "saveText": "Enregistrer",
    "cancelText": "Annuler",
    "editText": "Modifier",
    "helpText": "Aide",
    "yesText": "Oui",
    "noText": "Non",
    "okText": "OK",
    "newPickList": "Nouvelle liste de sélection",
    "items": "Eléments de liste de sélection",
    "number": "Commande",
    "enterValue": "Saisir la valeur",
    "lblMore": "Plus",
    "picklistAlreadyExists": "Picklist '${0}' existe déjà.",
    "messageOnSave": "La liste de sélection ${0} a été enregistrée. Veuillez continuer d'ajouter ou de modifier les informations de champ.",
    "permissionsToView": "Vous n'êtes pas autorisé à afficher.",
    "required": "Entrée obligatoire",
    "allowMultiples": "Autoriser les sélections multiples",
    "valueMustExist": "Le texte doit correspondre à un élément de la liste",
    "alphaSorted": "Trié par ordre alphabétique",
    "noneEditable": "Les utilisateurs ne peuvent pas modifier les éléments"
});