define(
"dojo/cldr/nls/pa/currency", //begin v1.x content
{
	"COP_displayName": "ਕੋਲੰਬੀਅਨ ਪੈਸੋ",
	"CZK_displayName": "ਚੈਕ ਗਣਰਾਜ ਕੋਰੁਨਾ",
	"TND_displayName": "ਟਿਉਨੀਸ਼ੀਆਈ ਦਿਨਾਰ",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ਜਮਾਇਕਨ ਡਾਲਰ",
	"PHP_displayName": "ਫਿਲਿਪੀਨੀ ਪੈਸੋ",
	"ALL_displayName": "ਅਲਬਾਨੀਆਈ ਲੇਕ",
	"USD_symbol": "US$",
	"LBP_displayName": "ਲੈਬਨਾਨੀ ਪਾਉਂਡ",
	"VND_displayName": "ਵਿਯਤਨਾਮੀ ਡੋਂਗ",
	"LYD_displayName": "ਲੀਬੀਅਨ ਦਿਨਾਰ",
	"RON_displayName": "ਰੋਮਾਨੀਆਈ ਲਿਯੂ",
	"MKD_displayName": "ਮੈਕਡੋਨੀਆਈ ਡੇਨਾਰ",
	"SEK_displayName": "ਸਵੀਡਿਸ਼ ਕਰੋਨਾ",
	"CNY_displayName": "ਚੀਨੀ ਯੁਆਨ",
	"IDR_displayName": "ਇੰਡੋਨੇਸ਼ੀਆਈ ਰੁਪਿਆਹ",
	"ILS_displayName": "ਇਜ਼ਰਾਈਲੀ ਨਵੀਂ ਸ਼ੇਕੇਲ",
	"YER_displayName": "ਯਮਨੀ ਰਿਆਲ",
	"TJS_displayName": "ਤਾਜਿਕਿਸਤਾਨੀ ਸੋਮੋਨੀ",
	"TTD_displayName": "ਟ੍ਰਿਨੀਡਾਡ ਅਤੇ ਟੋਬਾਗੋ ਡਾਲਰ",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "ਤੁਰਕਿਸ਼ ਲਿਰਾ",
	"EUR_displayName": "ਯੂਰੋ",
	"AED_displayName": "ਸੰਯੁਕਤ ਅਰਬ ਅਮੀਰਾਤ ਦਿਰਹਾਮ",
	"KZT_displayName": "ਕਜ਼ਾਕਸਤਾਨੀ ਤੇਂਗੇ",
	"BHD_displayName": "ਬਹਿਰੀਨੀ ਦਿਨਾਰ",
	"RUB_displayName": "ਰੂਸੀ ਰੂਬਲ",
	"NZD_displayName": "ਨਿਊਜ਼ੀਲੈਂਡ ਡਾਲਰ",
	"IQD_displayName": "ਇਰਾਕੀ ਦਿਨਾਰ",
	"TMT_displayName": "ਤੁਰਕਮੇਨਿਸਤਾਨੀ ਮਾਨਤ",
	"INR_symbol": "₹",
	"KGS_displayName": "ਕਿਰਗਿਸਤਾਨੀ ਸੋਮ",
	"KWD_displayName": "ਕੁਵੈਤੀ ਦਿਨਾਰ",
	"AFN_displayName": "ਅਫ਼ਗਾਨ ਅਫ਼ਗਾਨੀ",
	"ARS_displayName": "ਅਰਜਨਟਾਈਨ ਪੈਸੋ",
	"MAD_displayName": "ਮੋਰੱਕਨ ਦਿਰਹਾਮ",
	"BAM_displayName": "ਬੋਸਨੀਆ-ਹਰਜ਼ੇਗੋਵੀਨਾ ਬਦਲਣ੍ਯੋਗ ਮਾਰਕ",
	"BOB_displayName": "ਬੋਲੀਵੀਅਨ ਬੋਲੀਵੀਅਨੋ",
	"BND_displayName": "ਬਰੂਨੇਈ ਡਾਲਰ",
	"SGD_displayName": "ਸਿੰਗਾਪੁਰ ਡਾਲਰ",
	"MVR_displayName": "ਮਾਲਦੀਵੀ ਰੁਫੀਆ",
	"MXN_displayName": "ਮੈਕਸਿਕਨ ਪੈਸੋ",
	"DZD_displayName": "ਅਲਜੀਰਿਆਈ ਦਿਨਾਰ",
	"MXN_symbol": "MX$",
	"JOD_displayName": "ਜੌਰਡਨੀਆਈ ਦਿਨਾਰ",
	"PEN_displayName": "ਪੇਰੂਵੀਅਨ ਨਿਊਵੋ ਸੋਲ",
	"GTQ_displayName": "ਗੁਆਟੇਮਾਲਾ ਕੁਏਟਜ਼ਲ",
	"BYR_displayName": "ਬੇਲਾਰੂਸੀ ਰੂਬਲ",
	"CAD_displayName": "ਕੇਨੇਡਿਆਈ ਡਾਲਰ",
	"BZD_displayName": "ਬੇਲੀਜ਼ ਡਾਲਰ",
	"CLP_displayName": "ਚਿਲੀਅਨ ਪੈਸੋ",
	"XOF_displayName": "ਫ੍ਰੈਂਕ (CFA BCEAO)",
	"NOK_displayName": "ਨੌਰਵੇਜਿਅਨ ਕਰੌਨ",
	"DOP_displayName": "ਡੌਮਿਨਿਕਨ ਪੈਸੋ",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "ਦੱਖਣੀ ਕੋਰੀਆਈ ਵੋਨ",
	"USD_displayName": "ਯੂ.ਐਸ. ਡਾਲਰ",
	"UYU_displayName": "ਉਰੂਗੁਵਾਇਨ ਪੈਸੋ",
	"UZS_displayName": "ਉਜ਼ਬੇਕਿਸਤਾਨ ਸੋਮ",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ਕਤਰੀ ਰਿਆਲ",
	"SAR_displayName": "ਸਾਉਦੀ ਰਿਆਲ",
	"SYP_displayName": "ਸੀਰੀਆਈ ਪਾਉਂਡ",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "ਮਿਸਰੀ ਪਾਉਂਡ",
	"AMD_displayName": "ਆਰਮੀਨਿਆਈ ਦਰਮ",
	"GBP_displayName": "ਬ੍ਰਿਟਿਸ਼ ਪਾਉਂਡ ਸਟਰਲਿੰਗ",
	"HUF_displayName": "ਹੰਗਰਾਈ ਫੋਰਿੰਟ",
	"ISK_displayName": "ਆਈਸਲੈਂਡਿਕ ਕਰੌਨ",
	"IRR_displayName": "ਈਰਾਨੀ ਰਿਆਲ",
	"OMR_displayName": "ਓਮਾਨੀ ਰਿਆਲ",
	"TWD_displayName": "ਨਵਾਂ ਤਾਇਵਾਨ ਡਾਲਰ",
	"PAB_displayName": "ਪਨਾਮੇਨੀਅਨ ਬਾਲਬੋਆ",
	"UAH_displayName": "ਯੂਕਰੇਨੀਆਈ ਰਿਵਨਿਆ",
	"ETB_displayName": "ਇਥੋਪੀਆਈ ਬਿਰ",
	"PLN_displayName": "ਪੋਲਿਸ਼ ਜ਼ਲੌਟੀ",
	"VEF_displayName": "ਵੇਨੇਜ਼ੂਏਲਨ ਬੋਲੀਵਰ",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ਬ੍ਰਾਜ਼ਿਲਿਆਈ ਰੀਅਲ",
	"HKD_symbol": "HK$",
	"HKD_displayName": "ਹਾਂਗ ਕਾਂਗ ਡਾਲਰ",
	"NIO_displayName": "ਨਿਕਾਰਾਗੁਆਨ ਕੋਰਡੋਬਾ",
	"THB_symbol": "฿",
	"NPR_displayName": "ਨੇਪਾਲੀ ਰੁਪਏ",
	"PKR_displayName": "ਪਾਕਿਸਤਾਨੀ ਰੁਪਏ",
	"TWD_symbol": "NT$",
	"GEL_displayName": "ਜਾਰਜਿਆਈ ਲਾਰੀ",
	"AZN_displayName": "ਅਜ਼ਰਬੈਜਾਨੀ ਮਾਨਤ",
	"GBP_symbol": "£",
	"MYR_displayName": "ਮੇਲੇਸ਼ਿਆਈ ਰਿਨਗਿੱਟ",
	"DKK_displayName": "ਦਾਨਿਸ਼ ਕਰੌਨ",
	"THB_displayName": "ਥਾਈ ਬਾਹਤ",
	"BRL_symbol": "R$",
	"JPY_displayName": "ਜਾਪਾਨੀ ਯੇਨ",
	"KES_displayName": "ਕੀਨੀਆਈ ਸ਼ਿਲਿੰਗ",
	"KHR_displayName": "ਕੰਬੋਡੀਆਈ ਰੀਅਲ",
	"PYG_displayName": "ਪੈਰਾਗੁਵਾਇਨ ਗੁਆਰਾਨੀ",
	"VND_symbol": "₫",
	"LKR_displayName": "ਸ੍ਰੀ ਲੰਕਾਈ ਰੁਪਏ",
	"BGN_displayName": "ਬੁਲਗਾਰਿਆਈ ਲੇਵ",
	"BDT_displayName": "ਬੰਗਲਾਦੇਸ਼ੀ ਟਕਾ",
	"MOP_displayName": "ਮੇਕਾਨੀ ਪਟਾਕਾ",
	"HNL_displayName": "ਹਾਨਡੂਰਨ ਲੇਮਪਿਰਾ",
	"RWF_displayName": "ਰਵਾਂਡਨ ਫ੍ਰੈਂਕ",
	"CHF_displayName": "ਸਵਿਸ ਫ੍ਰੈਂਕ",
	"CRC_displayName": "ਕੋਸਟਾ ਰੀਕਨ ਕੋਲਨ",
	"INR_displayName": "ਭਾਰਤੀ ਰੁਪਏ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "ਦੱਖਣੀ ਅਫਰੀਕੀ ਰੈਂਡ",
	"AUD_displayName": "ਆਸਟ੍ਰੇਲੀਆਈ ਡਾਲਰ",
	"LAK_displayName": "ਲਾਓਟਿਆਈ ਕਿਪ",
	"MNT_displayName": "ਮੰਗੋਲੀਆਈ ਤੁਗਰਿਕ",
	"RSD_displayName": "ਸਰਬੀਆਈ ਦਿਨਾਰ",
	"HRK_displayName": "ਕਰੋਏਸ਼ੀਆਈ ਕੁਨਾ"
}
//end v1.x content
);