define("Sage/Groups/nls/zh-tw/GroupManager", {
    "ConfirmDeleteMessage": "您確定要刪除目前的群組?",
    "ConfirmDeleteFmtMessage": "您確定要刪除這個群組: ${0}",
    "InvalidSortStringMessage": "錯誤: 無效的排序字串 - ",
    "InvalidConditionStringMessage": "錯誤: 無效的條件字串 - ",
    "InvalidLayoutConditionStringMessage": "錯誤: 無效的配置字串 - ",
    "noneSelectedTitle": "未選取記錄",
    "noneSelectedPromptFmt": "未選取記錄。將會新增整個群組的 ${0} 筆記錄。要繼續嗎?",
    "noneSelectedRemovePromptFmt": "未選取記錄。將會移除整個群組的 ${0} 筆記錄。",
    "noRecordsInGroup": "這個群組沒有任何可選取的記錄。",
    "newGroupTitle": "將記錄新增至新群組",
    "newGroupNamePrompt": "${0} 選取的記錄會新增至這個新群組。<br><br>群組名稱：<br>${1}",
    "newGroupRePrompt": "&nbsp;&nbsp;<i>請輸入群組名稱。</i>",
    "invalidCharMsg": "名稱不可以包含: / \\ : * ? \" <> | 或 '",
    "groupNameText": "群組名稱:",
    "saveLookupDlgTitle": "將查閱結果儲存為新群組",
    "yesCaption": "是",
    "noCaption": "否",
    "cancelCaption": "取消",
    "okCaption": "確定",
    "LOCALSTORE_NAMESPACE": "SageGroups",
    "exportToExcel": "這個方法已經過時，請參閱 Sage.TaskPane.CommonTasksTasklet.exportToExcel。",
    "createAdHocGroupJob_Description": "群組: ${0}",
    "createAdHocGroupJob_Title": "建立群組",
    "createAdHocGroupJobError": "抱歉，建立群組時發生錯誤: ${0}",
    "createAdHocGroupJobProcessingJobMsg": "您可以繼續等待完成，或者可以關閉此訊息。您會在群組完成時收到通知。"
});