define("Sage/UI/nls/de/BulkUpdateWidget", {
    "dlgBulkActionUpdate_Title": "Aktualisierung als Massenvorgang",
    "pageLoading_Caption": "Eigenschaftsoptionen werden geladen...",
    "header_Caption": "Wählen Sie eine Eigenschaft aus, die aktualisiert werden soll.",
    "header_NoPropertiesEnabled": "${0}-Entität unterstützt Massenaktualisierungen, jedoch sind dafür keine Eigenschaften aktiviert. Wenden Sie sich an Ihren Systemadministrator, um weitere Informationen zu erhalten",
    "errorRequestPropertyOptions": "Fehler beim Lesen von Metadaten für die Entität ${0}. ${1}",
    "errorEntityNotSupported": "Die Entität ${0} unterstützt keine Massenaktualisierungen.",
    "update_Property_Caption": "Aktualisieren:",
    "addProperty_Tooltip": "Eigenschaft hinzufügen",
    "removeProperty_Tooltip": "Eigenschaft entfernen",
    "no_Caption": "Nein",
    "yes_Caption": "Ja",
    "days_Caption": "Tage",
    "moveOut_Caption": "Verschieben",
    "moveTo_Caption": "Auf den",
    "moveDate_Backward": "Zurück",
    "moveDate_Forward": "Vorwärts",
    "update_To_Caption": "In:",
    "lookupHeaderText": "${0} suchen",
    "lookupNameColText": "Name",
    "lookupTitleColText": "Titel",
    "lookupDepartmentColText": "Abteilung",
    "lookupRegionColText": "Region",
    "lookupTypeColText": "Typ",
    "lookupDescriptionColText": "Beschreibung",
    "btnOK_Caption": "OK",
    "btnCancel_Caption": "Abbrechen",
    "errorUnspecifiedValue": "Geben Sie einen Wert ein, bevor Sie den Vorgang fortsetzen, oder entfernen Sie die ungültige Zeile.",
    "errorRequestingJobMgr": "Bei der Aktualisierung ist ein Fehler aufgetreten: ${0}",
    "selectOption_Caption": "Wählen Sie eine Option aus...",
    "updateRecords_Caption": "Ausgewählte Datensätze werden aktualisiert",
    "chkScheduleJob_Caption": "Planen Sie diese Aktualisierung für ein bestimmtes Datum und eine bestimmte Uhrzeit ein.",
    "lookup_Caption": "Suchen",
    "job_Description": "Fehler bei der Massenaktualisierung",
    "errorDuplicateValue": "Die Eigenschaft wurde bereits ausgewählt",
    "errorInvalidPropertyType": "Eigenschaftstyp '${0}' wird für Massenaktualisierungen nicht unterstützt.",
    "calculatedField": "Berechnetes Feld",
    "standardId": "Standard-ID",
    "unknownPropertyType": "Unbekannt"
});