define("Sage/UI/nls/de/NotesHistoryList", {
    "typeText": "Typ",
    "showDbChangesText": "Datenbankänderungen anzeigen",
    "selectAllText": "Alle auswählen",
    "dateText": "Datum",
    "dateTimeText": "Datum/Uhrzeit",
    "dateRangeText": "Datumsbereich",
    "userText": "Benutzer",
    "accountText": "Firma",
    "contactText": "Kontakt",
    "opportunityText": "Verkaufschance",
    "regardingText": "Betreff",
    "notesText": "Notizen",
    "resultText": "Ergebnis",
    "categoryText": "Kategorie",
    "sendEmailText": "Per E-Mail senden",
    "sendToWordText": "An Word senden",
    "addNoteText": "Notiz hinzufügen",
    "completeAnActivityText": "Aktivität abschließen",
    "helpText": "Hilfe",
    "pleaseSelectRecordsText": "Wählen Sie einen oder mehrere Datensätze aus.",
    "UnableToFindWordMsg": "Microsoft Word kann nicht gestartet werden. Überprüfen Sie Ihre Sicherheitseinstellungen.",
    "printedOnText": "Gedruckt am",
    "errorNoData": "Keine an Ming.le freizugebende(n) Notizen/Historie vorhanden.",
    "yesButtonText": "Ja",
    "noButtonText": "Nein",
    "salesLogixPageTitle": "Infor CRM",
    "noRecordsSelectedProcessAll": "Sie haben keine Datensätze ausgewählt. Alle Notizen/die gesamte Historie, ${0} Datensatz/Datensätze, werden/wird an Ming.le freigegeben. Ist es OK, fortzufahren?",
    "errorShareMingle": "Fehler beim Freigeben von einem oder mehreren Notizen-/Historiendatensätzen an Ming.le.",
    "sharedToMingle": "Notizen/Historie wurde(n) freigegeben an Ming.le.",
    "sharingToMingle": "Freigeben an Ming.le",
    "shared": "Freigegeben",
    "pleaseWait": "Bitte warten...",
    "failedToPost": "Senden fehlgeschlagen: ${0}; Fehler: ${1}",
    "addressText": "Adresse",
    "mainPhoneText": "Haupttelefonnummer",
    "tollFreeText": "Gebührenfrei",
    "contactPhoneText": "Telefonnummer des Kontakts"
});