define("Sage/MainView/EntityMgr/nls/zh-tw/_BaseEntityDetailContent", {
    "FilterTabTitle": "篩選",
    "MetricTabTitle": "計量",
    "PropertyTabTitle": "欄位",
    "CalcFieldTabTitle": "計算欄位",
    "EntityTabTitle": "實體",
    "RelationTabTitle": "關聯",
    "dialogTitleAddField": "新增欄位至 ${0} 實體",
    "dialogTitleAddFilter": "新增篩選至 ${0} 實體",
    "dialogTitleAddMetric": "新增計量 ${0} 實體",
    "dialogTitleAddRelationship": "新增關聯至 ${0} 實體",
    "editDialogTitle": "在 ${1} 實體中編輯 ${0}",
    "FilterDialogTitle": "篩選",
    "MetricDialogTitle": "計量",
    "PropertyDialogTitle": "欄位",
    "RelationDialogTitle": "關聯",
    "FilterGridColumnFilter": "篩選名稱",
    "MetricGridColumnMetric": "計量名稱",
    "FilterGridColumnDisplay": "顯示名稱",
    "FilterGridColumnProperty": "欄位",
    "FilterGridColumnType": "計量或篩選",
    "FilterGridColumnIsMetric": "在儀表板",
    "FilterGridColumnLastUpdated": "上次修改",
    "FilterGridColumnDetails": "類型",
    "FilterGridDetailsDistinctFilter": "相異",
    "FilterGridDetailsDateDiffMetricFilter": "日期差異計量",
    "FilterGridDetailsRangeFilter": "範圍",
    "FilterGridDetailsMetricFilter": "計量",
    "FilterGridDetailsUserLookupFilter": "使用者查閱",
    "FilterGridDetailsLookupFilter": "查閱",
    "FilterGridDetailsCustom": "自訂",
    "GridHelp": "說明",
    "FilterGridAdd": "新增篩選",
    "FilterGridRemove": "移除篩選",
    "FilterGridEdit": "編輯篩選",
    "MetricGridAdd": "新增計量",
    "MetricGridRemove": "移除計量",
    "MetricGridEdit": "編輯計量",
    "PropertyGridAdd": "新增欄位",
    "PropertyGridRemove": "移除欄位",
    "PropertyGridEdit": "編輯欄位",
    "CalculatedGridAdd": "新增計算欄位",
    "CalculatedGridRemove": "移除計算欄位",
    "CalculatedGridEdit": "編輯計算欄位",
    "lblFilterName": "篩選名稱",
    "lblDisplayName": "顯示名稱",
    "lblFilterDp": "欄位",
    "lblTypeDp": "類型",
    "lblCharacter": "字元",
    "lblTypeSpecificContentBox": "輸入特定的內容方塊",
    "lblSaveButton": "儲存",
    "lblCancelButton": "取消",
    "lblOkButton": "確定",
    "lblWarning": "請選取一個項目。",
    "confirmDeleteFmtTxt": "您確定要刪除這 ${0} 個項目?",
    "filtersFor": "篩選用於",
    "metricsFor": "計量用於",
    "propertyFor": "欄位用於",
    "calculatedFor": "計算欄位用於",
    "defaultRangeRowValue": "輸入一個值",
    "customSql": "自訂 SQL",
    "displayName": "顯示名稱",
    "lower": "下限",
    "rangeId": "範圍 ID",
    "rangeName": "範圍名稱",
    "upper": "上限",
    "SUM": "總計 (加總)",
    "Contains": "包含",
    "StartsWith": "開始於",
    "EndsWith": "結束於",
    "LessThan": "小於",
    "GreaterThan": "大於",
    "LessThanEqual": "小於或等於",
    "GreaterThanEqual": "大於或等於",
    "Equal": "等於",
    "NotEqual": "不等於",
    "COUNT": "計數",
    "AVG": "平均",
    "MIN": "最小值",
    "MAX": "最大值",
    "totalRecordCountLabel": "記錄總數: ${0}",
    "propertyName": "名稱",
    "Description": "描述",
    "propertyType": "類型",
    "included": "包含",
    "calculatedFields": "已計算",
    "generate": "產生",
    "key": "金鑰",
    "relationFor": "關聯用於",
    "childEntity": "子項",
    "childProperty": "子欄位",
    "parentEntity": "父項",
    "parentProperty": "父欄位",
    "editable": "可編輯",
    "cardinality": "基數",
    "relationship": "關聯",
    "parentImport": "父項匯入",
    "parentMatch": "父項符合",
    "parentAudit": "父項稽核",
    "parentIncluded": "已包含父項",
    "childImport": "子項匯入",
    "childMatch": "子項符合",
    "childAudit": "子項稽核",
    "childIncluded": "已包含子項",
    "text": "文字",
    "memo": "備忘",
    "unicodeText": "unicode 文字",
    "unicodeMemo": "unicode 備忘",
    "integer": "整數",
    "double": "雙倍",
    "single": "單一",
    "decimal": "小數點",
    "short": "簡短",
    "standardId": "標準 ID",
    "trueFalse": "真/假",
    "yesNo": "是/否",
    "boolean": "布林值",
    "dateTime": "日期/時間",
    "email": "電子郵件",
    "phone": "電話",
    "pickList": "挑選清單",
    "owner": "擁有者",
    "lookup": "查閱",
    "dependencyLookup": "相依性查閱",
    "char": "圖表",
    "enum_": "列舉",
    "guid": "guid",
    "byte": "位元組",
    "binary": "二進位",
    "url": "URL",
    "string": "字串",
    "number": "數字",
    "notUniqueFor": "不是唯一的",
    "lblPluralName": "顯示複數名稱",
    "lblTitle": "標題",
    "IsExtension": "是延伸模組",
    "AdvOptions": "進階選項",
    "lblImport": "匯入",
    "lblMatch": "相符",
    "lblBulkUpdate": "大量更新",
    "lblAudited": "已稽核",
    "lblPut": "放置",
    "lblPost": "張貼",
    "lblDelete": "刪除",
    "lblHistory": "追蹤歷程記錄至",
    "metricNotEditable": "此計量不可編輯。"
});