define(
"dojo/cldr/nls/ca/currency", //begin v1.x content
{
	"COP_displayName": "peso colombià",
	"CZK_displayName": "corona txeca",
	"TND_displayName": "dinar tunisià",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "dòlar jamaicà",
	"PHP_displayName": "peso filipí",
	"ALL_displayName": "lek albanès",
	"USD_symbol": "$",
	"LBP_displayName": "lliura libanesa",
	"VND_displayName": "dong vietnamita",
	"LYD_displayName": "dinar libi",
	"RON_displayName": "leu romanès",
	"MKD_displayName": "denar macedoni",
	"SEK_displayName": "corona sueca",
	"CNY_displayName": "iuan xinès",
	"IDR_displayName": "rupia indonèsia",
	"ILS_displayName": "nou xéquel israelià",
	"YER_displayName": "rial iemenita",
	"TJS_displayName": "somoni tadjik",
	"TTD_displayName": "dòlar de Trinitat i Tobago",
	"CNY_symbol": "¥",
	"TRY_displayName": "lira turca",
	"EUR_displayName": "euro",
	"AED_displayName": "dirhem dels Emirats Àrabs Units",
	"KZT_displayName": "tenge kazakh",
	"BHD_displayName": "dinar de Bahrain",
	"RUB_displayName": "ruble rus",
	"NZD_displayName": "dòlar neozelandès",
	"IQD_displayName": "dinar iraquià",
	"TMT_displayName": "manat turcman",
	"ZWL_displayName": "dòlar zimbabuès (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "som kirguís",
	"KWD_displayName": "dinar kuwaitià",
	"AFN_displayName": "afgani afganès",
	"ARS_displayName": "peso argentí",
	"MAD_displayName": "dírham marroquí",
	"BAM_displayName": "marc convertible de Bòsnia i Hercegovina",
	"BOB_displayName": "boliviano bolivià",
	"BND_displayName": "dòlar de Brunei",
	"SGD_displayName": "dòlar de Singapur",
	"MVR_displayName": "rupia de les Maldives",
	"MXN_displayName": "peso mexicà",
	"DZD_displayName": "dinar algerià",
	"MXN_symbol": "MXN",
	"JOD_displayName": "dinar jordà",
	"PEN_displayName": "nou sol peruà",
	"GTQ_displayName": "quetzal guatemalenc",
	"BYR_displayName": "ruble bielorús",
	"CAD_displayName": "dòlar canadenc",
	"BZD_displayName": "dòlar de Belize",
	"CLP_displayName": "peso xilè",
	"XOF_displayName": "franc CFA BCEAO",
	"NOK_displayName": "corona noruega",
	"DOP_displayName": "peso dominicà",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "won sud-coreà",
	"USD_displayName": "dòlar dels Estats Units",
	"UYU_displayName": "peso uruguaià",
	"UZS_displayName": "som uzbek",
	"XOF_symbol": "XOF",
	"QAR_displayName": "riyal de Qatar",
	"SAR_displayName": "rial saudita",
	"SYP_displayName": "lliura síria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "lliura egípcia",
	"AMD_displayName": "dram armeni",
	"GBP_displayName": "lliura esterlina britànica",
	"HUF_displayName": "fòrint hongarès",
	"CSD_displayName": "dinar serbi antic",
	"ISK_displayName": "corona islandesa",
	"IRR_displayName": "rial iranià",
	"OMR_displayName": "rial omanita",
	"TWD_displayName": "nou dòlar de Taiwan",
	"PAB_displayName": "balboa panameny",
	"UAH_displayName": "hrívnia ucraïnesa",
	"ETB_displayName": "birr etíop",
	"PLN_displayName": "zloty polonès",
	"VEF_displayName": "bolívar veneçolà",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "real brasiler",
	"HKD_symbol": "HK$",
	"HKD_displayName": "dòlar de Hong Kong",
	"NIO_displayName": "córdoba oro nicaragüenca",
	"THB_symbol": "฿",
	"NPR_displayName": "rupia nepalesa",
	"PKR_displayName": "rupia pakistanesa",
	"TWD_symbol": "NT$",
	"GEL_displayName": "lari georgià",
	"AZN_displayName": "manat azerbaidjanès",
	"GBP_symbol": "£",
	"MYR_displayName": "ringgit de Malàisia",
	"DKK_displayName": "corona danesa",
	"THB_displayName": "baht tailandès",
	"BRL_symbol": "BRL",
	"JPY_displayName": "ien japonès",
	"KES_displayName": "xíling kenyà",
	"KHR_displayName": "riel cambodjà",
	"PYG_displayName": "guaraní paraguaià",
	"VND_symbol": "₫",
	"LKR_displayName": "rupia de Sri Lanka",
	"BGN_displayName": "lev búlgar",
	"BDT_displayName": "taka de Bangla Desh",
	"MOP_displayName": "pataca de Macau",
	"HNL_displayName": "lempira hondurenya",
	"RWF_displayName": "franc rwandès",
	"CHF_displayName": "franc suís",
	"CRC_displayName": "colón costa-riqueny",
	"INR_displayName": "rupia índia",
	"KRW_symbol": "₩",
	"ZAR_displayName": "rand sud-africà",
	"AUD_displayName": "dòlar australià",
	"LAK_displayName": "kip laosià",
	"MNT_displayName": "tögrög mongol",
	"RSD_displayName": "dinar serbi",
	"HRK_displayName": "kuna croata"
}
//end v1.x content
);