define("Sage/MainView/nls/fr/ActivityManager", {
    "titleFmtString": "${0}",
    "tabDisplayNameActivity": "Activités",
    "tabDisplayNameLit": "Documentation",
    "tabDisplayNameEvent": "Evénements",
    "tabDisplayNameConfirm": "Confirmations",
    "activityColNameComplete": "Terminer",
    "activityColNameAttachment": "Pièce jointe",
    "activityColNameRecurring": "Récurrent",
    "activityColNameAlarm": "Alarme",
    "activityColNameType": "ActivityType",
    "activityColNameStartDate": "StartDate",
    "activityColNameDuration": "Durée",
    "activityColNameContact": "Contact",
    "activityColNameLead": "Lead",
    "activityColNameAccount": "Compte",
    "activityColNameRegarding": "Objet",
    "activityColNamePriority": "Priorité",
    "activityColNameUserId": "Responsable",
    "activityTypePhone": "Téléphone",
    "activityTypeCall": "Appel",
    "activityTypeMeeting": "Rendez-vous",
    "activityTypePersonal": "Personnel"
});