define(
"dojo/cldr/nls/en/currency", //begin v1.x content
{
	"COP_displayName": "Colombian Peso",
	"CZK_displayName": "Czech Republic Koruna",
	"TND_displayName": "Tunisian Dinar",
	"JMD_displayName": "Jamaican Dollar",
	"PHP_displayName": "Philippine Peso",
	"ALL_displayName": "Albanian Lek",
	"USD_symbol": "$",
	"LBP_displayName": "Lebanese Pound",
	"VND_displayName": "Vietnamese Dong",
	"LYD_displayName": "Libyan Dinar",
	"RON_displayName": "Romanian Leu",
	"MKD_displayName": "Macedonian Denar",
	"SEK_displayName": "Swedish Krona",
	"CNY_displayName": "Chinese Yuan",
	"IDR_displayName": "Indonesian Rupiah",
	"ILS_displayName": "Israeli New Sheqel",
	"YER_displayName": "Yemeni Rial",
	"TJS_displayName": "Tajikistani Somoni",
	"TTD_displayName": "Trinidad and Tobago Dollar",
	"TRY_displayName": "Turkish Lira",
	"EUR_displayName": "Euro",
	"AED_displayName": "United Arab Emirates Dirham",
	"KZT_displayName": "Kazakhstani Tenge",
	"BHD_displayName": "Bahraini Dinar",
	"RUB_displayName": "Russian Ruble",
	"NZD_displayName": "New Zealand Dollar",
	"IQD_displayName": "Iraqi Dinar",
	"TMT_displayName": "Turkmenistani Manat",
	"ZWL_displayName": "Zimbabwean Dollar (2009)",
	"KGS_displayName": "Kyrgystani Som",
	"KWD_displayName": "Kuwaiti Dinar",
	"AFN_displayName": "Afghan Afghani",
	"ARS_displayName": "Argentine Peso",
	"MAD_displayName": "Moroccan Dirham",
	"BAM_displayName": "Bosnia-Herzegovina Convertible Mark",
	"BOB_displayName": "Bolivian Boliviano",
	"BND_displayName": "Brunei Dollar",
	"SGD_displayName": "Singapore Dollar",
	"MVR_displayName": "Maldivian Rufiyaa",
	"MXN_displayName": "Mexican Peso",
	"DZD_displayName": "Algerian Dinar",
	"JOD_displayName": "Jordanian Dinar",
	"PEN_displayName": "Peruvian Nuevo Sol",
	"GTQ_displayName": "Guatemalan Quetzal",
	"BYR_displayName": "Belarusian Ruble",
	"CAD_displayName": "Canadian Dollar",
	"BZD_displayName": "Belize Dollar",
	"CLP_displayName": "Chilean Peso",
	"XOF_displayName": "CFA Franc BCEAO",
	"NOK_displayName": "Norwegian Krone",
	"DOP_displayName": "Dominican Peso",
	"JPY_symbol": "¥",
	"KRW_displayName": "South Korean Won",
	"USD_displayName": "US Dollar",
	"UYU_displayName": "Uruguayan Peso",
	"UZS_displayName": "Uzbekistan Som",
	"QAR_displayName": "Qatari Rial",
	"SAR_displayName": "Saudi Riyal",
	"SYP_displayName": "Syrian Pound",
	"EGP_displayName": "Egyptian Pound",
	"AMD_displayName": "Armenian Dram",
	"GBP_displayName": "British Pound Sterling",
	"HUF_displayName": "Hungarian Forint",
	"CSD_displayName": "Serbian Dinar (2002–2006)",
	"ISK_displayName": "Icelandic Króna",
	"IRR_displayName": "Iranian Rial",
	"OMR_displayName": "Omani Rial",
	"TWD_displayName": "New Taiwan Dollar",
	"PAB_displayName": "Panamanian Balboa",
	"UAH_displayName": "Ukrainian Hryvnia",
	"ETB_displayName": "Ethiopian Birr",
	"PLN_displayName": "Polish Zloty",
	"VEF_displayName": "Venezuelan Bolívar",
	"BRL_displayName": "Brazilian Real",
	"HKD_displayName": "Hong Kong Dollar",
	"NIO_displayName": "Nicaraguan Córdoba",
	"NPR_displayName": "Nepalese Rupee",
	"PKR_displayName": "Pakistani Rupee",
	"GEL_displayName": "Georgian Lari",
	"AZN_displayName": "Azerbaijani Manat",
	"MYR_displayName": "Malaysian Ringgit",
	"DKK_displayName": "Danish Krone",
	"THB_displayName": "Thai Baht",
	"JPY_displayName": "Japanese Yen",
	"KES_displayName": "Kenyan Shilling",
	"KHR_displayName": "Cambodian Riel",
	"PYG_displayName": "Paraguayan Guarani",
	"LKR_displayName": "Sri Lankan Rupee",
	"BGN_displayName": "Bulgarian Lev",
	"BDT_displayName": "Bangladeshi Taka",
	"MOP_displayName": "Macanese Pataca",
	"HNL_displayName": "Honduran Lempira",
	"RWF_displayName": "Rwandan Franc",
	"CHF_displayName": "Swiss Franc",
	"CRC_displayName": "Costa Rican Colón",
	"INR_displayName": "Indian Rupee",
	"ZAR_displayName": "South African Rand",
	"AUD_displayName": "Australian Dollar",
	"LAK_displayName": "Laotian Kip",
	"MNT_displayName": "Mongolian Tugrik",
	"RSD_displayName": "Serbian Dinar",
	"HRK_displayName": "Croatian Kuna"
}
//end v1.x content
);