define(
"dojo/cldr/nls/kn/currency", //begin v1.x content
{
	"COP_displayName": "ಕೊಲೊಂಬಿಯೋದ ಪೆಸೊ",
	"CZK_displayName": "ಝೆಕ್ ಗಣರಾಜ್ಯ ಕೊರೂನ",
	"TND_displayName": "ತುನೀಸಿಯನ್ ದಿನಾರ್",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ಜಮೈಕನ್ ಡಾಲರ್",
	"PHP_displayName": "ಫಿಲಿಪ್ಪೈನ್ ಪೆಸೊ",
	"ALL_displayName": "ಅಲ್ಬೇನಿಯನ್ ಲೆಕ್",
	"USD_symbol": "US$",
	"LBP_displayName": "ಲೆಬೆನೀಸ್ ಪೌಂಡ್",
	"VND_displayName": "ವಿಯೆಟ್ನಾಮೀಸ್ ಡಾಂಗ್",
	"LYD_displayName": "ಲಿಬಿಯಾದ ದಿನಾರ್",
	"RON_displayName": "ರೊಮೇನಿಯನ್ ಲೆವು",
	"MKD_displayName": "ಮೆಸಡೋನಿಯನ್ ದಿನಾರ್",
	"SEK_displayName": "ಸ್ವೀಡಿಶ್ ಕ್ರೋನಾ",
	"CNY_displayName": "ಚೈನೀಸ್ ಯುವಾನ್",
	"IDR_displayName": "ಇಂಡೊನೇಷ್ಯಾ ರುಪೈ",
	"ILS_displayName": "ಇಸ್ರೇಲಿ ನ್ಯೂ ಶೇಖಲ್",
	"YER_displayName": "ಯೆಮನಿ ರಿಯಲ್",
	"TJS_displayName": "ತಜಕಿಸ್ತಾನಿ ಸೊಮೋನಿ",
	"TTD_displayName": "ತ್ರಿನಿದಾದ್ ಮತ್ತು ಟೊಬಾಗೊ ಡಾಲರ್",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "ತುರ್ಕಿಶ್ ಲಿರಾ",
	"EUR_displayName": "ಯೂರೊ",
	"AED_displayName": "ಸಂಯುಕ್ತ ಅರಬ್ ಎಮಿರೇಟ್ಗಳ ದಿರಾಮ್",
	"KZT_displayName": "ಕಜಕಿಸ್ತಾನ್ ತೆಂಗೇ",
	"BHD_displayName": "ಬಹ್ರೈನಿ ದಿನಾರ್",
	"RUB_displayName": "ರಶಿಯನ್ ರೂಬಲ್",
	"NZD_displayName": "ನ್ಯೂಜಿಲ್ಯಾಂಡ್ ಡಾಲರ್",
	"IQD_displayName": "ಇರಾಖಿಯನ್ ದಿನಾರ್",
	"TMT_displayName": "ತುರ್ಕ್ಮೇನಿಸ್ತಾನಿ ಮನಾತ್",
	"INR_symbol": "₹",
	"KGS_displayName": "ಕಿರ್ಗಿಸ್ತಾನಿ ಸೋಮ್",
	"KWD_displayName": "ಕುವೈತೀ ದಿನಾರ್",
	"AFN_displayName": "ಅಫ್ಘನ್ ಅಫಗಾನಿ",
	"ARS_displayName": "ಅರ್ಜೆಂಟಿನಾ ಪೆಸೊ",
	"MAD_displayName": "ಮೊರೊಕನ್ ದಿರ್ಹಮ್",
	"BAM_displayName": "ಬೋಸ್ನಿಯಾ-ಹರ್ಜ್ಗೋವಿನ ಪರಿವರ್ತನೀಯ ಗುರುತು",
	"BOB_displayName": "ಬೊಲಿವಿಯಾದ ಬೊಲಿವಿಯಾನೊ",
	"BND_displayName": "ಬ್ರೂನಿ ಡಾಲರ್",
	"SGD_displayName": "ಸಿಂಗಾಪುರ್ ಡಾಲರ್",
	"MVR_displayName": "ಮಾಲ್ಡೀವಿಯನ್ ರುಫಿಯಾ",
	"MXN_displayName": "ಮೆಕ್ಸಿಕೊದ ಪೆಸೊ",
	"DZD_displayName": "ಅಲ್ಗೇರಿಯನ್ ದಿನಾರ್",
	"MXN_symbol": "MX$",
	"JOD_displayName": "ಜೋರ್ಡಾನಿಯನ್ ದಿನಾರ್",
	"PEN_displayName": "ಪೆರುವಿಯನ್ ನವೆವೋ ಸೊಲ್",
	"GTQ_displayName": "ಗ್ವಾಟೆಮಾಲಾದ ಕುಯಿಟ್ಸಲ್",
	"BYR_displayName": "ಬೆಲಾರುಸಿಯನ್ ರೂಬಲ್",
	"CAD_displayName": "ಕೆನಡಾದ ಡಾಲರ್",
	"BZD_displayName": "ಬೆಲೀಜ್ ಡಾಲರ್",
	"CLP_displayName": "ಚಿಲಿಯ ಪೆಸೊ",
	"XOF_displayName": "CFA ಫ್ರಾಂಕ್ BCEAO",
	"NOK_displayName": "ನಾರ್ವೇಜಿಯನ್ ಕ್ರೋನ್",
	"DOP_displayName": "ಡೊಮಿನಿಕನ್ ಪೆಸೊ",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "ದಕ್ಷಿಣ ಕೊರಿಯನ್ ವೊನ್",
	"USD_displayName": "ಅಮೆರಿಕದ ಡಾಲರ್",
	"UYU_displayName": "ಉರುಗ್ವೆಯ ಪೆಸೊ",
	"UZS_displayName": "ಉಜ್ಬೈಕಿಸ್ತಾನ್ ಸೋಮ್",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ಖತಾರಿ ರಿಯಲ್",
	"SAR_displayName": "ಸೌದಿ ರಿಯಾಲ್",
	"SYP_displayName": "ಸಿರಿಯನ್ ಪೌಂಡ್",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "ಈಜಿಪ್ಟಿಯನ್ ಪೌಂಡ್",
	"AMD_displayName": "ಅರ್ಮೇನಿಯನ್ ಡ್ರಾಮ್",
	"GBP_displayName": "ಬ್ರಿಟೀಷ್ ಪೌಂಡ್ ಸ್ಟೆರ್ಲಿಂಗ್",
	"HUF_displayName": "ಹಂಗೇರಿಯನ್ ಫೋರಿಂಟ್",
	"ISK_displayName": "ಐಸ್ಲ್ಯಾಂಡಿಕ್ ಕ್ರೋನಾ",
	"IRR_displayName": "ಇರಾನಿಯನ್ ರಿಯಲ್",
	"OMR_displayName": "ಒಮಾನಿ ರಿಯಲ್",
	"TWD_displayName": "ನ್ಯೂ ತೈವಾನ್ ಡಾಲರ್",
	"PAB_displayName": "ಪನಾಮಾನಿಯನ್ ಬಲ್ಬೋವಾ",
	"UAH_displayName": "ಉಕ್ರೇನಿಯನ್ ಹ್ರಿವ್ನೀಯ",
	"ETB_displayName": "ಇಥಿಯೋಪಿಯನ್ ಬಿರ್",
	"PLN_displayName": "ಪೊಲಿಶ್ ಝ್ಲೋಟಿ",
	"VEF_displayName": "ವೆನಿಜುಲಿಯನ್ ಬೊಲಿವರ್",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ಬ್ರೆಜಿಲಿಯನ್ ರಿಯಲ್",
	"HKD_symbol": "HK$",
	"HKD_displayName": "ಹಾಂಗ್ ಕಾಂಗ್ ಡಾಲರ್",
	"NIO_displayName": "ನಿಕಾರಗ್ವಾದ ಕರ್ದೊಬಾ",
	"THB_symbol": "฿",
	"NPR_displayName": "ನೇಪಾಳದ ರುಪೀ",
	"PKR_displayName": "ಪಾಕಿಸ್ತಾನದ ರುಪೀ",
	"TWD_symbol": "NT$",
	"GEL_displayName": "ಜಾರ್ಜಿಯಾದ ಲಾರಿ",
	"AZN_displayName": "ಅಝರ್ಬೈಜಾನಿ ಮನಾತ್",
	"GBP_symbol": "£",
	"MYR_displayName": "ಮಲೇಶಿಯನ್ ರಿಂಗಿಟ್ಟ್",
	"DKK_displayName": "ಡ್ಯಾನಿಶ್ ಕ್ರೋನ್",
	"THB_displayName": "ಥಾಯ್ ಬಹ್ತ್",
	"BRL_symbol": "R$",
	"JPY_displayName": "ಜಪಾನೀಸ್ ಯೆನ್",
	"KES_displayName": "ಕೆನ್ಯನ್ ಶಿಲ್ಲಿಂಗ್",
	"KHR_displayName": "ಕಾಂಬೋಡಿಯನ್ ರಿಯಲ್",
	"PYG_displayName": "ಪೆರುಗ್ವೇಯ ಗ್ವಾರನೀ",
	"VND_symbol": "₫",
	"LKR_displayName": "ಶ್ರೀಲಂಕಾದ ರುಪೀ",
	"BGN_displayName": "ಬಲ್ಗೇರಿಯನ್ ಲೀವ್",
	"BDT_displayName": "ಬಾಂಗ್ಲಾದೇಶದ ಟಾಕಾ",
	"MOP_displayName": "ಮಕ್ಯೂದ ಪಟಕಾ",
	"HNL_displayName": "ಹೊಂಡುರಾನ್ ಲೆಂಪಿರಾ",
	"RWF_displayName": "ರಾವಂದನ್ ಫ್ರಾಂಕ್",
	"CHF_displayName": "ಸ್ವಿಸ್ ಫ್ರಾಂಕ್",
	"CRC_displayName": "ಕೋಸ್ಟಾ ರಿಕಾದ ಕೊಲೊನ್",
	"INR_displayName": "ಭಾರತೀಯ ರುಪಾಯಿ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "ದಕ್ಷಿಣ ಆಫ್ರಿಕನ್ ರಾಂಡ್",
	"AUD_displayName": "ಆಸ್ಟ್ರೇಲಿಯನ್ ಡಾಲರ್",
	"LAK_displayName": "ಲೋಟಿಯನ್ ಕಿಪ್",
	"MNT_displayName": "ಮಂಗೋಲಿಯಾದ ತುಗ್ರಿಕ್",
	"RSD_displayName": "ಸೆರ್ಬಿಯನ್ ದಿನಾರ್",
	"HRK_displayName": "ಕ್ರೊಯೆಷ್ಯಾದ ಕೂನಾ"
}
//end v1.x content
);