define("Sage/UI/Filters/nls/de/CheckBoxFilter", {
    "loadingText": "Wird geladen...",
    "moreText": "Elemente bearbeiten",
    "clearText": "Auswahl aufheben",
    "emptyText": "(Leer)",
    "nullText": "(Null)",
    "ofText": "/",
    "filterHasMetric": "Besitzt Kennzahl",
    "filterHasFilter": "Besitzt Filter",
    "filteroptionYesterday": "Gestern",
    "filteroptionToday": "Heute",
    "filteroptionThisWeek": "Diese Woche",
    "filteroptionThisMonth": "In diesen Monaten",
    "filteroptionThisQuarter": "Dieses Quartal",
    "filteroptionThisYear": "Dieses Jahr",
    "filteroptionLastWeek": "Letzte Woche",
    "filteroptionLastMonth": "Letzter Monat",
    "filteroptionLastQuarter": "Letztes Quartal",
    "filteroptionLastYear": "Letztes Jahr",
    "filteroptionWeektoStart": "Woche bis heute",
    "filteroptionMonthtoStart": "Monat bis heute",
    "filteroptionQtrtoStart": "Quartal bis heute",
    "filteroptionYeartoStart": "Jahr bis heute",
    "filteroptionOlder": "Älter",
    "filteroption0To999": "0 bis 999",
    "filteroption1000To9999": "1000 bis 9999",
    "filteroption10000To99999": "10.000 bis 99.999",
    "filteroption100000To499999": "100.000 bis 499.999",
    "filteroption500000To999999": "500.000 bis 999.999",
    "filteroption1000000AndHigher": "1.000.000 und mehr",
    "filteroptionT": "W"
});