define(
"dojo/cldr/nls/af/currency", //begin v1.x content
{
	"COP_displayName": "Colombiaanse peso",
	"CZK_displayName": "Tsjeggiese kroon",
	"TND_displayName": "Tunisiese dinar",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaikaanse dollar",
	"PHP_displayName": "Filippynse peso",
	"ALL_displayName": "Albanese lek",
	"USD_symbol": "US$",
	"LBP_displayName": "Lebanese pond",
	"VND_displayName": "Viëtnamese dong",
	"LYD_displayName": "Libiese dinar",
	"RON_displayName": "Roemeense leu",
	"MKD_displayName": "Macedoniese denar",
	"SEK_displayName": "Sweedse kroon",
	"CNY_displayName": "Sjinese joean renminbi",
	"IDR_displayName": "Indonesiese roepia",
	"ILS_displayName": "Israeliese nuwe sikkel",
	"YER_displayName": "Jemenitiese rial",
	"TJS_displayName": "Tadjikse roebel",
	"TTD_displayName": "Trinidad en Tobago dollar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Turkse lier",
	"EUR_displayName": "Euro",
	"AED_displayName": "Verenigde Arabiese Emirate dirham",
	"KZT_displayName": "Kazakse tenge",
	"BHD_displayName": "Bahrainse dinar",
	"RUB_displayName": "Russiese roebel",
	"NZD_displayName": "Nieu-Seeland dollar",
	"IQD_displayName": "Irakse dinar",
	"TMT_displayName": "Toerkmeense manat",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgisiese som",
	"KWD_displayName": "Koeweitse dinar",
	"AFN_displayName": "Afgaanse afgani",
	"ARS_displayName": "Argentynse peso",
	"MAD_displayName": "Marokkaanse dirham",
	"BAM_displayName": "Bosnië en Herzegowina omskakelbare marka",
	"BOB_displayName": "Boliviaanse boliviano",
	"BND_displayName": "Broeneise dollar",
	"SGD_displayName": "Singapoer-dollar",
	"MVR_displayName": "Malediviese rufia",
	"MXN_displayName": "Meksikaanse peso",
	"ZAR_symbol": "R",
	"MXN_symbol": "MX$",
	"DZD_displayName": "Algeriese dinar",
	"JOD_displayName": "Jordaniese dinar",
	"PEN_displayName": "Peruaanse nuwe sol",
	"GTQ_displayName": "Guatemalaanse quetzal",
	"BYR_displayName": "Belo-Russiese roebel",
	"CAD_displayName": "Kanadese dollar",
	"BZD_displayName": "Beliziese dollar",
	"CLP_displayName": "Chileense peso",
	"XOF_displayName": "CFA frank BCEAO",
	"NOK_displayName": "Noorse kroon",
	"DOP_displayName": "Dominikaanse peso",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Suid-Koreaanse won",
	"USD_displayName": "Amerikaanse dollar",
	"UYU_displayName": "Uruguaanse peso",
	"UZS_displayName": "Oezbekiese som",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Katarese rial",
	"SAR_displayName": "Saoedi-Arabiese riyal",
	"SYP_displayName": "Siriese pond",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Egiptiese pond",
	"AMD_displayName": "Armeense dram",
	"GBP_displayName": "Britse pond",
	"ISK_displayName": "Yslandse kroon",
	"IRR_displayName": "Iranse rial",
	"OMR_displayName": "Omaanse rial",
	"TWD_displayName": "Nuwe Taiwanese dollar",
	"PAB_displayName": "Panamese balboa",
	"UAH_displayName": "Oekraïnse hriwna",
	"ETB_displayName": "Etiopiese birr",
	"PLN_displayName": "Poolse zloty",
	"VEF_displayName": "Venezolaanse bolivar",
	"ILS_symbol": "₪",
	"BRL_displayName": "Brasiliaanse real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hong Kong dollar",
	"NIO_displayName": "Nicaraguaanse córdoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepalese roepee",
	"PKR_displayName": "Pakistanse roepee",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Georgiese lari",
	"AZN_displayName": "Azerbeidjaanse manat",
	"GBP_symbol": "£",
	"MYR_displayName": "Maleisiese ringgit",
	"DKK_displayName": "Deense kroon",
	"THB_displayName": "Thaise baht",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japannese jen",
	"KES_displayName": "Keniaanse sjieling",
	"KHR_displayName": "Kambodjaanse riel",
	"PYG_displayName": "Paraguaanse guarani",
	"VND_symbol": "₫",
	"LKR_displayName": "Sri Lankaanse roepee",
	"BGN_displayName": "Bulgaarse lev",
	"BDT_displayName": "Bangladesjiese taka",
	"MOP_displayName": "Macaose pataca",
	"HNL_displayName": "Hondurese lempira",
	"RWF_displayName": "Rwandiese frank",
	"CHF_displayName": "Switserse frank",
	"CRC_displayName": "Costa Ricaanse colón",
	"INR_displayName": "Indiese rupee",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Suid-Afrikaanse rand",
	"AUD_displayName": "Australiese dollar",
	"LAK_displayName": "Laosiaanse kip",
	"MNT_displayName": "Mongoolse toegrik",
	"RSD_displayName": "Serbiese dinar",
	"HRK_displayName": "Kroatiese kuna"
}
//end v1.x content
);