define(
"dojo/cldr/nls/km/currency", //begin v1.x content
{
	"COP_displayName": "ប៉ឺហ្សូ កូឡុំប៊ី",
	"CZK_displayName": "កូរុណា សាធារណៈឆេក",
	"TND_displayName": "ឌីណា ទុយនីស៊ី",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ដុល្លារ ហ្សាម៉ាអ៊ីក",
	"PHP_displayName": "ប៉ឺហ្សូ ហ្វីលីពីន",
	"ALL_displayName": "លិក អាល់បានី",
	"USD_symbol": "US$",
	"LBP_displayName": "ផោន លីបង់",
	"VND_displayName": "ដុង វៀតណាម",
	"LYD_displayName": "ឌីណា លីប៊ី",
	"RON_displayName": "លូ រូម៉ានី",
	"MKD_displayName": "ឌីណា ម៉ាសេដ្វាន",
	"SEK_displayName": "ក្រូណា ស៊ុយអែត",
	"CNY_displayName": "យ៉ន់ ចិន",
	"IDR_displayName": "រ៉ូព៉្យាស ឥណ្ឌូណេស៊ី",
	"ILS_displayName": "ស្ស៊ីហ្គែល អ៊ីស្រាអែល",
	"YER_displayName": "រៀល យេម៉ែន",
	"TJS_displayName": "សូមុនី តាហ្ស៊ីគីស្ថាន",
	"TTD_displayName": "ដុល្លារ ទ្រីនីដាដ និងតូបាហ្គោ",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "លីរ៉ា ទួគី",
	"EUR_displayName": "អឺរ៉ូ",
	"AED_displayName": "ឌៀរហាំ អេមីរ៉ាតអារ៉ាប់រួម",
	"KZT_displayName": "តង់ហ្គី កាហ្សាក់ស្ថាន",
	"BHD_displayName": "ឌីណា បារ៉ែន",
	"RUB_displayName": "រ៉ូបល រុស្ស៊ី",
	"NZD_displayName": "ដុល្លារ នូវែលសេឡង់",
	"IQD_displayName": "ឌីណា អ៊ីរ៉ាក់",
	"TMT_displayName": "ម៉ាណាត តួកម៉េនីស្ថាន",
	"INR_symbol": "₹",
	"KGS_displayName": "សុម កៀហ្ស៊ីស៊ីស្ថាន",
	"KWD_displayName": "ឌីណា គុយវ៉ែត",
	"AFN_displayName": "អាហ្វហ្គានី អាហ្វហ្គានីស្ថាន",
	"ARS_displayName": "ប៉ឺហ្សូ អាហ្សង់ទីន",
	"MAD_displayName": "ឌៀរហាំ ម៉ារ៉ុក",
	"BAM_displayName": "ម៉ាក ខុនវើ់ទីបល បូស្នី",
	"BOB_displayName": "បូលីវីណូ បូលីវី",
	"BND_displayName": "ដុល្លារ ប្រុយណេ",
	"SGD_displayName": "ដុល្លារ សិង្ហបូរី",
	"MVR_displayName": "រ៉ូហ្វីយ៉ា ម៉ាល់ឌីវ",
	"MXN_displayName": "ប៉ីហ្សូ ម៉ិកស៉ិក",
	"DZD_displayName": "ឌីណា អាល់ស៊េរី",
	"MXN_symbol": "MX$",
	"JOD_displayName": "ឌីណា ហ្ស៊កដានី",
	"PEN_displayName": "ញូវ៉ូសូល ប៉េរូ",
	"GTQ_displayName": "ហ្គីស្សាល ក្វាតេម៉ាឡា",
	"BYR_displayName": "រ៉ូបល បេឡារុស",
	"CAD_displayName": "ដុល្លារ កាណាដា",
	"BZD_displayName": "ដុល្លារ បេលី",
	"CLP_displayName": "ប៉ឺហ្សូ ស៊ីលី",
	"XOF_displayName": "ហ្វ្រង់ BCEAO CFA",
	"NOK_displayName": "ក្រូណេ ន័រវ៉េ",
	"DOP_displayName": "ប៉ឺហ្សូ ដូមីនីក",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "វូន កូរ៉េខាងត្បូង",
	"USD_displayName": "ដុល្លារ អាមេរិក",
	"UYU_displayName": "ប៉ឺហ្សូ អ៊ុយរូហ្គាយ",
	"UZS_displayName": "សុម អ៊ូសបេគីស្ថាន",
	"XOF_symbol": "CFA",
	"QAR_displayName": "រៀល កាតា",
	"SAR_displayName": "រីយ៉ាល អារ៉ាប៊ីសាអូឌីត",
	"SYP_displayName": "ផោន ស៊ីរី",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "ផោន អេហ្សីប",
	"AMD_displayName": "ដ្រាំ អាមេនី",
	"GBP_displayName": "ផោនស្ទែរលិញ ចក្រភពអង់គ្លេស",
	"HUF_displayName": "ហ្វូរីន ហុងគ្រី",
	"ISK_displayName": "ក្រូណា អ៊ីស្លង់",
	"IRR_displayName": "រៀល អ៊ីរ៉ង់",
	"OMR_displayName": "រៀល រូម៉ានី",
	"TWD_displayName": "ដុល្លារ តៃវ៉ាន់",
	"PAB_displayName": "បាល់ប៉ៅ ប៉ាណាម៉ា",
	"UAH_displayName": "ហ៊ូនីយ៉ា អ៊ុយក្រែន",
	"ETB_displayName": "ប៊័រ អេត្យូពី",
	"PLN_displayName": "ហ្សូទី ប៉ូឡូញ",
	"VEF_displayName": "ប៊ូលីវ៉ា វ៉េណេស៊ុយអេឡា",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "រៀល ប្រេស៊ីល",
	"HKD_symbol": "HK$",
	"HKD_displayName": "ដុល្លារ ហុងកុង",
	"NIO_displayName": "ខឌូបា នីការ៉ាហ្គា",
	"THB_symbol": "฿",
	"NPR_displayName": "រ៉ូពី នេប៉ាល់",
	"PKR_displayName": "រ៉ូពី ប៉ាគីស្ថាន",
	"TWD_symbol": "NT$",
	"GEL_displayName": "ឡារី ហ្សកហ្ស៊ី",
	"AZN_displayName": "ម៉ាណាត អាស៊ែបៃហ្សង់",
	"GBP_symbol": "£",
	"MYR_displayName": "រីងហ្គីត ម៉ាឡេស៊ី",
	"DKK_displayName": "ក្រូណេ ដាណាម៉ាក់",
	"THB_displayName": "បាត ថៃ",
	"BRL_symbol": "R$",
	"JPY_displayName": "យេន ជប៉ុន",
	"KES_displayName": "ស៊ីលិញ កេនយ៉ា",
	"KHR_displayName": "រៀល កម្ពុជា",
	"PYG_displayName": "ហ្គូរីនី ប៉ារ៉ាហ្គាយ",
	"VND_symbol": "₫",
	"LKR_displayName": "រ៉ូពី ស្រីលង្ការ",
	"BGN_displayName": "លីវ ប៊ុលហ្គារី",
	"BDT_displayName": "តាកា បង់ក្លាដែស",
	"MOP_displayName": "ប៉ាតាកា ម៉ាកាវ",
	"HNL_displayName": "លិមពីរ៉ា ហុងឌូរ៉ាស",
	"RWF_displayName": "ហ្វ្រង់ រវ៉ាន់ដា",
	"CHF_displayName": "ហ្វ្រង់ ស្វីស",
	"KHR_symbol": "៛",
	"CRC_displayName": "កូឡុង កូស្តារីកា",
	"INR_displayName": "រ៉ូពី ឥណ្ឌា",
	"KRW_symbol": "₩",
	"ZAR_displayName": "រ៉ង់ អាព្រិកខាងត្បូង",
	"AUD_displayName": "ដុល្លារ អូស្ត្រាលី",
	"LAK_displayName": "គីប ឡាវ",
	"MNT_displayName": "ទូរីក ម៉ុងហ្គោលី",
	"RSD_displayName": "ឌីណា សើប",
	"HRK_displayName": "គូណា ក្រូអាត"
}
//end v1.x content
);