define(
"dojo/cldr/nls/gsw/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbianische Peso",
	"CZK_displayName": "Tschechischi Chroone",
	"TND_displayName": "Tuneesische Dinar",
	"JMD_displayName": "Jamaika-Dollar",
	"PHP_displayName": "Philippiinische Peso",
	"ALL_displayName": "Lek",
	"USD_symbol": "$",
	"LBP_displayName": "Libaneesischs Pfund",
	"VND_displayName": "Dong",
	"LYD_displayName": "Lüübische Dinar",
	"RON_displayName": "Rumäänische Löi",
	"MKD_displayName": "Denar",
	"SEK_displayName": "Schweedischi Chroone",
	"CNY_displayName": "Renminbi Yuan",
	"IDR_displayName": "Indonesischi Rupie",
	"ILS_displayName": "Schekel",
	"YER_displayName": "Jeme-Rial",
	"TJS_displayName": "Tadschikischtan-Somoni",
	"TTD_displayName": "Trinidad-und-Tobago-Dollar",
	"TRY_displayName": "Nöii Türkischi Liire",
	"EUR_displayName": "Euro",
	"AED_displayName": "UAE Dirham",
	"KZT_displayName": "Tenge",
	"BHD_displayName": "Bahrain-Dinar",
	"RUB_displayName": "Russische Rubel",
	"NZD_displayName": "Neuseeland-Dollar",
	"IQD_displayName": "Irak-Dinar",
	"KGS_displayName": "Som",
	"KWD_displayName": "Kuwait-Dinar",
	"AFN_displayName": "Afghani",
	"ARS_displayName": "Argentinische Peso",
	"MAD_displayName": "Marokkanische Dirham",
	"BAM_displayName": "Konvertierbari Mark vo Bosnie und Herzegowina",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Brunei-Dollar",
	"SGD_displayName": "Singapur-Dollar",
	"MVR_displayName": "Rufiyaa",
	"MXN_displayName": "Mexikanische Peso",
	"DZD_displayName": "Algeerischi Dinar",
	"JOD_displayName": "Jordaanische Dinar",
	"PEN_displayName": "Nöie Sol",
	"GTQ_displayName": "Quetzal",
	"BYR_displayName": "Belarus Rubel (nöi)",
	"CAD_displayName": "Kanadische Dollar",
	"BZD_displayName": "Belize-Dollar",
	"CLP_displayName": "Tschileenische Peso",
	"XOF_displayName": "CFA-Franc (Wescht)",
	"NOK_displayName": "Norweegischi Chroone",
	"DOP_displayName": "Tominikanische Peso",
	"JPY_symbol": "¥",
	"KRW_displayName": "Süüdkoreanische Won",
	"USD_displayName": "US-Dollar",
	"UYU_displayName": "Uruguayische Peso",
	"UZS_displayName": "Usbeekischtan-Sum",
	"QAR_displayName": "Katar-Riyal",
	"SAR_displayName": "Saudi-Riyal",
	"SYP_displayName": "Süürischs Pfund",
	"EGP_displayName": "Ägüptischs Pfund",
	"AMD_displayName": "Dram",
	"GBP_displayName": "Pfund Schtörling",
	"HUF_displayName": "Forint",
	"CSD_displayName": "Alte Serbische Dinar",
	"ISK_displayName": "Iisländischi Chroone",
	"IRR_displayName": "Rial",
	"OMR_displayName": "Rial Omani",
	"TWD_displayName": "Nöii Taiwan-Dollar",
	"PAB_displayName": "Balboa",
	"UAH_displayName": "Hryvnia",
	"ETB_displayName": "Äthiopische Birr",
	"PLN_displayName": "Zloty",
	"VEF_displayName": "Bolivar",
	"BRL_displayName": "Brasilianische Real",
	"HKD_displayName": "Hongkong-Dollar",
	"NIO_displayName": "Nicaragua-Córdoba",
	"NPR_displayName": "Nepaleesischi Rupie",
	"CHF_symbol": "CHF",
	"PKR_displayName": "Pakischtanischi Rupie",
	"GEL_displayName": "Georgische Lari",
	"AZN_displayName": "Aserbeidschanische Manat",
	"MYR_displayName": "Malaysische Ringgit",
	"DKK_displayName": "Tänischi Chroone",
	"THB_displayName": "Baht",
	"JPY_displayName": "Yen",
	"KES_displayName": "Kenia-Schilling",
	"KHR_displayName": "Riel",
	"PYG_displayName": "Guarani",
	"LKR_displayName": "Sri-Lanka-Rupie",
	"BGN_displayName": "Bulgarische Lew",
	"BDT_displayName": "Taka",
	"MOP_displayName": "Pataca",
	"HNL_displayName": "Lempira",
	"RWF_displayName": "Ruanda-Franc",
	"CHF_displayName": "Schwiizer Franke",
	"CRC_displayName": "Costa Rica Colon",
	"INR_displayName": "Indischi Rupie",
	"ZAR_displayName": "Rand",
	"AUD_displayName": "Auschtralische Dollar",
	"LAK_displayName": "Kip",
	"MNT_displayName": "Tugrik",
	"RSD_displayName": "Serbische Dinar",
	"HRK_displayName": "Kuna"
}
//end v1.x content
);