define(
"dojo/cldr/nls/vi/currency", //begin v1.x content
{
	"COP_displayName": "Peso Colombia",
	"CZK_displayName": "Koruna Cộng hòa Séc",
	"TND_displayName": "Dinar Tunisia",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Đô la Jamaica",
	"PHP_displayName": "Peso Philipin",
	"ALL_displayName": "Lek Albania",
	"USD_symbol": "US$",
	"LBP_displayName": "Bảng Li-băng",
	"VND_displayName": "Đồng Việt Nam",
	"LYD_displayName": "Dinar Libi",
	"RON_displayName": "Leu Romania",
	"MKD_displayName": "Denar Macedonia",
	"SEK_displayName": "Krona Thụy Điển",
	"CNY_displayName": "Nhân dân tệ",
	"IDR_displayName": "Rupiah Indonesia",
	"ILS_displayName": "Sheqel Israel mới",
	"YER_displayName": "Rial Yemen",
	"TJS_displayName": "Somoni Tajikistan",
	"TTD_displayName": "Đô la Trinidad và Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lia Thổ Nhĩ Kỳ",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham UAE",
	"KZT_displayName": "Tenge Kazakhstan",
	"BHD_displayName": "Dinar Bahrain",
	"RUB_displayName": "Rúp Nga",
	"NZD_displayName": "Đô la New Zealand",
	"IQD_displayName": "Dinar I-rắc",
	"TMT_displayName": "Manat Turkmenistan",
	"ZWL_displayName": "Đồng Đô la Zimbabwe (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Som Kyrgyzstan",
	"KWD_displayName": "Dinar Kuwait",
	"AFN_displayName": "Afghani Afghanistan",
	"ARS_displayName": "Peso Argentina",
	"MAD_displayName": "Dirham Ma-rốc",
	"BAM_displayName": "Mark Bosnia-Herzegovina có thể chuyển đổi",
	"BOB_displayName": "Boliviano Bolivia",
	"BND_displayName": "Đô la Brunei",
	"SGD_displayName": "Đô la Singapore",
	"MVR_displayName": "Rufiyaa Maldives",
	"MXN_displayName": "Peso Mexico",
	"DZD_displayName": "Dinar Algeria",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar Jordan",
	"PEN_displayName": "Nuevo Sol Peru",
	"GTQ_displayName": "Quetzal Guatemala",
	"BYR_displayName": "Rúp Belarus",
	"CAD_displayName": "Đô la Canada",
	"BZD_displayName": "Đô la Belize",
	"CLP_displayName": "Peso Chile",
	"XOF_displayName": "Franc CFA BCEAO",
	"NOK_displayName": "Krone Na Uy",
	"DOP_displayName": "Peso Dominica",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won Hàn Quốc",
	"USD_displayName": "Đô la Mỹ",
	"UYU_displayName": "Peso Uruguay",
	"UZS_displayName": "Som Uzbekistan",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial Qatar",
	"SAR_displayName": "Riyal Ả Rập Xê-út",
	"SYP_displayName": "Bảng Syria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Bảng Ai Cập",
	"AMD_displayName": "Dram Armenia",
	"GBP_displayName": "Bảng Anh",
	"HUF_displayName": "Forint Hungaria",
	"CSD_displayName": "Đồng Dinar của Serbia (2002–2006)",
	"ISK_displayName": "Króna Iceland",
	"IRR_displayName": "Rial Iran",
	"OMR_displayName": "Rial Oman",
	"TWD_displayName": "Đô la Đài Loan mới",
	"PAB_displayName": "Balboa Panama",
	"UAH_displayName": "Hryvnia Ucraina",
	"ETB_displayName": "Birr Ethiopia",
	"PLN_displayName": "Zloty Ba Lan",
	"VEF_displayName": "Bolívar Venezuela",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Real Braxin",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Đô la Hồng Kông",
	"NIO_displayName": "Córdoba Nicaragua",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupee Nepal",
	"PKR_displayName": "Rupee Pakistan",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari Gruzia",
	"AZN_displayName": "Manat Azerbaijan",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit Malaysia",
	"DKK_displayName": "Krone Đan Mạch",
	"THB_displayName": "Bạt Thái Lan",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yên Nhật",
	"KES_displayName": "Shilling Kenya",
	"KHR_displayName": "Riel Campuchia",
	"PYG_displayName": "Guarani Paraguay",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupee Sri Lanka",
	"BGN_displayName": "Lev Bulgaria",
	"BDT_displayName": "Taka Bangladesh",
	"MOP_displayName": "Pataca Ma Cao",
	"HNL_displayName": "Lempira Honduras",
	"RWF_displayName": "Franc Rwanda",
	"CHF_displayName": "Franc Thụy sĩ",
	"CRC_displayName": "Colón Costa Rica",
	"INR_displayName": "Rupee Ấn Độ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand Nam Phi",
	"AUD_displayName": "Đô la Australia",
	"LAK_displayName": "Kip Lào",
	"MNT_displayName": "Tugrik Mông Cổ",
	"RSD_displayName": "Dinar Serbia",
	"HRK_displayName": "Kuna Croatia"
}
//end v1.x content
);