define("Sage/MainView/CopyUserProfile/nls/zh-tw/CopyUserProfile", {
    "dlg_Title": "複製設定檔",
    "dlg_Instructions": "選取要複製到其他使用者的使用者設定檔或範本。複製設定檔將會覆寫目前的設定。",
    "rad_SelectionLabel": "設定檔複製來源:",
    "rad_UserBtn": "現有使用者",
    "rad_TemplateBtn": "範本",
    "user_LookupLabel": "使用者",
    "template_LookupLabel": "範本",
    "lookupUserNameColText": "使用者名稱",
    "lookupTitleColText": "標題",
    "lookupDepartmentColText": "部門",
    "lookupRegionColText": "地區",
    "lookupUser_Caption": "使用者設定檔複製來源",
    "lookupUserNameTemplateColText": "範本",
    "chkGeneralLabel": "一般",
    "chkCalendarLabel": "行事曆",
    "chkEmployeeLabel": "員工",
    "chkClientLabel": "用戶端選項 (用戶端系統)",
    "chkSecurityLabel": "安全性",
    "chkServiceLabel": "服務/支援",
    "chkTeamsLabel": "團隊",
    "txtJobDescriptor": "複製使用者設定檔",
    "jobFailer": "發生嚴重錯誤"
});