define("Sage/UI/nls/it/BulkUpdateWidget", {
    "dlgBulkActionUpdate_Title": "Aggiornamento di massa",
    "pageLoading_Caption": "Caricamento opzioni proprietà in corso...",
    "header_Caption": "Selezionare una proprietà da aggiornare.",
    "header_NoPropertiesEnabled": "L'entità ${0} è abilitata per gli aggiornamenti di massa, tuttavia non sono presenti proprietà abilitate. Contattare l'amministratore di sistema per maggiori informazioni",
    "errorRequestPropertyOptions": "Si è verificato un errore durante la lettura dei metadati per l'entità ${0}. ${1}",
    "errorEntityNotSupported": "L'entità ${0} non supporta aggiornamenti di massa",
    "update_Property_Caption": "Aggiorna:",
    "addProperty_Tooltip": "Aggiungi proprietà",
    "removeProperty_Tooltip": "Rimuovi proprietà",
    "no_Caption": "No",
    "yes_Caption": "Sì",
    "days_Caption": "giorni",
    "moveOut_Caption": "Sposta",
    "moveTo_Caption": "A",
    "moveDate_Backward": "Indietro",
    "moveDate_Forward": "Avanti",
    "update_To_Caption": "A:",
    "lookupHeaderText": "Ricerca ${0}",
    "lookupNameColText": "Nome",
    "lookupTitleColText": "Titolo",
    "lookupDepartmentColText": "Reparto",
    "lookupRegionColText": "Regione",
    "lookupTypeColText": "Tipo",
    "lookupDescriptionColText": "Descrizione",
    "btnOK_Caption": "OK",
    "btnCancel_Caption": "Annulla",
    "errorUnspecifiedValue": "Specificare un valore prima di continuare o rimuovere la riga non valida.",
    "errorRequestingJobMgr": "Si è verificato un errore durante l'esecuzione dell'aggiornamento: ${0}",
    "selectOption_Caption": "Selezionare un'opzione...",
    "updateRecords_Caption": "Aggiornamento dei record selezionati",
    "chkScheduleJob_Caption": "Pianifica questo aggiornamento in modo che venga eseguito a una data/ora specifica.",
    "lookup_Caption": "Ricerca",
    "job_Description": "Si è verificato un errore di aggiornamento di massa",
    "errorDuplicateValue": "Proprietà già selezionata",
    "errorInvalidPropertyType": "Tipo proprietà '${0}' non supportato per gli aggiornamenti di massa.",
    "calculatedField": "Campo calcolato",
    "standardId": "ID standard",
    "unknownPropertyType": "Sconosciuto"
});