define("Sage/UI/nls/it/NotesHistoryList", {
    "typeText": "Tipo",
    "showDbChangesText": "Mostra modifiche al database",
    "selectAllText": "Seleziona tutto",
    "dateText": "Data",
    "dateTimeText": "Data/ora",
    "dateRangeText": "Intervallo di date",
    "userText": "Utente",
    "accountText": "Azienda",
    "contactText": "Contatto",
    "opportunityText": "Opportunità",
    "regardingText": "In relazione a",
    "notesText": "Note",
    "resultText": "Risultato",
    "categoryText": "Categoria",
    "sendEmailText": "Invia tramite e-mail",
    "sendToWordText": "Invia a Word",
    "addNoteText": "Aggiungi nota",
    "completeAnActivityText": "Completa un'attività",
    "helpText": "Guida",
    "pleaseSelectRecordsText": "Selezionare uno o più record",
    "UnableToFindWordMsg": "Impossibile avviare Microsoft Word. Controllare le impostazioni di sicurezza.",
    "printedOnText": "Stampato il",
    "errorNoData": "Non sono presenti note/cronologia da condividere su Ming.le.",
    "yesButtonText": "Sì",
    "noButtonText": "No",
    "salesLogixPageTitle": "Infor CRM",
    "noRecordsSelectedProcessAll": "Nessun record selezionato. Tutte le note/cronologia, ${0} record, saranno condivise su Ming.le. Procedere?",
    "errorShareMingle": "Si è verificato un errore nel tentativo di condividere uno o più record di note/cronologia su Ming.le.",
    "sharedToMingle": "Note/cronologia condivise su Ming.le.",
    "sharingToMingle": "Condivisione su Ming.le",
    "shared": "Condiviso",
    "pleaseWait": "Attendere...",
    "failedToPost": "Pubblicazione non riuscita: ${0}; errore: ${1}",
    "addressText": "Indirizzo",
    "mainPhoneText": "Telefono principale",
    "tollFreeText": "Numero verde",
    "contactPhoneText": "Telefono contatto"
});