define("Sage/MainView/GroupMgr/nls/zh-cn/ReleasesListPanelConfig", {
    "Dev": "Dev",
    "Rel": "已共享",
    "Family": "系列",
    "Name": "名称",
    "DisplayName": "显示名称",
    "Owner": "所有者",
    "SharedDate": "共享日期",
    "Type": "类型",
    "CreateDate": "创建日期",
    "ModifyDate": "修改日期",
    "Author": "作者",
    "Company": "公司",
    "Version": "版本",
    "SharedToName": "共享目标名称",
    "SharedToType": "共享目标类型",
    "UserType": "UserType",
    "BasedOn": "基于"
});