define("Sage/MainView/nls/it/ActivityManager", {
    "titleFmtString": "${0}",
    "tabDisplayNameActivity": "Attività",
    "tabDisplayNameLit": "Documentazione",
    "tabDisplayNameEvent": "Eventi",
    "tabDisplayNameConfirm": "Conferme",
    "activityColNameComplete": "Completa",
    "activityColNameAttachment": "Allegato",
    "activityColNameRecurring": "Ricorrente",
    "activityColNameAlarm": "Allarme",
    "activityColNameType": "ActivityType",
    "activityColNameStartDate": "StartDate",
    "activityColNameDuration": "Durata",
    "activityColNameContact": "Contatto",
    "activityColNameLead": "Lead",
    "activityColNameAccount": "Azienda",
    "activityColNameRegarding": "In relazione a",
    "activityColNamePriority": "Priorità",
    "activityColNameUserId": "coordinatore",
    "activityTypePhone": "Telefonata",
    "activityTypeCall": "Conferenza telefonica",
    "activityTypeMeeting": "Riunione",
    "activityTypePersonal": "Personale"
});