define("Sage/MainView/nls/it/FormMgrDetailPane", {
    "layoutTabText": "Layout",
    "propertiesTabText": "Proprietà",
    "toolsTabText": "Barra degli strumenti",
    "usageTabText": "Utilizzo per pagine",
    "columnText": "Colonna",
    "rowText": "Riga",
    "fieldNameText": "Nome campo",
    "displayNameText": "Nome visualizzato",
    "visibleText": "Visibile",
    "rowspanText": "Larghezza riga",
    "colspanText": "Larghezza colonna",
    "controlTypeText": "Tipo controllo",
    "buttonAlignmentText": "Allineamento pulsante:",
    "rightText": "Destra",
    "centerText": "Centra",
    "leftText": "Sinistra",
    "helpText": "Guida",
    "positionText": "Posizione",
    "portalText": "Portale",
    "pageText": "Pagina",
    "entityText": "Entità",
    "workspaceText": "Area di lavoro di destinazione",
    "modeText": "Mostra in modalità",
    "rolesText": "Ruolo accesso"
});