define("Sage/MainView/GroupMgr/templates/nls/ru/ReleasesDetailSummary", {
    "txtGroupFamily_Caption": "Семейство:",
    "txtGroupName_Caption": "Имя:",
    "txtGroupDisplayName_Caption": "Отображаемое имя:",
    "txtGroupDescription_Caption": "Описание:",
    "txtGroupId_Caption": "ИД:",
    "txtGroupMainTable_Caption": "Основная таблица:",
    "txtGroupEntityName_Caption": "Имя сущности:",
    "txtGroupCreateDate_Caption": "Дата создания:",
    "txtGroupCreateUser_Caption": "Автор:",
    "txtGroupModifyDate_Caption": "Дата изменения:",
    "txtGroupModifyUser_Caption": "Автор изменения:",
    "txtGroupInstallationDate_Caption": "Дата установки:",
    "txtGroupShared_Caption": "Общий доступ:",
    "txtGroupSharedDate_Caption": "Дата открытия общего доступа:",
    "txtGroupOwner_Caption": "Владелец:",
    "txtGroupUserId_Caption": "ИД пользователя:",
    "txtGroupAdhoc_Caption": "Спец. группа:",
    "txtGroupHidden_Caption": "Скрытый:",
    "txtGroupAuthor_Caption": "Автор:",
    "txtGroupCompany_Caption": "Компания:",
    "txtGroupCompanyVersion_Caption": "Версия компании:",
    "txtGroupDev_Caption": "Dev:",
    "txtGroupDataCode_Caption": "Код данных:",
    "txtGroupType_Caption": "Тип группы:",
    "txtGroupBasedOn_Caption": "ИД группы основы:",
    "txtGroupReleasedToType_Caption": "Тип получателя общего доступа:",
    "txtGroupReleasedTo_Caption": "Имя получателя общего доступа:",
    "txtGroupReleasedToTitle_Caption": "Название ресурса общего доступа:",
    "txtGroupReleasedToUserType_Caption": "Тип пользователя ресурса общего доступа:"
});