define(
"dojo/cldr/nls/es/currency", //begin v1.x content
{
	"COP_displayName": "peso colombiano",
	"CZK_displayName": "corona checa",
	"TND_displayName": "dinar tunecino",
	"CAD_symbol": "CA$",
	"JMD_displayName": "dólar de Jamaica",
	"PHP_displayName": "peso filipino",
	"ALL_displayName": "lek albanés",
	"USD_symbol": "$",
	"LBP_displayName": "libra libanesa",
	"VND_displayName": "dong vietnamita",
	"LYD_displayName": "dinar libio",
	"RON_displayName": "leu rumano",
	"MKD_displayName": "dinar macedonio",
	"SEK_displayName": "corona sueca",
	"CNY_displayName": "yuan chino",
	"IDR_displayName": "rupia indonesia",
	"ILS_displayName": "nuevo sheqel israelí",
	"YER_displayName": "rial yemení",
	"TJS_displayName": "somoni tayiko",
	"ARS_symbol": "AR$",
	"TTD_displayName": "dólar de Trinidad y Tobago",
	"CNY_symbol": "CNY",
	"TRY_displayName": "lira turca",
	"EUR_displayName": "euro",
	"AED_displayName": "dírham de los Emiratos Árabes Unidos",
	"KZT_displayName": "tenge kazako",
	"BHD_displayName": "dinar bahreiní",
	"RUB_displayName": "rublo ruso",
	"NZD_displayName": "dólar neozelandés",
	"IQD_displayName": "dinar iraquí",
	"TMT_displayName": "manat turcomano",
	"ZWL_displayName": "dólar zimbabuense",
	"INR_symbol": "INR",
	"KGS_displayName": "som kirguís",
	"KWD_displayName": "dinar kuwaití",
	"AFN_displayName": "afgani afgano",
	"ARS_displayName": "peso argentino",
	"MAD_displayName": "dírham marroquí",
	"BAM_displayName": "marco convertible de Bosnia-Herzegovina",
	"BOB_displayName": "boliviano",
	"BND_displayName": "dólar de Brunéi",
	"SGD_displayName": "dólar singapurense",
	"MVR_displayName": "rufiyaa de Maldivas",
	"MXN_displayName": "peso mexicano",
	"DZD_displayName": "dinar argelino",
	"MXN_symbol": "MX$",
	"JOD_displayName": "dinar jordano",
	"PEN_displayName": "nuevo sol peruano",
	"GTQ_displayName": "quetzal guatemalteco",
	"BYR_displayName": "rublo bielorruso",
	"CAD_displayName": "dólar canadiense",
	"BZD_displayName": "dólar de Belice",
	"CLP_displayName": "peso chileno",
	"XOF_displayName": "franco CFA BCEAO",
	"NOK_displayName": "corona noruega",
	"DOP_displayName": "peso dominicano",
	"JPY_symbol": "JPY",
	"KRW_displayName": "won surcoreano",
	"USD_displayName": "dólar estadounidense",
	"UYU_displayName": "peso uruguayo",
	"UZS_displayName": "som uzbeko",
	"XOF_symbol": "XOF",
	"QAR_displayName": "riyal de Qatar",
	"SAR_displayName": "riyal saudí",
	"SYP_displayName": "libra siria",
	"EGP_displayName": "libra egipcia",
	"AMD_displayName": "dram armenio",
	"GBP_displayName": "libra esterlina británica",
	"HUF_displayName": "florín húngaro",
	"CSD_displayName": "antiguo dinar serbio",
	"ISK_displayName": "corona islandesa",
	"IRR_displayName": "rial iraní",
	"OMR_displayName": "rial omaní",
	"TWD_displayName": "nuevo dólar taiwanés",
	"PAB_displayName": "balboa panameño",
	"UAH_displayName": "grivna ucraniana",
	"ETB_displayName": "birr etíope",
	"PLN_displayName": "zloty polaco",
	"VEF_displayName": "bolívar venezolano",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AU$",
	"BRL_displayName": "real brasileño",
	"HKD_symbol": "HKD",
	"HKD_displayName": "dólar de Hong Kong",
	"NIO_displayName": "córdoba nicaragüense",
	"NPR_displayName": "rupia nepalesa",
	"PKR_displayName": "rupia pakistaní",
	"TWD_symbol": "TWD",
	"GEL_displayName": "lari georgiano",
	"AZN_displayName": "manat azerí",
	"GBP_symbol": "GBP",
	"MYR_displayName": "ringgit malasio",
	"DKK_displayName": "corona danesa",
	"THB_displayName": "baht tailandés",
	"JPY_displayName": "yen japonés",
	"KES_displayName": "chelín keniata",
	"KHR_displayName": "riel camboyano",
	"PYG_displayName": "guaraní paraguayo",
	"LKR_displayName": "rupia de Sri Lanka",
	"BGN_displayName": "lev búlgaro",
	"BDT_displayName": "taka de Bangladesh",
	"MOP_displayName": "pataca de Macao",
	"HNL_displayName": "lempira hondureño",
	"RWF_displayName": "franco ruandés",
	"CHF_displayName": "franco suizo",
	"CRC_displayName": "colón costarricense",
	"INR_displayName": "rupia india",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "rand sudafricano",
	"AUD_displayName": "dólar australiano",
	"LAK_displayName": "kip laosiano",
	"MNT_displayName": "tugrik mongol",
	"RSD_displayName": "dinar serbio",
	"HRK_displayName": "kuna croata"
}
//end v1.x content
);