define("Sage/TaskPane/nls/zh-cn/_BaseTaskPaneTasklet", {
    "selectRecordsTitle": "选择无效",
    "selectRecords": "请选择一条记录，然后继续。",
    "selectSingleRecord": "请选择单条记录，然后继续。",
    "noRecordsSelectedProcessAll": "未选择任何记录。系统管理员将处理整个组，但若有数量上限，则处理到数量上限为止。是否继续?",
    "invalidSelectionTitle": "选择无效",
    "errorSelectionInfo": "检索有关选中记录的信息时出现错误。",
    "errorNoData": "无可用数据。",
    "yesButtonText": "是",
    "noButtonText": "否",
    "salesLogixPageTitle": "Infor CRM",
    "okButtonText": "确定",
    "cancelButtonText": "取消",
    "confirmBulkDeleteJob": "确定要删除选中的记录吗?",
    "deleteSelectedRecords": "删除 ${0}",
    "deleteJobError": "抱歉，删除 ${0} 作业时出错: ${1}",
    "deleteBulkJobTitle": "删除 ${0}",
    "promoteTitle": "升级",
    "getOrderTotalTitle": "获取订单总计",
    "integrationNotEnabled": "Back Office Extension 未启用",
    "error_PricingRequest": "请求定价服务时出现错误: ${0}"
});