define(
"dojo/cldr/nls/am/currency", //begin v1.x content
{
	"COP_displayName": "የኮሎምቢያ ፔሶ",
	"CZK_displayName": "ቼክ ሪፐፕሊክ ኮሩና",
	"TND_displayName": "የቱኒዚያ ዲናር",
	"EUR_symbol": "€",
	"JMD_displayName": "የጃማይካ ዶላር",
	"PHP_displayName": "የፊሊፒንስ ፔሶ",
	"ALL_displayName": "የአልባንያ ሌክ",
	"USD_symbol": "US$",
	"LBP_displayName": "የሊባኖስ ፓውንድ",
	"VND_displayName": "የቭየትናም ዶንግ",
	"LYD_displayName": "የሊቢያ ዲናር",
	"RON_displayName": "የሮማኒያ ለው",
	"MKD_displayName": "የሜቆድንያ ዲናር",
	"SEK_displayName": "የስዊድን ክሮና",
	"CNY_displayName": "የቻይና የን",
	"IDR_displayName": "የኢንዶኔዥያ ሩፒሃ",
	"ILS_displayName": "የእስራኤል አዲስ ሽቅል",
	"YER_displayName": "የየመን ሪአል",
	"TJS_displayName": "የታጂክስታን ሶሞኒ",
	"TTD_displayName": "የትሪንዳድ እና ቶቤጎዶላር",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "የቱርክ ሊራ",
	"EUR_displayName": "ዩሮ",
	"AED_displayName": "የተባበሩት የአረብ ኤምረትስ ዲርሀም",
	"KZT_displayName": "የካዛኪስታን ተንጌ",
	"BHD_displayName": "የባኽሬን ዲናር",
	"RUB_displayName": "የሩስያ ሩብል",
	"NZD_displayName": "የኒውዚላንድ ዶላር",
	"IQD_displayName": "የኢራቅ ዲናር",
	"TMT_displayName": "ቱርክሜኒስታኒ ማናት",
	"INR_symbol": "₹",
	"KGS_displayName": "የኪርጊስታን ሶም",
	"KWD_displayName": "የኩዌት ዲናር",
	"AFN_displayName": "የአፍጋን አፍጋኒ",
	"ARS_displayName": "የአርጀንቲና ፔሶ",
	"MAD_displayName": "የሞሮኮ ዲርሀም",
	"BAM_displayName": "የቦስኒያ ሄርዞጎቪና የሚመነዘር ማርክ",
	"BOB_displayName": "የቦሊቪያ ቦሊቪያኖ",
	"BND_displayName": "የብሩኔ ዶላር",
	"SGD_displayName": "የሲንጋፖር ዶላር",
	"MVR_displayName": "የማልዲቫ ሩፊያ",
	"MXN_displayName": "የሜክሲኮ ፔሶ",
	"DZD_displayName": "የአልጄሪያ ዲናር",
	"MXN_symbol": "MX$",
	"JOD_displayName": "የጆርዳን ዲናር",
	"PEN_displayName": "የፔሩቪያ ኑኤቮ ሶል",
	"GTQ_displayName": "ጓቲማላን ኩቲዛል",
	"BYR_displayName": "የቤላሩስያ ሩብል",
	"CAD_displayName": "የካናዳ ዶላር",
	"BZD_displayName": "የቤሊዝ ዶላር",
	"CLP_displayName": "የቺሊ ፔሶ",
	"XOF_displayName": "ሴኤፍአ ፍራንክ ቤሴእአኦ",
	"NOK_displayName": "የኖርዌይ ክሮን",
	"DOP_displayName": "የዶሚኒክ ፔሶ",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "የደቡብ ኮሪያ ዎን",
	"USD_displayName": "የአሜሪካን ዶላር",
	"UYU_displayName": "የኡራጓይ ፔሶ",
	"UZS_displayName": "የኡዝፔኪስታን ሶም",
	"XOF_symbol": "CFA",
	"QAR_displayName": "የኳታር ሪአል",
	"SAR_displayName": "የሳውዲ ሪያል",
	"SYP_displayName": "የሲሪያ ፓውንድ",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "የግብጽ ፓውንድ",
	"AMD_displayName": "የአርመን ድራም",
	"GBP_displayName": "የእንግሊዝ ፓውንድ ስተርሊንግ",
	"HUF_displayName": "የሁንጋሪ ፎሪንት",
	"ISK_displayName": "የአይስላንድ ክሮና",
	"IRR_displayName": "የኢራን ሪአል",
	"OMR_displayName": "የኦማን ሪአል",
	"TWD_displayName": "የአዲሷ ታይዋን ዶላር",
	"PAB_displayName": "ፓናማኒአን ባልቦአ",
	"UAH_displayName": "የዩክሬን ሀሪይቭኒአ",
	"ETB_displayName": "የኢትዮጵያ ብር",
	"PLN_displayName": "የፖላንድ ዝሎቲ",
	"VEF_displayName": "የቬንዝዌላ ቦሊቫር",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "የብራዚል ሪል",
	"HKD_symbol": "HK$",
	"HKD_displayName": "የሆንግኮንግ ዶላር",
	"NIO_displayName": "የኒካራጓ ኮርዶባ",
	"THB_symbol": "฿",
	"NPR_displayName": "የኔፓል ሩፒ",
	"PKR_displayName": "የፓኪስታን ሩፒ",
	"TWD_symbol": "NT$",
	"GEL_displayName": "የጆርጅያ ላሪ",
	"AZN_displayName": "የአዛርባጃን ማናት",
	"GBP_symbol": "£",
	"MYR_displayName": "የማሌዥያ ሪንጊት",
	"DKK_displayName": "የዴንማርክ ክሮን",
	"THB_displayName": "የታይላንድ ባህት",
	"BRL_symbol": "R$",
	"JPY_displayName": "የጃፓን የን",
	"KES_displayName": "የኬኒያ ሺሊንግ",
	"KHR_displayName": "የካምቦዲያ ሬል",
	"PYG_displayName": "የፓራጓይ ጉአራኒ",
	"VND_symbol": "₫",
	"LKR_displayName": "የሲሪላንካ ሩፒ",
	"BGN_displayName": "የቡልጋሪያ ሌቭ",
	"BDT_displayName": "የባንግላዲሽ ታካ",
	"MOP_displayName": "የማካኔዝ ፓታካ",
	"HNL_displayName": "የሃንዱራ ሌምፓአይራ",
	"RWF_displayName": "የሩዋንዳ ፍራንክ",
	"CHF_displayName": "የስዊስ ፍራንክ",
	"CRC_displayName": "የኮስታሪካ ኮሎን",
	"INR_displayName": "የሕንድ ሩፒ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "የደቡብ አፍሪካ ራንድ",
	"AUD_displayName": "የአውስትራሊያ ዶላር",
	"LAK_displayName": "የላኦቲ ኪፕ",
	"MNT_displayName": "የሞንጎሊያን ቱግሪክ",
	"ETB_symbol": "ብር",
	"RSD_displayName": "የሰርቢያ ዲናር",
	"HRK_displayName": "የክሮሽያ ኩና"
}
//end v1.x content
);