define("Sage/MainView/EntityMgr/nls/fr/EntityListPanelConfig", {
    "colNameEntityName": "Nom",
    "colNameType": "Type",
    "colNameTable": "Table",
    "colNameCreateUser": "Créé par",
    "colNameCreateDate": "Date de création",
    "colNameLastExecutionDate": "Dernière exécution",
    "colNameLastExecutionUser": "Dernière exécution par",
    "colNameModifyUser": "Modifié par",
    "colNameModifyDate": "Date de modification",
    "colNameEntityDisplayName": "Nom d'affichage",
    "colNameEntityTableName": "Table",
    "colNamePropertyCount": "Nombre de propriétés",
    "colNameFilterCount": "Nombre de filtres",
    "colNameMetricCount": "Nombre de mesures",
    "colNamePackage": "Package",
    "owner": "Propriétaire",
    "assignTo": "Affecter à",
    "newACI": "Nouveau domaine/catégorie/problème",
    "insertACI": "Insérer domaine/catégorie/problème",
    "autoAssign": "Auto-affectation",
    "areaCatIssue": "Domaine/catégorie/problème",
    "lookupACI": "Rechercher domaine/catégorie/problème",
    "displayName": "Nom d'affichage",
    "displayPluralName": "Afficher le nom au pluriel",
    "Title": "Titre",
    "IsExtension": "IsExtension",
    "Audited": "Audité",
    "OK": "OK",
    "Cancel": "Annuler"
});