define("Sage/Groups/nls/ru/GroupManager", {
    "ConfirmDeleteMessage": "Действительно удалить текущую группу?",
    "ConfirmDeleteFmtMessage": "Действительно удалить эту группу: ${0}",
    "InvalidSortStringMessage": "Ошибка: некорректная строка сортировки — ",
    "InvalidConditionStringMessage": "Ошибка: некорректная строка условия — ",
    "InvalidLayoutConditionStringMessage": "Ошибка: некорректная строка размещения — ",
    "noneSelectedTitle": "Ни одной записи не выбрано",
    "noneSelectedPromptFmt": "Записи не выбраны. Будет добавлена целая группа (количество записей: ${0}). Продолжить?",
    "noneSelectedRemovePromptFmt": "Записи не выбраны. Будет удалена целая группа, (количество записей: ${0}). Продолжить?",
    "noRecordsInGroup": "Нет записей, которые могут быть выбраны из этой группы.",
    "newGroupTitle": "Добавить записи в новую группу",
    "newGroupNamePrompt": "Выбранные записи (${0}) будут добавлены в эту новую группу.<br><br>Имя группы:<br>${1}",
    "newGroupRePrompt": "&nbsp;&nbsp;<i>Введите имя группы.</i>",
    "invalidCharMsg": "Имя не должно содержать следующие символы: / \\ : * ? \" <> | или \"",
    "groupNameText": "Имя группы:",
    "saveLookupDlgTitle": "Сохранить результаты поиска как новую группу",
    "yesCaption": "Да",
    "noCaption": "Нет",
    "cancelCaption": "Отмена",
    "okCaption": "OК",
    "LOCALSTORE_NAMESPACE": "SageGroups",
    "exportToExcel": "Этот метод является устаревшим, см. Sage.TaskPane.CommonTasksTasklet.exportToExcel.",
    "createAdHocGroupJob_Description": "Группа: ${0}",
    "createAdHocGroupJob_Title": "Создание группы",
    "createAdHocGroupJobError": "Во время создания группы возникла ошибка: ${0}",
    "createAdHocGroupJobProcessingJobMsg": "Можно подождать завершения или можно закрыть это сообщение. Вы получите уведомление после завершения группы."
});