define(
"dojo/cldr/nls/id/currency", //begin v1.x content
{
	"COP_displayName": "Peso Kolombia",
	"CZK_displayName": "Koruna Cheska",
	"TND_displayName": "Dinar Tunisia",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dolar Jamaika",
	"PHP_displayName": "Peso Filipina",
	"ALL_displayName": "Lek Albania",
	"USD_symbol": "US$",
	"LBP_displayName": "Pound Lebanon",
	"VND_displayName": "Dong Vietnam",
	"LYD_displayName": "Dinar Libya",
	"RON_displayName": "Leu Rumania",
	"MKD_displayName": "Denar Makedonia",
	"SEK_displayName": "Krona Swedia",
	"CNY_displayName": "Yuan China",
	"IDR_displayName": "Rupiah Indonesia",
	"ILS_displayName": "Shekel Baru Israel",
	"YER_displayName": "Rial Yaman",
	"TJS_displayName": "Somoni Tajikistan",
	"TTD_displayName": "Dolar Trinidad dan Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira Turki",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham Uni Emirat Arab",
	"KZT_displayName": "Tenge Kazakstan",
	"BHD_displayName": "Dinar Bahrain",
	"RUB_displayName": "Rubel Rusia",
	"NZD_displayName": "Dolar Selandia Baru",
	"IQD_displayName": "Dinar Irak",
	"TMT_displayName": "Manat Turkimenistan",
	"ZWL_displayName": "Dolar Zimbabwe (2009)",
	"INR_symbol": "Rs",
	"KGS_displayName": "Som Kirgistan",
	"KWD_displayName": "Dinar Kuwait",
	"AFN_displayName": "Afgani Afganistan",
	"ARS_displayName": "Peso Argentina",
	"MAD_displayName": "Dirham Maroko",
	"BAM_displayName": "Mark Konvertibel Bosnia-Herzegovina",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Dolar Brunei",
	"SGD_displayName": "Dolar Singapura",
	"MVR_displayName": "Rufiyaa Maladewa",
	"MXN_displayName": "Peso Meksiko",
	"DZD_displayName": "Dinar Algeria",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar Yordania",
	"PEN_displayName": "Nuevo Sol Peru",
	"GTQ_displayName": "Quetzal Guatemala",
	"BYR_displayName": "Rubel Belarusia",
	"CAD_displayName": "Dolar Kanada",
	"BZD_displayName": "Dolar Belize",
	"CLP_displayName": "Peso Cile",
	"XOF_displayName": "Franc CFA BCEAO",
	"NOK_displayName": "Krone Norwegia",
	"DOP_displayName": "Peso Dominika",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won Korea Selatan",
	"USD_displayName": "Dolar Amerika Serikat",
	"UYU_displayName": "Peso Uruguay",
	"UZS_displayName": "Som Uzbekistan",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial Qatar",
	"SAR_displayName": "Riyal Arab Saudi",
	"SYP_displayName": "Pound Suriah",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Pound Mesir",
	"AMD_displayName": "Dram Armenia",
	"GBP_displayName": "Pound Sterling Inggris",
	"HUF_displayName": "Forint Hungaria",
	"CSD_displayName": "Dinar Serbia (2002–2006)",
	"ISK_displayName": "Krona Islandia",
	"IRR_displayName": "Rial Iran",
	"OMR_displayName": "Rial Oman",
	"TWD_displayName": "Dolar Baru Taiwan",
	"PAB_displayName": "Balboa Panama",
	"UAH_displayName": "Hryvnia Ukraina",
	"ETB_displayName": "Birr Etiopia",
	"PLN_displayName": "Polandia Zloty",
	"VEF_displayName": "Bolivar Venezuela",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Real Brasil",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dolar Hong Kong",
	"NIO_displayName": "Cordoba Nikaragua",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupee Nepal",
	"PKR_displayName": "Rupee Pakistan",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari Georgia",
	"AZN_displayName": "Manat Azerbaijan",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit Malaysia",
	"DKK_displayName": "Krone Denmark",
	"THB_displayName": "Baht Thailand",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yen Jepang",
	"KES_displayName": "Shilling Kenya",
	"KHR_displayName": "Riel Kamboja",
	"PYG_displayName": "Guarani Paraguay",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupee Sri Lanka",
	"BGN_displayName": "Lev Bulgaria",
	"BDT_displayName": "Taka Bangladesh",
	"IDR_symbol": "Rp",
	"HNL_displayName": "Lempira Honduras",
	"MOP_displayName": "Pataca Makau",
	"RWF_displayName": "Franc Rwanda",
	"CHF_displayName": "Franc Swiss",
	"CRC_displayName": "Colon Kosta Rika",
	"INR_displayName": "Rupee India",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand Afrika Selatan",
	"AUD_displayName": "Dolar Australia",
	"LAK_displayName": "Kip Laos",
	"MNT_displayName": "Tugrik Mongolia",
	"RSD_displayName": "Dinar Serbia",
	"HRK_displayName": "Kuna Kroasia"
}
//end v1.x content
);