define("Sage/TaskPane/nls/ru/_BaseTaskPaneTasklet", {
    "selectRecordsTitle": "Некорректное выделение",
    "selectRecords": "Выберите запись, чтобы продолжить.",
    "selectSingleRecord": "Выберите одну запись, чтобы продолжить.",
    "noRecordsSelectedProcessAll": "Записи не выбраны. Будет обработана целая группа до максимального лимита, установленного системным администратором (если установлено). Продолжить?",
    "invalidSelectionTitle": "Некорректное выделение",
    "errorSelectionInfo": "При получении информации о выбранных записях возникла ошибка.",
    "errorNoData": "Данные недоступны.",
    "yesButtonText": "Да",
    "noButtonText": "Нет",
    "salesLogixPageTitle": "Infor CRM",
    "okButtonText": "OК",
    "cancelButtonText": "Отмена",
    "confirmBulkDeleteJob": "Действительно удалить выбранные записи?",
    "deleteSelectedRecords": "Удалить \"${0}\"",
    "deleteJobError": "Во время задания удаления \"${0}\" возникла ошибка: ${1}",
    "deleteBulkJobTitle": "Удалить \"${0}\"",
    "promoteTitle": "Выдвинуть",
    "getOrderTotalTitle": "Получить итог заказа",
    "integrationNotEnabled": "Back Office Extension не активирован",
    "error_PricingRequest": "Во время запроса службы расчета цены возникла ошибка: ${0}"
});