define("Sage/TaskPane/nls/ru/CommonTasksTasklet", {
    "okButtonText": "OК",
    "loadingText": "загрузка...",
    "noPrimaryEmail": "Нет основной электронной почты",
    "selectFileFormat": "Выберите формат файла:",
    "exportToFile_OptionCSV": "Стандартный CSV",
    "exportToFile_OptionTab": "Разделитель: табуляция (рекомендуется для Microsoft Excel)",
    "exportToFile_OptionSaveFormat": "Запомнить мой выбор и больше не спрашивать.",
    "exportToFile_OK": "OК",
    "exportToFile_Cancel": "Отмена",
    "exportToFile_DialogTitle": "Экспорт",
    "exportToExcel_Caption": "Экспорт",
    "errorRequestingJobMgr": "Ошибка при запросе диспетчера заданий: ${0}",
    "errorExecutionAction": "Возникла ошибка во время выполнения \"${0}\"",
    "exportProcessingJobMsg": "Во время выполнения экспорта вы можете ожидать завершения операции или перейти к отчетам, чтобы открыть файл.",
    "errorBulkActionNotSupported": "\"${0}\" не поддерживает массовые обновления. Обратитесь к системному администратору.",
    "errorBulkActionRequest": "Ошибка при запросе массового обновления, обратитесь к системному администратору.",
    "copyProfileNoneSelected": "Требуется выбрать по крайней мере одного пользователя.",
    "deleteJob_Description": "Ошибка массового удаления",
    "errorRequestEntityImportable": "Во время получения атрибутов сущности возникла ошибка. ${0}",
    "entityNotImportable": "\"${0}\" не поддерживает импорт. Обратитесь к системному администратору."
});