define("Sage/MainView/ActivityMgr/templates/nls/zh-cn/ConfirmationDetailSummary", {
    "txtPhone_Caption": "电话:",
    "lnkOpportunity_Caption": "销售机会:",
    "txtStartTime_Caption": "开始时间:",
    "lnkContactName_Caption": "联系人:",
    "lnkLeadName_Caption": "销售线索:",
    "lnkTicket_Caption": "工单:",
    "txtLocation_Caption": "地点:",
    "txtLeader_Caption": "负责人:",
    "txtDuration_Caption": "持续时间:",
    "lnkAccountName_Caption": "客户:",
    "lnkCompanyName_Caption": "公司:",
    "txtNotes_Caption": "备注:",
    "btnComplete_Caption": "完成",
    "txtFromUser_Caption": "自:",
    "btnDelete_Caption": "删除",
    "btnDecline_Caption": "拒绝",
    "btnAccept_Caption": "接受"
});