define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/zh-tw/AddEditDialog", {
    "dialogTitleAddField": "新增欄位至 ${0} 實體",
    "dialogTitleAddFilter": "新增篩選至 ${0} 實體",
    "dialogTitleAddMetric": "新增計量 ${0} 實體",
    "dialogTitleAddRelationship": "新增關聯至 ${0} 實體",
    "editDialogTitle": "在 ${1} 實體中編輯 ${0}",
    "lblFilter": "篩選",
    "lblMetric": "計量",
    "lblFilters": "篩選",
    "lblMetrics": "計量",
    "lblDistinct": "相異",
    "lblRange": "範圍",
    "lblUserLookup": "使用者查閱",
    "lblAdd": "新增",
    "lblEdit": "編輯",
    "lblRemove": "移除",
    "lblHelp": "說明",
    "lblFilterName": "篩選名稱",
    "lblMetricName": "計量名稱",
    "lblDisplayName": "顯示名稱",
    "lblName": "名稱",
    "lblDisplay": "顯示",
    "lblCalculated": "已計算",
    "lblCalculation": "計算",
    "lblDescription": "描述",
    "lblFieldsName": "欄位名稱",
    "lblCalculatedFieldsName": "計算欄位名稱",
    "lblFilterDp": "欄位",
    "lblTypeDp": "類型",
    "lblCharacter": "字元",
    "lblFrom": "從",
    "lblTo": "至",
    "lblOperators": "運算子",
    "lblAggregation": "彙總",
    "lblTypeSpecificContentBox": "輸入特定的內容方塊",
    "lblSaveButton": "確定",
    "lblCancelButton": "取消",
    "DateDiffCheckerValue": "日期差異計量",
    "InvalidFilterName": "無效的篩選名稱",
    "InvalidRangeName": "無效的範圍名稱",
    "RequiredFilterName": "必須提供篩選名稱",
    "RequiredRangeName": "必須提供範圍名稱",
    "FieldMustBeANumber": "字元欄位必須是整數",
    "SelectAnItem": "請選取一個項目。",
    "ItemRequired": "必須提供項目",
    "ItemInvalid": "項目無效",
    "LowerMustBeLessThanUpper": "下限值必須小於上限值。",
    "defaultRangeRowValue": "輸入一個值",
    "totalRecordCountLabel": "記錄總數: ${0}",
    "lblNew": "新增",
    "lblExisting": "現有",
    "lblExistingCalc": "現有計算欄位",
    "validNameMsg": "有效的輸入以大寫字母開頭且<br>可包含英數值和底線。",
    "propertyName": "名稱",
    "displayName": "顯示",
    "dataTypeId": "類型",
    "dataTypeData": "類型屬性",
    "length": "長度",
    "scale": "縮放",
    "precision": "精確度",
    "isIncluded": "包含",
    "isReadOnly": "唯讀",
    "displayCategory": "顯示類別",
    "sdata": "Sdata",
    "bulkAction": "大量動作",
    "canBulkUpdate": "可以大量更新",
    "canImport": "匯入",
    "canMatch": "相符",
    "generate": "產生",
    "audited": "已稽核",
    "notUniqueFor": "不是唯一的",
    "notUnique": "不是唯一的",
    "nlsCode": "NLS 代碼",
    "nlsName": "NLS 名稱",
    "showTranslations": "顯示翻譯",
    "hideTranslations": "隱藏翻譯",
    "standardIds": "標準 ID",
    "others": "其他",
    "SelectField": "請選取一個欄位！",
    "SelectOneField": "請僅選取一個欄位！",
    "parent": "父實體和聯結欄位",
    "child": "子實體和聯結欄位",
    "cardinality": "關聯",
    "cascade": "重疊顯示",
    "includeParent": "包含子實體中的父關聯內容",
    "includeChild": "包含父實體中的子關聯內容",
    "existingRelaton": "這個關聯已經存在！"
});