define(
"dojo/cldr/nls/cy/currency", //begin v1.x content
{
	"COP_displayName": "Peso Colombia",
	"CZK_displayName": "Koruna Tsiec",
	"TND_displayName": "Dinar Tunisia",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Doler Jamaica",
	"PHP_displayName": "Peso Pilipinas",
	"ALL_displayName": "Lek Albania",
	"USD_symbol": "US$",
	"LBP_displayName": "Punt Libanus",
	"VND_displayName": "Dong Fietnam",
	"LYD_displayName": "Dinar Libya",
	"RON_displayName": "Leu Rwmania",
	"MKD_displayName": "Denar Macedonia",
	"SEK_displayName": "Krona Sweden",
	"CNY_displayName": "Yuan Tsieina",
	"IDR_displayName": "Rupiah Indonesia",
	"ILS_displayName": "Shegel Newydd Israel",
	"YER_displayName": "Rial Yemen",
	"TJS_displayName": "Somoni Tajikistan",
	"TTD_displayName": "Doler Trinidad a Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira Twrci",
	"EUR_displayName": "Ewro",
	"AED_displayName": "Dirham Yr Emiradau Arabaidd Unedig",
	"KZT_displayName": "Tenge Kazakstan",
	"BHD_displayName": "Dinar Bahrain",
	"RUB_displayName": "Rwbl Rwsia",
	"NZD_displayName": "Doler Seland Newydd",
	"IQD_displayName": "Dinar Irac",
	"TMT_displayName": "Manat Turkmenistan",
	"INR_symbol": "₹",
	"KGS_displayName": "Som Kyrgyzstan",
	"KWD_displayName": "Dinar Kuwait",
	"AFN_displayName": "Afghani Afghanistan",
	"ARS_displayName": "Peso yr Ariannin",
	"MAD_displayName": "Dirham Moroco",
	"BAM_displayName": "Marc Trosadwy Bosnia a Hercegovina",
	"BOB_displayName": "Boliviano Bolifia",
	"BND_displayName": "Doler Brunei",
	"SGD_displayName": "Doler Singapore",
	"MVR_displayName": "Rufiyaa'r Maldives",
	"MXN_displayName": "Peso México",
	"DZD_displayName": "Dinar Algeria",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar Gwlad yr Iorddonen",
	"PEN_displayName": "Nuevo Sol Periw",
	"GTQ_displayName": "Quetzal Guatemala",
	"BYR_displayName": "Rwbl Belarws",
	"CAD_displayName": "Doler Canada",
	"BZD_displayName": "Doler Belize",
	"CLP_displayName": "Peso Chile",
	"XOF_displayName": "Ffranc CFA y BCEAO",
	"NOK_displayName": "Krone Norwy",
	"DOP_displayName": "Peso Gweriniaeth Dominica",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won De Korea",
	"USD_displayName": "Doler UDA",
	"UYU_displayName": "Peso Uruguay",
	"UZS_displayName": "Som Uzbekistan",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial Qatar",
	"SAR_displayName": "Riyal Saudi Arabia",
	"SYP_displayName": "Punt Syria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Punt Yr Aifft",
	"AMD_displayName": "Dram Armenia",
	"GBP_displayName": "Punt Sterling Prydain",
	"HUF_displayName": "Fforint Hwngari",
	"ISK_displayName": "Króna Gwlad yr Iâ",
	"IRR_displayName": "Rial Iran",
	"OMR_displayName": "Rial Oman",
	"TWD_displayName": "Doler Newydd Taiwan",
	"PAB_displayName": "Balboa Panama",
	"UAH_displayName": "Hryvnia Wcráin",
	"ETB_displayName": "Birr Ethiopia",
	"PLN_displayName": "Zloty Gwlad Pwyl",
	"VEF_displayName": "Bolívar Venezuela",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Real Brasil",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Doler Hong Kong",
	"NIO_displayName": "Córdoba Nicaragua",
	"THB_symbol": "฿",
	"NPR_displayName": "Rwpî Nepal",
	"PKR_displayName": "Rwpî Pacistan",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari Georgia",
	"AZN_displayName": "Manat Azerbaijan",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit Malaysia",
	"DKK_displayName": "Krone Denmarc",
	"THB_displayName": "Baht Gwlad Thai",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yen Japan",
	"KES_displayName": "Swllt Kenya",
	"KHR_displayName": "Riel Cambodia",
	"PYG_displayName": "Guarani Paraguay",
	"VND_symbol": "₫",
	"LKR_displayName": "Rwpî Sri Lanka",
	"BGN_displayName": "Lev Bwlgaria",
	"BDT_displayName": "Taka Bangladesh",
	"MOP_displayName": "Pataca Macau",
	"HNL_displayName": "Lempira Honduras",
	"RWF_displayName": "Ffranc Rwanda",
	"CHF_displayName": "Ffranc y Swistir",
	"CRC_displayName": "Colón Costa Rica",
	"INR_displayName": "Rwpî India",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Rand De Affrica",
	"AUD_displayName": "Doler Awstralia",
	"LAK_displayName": "Kip Laos",
	"MNT_displayName": "Tugrik Mongolia",
	"RSD_displayName": "Dinar Serbia",
	"HRK_displayName": "Kuna Croatia"
}
//end v1.x content
);