define("Sage/Services/nls/zh-tw/ActivityService", {
    "txtErrorActionMsg": "很抱歉，由於發生錯誤，因此動作不成功。",
    "txtActivity": "活動",
    "txtActivities": "活動",
    "txtActionDeleteActivites": "刪除活動",
    "txtActionDeleteActivitiesQuestion": "只會刪除您有權限刪除的活動。<P>您確定要刪除 {0} 個選取的 {1}?",
    "txtAlarm": "鬧鐘",
    "txtAlarms": "鬧鐘",
    "txtActionSnoozeAlarm": "延期鬧鐘",
    "txtActionSnoozeQuestion": "您確定要讓 {2} 的 {0} 個選取的{1} 延期?",
    "txtActionSnoozeAllQuestion": "您確定要讓 {1} 的所有 {0} 延期?",
    "txtActionDismissAlarms": "關閉鬧鐘",
    "txtActionDismissAlarmsQuestion": "您確定要關閉 {0} 個選取的 {1}?",
    "txtEvent": "事件",
    "txtEvents": "事件",
    "txtActionDeleteEvents": "刪除事件",
    "txtActionDeleteEventsQuestion": "只會刪除您有權限刪除的事件。<P> 您確定要刪除 {0} 個選取的 {1}?",
    "txtConfirmation": "確認",
    "txtConfirmations": "確認",
    "txtActionAcceptConfirmations": "接受確認",
    "txtActionAcceptConfirmQuestion": "您確定要接受 {0} 個選取的 {1}? 這個動作只能在新的或已變更的確認上執行。所有其他確認將會被略過。",
    "txtDeclineConfirmations": "拒絕確認",
    "txtActionDeclineConfrimQuestion": "您確定要拒絕 {0} 個選取的 {1}? 這個動作只能在新的或已變更的確認上執行。所有其他確認將會被略過。",
    "txtActionRemoveConfirmations": "刪除確認",
    "txtActionRemoveConfirmationsQuestion": "您確定要刪除 {0} 個選取的 {1}? 這個動作只能在負責人、拒絕或刪除的確認上執行。所有其他確認將會被略過。",
    "txtLiteratureRequest": "文宣要求",
    "txtLiteratureRequests": "文宣要求",
    "txtActionDeleteLiteratureRequests": "刪除文宣要求",
    "txtActionDeleteLiteratureRequestsQuestion": "只會刪除您有權限刪除的文宣要求。<P> 您確定要刪除 {0} 個選取的 {1}?"
});