define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/it/AddEditDialog", {
    "dialogTitleAddField": "Aggiungi campo a entità ${0}",
    "dialogTitleAddFilter": "Aggiungi filtro a entità ${0}",
    "dialogTitleAddMetric": "Aggiungi metrica a entità ${0}",
    "dialogTitleAddRelationship": "Aggiungi relazione a entità ${0}",
    "editDialogTitle": "Modifica ${0} in entità ${1}",
    "lblFilter": "Filtro",
    "lblMetric": "Metrica",
    "lblFilters": "Filtri",
    "lblMetrics": "Metriche",
    "lblDistinct": "Singolo",
    "lblRange": "Intervallo",
    "lblUserLookup": "Ricerca utenti",
    "lblAdd": "Aggiungi",
    "lblEdit": "Modifica",
    "lblRemove": "Rimuovi",
    "lblHelp": "Guida",
    "lblFilterName": "Nome filtro",
    "lblMetricName": "Nome metrica",
    "lblDisplayName": "Nome visualizzato",
    "lblName": "Nome",
    "lblDisplay": "Visualizza",
    "lblCalculated": "Calcolato",
    "lblCalculation": "Calcolo",
    "lblDescription": "Descrizione",
    "lblFieldsName": "Nome campo",
    "lblCalculatedFieldsName": "Nome campo calcolato",
    "lblFilterDp": "Campi",
    "lblTypeDp": "Tipo",
    "lblCharacter": "Caratteri",
    "lblFrom": "Da",
    "lblTo": "A",
    "lblOperators": "Operatori",
    "lblAggregation": "Aggregazioni",
    "lblTypeSpecificContentBox": "Casella contenuto di tipo specifico",
    "lblSaveButton": "OK",
    "lblCancelButton": "Annulla",
    "DateDiffCheckerValue": "Metrica differenza data",
    "InvalidFilterName": "Nome filtro non valido",
    "InvalidRangeName": "Nome metrica non valido",
    "RequiredFilterName": "Nome filtro obbligatorio",
    "RequiredRangeName": "Nome intervallo obbligatorio",
    "FieldMustBeANumber": "Il campo Carattere deve essere un numero intero",
    "SelectAnItem": "Selezionare un elemento",
    "ItemRequired": "Elemento obbligatorio",
    "ItemInvalid": "Elemento non valido",
    "LowerMustBeLessThanUpper": "Il valore inferiore deve essere più piccolo del valore superiore.",
    "defaultRangeRowValue": "Immettere un valore",
    "totalRecordCountLabel": "Record totali: ${0}",
    "lblNew": "Nuovo",
    "lblExisting": "Esistente",
    "lblExistingCalc": "Campo calcolato esistente",
    "validNameMsg": "Una voce valida inizia con una lettera maiuscola e<br> può contenere valori alfanumerici e caratteri di sottolineatura.",
    "propertyName": "Nome",
    "displayName": "Visualizza",
    "dataTypeId": "Tipo",
    "dataTypeData": "Attributi di tipo",
    "length": "Lunghezza",
    "scale": "Scala",
    "precision": "Precisione",
    "isIncluded": "Incluso",
    "isReadOnly": "Sola lettura",
    "displayCategory": "Categoria visualizzazione",
    "sdata": "Sdata",
    "bulkAction": "Azione di massa",
    "canBulkUpdate": "Può effettuare aggiornamenti in blocco",
    "canImport": "Importa",
    "canMatch": "Corrispondenza",
    "generate": "Genera",
    "audited": "Controllato",
    "notUniqueFor": "non è unico per",
    "notUnique": "non è univoco",
    "nlsCode": "Codice NLS",
    "nlsName": "Nome NLS",
    "showTranslations": "Mostra traduzioni",
    "hideTranslations": "Nascondi traduzioni",
    "standardIds": "ID standard",
    "others": "Altri",
    "SelectField": "Selezionare un campo.",
    "SelectOneField": "Selezionare solo un campo.",
    "parent": "Entità padre e campo di join",
    "child": "Entità figlio e campo di join",
    "cardinality": "Relazione",
    "cascade": "Sovrapponi",
    "includeParent": "Includi proprietà relazione padre in entità figlio",
    "includeChild": "Includi proprietà relazione figlio in entità padre",
    "existingRelaton": "Questa relazione esiste già."
});