define("Sage/MainView/ReportMgr/nls/ru/BaseReportScheduleEditor", {
    "dlgReportScheduleDetails_Schedule_Title": "Добавить/редактировать расписание",
    "dlgReportScheduleDetails_RunReport_Title": "Запустить отчет",
    "txtReportType_Caption": "Тип отчета",
    "txtReportName_Caption": "Имя отчета",
    "txtOutputFormat_Caption": "Формат",
    "txtRunAs_Caption": "Выполнить от имени",
    "txtScheduleName_Caption": "Имя расписания",
    "txtScheduleDescription_Caption": "Описание",
    "cmbScheduleFrequency_Caption": "Частота",
    "cmbArchive_Caption": "Архивация отчетов старше",
    "dtStartTime_Caption": "Запуск с",
    "dtEndTime_Caption": "Запуск по",
    "txtRepeatCount_Caption": "Число повторений",
    "txtRepeatInterval_Caption": "Интервал повторения",
    "cmdOK_Caption": "OК",
    "cmdCancel_Caption": "Отмена",
    "tabSchedule_Caption": "Сведения о расписании",
    "txtOnDemandScheduleName": "По запросу",
    "txtReportSuccessfullyScheduled": "Расписание отчета составлено.",
    "dlgScheduleReport_Title": "Запланировать отчет",
    "txtName": "Имя",
    "txtSelectUser": "Выбрать пользователя",
    "txtOK": "OК"
});