define(
"dojo/cldr/nls/fr/currency", //begin v1.x content
{
	"COP_displayName": "peso colombien",
	"CZK_displayName": "couronne tchèque",
	"TND_displayName": "dinar tunisien",
	"EUR_symbol": "€",
	"CAD_symbol": "$CA",
	"JMD_displayName": "dollar jamaïcain",
	"PHP_displayName": "peso philippin",
	"ALL_displayName": "lek albanais",
	"USD_symbol": "$US",
	"LBP_displayName": "livre libanaise",
	"VND_displayName": "dông vietnamien",
	"LYD_displayName": "dinar libyen",
	"RON_displayName": "leu roumain",
	"MKD_displayName": "denar macédonien",
	"TTD_symbol": "$TT",
	"SEK_displayName": "couronne suédoise",
	"CNY_displayName": "yuan renminbi chinois",
	"IDR_displayName": "roupie indonésienne",
	"ILS_displayName": "nouveau shekel israélien",
	"YER_displayName": "rial yéménite",
	"TJS_displayName": "somoni tadjik",
	"ARS_symbol": "$AR",
	"TTD_displayName": "dollar trinidadien",
	"CNY_symbol": "¥CN",
	"TRY_displayName": "livre turque",
	"EUR_displayName": "euro",
	"AED_displayName": "dirham des Émirats arabes unis",
	"KZT_displayName": "tenge kazakh",
	"BHD_displayName": "dinar bahreïni",
	"RUB_displayName": "rouble russe",
	"LBP_symbol": "£LB",
	"NZD_displayName": "dollar néo-zélandais",
	"IQD_displayName": "dinar irakien",
	"TMT_displayName": "nouveau manat turkmène",
	"CLP_symbol": "$CL",
	"ZWL_displayName": "dollar zimbabwéen (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "som kirghize",
	"KWD_displayName": "dinar koweïtien",
	"AFN_displayName": "afghani afghan",
	"ARS_displayName": "peso argentin",
	"MAD_displayName": "dirham marocain",
	"BAM_displayName": "mark convertible bosniaque",
	"BOB_displayName": "boliviano bolivien",
	"BND_displayName": "dollar brunéien",
	"SGD_displayName": "dollar de Singapour",
	"MVR_displayName": "rufiyaa maldivien",
	"MXN_displayName": "peso mexicain",
	"DZD_displayName": "dinar algérien",
	"MXN_symbol": "$MX",
	"JOD_displayName": "dinar jordanien",
	"PEN_displayName": "nouveau sol péruvien",
	"UYU_symbol": "$UY",
	"GTQ_displayName": "quetzal guatémaltèque",
	"BYR_displayName": "rouble biélorusse",
	"CAD_displayName": "dollar canadien",
	"BZD_displayName": "dollar bélizéen",
	"CLP_displayName": "peso chilien",
	"XOF_displayName": "franc CFA (BCEAO)",
	"NOK_displayName": "couronne norvégienne",
	"DOP_displayName": "peso dominicain",
	"JPY_symbol": "¥JP",
	"KRW_displayName": "won sud-coréen",
	"USD_displayName": "dollar des États-Unis",
	"UYU_displayName": "peso uruguayen",
	"UZS_displayName": "sum ouzbek",
	"XOF_symbol": "CFA",
	"QAR_displayName": "rial qatari",
	"BND_symbol": "$BN",
	"SAR_displayName": "rial saoudien",
	"SYP_displayName": "livre syrienne",
	"EGP_symbol": "£EG",
	"NZD_symbol": "$NZ",
	"EGP_displayName": "livre égyptienne",
	"AMD_displayName": "dram arménien",
	"GBP_displayName": "livre sterling",
	"HUF_displayName": "forint hongrois",
	"CSD_displayName": "dinar serbo-monténégrin",
	"ISK_displayName": "couronne islandaise",
	"IRR_displayName": "rial iranien",
	"OMR_displayName": "rial omanais",
	"TWD_displayName": "nouveau dollar taïwanais",
	"PAB_displayName": "balboa panaméen",
	"UAH_displayName": "hryvnia ukrainienne",
	"ETB_displayName": "birr éthiopien",
	"PLN_displayName": "zloty polonais",
	"VEF_displayName": "bolivar vénézuélien",
	"ILS_symbol": "₪",
	"AUD_symbol": "$AU",
	"BRL_displayName": "réal brésilien",
	"HKD_symbol": "$HK",
	"HKD_displayName": "dollar de Hong Kong",
	"NIO_displayName": "córdoba oro nicaraguayen",
	"SGD_symbol": "$SG",
	"THB_symbol": "฿",
	"NPR_displayName": "roupie népalaise",
	"PKR_displayName": "roupie pakistanaise",
	"TWD_symbol": "$TW",
	"GEL_displayName": "lari géorgien",
	"AZN_displayName": "manat azéri",
	"GBP_symbol": "£GB",
	"MYR_displayName": "ringgit malais",
	"DKK_displayName": "couronne danoise",
	"THB_displayName": "baht thaïlandais",
	"JPY_displayName": "yen japonais",
	"KES_displayName": "shilling kényan",
	"BZD_symbol": "$BZ",
	"KHR_displayName": "riel cambodgien",
	"PYG_displayName": "guaraní paraguayen",
	"VND_symbol": "₫",
	"BGN_displayName": "lev bulgare",
	"BDT_displayName": "taka bangladeshi",
	"LKR_displayName": "roupie srilankaise",
	"COP_symbol": "$CO",
	"HNL_displayName": "lempira hondurien",
	"MOP_displayName": "pataca macanaise",
	"RWF_displayName": "franc rwandais",
	"CHF_displayName": "franc suisse",
	"CRC_displayName": "colón costaricain",
	"INR_displayName": "roupie indienne",
	"KRW_symbol": "₩",
	"ZAR_displayName": "rand sud-africain",
	"AUD_displayName": "dollar australien",
	"LAK_displayName": "kip loatien",
	"MNT_displayName": "tugrik mongol",
	"RSD_displayName": "dinar serbe",
	"HRK_displayName": "kuna croate"
}
//end v1.x content
);