define("Sage/MainView/GroupMgr/templates/nls/zh-cn/GroupDetailSummary", {
    "txtGroupFamily_Caption": "系列:",
    "txtGroupName_Caption": "名称:",
    "txtGroupDisplayName_Caption": "显示名称:",
    "txtGroupDescription_Caption": "描述:",
    "txtGroupId_Caption": "ID:",
    "txtGroupMainTable_Caption": "主表:",
    "txtGroupEntityName_Caption": "实体名称:",
    "txtGroupCreateDate_Caption": "创建日期:",
    "txtGroupCreateUser_Caption": "创建用户:",
    "txtGroupModifyDate_Caption": "修改日期:",
    "txtGroupModifyUser_Caption": "修改用户:",
    "txtGroupInstallationDate_Caption": "安装日期:",
    "txtGroupShared_Caption": "共享:",
    "txtGroupSharedDate_Caption": "共享日期:",
    "txtGroupOwner_Caption": "所有者:",
    "txtGroupUserId_Caption": "用户 ID:",
    "txtGroupAdhoc_Caption": "特别:",
    "txtGroupHidden_Caption": "隐藏:",
    "txtGroupAuthor_Caption": "作者:",
    "txtGroupCompany_Caption": "公司:",
    "txtGroupCompanyVersion_Caption": "公司版本:",
    "txtGroupDev_Caption": "Dev:",
    "txtGroupDataCode_Caption": "数据代码:",
    "txtGroupType_Caption": "组类型:",
    "txtGroupUserDefault_Caption": "用户默认值:"
});