define("Sage/MainView/ActivityMgr/nls/fr/ActivityListPanelConfig", {
    "colNameComplete": "Terminer",
    "colNameAttachment": "Pièce jointe",
    "colNameRecurring": "Récurrent",
    "colNameAlarm": "Alarme",
    "colNameType": "Type d'activité",
    "colNameStartDate": "Date de début",
    "colNameDuration": "Durée",
    "colNameContact": "Nom",
    "colNameLead": "Lead",
    "colNameAccount": "Compte/Société",
    "colNameCompany": "Société",
    "colNameRegarding": "Objet",
    "colNamePriority": "Priorité",
    "colNameUserId": "Responsable",
    "colNameTimeless": "Heure indéfinie",
    "colNameTypeName": "Type",
    "colNameContactName": "Nom",
    "SnoozeAlarm": "Mettre en veille l'alarme",
    "DismissAlarm": "Ignorer l'alarme",
    "colNameUnConfirmStatus": "Non confirmé",
    "colNameAssociationCount": "Nombre de participants"
});