define("Sage/MainView/ActivityMgr/nls/fr/EditEventEditor", {
    "titleScheduleText": "Planifier un événement",
    "titleEditText": "Modifier un événement",
    "lblDayTypeText": "Type de jour :",
    "lblStartDateText": "Date de début :",
    "lblEndDateText": "Date de fin :",
    "lblUserText": "Utilisateur :",
    "lookupUserText": "Rechercher un utilisateur",
    "lblCategoryText": "Catégorie :",
    "lblLocationText": "Emplacement :",
    "lblDescriptionText": "Description :",
    "btnOkayText": "OK",
    "btnCancelText": "Annuler",
    "btnHelpText": "Aide",
    "eventTypeActiveText": "Actif",
    "eventTypeBusinessTripText": "Voyage d'affaires",
    "eventTypeConferenceText": "Conférence",
    "eventTypeHolidayText": "Férié",
    "eventTypeOffText": "Inactif",
    "eventTypeTradeShowText": "Salon commercial",
    "eventTypeUnavailableText": "Non disponible",
    "eventTypeVacationText": "Congé",
    "errorText": "Impossible de créer l'événement car une erreur s'est produite.",
    "invaildDatesText": "La date de fin ne peut être antérieure à la date de début.",
    "nameText": "Nom"
});