define("Sage/MainView/ActivityMgr/nls/fr/HistoryEditor", {
    "labelWidth": "100",
    "tabNameGeneralText": "Général",
    "tabNameAttachmentsText": "Pièces jointes",
    "scheduleText": "Planification",
    "startTimeText": "Planifié",
    "completedDateText": "Terminé",
    "timeLessText": "Heure indéfinie",
    "durationText": "Durée",
    "contactText": "Contact",
    "accountText": "Compte",
    "leadText": "Lead",
    "opportunityText": "Opportunité",
    "ticketText": "Ticket",
    "companyText": "Société",
    "regardingText": "Objet",
    "resultText": "Résultat",
    "notesText": "Notes",
    "priorityText": "Priorité",
    "leaderText": "Responsable",
    "categoryText": "Catégorie",
    "locationText": "Emplacement",
    "scheduledByFormatText": "Planifié par ${user} le ${date}",
    "cancelText": "Annuler",
    "okText": "OK",
    "deleteText": "Supprimer",
    "lookupActText": "Rechercher un compte",
    "lookupContactText": "Rechercher un contact",
    "lookupOpportunityText": "Rechercher une opportunité",
    "lookupTicketText": "Rechercher un ticket",
    "lookupLeadText": "Rechercher un lead",
    "lookupLeaderText": "Rechercher le responsable",
    "lookupResourcesText": "Recherche",
    "mainPhoneText": "Téléphone principal",
    "typeText": "Type",
    "subTypeText": "Sous-type",
    "nameText": "Nom",
    "cityText": "Ville",
    "stateText": "Département",
    "workphoneText": "Téléphone professionnel",
    "emailText": "E-mail",
    "acctMgrText": "Resp. du compte",
    "descriptionText": "Description",
    "stageText": "Phase",
    "statusText": "Etat",
    "ownerText": "Propriétaire",
    "ticketNumberText": "Numéro de ticket",
    "phoneText": "Téléphone",
    "urgencyText": "Priorité",
    "areaText": "Domaine",
    "recurringText": "Récurrent",
    "followupText": "Suivi",
    "noneText": "Aucun(e)",
    "carryOverAttachmentsText": "Reporter les pièces jointes",
    "carryOverNotesText": "Reporter les notes",
    "asScheduledText": "Telle que planifiée",
    "insertText": "Insérer",
    "couldNotSaveErrorText": "Impossible d'enregistrer l'historique car une erreur s'est produite.",
    "deleteMessage": "Vous êtes sur le point de supprimer définitivement cet enregistrement.",
    "deleteTitle": "Supprimer l'historique",
    "couldNotDeleteErrorText": "Impossible de supprimer l'historique car une erreur s'est produite.",
    "postalText": "Code postal",
    "tabNameParticipants": "Tous les participants"
});