define(
"dojo/cldr/nls/sq/currency", //begin v1.x content
{
	"COP_displayName": "Peso kolumbiane",
	"CZK_displayName": "Koruna e Republikës Çeke",
	"TND_displayName": "Dinar tunizian",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dollar xhamajkan",
	"PHP_displayName": "Peso filipinase",
	"ALL_displayName": "Leku shqiptar",
	"USD_symbol": "US$",
	"LBP_displayName": "Sterlina libaneze",
	"VND_displayName": "Dongë vietnameze",
	"LYD_displayName": "Dinar libian",
	"RON_displayName": "Leu rumun",
	"MKD_displayName": "Denar maqedonas",
	"SEK_displayName": "Korona suedeze",
	"CNY_displayName": "Juani kinez",
	"IDR_displayName": "Rupi indoneziane",
	"ILS_displayName": "Shekeli izrealit",
	"YER_displayName": "Rial i Jemenit",
	"TJS_displayName": "Somona taxhike",
	"TTD_displayName": "Dollar i Trinidadit dhe Tobagos",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lirë turke",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirhami i Emirateve të Bashkuara Arabe",
	"KZT_displayName": "Tenga kazake",
	"ALL_symbol": "Lekë",
	"BHD_displayName": "Dinar i Bahreinit",
	"RUB_displayName": "Rubla ruse",
	"NZD_displayName": "Dollar i Zelandës së Re",
	"IQD_displayName": "Dinar irakian",
	"TMT_displayName": "Manata turkmene",
	"INR_symbol": "₹",
	"KGS_displayName": "Soma kirgize",
	"KWD_displayName": "Dinar kuvajtian",
	"AFN_displayName": "Afgani afgan",
	"ARS_displayName": "Peso argjentinase",
	"MAD_displayName": "Dirham maroken",
	"BAM_displayName": "Marka e Bosnjë-Hercegovinës [e shkëmbyeshme]",
	"BOB_displayName": "Boliviani bolivian",
	"BND_displayName": "Dollar i Bruneit",
	"SGD_displayName": "Dollar i Singaporit",
	"MVR_displayName": "Rufiu i Maldivit",
	"MXN_displayName": "Peso meksikane",
	"DZD_displayName": "Dinar algjerian",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar jordanez",
	"PEN_displayName": "Sola nuevo-peruane",
	"GTQ_displayName": "Kuecali i Guatemalës",
	"BYR_displayName": "Rubla bjelloruse",
	"CAD_displayName": "Dollari kanadez",
	"BZD_displayName": "Dollar Belize",
	"CLP_displayName": "Peso kiliane",
	"XOF_displayName": "Franga e Bregut të Fildishtë",
	"NOK_displayName": "Krona norvegjeze",
	"DOP_displayName": "Peso dominikane",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Uoni i Koresë së Jugut",
	"USD_displayName": "Dollari amerikan",
	"UYU_displayName": "Peso uruguaiane",
	"UZS_displayName": "Soma uzbeke",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial i Katarit",
	"SAR_displayName": "Rial saudit",
	"SYP_displayName": "Sterlina siriane",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Stërlina egjiptiane",
	"AMD_displayName": "Drami armen",
	"GBP_displayName": "Sterlina britanike",
	"HUF_displayName": "Forinta hungareze",
	"ISK_displayName": "Krona islandeze",
	"IRR_displayName": "Rial iranian",
	"OMR_displayName": "Riali i Omanit",
	"TWD_displayName": "Dollar tajvanez",
	"PAB_displayName": "Balboa panameze",
	"UAH_displayName": "Rivnia ukrainase",
	"ETB_displayName": "Bira etiopase",
	"PLN_displayName": "Zllota polake",
	"VEF_displayName": "Bolivar venezuelian",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Real brazilian",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dollar i Hong Kongut",
	"NIO_displayName": "Kordoba nikaraguane",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupi nepaleze",
	"PKR_displayName": "Rupi pakistaneze",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari gjeorgjian",
	"AZN_displayName": "Manata azere",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringit malajzian",
	"DKK_displayName": "Koronë daneze",
	"THB_displayName": "Bata tajlandeze",
	"BRL_symbol": "R$",
	"JPY_displayName": "Jen japonez",
	"KES_displayName": "Shilinga keniane",
	"KHR_displayName": "Rial kamboxhian",
	"PYG_displayName": "Guaran paraguaian",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupi e Sri Lankës",
	"BGN_displayName": "Levi bullgar",
	"BDT_displayName": "Takë e Bangladeshit",
	"MOP_displayName": "Patakë e Makaos",
	"HNL_displayName": "Lempira hondurase",
	"RWF_displayName": "Franga ruandeze",
	"CHF_displayName": "Franga zvicerane",
	"CRC_displayName": "Koloni kostarikan",
	"INR_displayName": "Rupi indiane",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Randa e Afrikës së Jugut",
	"AUD_displayName": "Dollar australian",
	"LAK_displayName": "Kipa e Laosit",
	"MNT_displayName": "Tugrika mongole",
	"RSD_displayName": "Dinar serb",
	"HRK_displayName": "Kuna kroate"
}
//end v1.x content
);