define("Sage/Services/nls/it/ActivityService", {
    "txtErrorActionMsg": "L'azione non è riuscita e si è verificato un errore.",
    "txtActivity": "Attività",
    "txtActivities": "Attività",
    "txtActionDeleteActivites": "Elimina attività",
    "txtActionDeleteActivitiesQuestion": "Verranno eliminate solo le attività per cui si dispone dell'autorizzazione di eliminazione. <P> Eliminare le {0} {1} selezionate?",
    "txtAlarm": "allarme",
    "txtAlarms": "Allarmi",
    "txtActionSnoozeAlarm": "Posponi allarme",
    "txtActionSnoozeQuestion": "Posporre i {0} {1} selezionati per {2}?",
    "txtActionSnoozeAllQuestion": "Posporre tutti gli {0} per {1}?",
    "txtActionDismissAlarms": "Ignora allarmi",
    "txtActionDismissAlarmsQuestion": "Ignorare i {0} {1} selezionati?",
    "txtEvent": "Evento",
    "txtEvents": "Eventi",
    "txtActionDeleteEvents": "Elimina eventi",
    "txtActionDeleteEventsQuestion": "Verranno eliminati solo gli eventi per cui si dispone dell'autorizzazione di eliminazione. <P> Eliminare i {0} {1} selezionati?",
    "txtConfirmation": "conferma",
    "txtConfirmations": "conferme",
    "txtActionAcceptConfirmations": "Accettare le conferme",
    "txtActionAcceptConfirmQuestion": "Accettare le {0} {1} selezionate? Questa azione può essere eseguita solo su conferme nuove o modificate. Tutte le altre verranno ignorate.",
    "txtDeclineConfirmations": "Rifiutare le conferme",
    "txtActionDeclineConfrimQuestion": "Rifiutare le {0} {1} selezionate? Questa azione può essere eseguita solo su conferme nuove o modificate. Tutte le altre verranno ignorate.",
    "txtActionRemoveConfirmations": "Elimina conferme",
    "txtActionRemoveConfirmationsQuestion": "Eliminare il {0} selezionato {1}? Questa azione può essere eseguita solo su conferme Coordinatore, Rifiutate o Eliminate. Tutte le altre verranno ignorate.",
    "txtLiteratureRequest": "richiesta documentazione",
    "txtLiteratureRequests": "richieste documentazione",
    "txtActionDeleteLiteratureRequests": "Elimina richieste documentazione",
    "txtActionDeleteLiteratureRequestsQuestion": "Verranno eliminate solo le richieste di documentazione per cui si dispone dell'autorizzazione di eliminazione. <P> Eliminare le {0} {1} selezionate?"
});