define(
"dojo/cldr/nls/sw/currency", //begin v1.x content
{
	"COP_displayName": "Peso ya Kolombia",
	"CZK_displayName": "Koruna ya Jamhuri ya Cheki",
	"TND_displayName": "dinari ya Tunisia",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Dola ya Jamaica",
	"PHP_displayName": "Peso ya Ufilipino",
	"ALL_displayName": "Lek ya Albania",
	"USD_symbol": "US$",
	"LBP_displayName": "Pauni ya Lebanon",
	"VND_displayName": "Dong ya Kivietinamu",
	"LYD_displayName": "dinari ya Libya",
	"RON_displayName": "Leu ya Romania",
	"MKD_displayName": "Denar ya Masedonia",
	"SEK_displayName": "Krona ya Uswidi",
	"CNY_displayName": "yuan Renminbi ya China",
	"IDR_displayName": "Rupiah ya Indonesia",
	"ILS_displayName": "Sheqel Mpya ya Israeli",
	"YER_displayName": "Rial ya Yemen",
	"TJS_displayName": "Somoni ya Tajikistani",
	"TTD_displayName": "Dola ya Trinidad na Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Lira ya Uturuki",
	"EUR_displayName": "yuro",
	"AED_displayName": "dirham ya Falme za Kiarabu",
	"KZT_displayName": "Tenge ya Kazakistani",
	"BHD_displayName": "dinari ya Bahareni",
	"RUB_displayName": "Ruble ya Urusi",
	"NZD_displayName": "Dola ya Nyuzilandi",
	"IQD_displayName": "Dinari ya Irak",
	"TMT_displayName": "Manat ya Turukimenistani",
	"INR_symbol": "₹",
	"KGS_displayName": "Som ya Kirigistani",
	"KWD_displayName": "Dinar ya Kuwait",
	"AFN_displayName": "Afghani ya Afuganistani",
	"ARS_displayName": "Peso ya Ajentina",
	"MAD_displayName": "dirham ya Moroko",
	"BAM_displayName": "Mark ya Bosnia na Hezegovina Inayoweza Kubadilishwa",
	"BOB_displayName": "Boliviano ya Bolivia",
	"BND_displayName": "Dola ya Brunei",
	"SGD_displayName": "Dola ya Singapuri",
	"MVR_displayName": "Rufiyaa ya Maldivi",
	"MXN_displayName": "Peso ya Meksiko",
	"DZD_displayName": "dinari ya Aljeria",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Dinar ya Yordani",
	"PEN_displayName": "Nuevo Sol ya Peru",
	"GTQ_displayName": "Quetzal ya Guatemala",
	"BYR_displayName": "Ruble ya Belarusi",
	"CAD_displayName": "dola ya Kanada",
	"BZD_displayName": "Dola ya Belize",
	"CLP_displayName": "Peso ya Chile",
	"XOF_displayName": "faranga CFA BCEAO",
	"NOK_displayName": "Krone ya Norwe",
	"DOP_displayName": "Peso ya Dominika",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Won ya Korea Kusini",
	"USD_displayName": "dola ya Marekani",
	"UYU_displayName": "Peso ya Urugwai",
	"UZS_displayName": "Som ya Uzibekistani",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Rial ya Katari",
	"SAR_displayName": "riyal ya Saudia",
	"SYP_displayName": "Pauni ya Syria",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "pauni ya Misri",
	"AMD_displayName": "Dram ya Armenia",
	"GBP_displayName": "pauni ya Uingereza",
	"HUF_displayName": "Forint ya Hangaria",
	"ISK_displayName": "Krona ya Isilandi",
	"IRR_displayName": "Rial ya Iran",
	"OMR_displayName": "Rial ya Oman",
	"TWD_displayName": "Dola ya Taiwan",
	"PAB_displayName": "Balboa ya Panama",
	"UAH_displayName": "Hryvnia ya Ukrania",
	"ETB_displayName": "bir ya Uhabeshi",
	"PLN_displayName": "Zloty ya Polandi",
	"VEF_displayName": "Bolivar ya Venezuela",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Real ya Brazil",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Dola ya Hong Kong",
	"NIO_displayName": "Kodoba ya Nikaragua",
	"THB_symbol": "฿",
	"NPR_displayName": "Rupee ya Nepali",
	"PKR_displayName": "Rupee ya Pakistan",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Lari ya Georgia",
	"AZN_displayName": "Manat ya Azebaijan",
	"GBP_symbol": "£",
	"MYR_displayName": "Ringgit ya Malaysia",
	"DKK_displayName": "Krone ya Denmaki",
	"THB_displayName": "Baht ya Tailandi",
	"BRL_symbol": "R$",
	"JPY_displayName": "sarafu ya Kijapani",
	"KES_displayName": "shilingi ya Kenya",
	"KHR_displayName": "Riel ya Kambodia",
	"PYG_displayName": "Guarani ya Paragwai",
	"VND_symbol": "₫",
	"LKR_displayName": "Rupee ya Sri Lanka",
	"BGN_displayName": "Lev ya Bulgaria",
	"BDT_displayName": "Taka ya Bangladesh",
	"MOP_displayName": "Pataca ya Macau",
	"HNL_displayName": "Lempira ya Hondurasi",
	"RWF_displayName": "faranga ya Rwanda",
	"CHF_displayName": "faranga ya Uswisi",
	"CRC_displayName": "Colon ya Kostarika",
	"INR_displayName": "rupia ya India",
	"KES_symbol": "Ksh",
	"KRW_symbol": "₩",
	"ZAR_displayName": "randi ya Afrika Kusini",
	"AUD_displayName": "dola ya Australia",
	"LAK_displayName": "Kip ya Laosi",
	"MNT_displayName": "Tugrik ya Mongolia",
	"RSD_displayName": "Dinar ya Serbia",
	"HRK_displayName": "Kuna ya Kroeshia"
}
//end v1.x content
);