define("Sage/Services/nls/fr/ActivityService", {
    "txtErrorActionMsg": "Cette action a échoué car une erreur est survenue.",
    "txtActivity": "Activité",
    "txtActivities": "Activités",
    "txtActionDeleteActivites": "Supprimer des activités",
    "txtActionDeleteActivitiesQuestion": "Seules les activités que vous avez l'autorisation de supprimer seront supprimées.<P>Voulez-vous vraiment supprimer les {0} {1} sélectionnées ?",
    "txtAlarm": "Alarme",
    "txtAlarms": "Alarmes",
    "txtActionSnoozeAlarm": "Mettre en veille l'alarme",
    "txtActionSnoozeQuestion": "Voulez-vous vraiment mettre en veille les {0} {1} sélectionné(s)s pour {2} ?",
    "txtActionSnoozeAllQuestion": "Voulez-vous vraiment mettre en veille tous les {0} pour {1} ?",
    "txtActionDismissAlarms": "Annuler les alarmes",
    "txtActionDismissAlarmsQuestion": "Voulez-vous vraiment annuler la {0} {1} sélectionnée ?",
    "txtEvent": "Evénement",
    "txtEvents": "Evénements",
    "txtActionDeleteEvents": "Supprimer les événements",
    "txtActionDeleteEventsQuestion": "Seuls les événements que vous avez l'autorisation de supprimer seront supprimés.<P>Voulez-vous vraiment supprimer le {0} {1} sélectionnés ?",
    "txtConfirmation": "Confirmation",
    "txtConfirmations": "Confirmations",
    "txtActionAcceptConfirmations": "Accepter les confirmations",
    "txtActionAcceptConfirmQuestion": "Voulez-vous vraiment accepter les {0} {1} sélectionnées ? Cette action ne peut être effectuée que sur les nouvelles confirmations ou les confirmations modifiées. Toutes les autres seront ignorées.",
    "txtDeclineConfirmations": "Refuser les confirmations",
    "txtActionDeclineConfrimQuestion": "Voulez-vous vraiment refuser les {0} {1} sélectionnées ? Cette action ne peut être effectuée que sur les nouvelles confirmations ou les confirmations modifiées. Toutes les autres seront ignorées.",
    "txtActionRemoveConfirmations": "Supprimer les confirmations",
    "txtActionRemoveConfirmationsQuestion": "Voulez-vous vraiment supprimer les {0} {1} sélectionnées ? Cette action peut uniquement être effectuée sur les confirmations de type Organisateur, Refusé ou Supprimé. Toutes les autres seront ignorées.",
    "txtLiteratureRequest": "Demande de documentation",
    "txtLiteratureRequests": "Demandes de documentation",
    "txtActionDeleteLiteratureRequests": "Supprimer les demandes de documentation",
    "txtActionDeleteLiteratureRequestsQuestion": "Seules les demandes de documentation que vous avez l'autorisation de supprimer seront supprimées. <P> Voulez-vous vraiment supprimer les {0} {1} sélectionnées ?"
});