define("Sage/MainView/Lead/nls/it/ImportLeadsWizard", {
    "yestText": "Sì",
    "noText": "No",
    "confirmOverwriteFileMsg": "Hai un file d'importazione attualmente selezionato. Vuoi sovrascriverlo?",
    "importProgressCaption": "Risultati del processo di importazione",
    "lblPrimaryProgress": "Elaborazione del file di importazione. Attendere...",
    "lblTotalRecords": "Totale record:",
    "lblTotalRecordsProcessed": "Processato:",
    "lblTotalRecordsImported": "Importato:",
    "lblTotalRecordsMerged": "Uniti:",
    "lblTotalDuplicates": "Duplicati:",
    "lblTotalProjectedDuplicates": "Duplicati previsti:",
    "lblDuplicateRate": "Percentuale duplicati:",
    "lblTotalErrors": "Errori:",
    "calculatingText": "Calcolo in corso attendere prego...",
    "importStatusProcessing": "Elaborazione in corso",
    "importStatusCompleted": "Completato",
    "abortImportProcessStatus": "Interrompi",
    "btnCancelText": "Interrompi",
    "btnCloseText": "Chiudi",
    "lblImportHistoryLinkText": "Per visualizzare i risultati della cronologia d'importazione fare clic sul numero qui sotto:",
    "lblImportLinkNumber": "Numero importazione: ",
    "errorRequestImportHistory": "Si è verificato un errore nell'esecuzione della richiesta di esecuzione sdata per l'endpoint importHistory."
});