define(
"dojo/cldr/nls/ka/currency", //begin v1.x content
{
	"COP_displayName": "კოლუმბიური პესო",
	"CZK_displayName": "ჩეხური კრონა",
	"TND_displayName": "ტუნისური დინარი",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "იამაიკური დოლარი",
	"PHP_displayName": "ფილიპინური პესო",
	"ALL_displayName": "ალბანური ლეკი",
	"USD_symbol": "US$",
	"LBP_displayName": "ლიბანური ფუნტი",
	"VND_displayName": "ვიეტნამური დონგი",
	"LYD_displayName": "ლიბიური დინარი",
	"RON_displayName": "რუმინული ლეუ",
	"MKD_displayName": "მაკედონიური დინარი",
	"SEK_displayName": "შვედური კრონა",
	"CNY_displayName": "ჩინური იუანი",
	"IDR_displayName": "ინდონეზიური რუპია",
	"ILS_displayName": "ისრაელის ახალი შეკელი",
	"YER_displayName": "იემენის რეალი",
	"TJS_displayName": "ტაჯიკური სომონი",
	"TTD_displayName": "ტრინიდად და ტობაგოს დოლარი",
	"CNY_symbol": "CNY",
	"TRY_displayName": "ახალი თურქული ლირა",
	"EUR_displayName": "ევრო",
	"AED_displayName": "არაბთა გაერთიანებული საამიროების დირჰამი",
	"KZT_displayName": "ყაზახური ტენგე",
	"BHD_displayName": "ბაჰრეინული დინარი",
	"RUB_displayName": "რუსული რუბლი",
	"NZD_displayName": "ახალი ზელანდიის დოლარი",
	"IQD_displayName": "ერაყული დინარი",
	"TMT_displayName": "თურქმენეთის მანათი",
	"INR_symbol": "INR",
	"KGS_displayName": "ყირგიზული სომი",
	"KWD_displayName": "ქუვეითური დინარი",
	"AFN_displayName": "ავღანური ავღანი",
	"ARS_displayName": "არგენტინული პესო",
	"MAD_displayName": "მაროკოს დირჰამი",
	"BAM_displayName": "ბოსნია და ჰერცოგოვინას კონვერტირებადი მარკა",
	"BOB_displayName": "ბოლივიური ბოლივიანო",
	"BND_displayName": "ბრუნეული დოლარი",
	"SGD_displayName": "სინგაპურის დოლარი",
	"MVR_displayName": "მალდივური რუფია",
	"MXN_displayName": "მექსიკური პესო",
	"DZD_displayName": "ალჟირული დინარი",
	"MXN_symbol": "MX$",
	"JOD_displayName": "იორდანიული დოლარი",
	"PEN_displayName": "პერუს ახალი სოლი",
	"GTQ_displayName": "გვატემალური კეტსალი",
	"BYR_displayName": "ბელორუსული რუბლი",
	"CAD_displayName": "კანადური დოლარი",
	"BZD_displayName": "ბელიზის დოლარი",
	"CLP_displayName": "ჩილეს პესო",
	"XOF_displayName": "(CFA) ფრანკი (BCEAO)",
	"NOK_displayName": "ნორვეგიული კრონა",
	"DOP_displayName": "დომინიკური პესო",
	"JPY_symbol": "JPY",
	"KRW_displayName": "სამხრეთ კორეული ვონი",
	"USD_displayName": "აშშ დოლარი",
	"UYU_displayName": "ურუგვაის პესო",
	"UZS_displayName": "უზბეკური სუმი",
	"XOF_symbol": "CFA",
	"QAR_displayName": "კატარის რიალი",
	"SAR_displayName": "საუდის არაბეთის რიალი",
	"SYP_displayName": "სირიული ფუნტი",
	"NZD_symbol": "NZD",
	"EGP_displayName": "ეგვიპტური გირვანქა",
	"AMD_displayName": "სომხური დრამი",
	"GBP_displayName": "ბრიტანული გირვანქა სტერლინგი",
	"HUF_displayName": "უნგრული ფორინტი",
	"CSD_displayName": "ძველი სერბიული დინარი",
	"ISK_displayName": "ისლანდიური კრონა",
	"IRR_displayName": "ირანული რიალი",
	"OMR_displayName": "ომანის რიალი",
	"TWD_displayName": "ტაივანური ახალი დოლარი",
	"PAB_displayName": "პანამური ბალბოა",
	"UAH_displayName": "უკრაინული გრივნა",
	"ETB_displayName": "ეთიოპიური ბირი",
	"PLN_displayName": "პოლონური ზლოტი",
	"VEF_displayName": "ვენესუელის ბოლივარი",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "ბრაზილიური რეალი",
	"HKD_symbol": "HKD",
	"HKD_displayName": "ჰონკონგის დოლარი",
	"NIO_displayName": "ნიკარაგუული კორდობა",
	"THB_symbol": "THB",
	"NPR_displayName": "ნეპალური რუპია",
	"PKR_displayName": "პაკისტანური რუპია",
	"TWD_symbol": "TWD",
	"GEL_displayName": "ქართული ლარი",
	"AZN_displayName": "აზერბაიჯანული მანათი",
	"GBP_symbol": "£",
	"MYR_displayName": "მალაიზიური რინგიტი",
	"DKK_displayName": "დანიური კრონა",
	"THB_displayName": "ტაილანდური ბატი",
	"BRL_symbol": "R$",
	"JPY_displayName": "იაპონური იენი",
	"KES_displayName": "კენიური შილინგი",
	"KHR_displayName": "კამბოჯური რიელი",
	"PYG_displayName": "პარაგვაული გუარანი",
	"VND_symbol": "VND",
	"LKR_displayName": "შრი-ლანკური რუპია",
	"BGN_displayName": "ბულგარული ლევი",
	"BDT_displayName": "ბანგლადეშური ტაკა",
	"MOP_displayName": "მაკაუს პატაკა",
	"HNL_displayName": "ჰონდურასული ლემპირა",
	"RWF_displayName": "რუანდული ფრანკი",
	"CHF_displayName": "შვეიცარიული ფრანკი",
	"CRC_displayName": "კოსტა-რიკული კოლონი",
	"INR_displayName": "ინდური რუპია",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "სამხრეთ აფრიკული რანდი",
	"AUD_displayName": "ავსტრალიური დოლარი",
	"LAK_displayName": "ლაოსური კიპი",
	"MNT_displayName": "მონღოლური ტუგრიკი",
	"RSD_displayName": "სერბული დინარი",
	"HRK_displayName": "ხორვატული კუნა"
}
//end v1.x content
);