define("Sage/TaskPane/nls/fr/CommonTasksTasklet", {
    "okButtonText": "OK",
    "loadingText": "Chargement...",
    "noPrimaryEmail": "Aucun e-mail principal n'est disponible",
    "selectFileFormat": "Sélectionner un format de fichier :",
    "exportToFile_OptionCSV": "CSV standard",
    "exportToFile_OptionTab": "Délimitation par des tabulations (recommandé pour Microsoft Excel)",
    "exportToFile_OptionSaveFormat": "Se souvenir de mon choix et ne plus me le demander.",
    "exportToFile_OK": "OK",
    "exportToFile_Cancel": "Annuler",
    "exportToFile_DialogTitle": "Exporter",
    "exportToExcel_Caption": "Exportation",
    "errorRequestingJobMgr": "Une erreur s'est produite lors de l'interrogation du gestionnaire de tâches : ${0}",
    "errorExecutionAction": "Une erreur s'est produite lors de l'exécution de l'action ${0}",
    "exportProcessingJobMsg": "Traitement de l'exportation en cours. Vous pouvez attendre la fin de l'opération ou accéder aux rapports pour ouvrir votre fichier.",
    "errorBulkActionNotSupported": "${0} ne prend pas en charge les mises à jour d'action en bloc. Veuillez contacter votre administrateur système.",
    "errorBulkActionRequest": "Une erreur s'est produite lors de la demande d'options de mise à jour en bloc. Veuillez contacter votre administrateur système.",
    "copyProfileNoneSelected": "Vous devez sélectionner au moins un utilisateur !",
    "deleteJob_Description": "Erreur(s) de suppression en bloc",
    "errorRequestEntityImportable": "Une erreur s'est produite lors de la récupération des attributs d'entité. ${0}",
    "entityNotImportable": "${0} ne prend pas en charge l'importation. Veuillez contacter votre administrateur système."
});