define(
"dojo/cldr/nls/ml/currency", //begin v1.x content
{
	"COP_displayName": "കൊളംബിയൻ പെസോ",
	"CZK_displayName": "ചെക്ക് റിപ്പബ്ലിക് കൊരൂന",
	"TND_displayName": "തുനീസിയൻ ദിനാർ",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ജമൈക്കൻ ഡോളർ",
	"PHP_displayName": "ഫിലിപ്പൈൻ പെസോ",
	"ALL_displayName": "അൽബേനിയൻ ലെക്",
	"USD_symbol": "$",
	"LBP_displayName": "ലെബനീസ് പൌണ്ട്",
	"VND_displayName": "വിയറ്റ്നാമീസ് ഡോങ്",
	"LYD_displayName": "ലിബിയൻ ദിനാർ",
	"RON_displayName": "റൊമേനിയൻ ലിയു",
	"MKD_displayName": "മാസിഡോണിയൻ ദിനാർ",
	"SEK_displayName": "സ്വീഡിഷ് ക്രോണ",
	"CNY_displayName": "ചൈനീസ് യുവാൻ",
	"IDR_displayName": "ഇന്തോനേഷ്യൻ രൂപ",
	"ILS_displayName": "ഇസ്രായേലി ഷക്കേൽ",
	"YER_displayName": "യമനി റിയാൽ",
	"TJS_displayName": "താജിക്കിസ്ഥാൻ സൊമോനി",
	"TTD_displayName": "ട്രിനിഡാഡ് ആൻഡ് റ്റൊബാഗോ ഡോളർ",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "തുർക്കിഷ് ലിറ",
	"EUR_displayName": "യൂറോ",
	"AED_displayName": "യു.എ.ഇ. ദിർഹം",
	"KZT_displayName": "കസാഖ്സ്ഥാൻ റ്റെംഗെ",
	"BHD_displayName": "ബഹറിൻ ദിനാർ",
	"RUB_displayName": "റഷ്യൻ റൂബിൾ",
	"NZD_displayName": "ന്യൂസിലാൻഡ് ഡോളർ",
	"IQD_displayName": "ഇറാക്കി ദിനാർ",
	"TMT_displayName": "തുർക്കമനിസ്ഥാനി മനാത്ത്",
	"INR_symbol": "₹",
	"KGS_displayName": "കിർഗിസ്ഥാൻ സോം",
	"KWD_displayName": "കുവൈറ്റി ദിനാർ",
	"AFN_displayName": "അഫ്ഗാൻ അഫ്ഗാനി",
	"ARS_displayName": "അർജൻറീൻ പെസോ",
	"MAD_displayName": "മൊറോക്കൻ ദിർഹം",
	"BAM_displayName": "ബോസ്നിയ-ഹെർസഗോവിന കൺവേർട്ടിബിൾ മാർക്ക്",
	"BOB_displayName": "ബൊളീവിയൻ ബൊളിവിയാനോ",
	"BND_displayName": "ബ്രൂണെ ഡോളർ",
	"SGD_displayName": "സിംഗപ്പൂർ ഡോളർ",
	"MVR_displayName": "മാലദ്വീപ് രൂപ",
	"MXN_displayName": "മെക്സിക്കൻ പെസോ",
	"DZD_displayName": "അൾജീരിയൻ ദിനാർ",
	"MXN_symbol": "MX$",
	"JOD_displayName": "ജോർദ്ദാൻ ദിനാർ",
	"PEN_displayName": "പെറൂവിയൻ സോൾ ന്യൂവോ",
	"GTQ_displayName": "ഗ്വാട്ടിമാല ക്വെറ്റ്സൽ",
	"BYR_displayName": "ബെലാറഷ്യൻ റൂബിൾ",
	"CAD_displayName": "കനേഡിയൻ ഡോളർ",
	"BZD_displayName": "ബെലീസ് ഡോളർ",
	"CLP_displayName": "ചിലിയൻ പെസോ",
	"XOF_displayName": "CFA ഫ്രാങ്ക് BCEAO",
	"NOK_displayName": "നോർവീജിയൻ ക്രോണെ",
	"DOP_displayName": "ഡൊമിനിക്കൻ പെസോ",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "ദക്ഷിണ കൊറിയൻ വോൺ",
	"USD_displayName": "യു.എസ്. ഡോളർ",
	"UYU_displayName": "ഉറുഗ്വേൻ പെസോ",
	"UZS_displayName": "ഉസ്ബക്കിസ്ഥാൻ സം",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ഖത്തർ റിയാൽ",
	"SAR_displayName": "സൌദി റിയാൽ",
	"SYP_displayName": "സിറിയൻ പൌണ്ട്",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "ഈജിപ്ഷ്യൻ പൌണ്ട്",
	"AMD_displayName": "അർമേനിയൻ ഡ്രാം",
	"GBP_displayName": "ബ്രിട്ടീഷ് പൌണ്ട് സ്റ്റെർലിംങ്",
	"HUF_displayName": "ഹംഗേറിയൻ ഫോറിൻറ്",
	"CSD_displayName": "പ്രാചീന സെർബിയൻ ദിനാർ",
	"ISK_displayName": "ഐസ്ലാൻഡിക് ക്രോണ",
	"IRR_displayName": "ഇറാനിയൻ റിയാൽ",
	"OMR_displayName": "ഒമാൻ റിയാൽ",
	"TWD_displayName": "തായ്വാൻ ഡോളർ",
	"PAB_displayName": "പനാമെയ്നിയൻ ബാൽബോവ",
	"UAH_displayName": "യുക്രേനിയൻ ഹ്രിവ്നിയ",
	"ETB_displayName": "എത്യോപ്പിയൻ ബിർ",
	"PLN_displayName": "പോളിഷ് സ്ലോട്ടി",
	"VEF_displayName": "വെനസ്വേലൻ ബോലിവർ",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ബ്രസീലിയൻ റിയാൽ",
	"HKD_symbol": "HK$",
	"HKD_displayName": "ഹോങ് കോങ് ഡോളർ",
	"NIO_displayName": "നികരാഗ്വൻ കൊർഡോബ ഒരോ",
	"THB_symbol": "฿",
	"NPR_displayName": "നേപ്പാളി രൂപ",
	"PKR_displayName": "പാക്കിസ്ഥാനി രൂപ",
	"TWD_symbol": "NT$",
	"GEL_displayName": "ജോർജ്ജിയൻ ലാരി",
	"AZN_displayName": "അസർബയ്ജാനിയൻ മനത്",
	"GBP_symbol": "£",
	"MYR_displayName": "മലേഷ്യൻ റിംഗിറ്റ്",
	"DKK_displayName": "ഡാനിഷ് ക്രോണെ",
	"THB_displayName": "തായ് ബാത്ത്",
	"JPY_displayName": "ജപ്പാനീസ് യെൻ",
	"KES_displayName": "കെനിയൻ ഷില്ലിംഗ്",
	"KHR_displayName": "കംബോഡിയൻ റീൽ",
	"PYG_displayName": "പരാഗ്വേയൻ ഗ്വരനീ",
	"VND_symbol": "₫",
	"LKR_displayName": "ശ്രീലങ്കൻ രൂപ",
	"BGN_displayName": "ബൾഗേറിയൻ ന്യൂലവ്",
	"BDT_displayName": "ബംഗ്ലാദേശി ടാക്ക",
	"MOP_displayName": "മക്കാനീസ് പതാക്ക",
	"HNL_displayName": "ഹോൻഡ്യുറാസ് ലെംപീര",
	"RWF_displayName": "റുവാണ്ടൻ ഫ്രാങ്ക്",
	"CHF_displayName": "സ്വിസ് ഫ്രാങ്ക്",
	"CRC_displayName": "കോസ്റ്റാ റിക്കൻ കോളൻ",
	"INR_displayName": "ഇന്ത്യൻ രൂപ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "ദക്ഷിണ ആഫ്രിക്കൻ റാൻഡ്",
	"AUD_displayName": "ആസ്ട്രേലിയൻ ഡോളർ",
	"LAK_displayName": "ലാവോഷിയൻ കിപ്",
	"MNT_displayName": "മംഗോളിയൻ തുഗ്രിക്",
	"RSD_displayName": "സെർബിയൻ ദിനാർ",
	"HRK_displayName": "ക്രൊയേഷ്യൻ ക്യൂന"
}
//end v1.x content
);