define("Sage/UI/nls/ru/SDataFeed", {
    "contractText": "Договор",
    "contractRequiredText": "Требуется договор",
    "sdataUrlText": "URL-адрес SData",
    "titleText": "Название",
    "usernameText": "Имя пользователя",
    "passwordText": "Пароль",
    "logOnText": "Вход",
    "urlRequiredText": "Требуется URL-адрес SData",
    "urlImproperFormatText": "URL-адрес SData имеет недопустимый формат. Пример: http://localhost/sdata/slx/dynamic/-/",
    "customNoAuthText1": "Приносим извинения за неудобство, но ваш запрос не может быть выполнен. Данные авторизации для этого канала ошибочны или отсутствуют.",
    "customNoAuthText2": "Обновите имя пользователя и пароль для:",
    "feedText": "Канал SData",
    "urlAuthenticationText": "Введите пользовательский канал SData",
    "selectFeedText": "Выберите канал",
    "nextText": "Дальше &gt;",
    "warningText": "Информация",
    "invalidWhereText": "Некорректный оператор where. Проверьте оператор where на ошибки форматирования. Дополнительные сведения см. в разделе справки \"Создание оператора where\".",
    "failedToLoadUrlText": "Не удалось загрузить запрошенный канал. Выберите другой канал или обратитесь к системному администратору.",
    "noFeedSelectedText": "Не выбран тип канала",
    "resourceText": "Ресурс",
    "whereText": "Оператор Where",
    "previousText": "&lt;Назад",
    "noResourceSelectedText": "Выберите ресурс",
    "noColumnsSelectedText": "Выберите один или несколько столбцов для отображения в виджете.",
    "limitRangeText": "Введите значение от 1 до 100",
    "testText": "Тест",
    "cancelText": "Отмена",
    "finishText": "Завершить",
    "exampleQueryText1": "Пример:",
    "exampleQueryText2": "IP-адрес компьютера",
    "exampleQueryText3": "номер порта",
    "exampleWhereText": "Узнать больше",
    "numberRecordsText": "Видимые записи",
    "sageSalesLogixDynamic": "Динамическая сущность Saleslogix",
    "sageSalesLogixSystem": "Система Saleslogix",
    "selectColumnsFromText": "Доступные столбцы:",
    "selectedColumnsFromText": "Выбранные столбцы:"
});