define(
"dojo/cldr/nls/ur/currency", //begin v1.x content
{
	"COP_displayName": "کولمبین پیسہ",
	"CZK_displayName": "جمہوریہ چیک کرونا",
	"TND_displayName": "تیونیسیائی دینار",
	"PHP_displayName": "فلپائینی پیسہ",
	"JMD_displayName": "جمائیکن ڈالر",
	"ALL_displayName": "البانیا کا لیک",
	"USD_symbol": "$",
	"LBP_displayName": "لبانی پونڈ",
	"VND_displayName": "ویتنامی ڈانگ",
	"LYD_displayName": "لیبیائی دینار",
	"RON_displayName": "رومانیائی لیو",
	"MKD_displayName": "مقدونیائی دینار",
	"SEK_displayName": "سویڈن کرونا",
	"CNY_displayName": "چینی یوآن",
	"IDR_displayName": "انڈونیشین روپیہ",
	"ILS_displayName": "اسرائیلی نیا شیکل",
	"YER_displayName": "یمنی ریال",
	"TJS_displayName": "تاجکستانی سومونی",
	"TTD_displayName": "ترینیداد اور ٹوباگو کا ڈالر",
	"TRY_displayName": "ترکی لیرا",
	"EUR_displayName": "یورو",
	"AED_displayName": "متحدہ عرب اماراتی درہم",
	"KZT_displayName": "قزاخستانی ٹینگ",
	"BHD_displayName": "بحرینی دینار",
	"RUB_displayName": "روسی روبل",
	"NZD_displayName": "نیوزی لینڈ ڈالر",
	"IQD_displayName": "عراقی دینار",
	"TMT_displayName": "ترکمانستانی منات",
	"KGS_displayName": "کرغستانی سوم",
	"KWD_displayName": "کویتی دینار",
	"AFN_displayName": "افغان افغانی",
	"ARS_displayName": "ارجنٹائن پیسہ",
	"MAD_displayName": "مراکشی درہم",
	"BAM_displayName": "بوسنیا ہرزیگووینا کا قابل منتقلی نشان",
	"BOB_displayName": "بولیوین بولیویانو",
	"BND_displayName": "برونئی ڈالر",
	"SGD_displayName": "سنگا پور ڈالر",
	"MVR_displayName": "مالدیپ کا روفیہ",
	"MXN_displayName": "میکسیکی پیسہ",
	"DZD_displayName": "الجیریائی دینار",
	"JOD_displayName": "اردنی دینار",
	"PEN_displayName": "پیروین نیووسول",
	"GTQ_displayName": "گواٹے مالا کا کوئٹزل",
	"BYR_displayName": "بیلاروسی روبل",
	"CAD_displayName": "کنیڈین ڈالر",
	"BZD_displayName": "بیلائز ڈالر",
	"CLP_displayName": "چلّین پیسہ",
	"XOF_displayName": "CFA فرانک BCEAO",
	"NOK_displayName": "ناروے کرونر",
	"DOP_displayName": "ڈومنیکن پیسو",
	"KRW_displayName": "جنوبی کوریائی وون",
	"USD_displayName": "امریکی ڈالر",
	"UYU_displayName": "یوروگویان پیسو",
	"UZS_displayName": "ازبکستان سوم",
	"XOF_symbol": "CFA",
	"QAR_displayName": "قطری ریال",
	"SAR_displayName": "سعودی ریال",
	"SYP_displayName": "شامی پونڈ",
	"EGP_displayName": "مصری پائونڈ",
	"AMD_displayName": "آرمینیائی ڈرم",
	"GBP_displayName": "انگلستانی پاونڈ سٹرلنگ",
	"HUF_displayName": "ہنگرین فورنٹ",
	"ISK_displayName": "آئس لینڈ کا کرونا",
	"IRR_displayName": "ایرانی ریال",
	"OMR_displayName": "عمانی ریال",
	"TWD_displayName": "نیو تائیوان ڈالر",
	"PAB_displayName": "پنامہ کا بالبوآ",
	"UAH_displayName": "یوکرینیائی ہریونیا",
	"ETB_displayName": "ایتھوپیائی بِرّ",
	"PLN_displayName": "پولش نیو زلوٹی",
	"VEF_displayName": "وینزویلا بولیور",
	"AUD_symbol": "A$",
	"BRL_displayName": "برازیلی ریئل",
	"HKD_displayName": "ھانگ کانگ ڈالر",
	"NIO_displayName": "نکارا گوا کا کورڈوبا",
	"NPR_displayName": "نیپالی روپیہ",
	"PKR_displayName": "پاکستانی روپیہ",
	"GEL_displayName": "جارجیائی لاری",
	"AZN_displayName": "آذربائجانی منات",
	"MYR_displayName": "ملیشیائی رنگِٹ",
	"DKK_displayName": "ڈنمارک کرونر",
	"THB_displayName": "تھائی باہت",
	"JPY_displayName": "جاپانی ین",
	"KES_displayName": "کینیائی شلنگ",
	"KHR_displayName": "کمبوڈیائی ریئل",
	"PKR_symbol": "Rs",
	"PYG_displayName": "پیراگوئے کا گوآرنی",
	"LKR_displayName": "سری لنکائی روپیہ",
	"BGN_displayName": "بلغارین لیو",
	"BDT_displayName": "بنگلہ دیشی ٹکا",
	"MOP_displayName": "میکانیز پٹاکا",
	"HNL_displayName": "ہونڈوران لیمپیرا",
	"RWF_displayName": "روانڈا کا فرینک",
	"CHF_displayName": "سوئس فرانکس",
	"CRC_displayName": "کوسٹا ریکا کا کولن",
	"INR_displayName": "انڈین روپیہ",
	"ZAR_displayName": "جنوبی افریقی رانڈ",
	"AUD_displayName": "آسٹریلین ڈالر",
	"LAK_displayName": "لاؤشیائی کِپ",
	"MNT_displayName": "منگولیائی ٹگرِ",
	"RSD_displayName": "سربین دینار",
	"HRK_displayName": "کروشین کونا"
}
//end v1.x content
);