define("Sage/MainView/ActivityMgr/nls/de/EditEventEditor", {
    "titleScheduleText": "Ereignis planen",
    "titleEditText": "Ereignis bearbeiten",
    "lblDayTypeText": "Tagestyp:",
    "lblStartDateText": "Startdatum:",
    "lblEndDateText": "Enddatum:",
    "lblUserText": "Benutzer:",
    "lookupUserText": "Benutzer suchen",
    "lblCategoryText": "Kategorie:",
    "lblLocationText": "Standort:",
    "lblDescriptionText": "Beschreibung:",
    "btnOkayText": "OK",
    "btnCancelText": "Abbrechen",
    "btnHelpText": "Hilfe",
    "eventTypeActiveText": "Aktiv",
    "eventTypeBusinessTripText": "Geschäftsreise",
    "eventTypeConferenceText": "Konferenz",
    "eventTypeHolidayText": "Feiertag",
    "eventTypeOffText": "Frei",
    "eventTypeTradeShowText": "Messe",
    "eventTypeUnavailableText": "Nicht verfügbar",
    "eventTypeVacationText": "Urlaub",
    "errorText": "Das Ereignis konnte aufgrund eines Fehlers nicht erstellt werden.",
    "invaildDatesText": "Das Enddatum darf nicht vor dem Startdatum liegen.",
    "nameText": "Name"
});