define("Sage/MainView/ActivityMgr/nls/de/HistoryEditor", {
    "labelWidth": "100",
    "tabNameGeneralText": "Allgemein",
    "tabNameAttachmentsText": "Anlagen",
    "scheduleText": "Zeitplan",
    "startTimeText": "Geplant",
    "completedDateText": "Abgeschlossen",
    "timeLessText": "Ohne Zeitangabe",
    "durationText": "Dauer",
    "contactText": "Kontakt",
    "accountText": "Firma",
    "leadText": "Interessent",
    "opportunityText": "Verkaufschance",
    "ticketText": "Ticket",
    "companyText": "Unternehmen",
    "regardingText": "Betreff",
    "resultText": "Ergebnis",
    "notesText": "Notizen",
    "priorityText": "Priorität",
    "leaderText": "Organisator",
    "categoryText": "Kategorie",
    "locationText": "Standort",
    "scheduledByFormatText": "Geplant von ${user} am ${date}",
    "cancelText": "Abbrechen",
    "okText": "OK",
    "deleteText": "Löschen",
    "lookupActText": "Firma suchen",
    "lookupContactText": "Kontakt suchen",
    "lookupOpportunityText": "Verkaufschance suchen",
    "lookupTicketText": "Ticket suchen",
    "lookupLeadText": "Interessent suchen",
    "lookupLeaderText": "Organisator suchen",
    "lookupResourcesText": "Suchen",
    "mainPhoneText": "Haupttelefonnummer",
    "typeText": "Typ",
    "subTypeText": "Untertyp",
    "nameText": "Name",
    "cityText": "Stadt",
    "stateText": "Bundesland",
    "workphoneText": "Geschäftliche Telefonnummer",
    "emailText": "E-Mail",
    "acctMgrText": "Account-Manager",
    "descriptionText": "Beschreibung",
    "stageText": "Phase",
    "statusText": "Status",
    "ownerText": "Zugriffsberechtigter",
    "ticketNumberText": "Ticketnummer",
    "phoneText": "Telefon",
    "urgencyText": "Dringlichkeit",
    "areaText": "Bereich",
    "recurringText": "Wiederkehrend",
    "followupText": "Folgeaktivität",
    "noneText": "Keine",
    "carryOverAttachmentsText": "Anlagen übertragen",
    "carryOverNotesText": "Notizen übertragen",
    "asScheduledText": "Wie geplant",
    "insertText": "Einfügen",
    "couldNotSaveErrorText": "Da ein Fehler auftrat, konnte die Historie leider nicht gespeichert werden.",
    "deleteMessage": "Sie sind im Begriff, diesen Datensatz endgültig zu löschen.",
    "deleteTitle": "Historie löschen",
    "couldNotDeleteErrorText": "Da ein Fehler auftrat, konnte die Historie leider nicht gelöscht werden.",
    "postalText": "Postleitzahl",
    "tabNameParticipants": "Alle Teilnehmer"
});