define("Sage/MainView/ActivityMgr/nls/de/RecurringEditor", {
    "activityOccurrsText": "Diese Aktivität erfolgt...",
    "onceText": "Einmalig",
    "dailyText": "Täglich",
    "weeklyText": "Wöchentlich",
    "monthlyText": "Monatlich",
    "yearlyText": "Jährlich",
    "occursOnceText": "Diese Aktivität erfolgt nur einmal",
    "everyText": "Alle",
    "daysText": "Tag(e)",
    "daysAfterText": "Tag(e) nach Abschluss",
    "startRecurringText": "Wiederholung starten: ",
    "endAfterText": "Beenden nach",
    "endOnText": "Wiederholung beenden",
    "occurrencesText": "Vorkommen",
    "weeksOnText": "Woche(n) am",
    "monText": "Montag",
    "tueText": "Dienstag",
    "wedText": "Mittwoch",
    "thurText": "Donnerstag",
    "friText": "Freitag",
    "satText": "Samstag",
    "sunText": "Sonntag",
    "weeksAfterText": "Woche(n) nach Abschluss",
    "monthsOnText": "Monat(e) an Tag",
    "monthsOnTheText": "Monat(e) am",
    "monthsAfterText": "Monat(e) nach Abschluss",
    "firstText": "1.",
    "secondText": "2.",
    "thirdText": "3.",
    "fourthText": "4.",
    "lastText": "letzten",
    "yearsOnText": "Jahr(e) am",
    "yearsAfterText": "Jahr(e) nach Abschluss",
    "janText": "Januar",
    "febText": "Februar",
    "marText": "März",
    "aprText": "April",
    "mayText": "Mai",
    "junText": "Juni",
    "julText": "Juli",
    "augText": "August",
    "sepText": "September",
    "octText": "Oktober",
    "novText": "November",
    "decText": "Dezember",
    "theText": "Am",
    "inText": "im"
});