define("Sage/MainView/ReportMgr/Crystal/nls/ru/CrystalReportConditionEditor", {
    "dlgCrystalReportConditionDetails_Title": "Добавить/редактировать условие",
    "cmdOK_Caption": "OК",
    "cmdCancel_Caption": "Отмена",
    "cmbConditionType_Caption": "Поиск по",
    "txtInvalidParameterTitle": "Некорректный параметр: \"\".",
    "txtInvalidParameterMessage": "Некорректный параметр: \"${0}\".",
    "lkpUser_Caption": "Пользователь",
    "lkpGroup_Caption": "Группа",
    "txtSelectUser": "Выбрать пользователя",
    "chkCurrentUser_Caption": "Текущий пользователь",
    "txtName": "Имя",
    "txtOK": "OК",
    "txtSelectGroup": "Выбрать группу",
    "cmbDateRange_Caption": "Диапазон дат",
    "cmbDateRange_SpecificDates_Caption": "Точные даты",
    "cmbDateRange_ThisWeek_Caption": "Эта неделя",
    "cmbDateRange_ThisMonth_Caption": "Этот месяц",
    "cmbDateRange_ThisQuarter_Caption": "Этот квартал",
    "cmbDateRange_ThisYear_Caption": "Этот год",
    "cmbDateRange_LastWeek_Caption": "Прошлая неделя",
    "cmbDateRange_LastMonth_Caption": "Прошлый месяц",
    "cmbDateRange_LastQuarter_Caption": "Прошлый квартал",
    "cmbDateRange_LastYear_Caption": "Прошлый год",
    "cmbDateRange_MonthToDate_Caption": "С начала месяца",
    "cmbDateRange_QuarterToDate_Caption": "С начала квартала",
    "cmbDateRange_YearToDate_Caption": "С начала года",
    "dtFromDate_Caption": "От",
    "dtToDate_Caption": "Для",
    "cmbTable_Caption": "Таблица",
    "cmbField_Caption": "Поле",
    "cmbOperator_Caption": "Оператор",
    "txtValue_Caption": "Значение",
    "txtNumericValueFrom_Caption": "От",
    "txtNumericValueTo_Caption": "Для"
});