define("Sage/MainView/CopyUserProfile/nls/ru/CopyUserProfile", {
    "dlg_Title": "Копировать профиль",
    "dlg_Instructions": "Выберите профиль пользователя или шаблон для копирования для других пользователей. Копирование профиля обновит текущие настройки.",
    "rad_SelectionLabel": "Копировать профиль из:",
    "rad_UserBtn": "Существующий пользователь",
    "rad_TemplateBtn": "Шаблон",
    "user_LookupLabel": "Пользователь",
    "template_LookupLabel": "Шаблон",
    "lookupUserNameColText": "Имя пользователя",
    "lookupTitleColText": "Название",
    "lookupDepartmentColText": "Отдел",
    "lookupRegionColText": "Регион",
    "lookupUser_Caption": "Пользователь для копирования профиля",
    "lookupUserNameTemplateColText": "Шаблон",
    "chkGeneralLabel": "Общее",
    "chkCalendarLabel": "Календарь",
    "chkEmployeeLabel": "Сотрудник",
    "chkClientLabel": "Параметры клиента (клиентская система)",
    "chkSecurityLabel": "Безопасность",
    "chkServiceLabel": "Сервис/поддержка",
    "chkTeamsLabel": "Команды",
    "txtJobDescriptor": "Копировать профиль пользователя",
    "jobFailer": "Возникла критическая ошибка"
});