define("Sage/UI/nls/ru/ActivityScheduler", {
    "tooltipTime": "Время",
    "tooltipContactName": "Контакт",
    "tooltipAccountName": "Клиент",
    "tooltipCompanyName": "Компания",
    "tooltipLeadName": "Заинтересованное лицо",
    "tooltipPhoneNumber": "Телефон",
    "tooltipRegarding": "Тема",
    "tooltipPriority": "Приоритет",
    "tooltipNotes": "Заметки",
    "tooltipType": "Тип",
    "tooltipDayType": "Тип дня",
    "tooltipStartDate": "Дата начала",
    "tooltipEndDate": "Дата окончания",
    "tooltipLocation": "Местоположение",
    "tooltipDescription": "Описание",
    "completedText": "(завершено)",
    "tooltipMoreActivities": "Нажмите, чтобы увидеть больше действий",
    "scheduler_dates": {
        "month_full": [
            "Январь",
            "Февраль",
            "Март",
            "Апрель",
            "Май",
            "Июнь",
            "Июль",
            "Август",
            "Сентябрь",
            "Октябрь",
            "Ноябрь",
            "Декабрь"
        ],
        "month_short": [
            "Янв",
            "Фев",
            "Мар",
            "Апр",
            "Май",
            "Июнь",
            "Июль",
            "Авг",
            "Сен",
            "Окт",
            "Ноя",
            "Дек"
        ],
        "day_full": [
            "Воскресенье",
            "Понедельник",
            "Вторник",
            "Среда",
            "Четверг",
            "Пятница",
            "Суббота"
        ],
        "day_short": [
            "Вс",
            "Пн",
            "Вт",
            "Ср",
            "Чт",
            "Пт",
            "Сб"
        ]
    },
    "scheduler_labels": {
        "dhx_cal_today_button": "Сегодня",
        "day_tab": "День",
        "week_tab": "Неделя",
        "workweek_tab": "Рабочая неделя",
        "month_tab": "Месяц",
        "new_event": "Новое событие",
        "icon_save": "Сохранить",
        "icon_cancel": "Отмена",
        "icon_details": "Подробности",
        "icon_edit": "Редактировать",
        "icon_delete": "Удалить",
        "confirm_closing": "",
        "confirm_deleting": "События будут удалены окончательно, вы уверены?",
        "section_description": "Описание",
        "section_time": "Период времени",
        "full_day": "Полный день",
        "confirm_recurring": "Вы хотите редактировать весь набор повторяющихся событий?",
        "section_recurring": "Повторение событий",
        "button_recurring": "Выключено",
        "button_recurring_open": "Активировано",
        "agenda_tab": "Повестка дня",
        "date": "Дата",
        "description": "Описание",
        "year_tab": "Год",
        "week_agenda_tab": "Повестка дня"
    }
});