define("Sage/UI/nls/ru/JobSchedulingWidget", {
    "lblCreateSchedule": "Создать расписание задания для запуска",
    "lblEveryText": "Каждый",
    "lblOnText": "в",
    "lblOnTheText": "в",
    "lblAtText": "в",
    "lblMinutesPastHour": "мин. после часа",
    "lblFromTimeText": "Запуск с",
    "lblToTimeText": "для",
    "lblMinutesFrequency": "минуты",
    "lblHourlyFrequency": "часы",
    "lblDailyFrequency": "день",
    "lblWeekDayFrequency": "будний день",
    "lblWeeklyFrequency": "неделя",
    "lblMonthlyFrequency": "месяц",
    "lblYearlyFrequency": "год",
    "lblSunday": "Воскресенье",
    "lblMonday": "Понедельник",
    "lblTuesday": "Вторник",
    "lblWednesday": "Среда",
    "lblThursday": "Четверг",
    "lblFriday": "Пятница",
    "lblSaturday": "Суббота",
    "lblFirstDay": "первый",
    "lblSecondDay": "второй",
    "lblThirdDay": "третий",
    "lblFourthDay": "четвертый",
    "lblCronExpressionText": "Выражение cron",
    "txtInvalidScheduleTitle": "Недопустимое расписание",
    "txtInvalidDatesMessage": "Время окончания не должно быть раньше времени начала. Исправьте эту информацию перед продолжением.",
    "txtInvalidScheduleTime": "Указанное время начала и окончания не позволяет выполнить это расписание. Исправьте эту информацию перед продолжением.",
    "txtInvalidStartDate": "Требуется дата начала. Укажите дату начала перед продолжением.",
    "txtInvalidEndDate": "Требуется дата окончания. Укажите дату окончания перед продолжением."
});