define("Sage/UI/nls/ru/NotesHistoryList", {
    "typeText": "Тип",
    "showDbChangesText": "Показать изменения базы данных",
    "selectAllText": "Выбрать все",
    "dateText": "Дата",
    "dateTimeText": "Дата/время",
    "dateRangeText": "Диапазон дат",
    "userText": "Пользователь",
    "accountText": "Клиент",
    "contactText": "Контакт",
    "opportunityText": "Возможность",
    "regardingText": "Тема",
    "notesText": "Заметки",
    "resultText": "Результат",
    "categoryText": "Категория",
    "sendEmailText": "Отправить по электронной почте",
    "sendToWordText": "Отправить в Word",
    "addNoteText": "Добавить заметку",
    "completeAnActivityText": "Завершить действие",
    "helpText": "Справка",
    "pleaseSelectRecordsText": "Выберите одну или несколько записей",
    "UnableToFindWordMsg": "Невозможно запустить Microsoft Word. Проверьте ваши установки по безопасности.",
    "printedOnText": "Дата печати",
    "errorNoData": "Отсутствуют заметки/история, чтобы открыть общий доступ к ним для Ming.le.",
    "yesButtonText": "Да",
    "noButtonText": "Нет",
    "salesLogixPageTitle": "Infor CRM",
    "noRecordsSelectedProcessAll": "Не выбрано ни одной записи. Все заметки/история (кол-во записей: ${0}), будут открыты для общего доступа для Ming.le. Продолжить?",
    "errorShareMingle": "Возникла ошибка при открытии общего доступа к одной или нескольким заметкам/истории для Ming.le.",
    "sharedToMingle": "Заметки/история открыты для общего доступа для Ming.le.",
    "sharingToMingle": "Общий доступ для Ming.le",
    "shared": "Открыто для общего доступа",
    "pleaseWait": "Подождите...",
    "failedToPost": "Не удалось опубликовать: ${0}; ошибка: ${1}",
    "addressText": "Адрес",
    "mainPhoneText": "Основной телефон",
    "tollFreeText": "Бесплатный справочный телефон",
    "contactPhoneText": "Контактный телефон"
});