define("Sage/MainView/GroupMgr/templates/nls/zh-tw/ReleasesDetailSummary", {
    "txtGroupFamily_Caption": "系列:",
    "txtGroupName_Caption": "名稱:",
    "txtGroupDisplayName_Caption": "顯示名稱:",
    "txtGroupDescription_Caption": "描述:",
    "txtGroupId_Caption": "ID:",
    "txtGroupMainTable_Caption": "主要表格:",
    "txtGroupEntityName_Caption": "實體名稱:",
    "txtGroupCreateDate_Caption": "建立日期:",
    "txtGroupCreateUser_Caption": "建立使用者:",
    "txtGroupModifyDate_Caption": "修改日期:",
    "txtGroupModifyUser_Caption": "修改使用者:",
    "txtGroupInstallationDate_Caption": "安裝日期:",
    "txtGroupShared_Caption": "共用:",
    "txtGroupSharedDate_Caption": "共用日期:",
    "txtGroupOwner_Caption": "擁有者:",
    "txtGroupUserId_Caption": "使用者 ID:",
    "txtGroupAdhoc_Caption": "臨時:",
    "txtGroupHidden_Caption": "隱藏:",
    "txtGroupAuthor_Caption": "作者:",
    "txtGroupCompany_Caption": "公司:",
    "txtGroupCompanyVersion_Caption": "公司版本:",
    "txtGroupDev_Caption": "Dev:",
    "txtGroupDataCode_Caption": "資料代碼 :",
    "txtGroupType_Caption": "群組類型:",
    "txtGroupBasedOn_Caption": "依據群組 ID:",
    "txtGroupReleasedToType_Caption": "共用對象類型:",
    "txtGroupReleasedTo_Caption": "共用對象名稱:",
    "txtGroupReleasedToTitle_Caption": "共用對象標題:",
    "txtGroupReleasedToUserType_Caption": "共用對象使用者類型:"
});