define("Sage/UI/Alarms/nls/zh-cn/AlarmPane", {
    "dismissAllText": "全部消除",
    "dismissText": "消除",
    "fiveMinText": "5 分钟",
    "tenMinText": "10 分钟",
    "fifteenMinText": "15 分钟",
    "thirtyMinText": "30 分钟",
    "oneHourText": "1 小时",
    "twoHourText": "2 小时",
    "fourHourText": "4 小时",
    "eightHourText": "8 小时",
    "oneDayText": "1 天",
    "twoDayText": "2 天",
    "threeDayText": "3 天",
    "oneWeekText": "1 周",
    "twoWeekText": "2 周",
    "snoozeText": "推迟",
    "snoozeByText": "推迟:",
    "snoozeAllText": "全部推迟",
    "showCalendarText": "显示日历"
});