define(
"dojo/cldr/nls/el/currency", //begin v1.x content
{
	"COP_displayName": "Πέσο Κολομβίας",
	"CZK_displayName": "Κορόνα Τσεχίας",
	"TND_displayName": "Δηνάριο Τυνησίας",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Δολάριο Τζαμάικας",
	"PHP_displayName": "Πέσο Φιλιππίνων",
	"ALL_displayName": "Λεκ Αλβανίας",
	"USD_symbol": "$",
	"LBP_displayName": "Λίρα Λιβάνου",
	"VND_displayName": "Ντονγκ Βιετνάμ",
	"LYD_displayName": "Δηνάριο Λιβύης",
	"RON_displayName": "Λέου Ρουμανίας",
	"MKD_displayName": "Δηνάριο Π.Γ.Δ.Μ.",
	"SEK_displayName": "Κορόνα Σουηδίας",
	"CNY_displayName": "Γουάν Κίνας",
	"IDR_displayName": "Ρουπία Ινδονησίας",
	"ILS_displayName": "Νέο Σέκελ Ισραήλ",
	"YER_displayName": "Ριάλ Υεμένης",
	"TJS_displayName": "Σομόνι Τατζικιστάν",
	"TTD_displayName": "Δολάριο Τρινιντάντ και Τομπάγκο",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Τουρκική Λίρα",
	"EUR_displayName": "Ευρώ",
	"AED_displayName": "Ντιράμ Ηνωμένων Αραβικών Εμιράτων",
	"KZT_displayName": "Τένγκε Καζακστάν",
	"BHD_displayName": "Δηνάριο Μπαχρέιν",
	"RUB_displayName": "Ρούβλι Ρωσίας",
	"NZD_displayName": "Δολάριο Νέας Ζηλανδίας",
	"IQD_displayName": "Δηνάριο Ιράκ",
	"TMT_displayName": "Μάνατ Τουρκμενιστάν",
	"ZWL_displayName": "Δολάριο Ζιμπάμπουε (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Σομ Κιργιζίας",
	"KWD_displayName": "Δηνάριο Κουβέιτ",
	"AFN_displayName": "Αφγάνι Αφγανιστάν",
	"ARS_displayName": "Πέσο Αργεντινής",
	"MAD_displayName": "Ντιράμ Μαρόκου",
	"BAM_displayName": "Μετατρέψιμο Μάρκο Βοσνίας-Ερζεγοβίνης",
	"BOB_displayName": "Μπολιβιάνο Βολιβίας",
	"BND_displayName": "Δολάριο Μπρουνέι",
	"SGD_displayName": "Δολάριο Σιγκαπούρης",
	"MVR_displayName": "Ρουφίγια Μαλδίβων",
	"MXN_displayName": "Πέσο Μεξικού",
	"DZD_displayName": "Δηνάριο Αλγερίας",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Δηνάριο Ιορδανίας",
	"PEN_displayName": "Νέο Σολ Περού",
	"GTQ_displayName": "Κουετσάλ Γουατεμάλας",
	"BYR_displayName": "Ρούβλι Λευκορωσίας",
	"CAD_displayName": "Δολάριο Καναδά",
	"BZD_displayName": "Δολάριο Μπελίζ",
	"CLP_displayName": "Πέσο Χιλής",
	"XOF_displayName": "Φράγκο CFA Δυτικής Αφρικής",
	"NOK_displayName": "Κορόνα Νορβηγίας",
	"DOP_displayName": "Πέσο Δομινικανής Δημοκρατίας",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Γουόν Νότιας Κορέας",
	"USD_displayName": "Δολάριο ΗΠΑ",
	"UYU_displayName": "Πέσο Ουρουγουάης",
	"UZS_displayName": "Σομ Ουζμπεκιστάν",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Ριάλ Κατάρ",
	"SAR_displayName": "Ριάλ Σαουδικής Αραβίας",
	"SYP_displayName": "Λίρα Συρίας",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Λίρα Αιγύπτου",
	"AMD_displayName": "Ντραμ Αρμενίας",
	"GBP_displayName": "Λίρα Στερλίνα Βρετανίας",
	"HUF_displayName": "Φιορίνι Ουγγαρίας",
	"CSD_displayName": "Παλαιό Δηνάριο Σερβίας",
	"ISK_displayName": "Κορόνα Ισλανδίας",
	"IRR_displayName": "Ριάλ Ιράν",
	"OMR_displayName": "Ριάλ Ομάν",
	"TWD_displayName": "Νέο δολάριο Ταϊβάν",
	"PAB_displayName": "Μπαλμπόα Παναμά",
	"UAH_displayName": "Γρίβνα Ουκρανίας",
	"ETB_displayName": "Μπιρ Αιθιοπίας",
	"PLN_displayName": "Ζλότι Πολωνίας",
	"VEF_displayName": "Μπολιβάρ Βενεζουέλας",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Ρεάλ Βραζιλίας",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Δολάριο Χονγκ Κονγκ",
	"NIO_displayName": "Χρυσή Κόρδοβα Νικαράγουας",
	"THB_symbol": "฿",
	"NPR_displayName": "Ρουπία Νεπάλ",
	"PKR_displayName": "Ρουπία Πακιστάν",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Λάρι Γεωργίας",
	"AZN_displayName": "Μανάτ Αζερμπαϊτζάν",
	"GBP_symbol": "£",
	"MYR_displayName": "Ρινγκίτ Μαλαισίας",
	"DKK_displayName": "Κορόνα Δανίας",
	"THB_displayName": "Μπατ Ταϊλάνδης",
	"BRL_symbol": "R$",
	"JPY_displayName": "Γιεν Ιαπωνίας",
	"KES_displayName": "Σελίνι Κένυας",
	"KHR_displayName": "Ρίελ Καμπότζης",
	"PYG_displayName": "Γκουαρανί Παραγουάης",
	"VND_symbol": "₫",
	"LKR_displayName": "Ρουπία Σρι Λάνκα",
	"BGN_displayName": "Λεβ Βουλγαρίας",
	"BDT_displayName": "Τάκα Μπαγκλαντές",
	"MOP_displayName": "Πατάκα Μακάο",
	"HNL_displayName": "Λεμπίρα Ονδούρας",
	"RWF_displayName": "Φράγκο Ρουάντας",
	"CHF_displayName": "Φράγκο Ελβετίας",
	"CRC_displayName": "Κολόν Κόστα Ρίκα",
	"INR_displayName": "Ρουπία Ινδίας",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Ραντ Νότιας Αφρικής",
	"AUD_displayName": "Δολάριο Αυστραλίας",
	"LAK_displayName": "Κιπ Λάος",
	"MNT_displayName": "Τουγκρίκ Μογγολίας",
	"RSD_displayName": "Δηνάριο Σερβίας",
	"HRK_displayName": "Κούνα Κροατίας"
}
//end v1.x content
);