define(
"dojo/cldr/nls/sr-latn/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbijski pezo",
	"CZK_displayName": "Češka kruna",
	"TND_displayName": "Tunežanski dinar",
	"EUR_symbol": "€",
	"JMD_displayName": "Jamajkanski dolar",
	"PHP_displayName": "Filipinski pezo",
	"ALL_displayName": "Albanski lek",
	"LBP_displayName": "Libanska funta",
	"VND_displayName": "Vijetnamski dong",
	"LYD_displayName": "Libijski dinar",
	"RON_displayName": "Rumunski lej (1952–2006)",
	"MKD_displayName": "Makedonski denar",
	"SEK_displayName": "Švedska kruna",
	"CNY_displayName": "Kineski juan renminbi",
	"IDR_displayName": "Indonežanska rupija",
	"ILS_displayName": "Izraelski novi šekel",
	"YER_displayName": "Jemenski rijal",
	"TJS_displayName": "Tadžihistanski somon",
	"TTD_displayName": "Trinidad tobagoški dolar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Turska lira",
	"EUR_displayName": "Evro",
	"AED_displayName": "Ujedinjeni arapski emirati dirham",
	"KZT_displayName": "Kazahstanski tendž",
	"BHD_displayName": "Bahreinski dinar",
	"RUB_displayName": "Ruska rublja",
	"NZD_displayName": "Novozelandski dolar",
	"IQD_displayName": "Irački dinar",
	"TMT_displayName": "Turkmenistanski manat",
	"ZWL_displayName": "Zimbabveanski dolar (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgistanski som",
	"KWD_displayName": "Kuvajtski dinar",
	"TRY_symbol": "Tl",
	"AFN_displayName": "Avganistanski avgani",
	"ARS_displayName": "Argentinski pezo",
	"PLN_symbol": "zl",
	"MAD_displayName": "Marokanski dirham",
	"BAM_displayName": "Konvertibilna marka",
	"BOB_displayName": "Bolivijski Boliviano",
	"BND_displayName": "Brunejski dolar",
	"SGD_displayName": "Singapurski dolar",
	"MVR_displayName": "Maldivska rufija",
	"MXN_displayName": "Meksički pezo",
	"DZD_displayName": "Alžirski dinar",
	"BAM_symbol": "KM",
	"JOD_displayName": "Jordanski dinar",
	"PEN_displayName": "Peruanski nuevo sol",
	"GTQ_displayName": "Gvatemalski kvecal",
	"BYR_displayName": "Beloruska rublja",
	"CAD_displayName": "Kanadski dolar",
	"BZD_displayName": "Belize dolar",
	"CLP_displayName": "Čileanski pezo",
	"XOF_displayName": "CFA franak BCEAO",
	"NOK_displayName": "Norveška kruna",
	"DOP_displayName": "Dominikanski pezo",
	"JPY_symbol": "¥",
	"KRW_displayName": "Južnokorejski Von",
	"USD_displayName": "Američki dolar",
	"UYU_displayName": "Urugvajski pezo",
	"UZS_displayName": "Uzbekistanski som",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Katarški rijal",
	"SAR_displayName": "Saudijski rijal",
	"SYP_displayName": "Sirijska funta",
	"EGP_displayName": "Egipatska funta",
	"AMD_displayName": "Jermenski dram",
	"GBP_displayName": "Britanska funta sterlinga",
	"HUF_displayName": "Mađarska forinta",
	"CSD_displayName": "Stari srpski dinar",
	"ISK_displayName": "Islandska kruna",
	"RSD_symbol": "din.",
	"IRR_displayName": "Iranski rijal",
	"OMR_displayName": "Omanski rijal",
	"TWD_displayName": "Novi tajvanski dolar",
	"PAB_displayName": "Panamska balboa",
	"UAH_displayName": "Ukrajinska hrivnja",
	"ETB_displayName": "Etiopijski bir",
	"PLN_displayName": "Poljski zlot",
	"VEF_displayName": "Venecuelanski bolivar",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Brazilski Real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hongkonški dolar",
	"NIO_displayName": "Nikaragvanska zlatna kordoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepalska rupija",
	"PKR_displayName": "Pakistanska rupija",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Gruzijski lari",
	"AZN_displayName": "Azerbejdžanski manat",
	"GBP_symbol": "£",
	"MYR_displayName": "Malezijski ringgit",
	"DKK_displayName": "Danska kruna",
	"THB_displayName": "Tai baht",
	"JPY_displayName": "Japanski jen",
	"KES_displayName": "Kenijski šiling",
	"KHR_displayName": "Kambodžanski rijel",
	"PYG_displayName": "Paragvajski guarni",
	"VND_symbol": "₫",
	"LKR_displayName": "Šrilankanska rupija",
	"BGN_displayName": "Bugarski lev",
	"BDT_displayName": "Bangladeška taka",
	"MOP_displayName": "Makaniška pataka",
	"HNL_displayName": "Honduraška lempira",
	"RWF_displayName": "Ruandski franak",
	"CHF_displayName": "Švajcarski franak",
	"CRC_displayName": "Kostarikanski kolon",
	"INR_displayName": "Indijska rupija",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Južno-afrički rand",
	"AUD_displayName": "Australijski dolar",
	"LAK_displayName": "Laoški kip",
	"CZK_symbol": "Kč",
	"MNT_displayName": "Mongolski tugrik",
	"RSD_displayName": "Srpski dinar",
	"HRK_displayName": "Hrvatska kuna"
}
//end v1.x content
);