define("Sage/UI/Dashboard/nls/zh-tw/DashboardTabController", {
    "newTabText": "新標籤",
    "addContentText": "新增內容",
    "editOptionsText": "編輯選項",
    "hideTabText": "隱藏標籤",
    "closeText": "關閉",
    "copyTabText": "複製標籤",
    "showTabText": "顯示標籤",
    "shareTabText": "共用標籤",
    "deleteTabText": "刪除標籤",
    "deleteTabConfirmText": "您確定要刪除這個標籤?",
    "descriptionText": "描述",
    "everyoneText": "所有人",
    "saveTabText": "儲存標籤",
    "helpText": "說明",
    "addText": "新增",
    "invalidMessage": "無效的字元",
    "invalidDuplicateMessage": "標題必須是唯一。",
    "deleteText": "刪除",
    "titleText": "標題:",
    "chooseTemplateText": "選擇您想使用的範本:",
    "oneColumnText": "一欄",
    "twoColumnText": "兩欄分隔",
    "fatLeftText": "兩欄 (左欄較大)",
    "fatRightText": "兩欄 (右欄較大)",
    "makeDefaultText": "設為預設",
    "releaseFetchErrorText": "擷取發行清單時發生錯誤。",
    "releaseDeleteNoneSelected": "未選取項目。",
    "releasedToText": "發行對象:",
    "typeText": "類型",
    "addLookup": "新增",
    "okButton": "確定",
    "errorText": "錯誤",
    "warningText": "警告",
    "permissionErrorText": "錯誤: 使用者沒有權限執行這個動作。",
    "permissionErrorPerformCopyText": "您要建立頁面的個人複本?",
    "yesText": "是",
    "noText": "否",
    "DeletingReleasedWidget": "您確定要刪除這個儀表板標籤? 這個標籤已經與 ${0} 位使用者共用。刪除此標籤也會刪除所有使用者的標籤。",
    "Welcome": "歡迎使用"
});