define("Sage/UI/Dashboard/nls/zh-tw/WidgetDefinition", {
    "defaultWidgetText": "編輯小組件設定",
    "settingsText": "設定",
    "viewGroupText": "檢視群組",
    "Bar_Chart": "長條圖",
    "Column_Chart": "直條圖",
    "Group_List": "群組清單",
    "Pie_Chart": "圓形圖",
    "Funnel_Chart": "漏斗圖",
    "Line_Chart": "折線圖",
    "SData_Feed": "SData 摘要",
    "Web_Feed": "網頁摘要",
    "Website": "網站",
    "Default": "預設",
    "Links": "連結",
    "Recently_Viewed": "最近檢視",
    "Todays_Activities": "今日的活動",
    "Today_s_Activities": "今日的活動",
    "Welcome": "歡迎使用",
    "Closing_Opportunities": "關閉商機",
    "Quick_Actions": "快速動作",
    "Do_You_Know___": "您是否知道...",
    "All_Leads": "所有銷售線索",
    "My_Notes": "我的備註",
    "Open_Opportunities": "未結商機",
    "My_Top_Opportunities": "我的最佳商機",
    "My_Pipeline": "我的管線",
    "Recent_Lead_Creation_History": "最近的銷售線索建立歷程記錄",
    "My_Activity_trend": "我的活動趨勢",
    "My_Completed_Activities_by_Type": "我完成的活動類型比例",
    "Active_Campaigns": "進行中行銷活動",
    "All_Open_Opportunities": "所有未結商機",
    "Top_Opportunities": "最佳商機",
    "Open_Defect_Distribution": "開啟瑕疵發佈",
    "My_Dashboard": "我的儀表板",
    "Sales": "銷售",
    "Group_List_Description": "依實體顯示群組記錄清單。例如，進行中行銷活動的群組。",
    "Welcome_Description": "顯示 Saleslogix 簡介，並含有「適用於網頁的 Saleslogix 簡介」說明主題的連結。",
    "Line_Chart_Description": "將資料顯示為一連串的資料點 (透過線條連接)。這在資料代表許多群組或類別時非常實用。",
    "Bar_Chart_Description": "將資料顯示為一組橫列。這在比較數組資料時非常實用。",
    "Column_Chart_Description": "將資料顯示為一組依類別群組的直列。這在顯示經過一段時間之後的資料變更或說明項目間之比較時非常實用。",
    "Funnel_Chart_Description": "將資料顯示為漏斗形狀的漸進式比例。資料會以百分比表示，而且沒有座標軸。",
    "Pie_Chart_Description": "將資料顯示為整體的比例。每個值都會計算為總和的百分比。此圖沒有座標軸。",
    "Recently_Viewed_Description": "顯示最近檢視記錄的連結，且含有可識別該類型的圖示。例如，客戶或聯絡人。",
    "Todays_Activities_Description": "顯示您今日活動的連結。",
    "Links_Description": "顯示您建立的連結。例如，連結至 Saleslogix 中的詳細資料檢視，或連結至外部網站。",
    "SData_Feed_Description": "使用 SData (Sage Data) 摘要顯示網頁摘要。例如，會計整合或 Saleslogix 資料庫的摘要。",
    "Web_Feed_Description": "顯示 RSS 或 Atom 摘要資訊。",
    "Website_Description": "顯示您選擇的網站。"
});