define("Sage/Utility/nls/it/Activity", {
    "ToDo": "Attività da svolgere",
    "PhoneCall": "Telefonata",
    "Meeting": "Riunione",
    "Personal": "Attività personale",
    "Literature": "Documentazione",
    "Fax": "Fax",
    "Letter": "Lettera",
    "Note": "Nota",
    "Email": "E-mail",
    "Document": "Documento",
    "DatabaseChange": "Modifica database",
    "Event": "Evento",
    "ScheduledEvent": "Evento pianificato",
    "Contact": "Contatto",
    "Lead": "Lead",
    "New": "Nuovo",
    "Change": "Modifica",
    "Deleted": "Eliminato",
    "Confirm": "Conferma",
    "Decline": "Rifiuta",
    "Unknown": "Sconosciuto",
    "Leader": "Coordinatore",
    "Complete": "Completa",
    "confirmTypeChanged": "Cambiato",
    "confirmTypeConfirmed": "Confermato",
    "confirmTypeDeleted": "Eliminato",
    "timelessText": "senza limiti di tempo"
});