define(
"dojo/cldr/nls/uk/currency", //begin v1.x content
{
	"COP_displayName": "колумбійський песо",
	"CZK_displayName": "чеська крона",
	"TND_displayName": "туніський динар",
	"EUR_symbol": "€",
	"CAD_symbol": "CAD",
	"JMD_displayName": "ямайський долар",
	"PHP_displayName": "філіппінський песо",
	"ALL_displayName": "албанський лек",
	"USD_symbol": "USD",
	"LBP_displayName": "ліванський фунт",
	"VND_displayName": "вʼєтнамський донг",
	"LYD_displayName": "лівійський динар",
	"RON_displayName": "румунський лей",
	"MKD_displayName": "македонський денар",
	"SEK_displayName": "шведська крона",
	"CNY_displayName": "китайський юань",
	"IDR_displayName": "індонезійська рупія",
	"ILS_displayName": "ізраїльський новий шекель",
	"YER_displayName": "єменський ріал",
	"TJS_displayName": "таджицький сомоні",
	"TTD_displayName": "долар Тринідаду і Тобаго",
	"CNY_symbol": "CNY",
	"TRY_displayName": "турецька ліра",
	"EUR_displayName": "євро",
	"AED_displayName": "дирхам ОАЕ",
	"KZT_displayName": "казахстанський тенге",
	"BHD_displayName": "бахрейнський динар",
	"RUB_displayName": "російський рубль",
	"NZD_displayName": "новозеландський долар",
	"IQD_displayName": "іракський динар",
	"TMT_displayName": "туркменський манат",
	"ZWL_displayName": "зімбабвійський долар (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "киргизький сом",
	"KWD_displayName": "кувейтський динар",
	"AFN_displayName": "афганський афгані",
	"ARS_displayName": "аргентинський песо",
	"MAD_displayName": "марокканський дирхам",
	"BAM_displayName": "конвертована марка Боснії і Герцеговини",
	"BOB_displayName": "болівійський болівіано",
	"BND_displayName": "брунейський долар",
	"SGD_displayName": "сінгапурський долар",
	"MVR_displayName": "мальдівська руфія",
	"MXN_displayName": "мексиканський песо",
	"DZD_displayName": "алжирський динар",
	"MXN_symbol": "MXN",
	"JOD_displayName": "йорданський динар",
	"PEN_displayName": "перуанський новий сол",
	"GTQ_displayName": "гватемальський кетсаль",
	"BYR_displayName": "білоруський рубль",
	"CAD_displayName": "канадський долар",
	"BZD_displayName": "белізький долар",
	"CLP_displayName": "чилійський песо",
	"XOF_displayName": "західноафриканський франк",
	"NOK_displayName": "норвезька крона",
	"DOP_displayName": "домініканський песо",
	"JPY_symbol": "¥",
	"KRW_displayName": "південнокорейський вон",
	"USD_displayName": "долар США",
	"UYU_displayName": "уругвайський песо",
	"UZS_displayName": "узбецький сум",
	"XOF_symbol": "CFA",
	"QAR_displayName": "катарський ріал",
	"SAR_displayName": "саудівський ріал",
	"SYP_displayName": "сирійський фунт",
	"NZD_symbol": "NZD",
	"EGP_displayName": "єгипетський фунт",
	"AMD_displayName": "вірменський драм",
	"GBP_displayName": "англійський фунт стерлінгів",
	"UAH_symbol": "₴",
	"HUF_displayName": "угорський форинт",
	"CSD_displayName": "старий сербський динар",
	"ISK_displayName": "ісландська крона",
	"RSD_symbol": "дин.",
	"IRR_displayName": "іранський ріал",
	"OMR_displayName": "оманський ріал",
	"TWD_displayName": "новий тайванський долар",
	"PAB_displayName": "панамська бальбоа",
	"UAH_displayName": "українська гривня",
	"ETB_displayName": "ефіопський бир",
	"RUB_symbol": "руб.",
	"PLN_displayName": "польський злотий",
	"VEF_displayName": "венесуельський болівар",
	"ILS_symbol": "ILS",
	"AZN_symbol": "ман.",
	"AUD_symbol": "AU$",
	"BRL_displayName": "бразильський реал",
	"HKD_symbol": "HKD",
	"HKD_displayName": "гонконгський долар",
	"NIO_displayName": "нікарагуанська кордоба оро",
	"THB_symbol": "THB",
	"NPR_displayName": "непальська рупія",
	"PKR_displayName": "пакистанська рупія",
	"TWD_symbol": "TWD",
	"GEL_displayName": "грузинський ларі",
	"AZN_displayName": "азербайджанський манат",
	"GBP_symbol": "£",
	"MYR_displayName": "малайзійський рингіт",
	"DKK_displayName": "данська крона",
	"THB_displayName": "таїландський бат",
	"BRL_symbol": "BRL",
	"JPY_displayName": "японська єна",
	"KES_displayName": "кенійський шилінг",
	"KHR_displayName": "камбоджійський рієль",
	"PYG_displayName": "парагвайський гуарані",
	"VND_symbol": "VND",
	"LKR_displayName": "шрі-ланкійська рупія",
	"BGN_displayName": "болгарський лев",
	"BDT_displayName": "бангладеська така",
	"HNL_displayName": "гондураська лемпіра",
	"MOP_displayName": "патака Макао",
	"RWF_displayName": "руандійський франк",
	"CHF_displayName": "швейцарський франк",
	"CRC_displayName": "костариканський колон",
	"INR_displayName": "індійська рупія",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "південноафриканський ранд",
	"AUD_displayName": "австралійський долар",
	"LAK_displayName": "лаоський кіп",
	"MNT_displayName": "монгольський тугрик",
	"RSD_displayName": "сербський динар",
	"HRK_displayName": "хорватська куна"
}
//end v1.x content
);