define("Sage/MainView/EntityMgr/EntityWizard/nls/de/_EntityWizardDialog", {
    "lblNewEntityWizard": "Assistent für neue Entitäten",
    "lblCreateEntity": "Entität erstellen",
    "lblCreateEntityFromTable": "Neue Entität aus einer Tabelle erstellen",
    "lblEntityName": "Name",
    "lblDisplayName": "Anzeigen",
    "lblPackage": "Paket",
    "lblEntityUsed": "Entitätsname wird bereits verwendet!",
    "lblNext": "Weiter",
    "lblCancel": "Abbrechen",
    "lblBack": "Zurück",
    "lblEnterProperties": "Felder eingeben",
    "lblAddNewProperty": "Klicken Sie auf die Schaltfläche zum Hinzufügen (+), um der Entität neue Felder hinzuzufügen",
    "lblPropertyName": "Feldname",
    "lblDataType": "Datentyp",
    "lblLength": "Länge",
    "lblSure": "Sind Sie sicher?",
    "lblThisStepCreateEntity": "Mit der Durchführung dieses Schrittes erstellen Sie die Entitäten und das notwendige Schema.",
    "lblEntity": "Entität",
    "lblProperties": "Felder",
    "lblStatus": "Status",
    "lblSuccess": "Erfolg",
    "lblSuccessMsg": "Entität erfolgreich erstellt.",
    "lblError": "Fehler",
    "lblFailed": "Fehlgeschlagen",
    "lblErrorMsg": "Fehler, Entitätserstellung fehlgeschlagen!",
    "lblFinish": "Fertig stellen",
    "lblInvalidEntry": "Ein gültiger Eintrag beginnt mit einem Großbuchstaben und kann alphanumerische Werte enthalten",
    "lblRequired": "Erforderlich",
    "lblErrorRelation": "Fehler beim Herstellen von Beziehung mit",
    "lblRelationship": "Primäre Beziehung",
    "lblSelectEntity": "Legen Sie fest, ob diese Entität über eine primäre Beziehung zu einer anderen Entität verfügt",
    "lblExistingEntity": "In Beziehung zu vorhandener Entität setzen",
    "lblRelatedEntity": "In Beziehung stehende Entität",
    "lblRelationType": "Beziehungstyp",
    "addFieldDialogTitle": "Feld hinzufügen",
    "editFieldDialogTitle": "Feld bearbeiten",
    "noDeleteSysProps": "Systemeigenschaften können nicht gelöscht werden",
    "noEditSysProps": "Systemeigenschaften können nicht bearbeitet werden",
    "NoRecordsSelected": "Es sind keine Datensätze ausgewählt.",
    "lblNullable": "Darf Null sein",
    "CreateUser": "Angelegt von",
    "CreateDate": "Erstellungsdatum",
    "ModifyUser": "Geändert von",
    "ModifyDate": "Änderungsdatum"
});