define("Sage/UI/Forms/nls/zh-cn/FormFromSData", {
    "addText": "添加",
    "deleteText": "删除",
    "saveText": "保存",
    "cancelText": "取消",
    "editText": "编辑",
    "helpText": "帮助",
    "yesText": "是",
    "noText": "否",
    "okText": "确定",
    "newPickList": "新选择列表",
    "items": "选择列表项目",
    "number": "顺序",
    "enterValue": "输入值",
    "lblMore": "更多",
    "picklistAlreadyExists": "Picklist“${0}”已存在。",
    "messageOnSave": "已保存选择列表 ${0}。请继续添加或编辑字段信息。",
    "permissionsToView": "您无权查看。",
    "required": "必需条目",
    "allowMultiples": "允许多选",
    "valueMustExist": "文本必须与列表项目匹配",
    "alphaSorted": "按字母顺序排序",
    "noneEditable": "用户不能编辑项目"
});