define("Sage/MainView/Contact/nls/zh-tw/ContactSearchForDuplicates", {
    "svAccount_Caption": "客戶:",
    "svCompany_Caption": "公司:",
    "svEmail_Caption": "電子郵件:",
    "svName_Caption": "名稱:",
    "svTitle_Caption": "標題:",
    "svType_Caption": "類型:",
    "svSubType_Caption": "子類型:",
    "svAccMgr_Caption": "客戶經理:",
    "svHomePhone_Caption": "住家電話:",
    "svWorkPhone_Caption": "公司電話:",
    "svMobilePhone_Caption": "行動電話:",
    "svStatus_Caption": "狀態:",
    "svWebAddress_Caption": "網頁:",
    "svEntityAccount_Caption": "客戶",
    "svEntityLead_Caption": "銷售線索",
    "svEntityContact_Contact": "聯絡人",
    "svTollFree_Caption": "免付費:",
    "svIndustry_Caption": "行業:",
    "svDivision_Caption": "事業處:",
    "svMainPhone_Caption": "主要電話:",
    "LeadSummaryView_Title": "摘要檢視 - 銷售線索",
    "ContactSummaryView_Title": "摘要檢視 - 聯絡人",
    "AccountSummaryView_Title": "摘要檢視 - 客戶",
    "closeText": "關閉",
    "errorLoadingSummaryView": "載入摘要檢視時發生錯誤: ${0}"
});