define("Sage/QuickForms/Design/Editors/nls/it/ComboBoxAdvancedPropertyEditor", {
    "titleText": "Avanzato",
    "appearanceText": "Aspetto",
    "behaviorText": "Comportamento",
    "controlInfoText": "Info di controllo",
    "dataText": "Dati",
    "itemGroupText": "Elementi",
    "controlIdText": "ID controllo:",
    "controlIdTooltipText": "Identificatore per questo controllo.",
    "controlLabelPlacementText": "Posizione etichetta:",
    "controlLabelPlacementTooltipText": "Posizione etichetta in relazione al controllo.",
    "controlTypeText": "Tipo di controllo.",
    "controlTypeTooltipText": "Tipo di controllo Saleslogix.",
    "dataSourceText": "Origine dati:",
    "dataSourceTooltipText": "Origine dei dati per questo controllo, come un altro controllo o un'entità.",
    "defaultDataBindingText": "Associazioni dati:",
    "defaultDataBindingTooltipText": "Campo nel database utilizzato da questo controllo.",
    "enabledText": "Abilitato:",
    "enabledTooltipText": "Consente all'utente di interagire con questo controllo.",
    "itemsText": "Elementi:",
    "itemsTooltipText": "Valori che l'utente può selezionare.",
    "textFieldText": "Campo di testo:",
    "textFieldTooltipText": "Il nome del campo dell’origine dati utilizzato per inserire il testo visibile degli elementi dell'elenco.",
    "valueFieldText": "Campo valore:",
    "valueFieldTooltipText": "Il nome del campo dell’origine dati utilizzato per inserire il valore degli elementi dell'elenco.",
    "visibleText": "Visibile:",
    "visibleTooltipText": "Mostra o nasconde questo controllo nel modulo.",
    "labelPlacementText": {
        "left": "Sinistra",
        "right": "Destra",
        "top": "Alto",
        "none": "Nessuno"
    },
    "hasItemsText": "Imposta",
    "noItemsText": "Non impostato"
});