define("Sage/QuickForms/Design/Editors/nls/it/PickListAdvancedPropertyEditor", {
    "titleText": "Avanzato",
    "appearanceText": "Aspetto",
    "behaviorText": "Comportamento",
    "controlInfoText": "Info di controllo",
    "dataText": "Dati",
    "allowMultiplesText": "Consente la selezione multipla:",
    "allowMultiplesTooltipText": "Permette di selezionare più di un elemento.",
    "canEditTextText": "Possibile modificare il testo:",
    "canEditTextTooltipText": "Consente all'utente di digitare un valore.",
    "controlIdText": "ID controllo:",
    "controlIdTooltipText": "Identificatore per questo controllo.",
    "controlLabelPlacementText": "Posizione etichetta:",
    "controlLabelPlacementTooltipText": "Posizione etichetta in relazione al controllo.",
    "controlTypeText": "Tipo di controllo.",
    "controlTypeTooltipText": "Tipo di controllo Saleslogix.",
    "defaultDataBindingText": "Associazioni dati:",
    "defaultDataBindingTooltipText": "Campo nel database utilizzato da questo controllo.",
    "displayModeText": "Modalità di visualizzazione:",
    "displayModeTooltipText": "Modalità di visualizzazione del controllo: casella di testo, collegamenti ipertestuali o testo normale.",
    "enabledText": "Abilitato:",
    "enabledTooltipText": "Consente all'utente di interagire con questo controllo.",
    "maxLengthText": "Lunghezza massima:",
    "maxLengthTooltipText": "Numero massimo di caratteri che l'utente può inserire.",
    "mustExistInListText": "L'elemento deve esistere:",
    "mustExistInListTooltipText": "Il valore inserito deve essere presente nell’elenco.",
    "pickListNameText": "Nome elenco di selezione:",
    "pickListNameTooltipText": "Nome dell'elenco di valori che l'utente può selezionare da quando inserisce i dati.",
    "requiredText": "Obbligatorio:",
    "requiredTooltipText": "Richiede un valore durante il salvataggio di dati.",
    "storageModeText": "Modalità di archiviazione:",
    "storageModeTooltipText": "Modalità di archiviazione del valore: testo, ID o codice.",
    "visibleText": "Visibile:",
    "visibleTooltipText": "Mostra o nasconde questo controllo nel modulo.",
    "labelPlacementText": {
        "left": "Sinistra",
        "right": "Destra",
        "top": "Alto",
        "none": "Nessuno"
    },
    "displayModeTypeText": {
        "AsControl": "Come controllo",
        "AsText": "Come testo",
        "AsHyperlink": "Come collegamento ipertestuale"
    },
    "storageModeTypeText": {
        "Text": "Testo",
        "Id": "ID",
        "Code": "Codice"
    },
    "pickListRequestErrorText": "Impossibile recuperare gli elenchi di selezione dal server."
});