define("Sage/UI/nls/it/JobSchedulingWidget", {
    "lblCreateSchedule": "Crea pianificazione processo da eseguire",
    "lblEveryText": "Ogni",
    "lblOnText": "il",
    "lblOnTheText": "il",
    "lblAtText": "a",
    "lblMinutesPastHour": "minuti dopo l'ora",
    "lblFromTimeText": "Esegui da",
    "lblToTimeText": "a",
    "lblMinutesFrequency": "minuti",
    "lblHourlyFrequency": "ora/e",
    "lblDailyFrequency": "giorno",
    "lblWeekDayFrequency": "giorno feriale",
    "lblWeeklyFrequency": "settimana",
    "lblMonthlyFrequency": "mese",
    "lblYearlyFrequency": "anno",
    "lblSunday": "Domenica",
    "lblMonday": "Lunedì",
    "lblTuesday": "Martedì",
    "lblWednesday": "Mercoledì",
    "lblThursday": "Giovedì",
    "lblFriday": "Venerdì",
    "lblSaturday": "Sabato",
    "lblFirstDay": "primo",
    "lblSecondDay": "secondo",
    "lblThirdDay": "terzo",
    "lblFourthDay": "quarto",
    "lblCronExpressionText": "Espressione cron",
    "txtInvalidScheduleTitle": "Pianificazione non valida",
    "txtInvalidDatesMessage": "L'ora di fine deve essere successiva all'ora di inizio. Correggere questa informazione prima di continuare.",
    "txtInvalidScheduleTime": "Le ore di inizio e fine specificate impediranno l'esecuzione di questa pianificazione. Correggere questa informazione prima di continuare.",
    "txtInvalidStartDate": "La data di inizio è obbligatoria. Specificare una data di inizio prima di continuare.",
    "txtInvalidEndDate": "La data di fine è obbligatoria. Specificare una data di fine prima di continuare."
});