define("Sage/QuickForms/Design/Editors/nls/ru/ComboBoxAdvancedPropertyEditor", {
    "titleText": "Дополнительно",
    "appearanceText": "Внешний вид",
    "behaviorText": "Поведение",
    "controlInfoText": "Информация об элементе управления",
    "dataText": "Данные",
    "itemGroupText": "Элементы",
    "controlIdText": "ИД элемента управления:",
    "controlIdTooltipText": "Идентификатор для этого элемента управления.",
    "controlLabelPlacementText": "Расположение метки:",
    "controlLabelPlacementTooltipText": "Позиция метки по отношению к элементу управления.",
    "controlTypeText": "Тип элемента управления:",
    "controlTypeTooltipText": "Тип управляющего элемента Saleslogix.",
    "dataSourceText": "Источник данных:",
    "dataSourceTooltipText": "Источник данных для этого элемента управления, такой как другой элемент управления или сущность.",
    "defaultDataBindingText": "Привязка данных:",
    "defaultDataBindingTooltipText": "Поле (поля) в базе данных, используемое этим элементом управления.",
    "enabledText": "Активировано:",
    "enabledTooltipText": "Позволяет пользователю взаимодействовать с этим элементом управления.",
    "itemsText": "Элементы:",
    "itemsTooltipText": "Пользователь может выбирать значения.",
    "textFieldText": "Текстовое поле:",
    "textFieldTooltipText": "Имя поля источника данных, используемые для заполнения видимой части элементов списка.",
    "valueFieldText": "Поле с значением:",
    "valueFieldTooltipText": "Имя поля источника данных, используемого для заполнения значений списка.",
    "visibleText": "Видимый:",
    "visibleTooltipText": "Показать или скрыть этот элемент управления в форме.",
    "labelPlacementText": {
        "left": "По левому краю",
        "right": "По правому краю",
        "top": "Верхнее",
        "none": "Нет"
    },
    "hasItemsText": "Установлено",
    "noItemsText": "Не установлено"
});