define("Sage/QuickForms/Design/Editors/nls/ru/DataGridAdvancedPropertyEditor", {
    "titleText": "Дополнительно",
    "appearanceText": "Внешний вид",
    "behaviorText": "Поведение",
    "controlInfoText": "Информация об элементе управления",
    "dataText": "Данные",
    "controlIdText": "ИД элемента управления:",
    "controlIdTooltipText": "Идентификатор для этого элемента управления.",
    "controlTypeText": "Тип элемента управления:",
    "controlTypeTooltipText": "Тип управляющего элемента Saleslogix.",
    "dataSourceText": "Источник данных:",
    "dataSourceTooltipText": "Источник данных для этого элемента управления, такой как другой элемент управления или сущность.",
    "emptyTableRowText": "Текст пустой таблицы:",
    "emptyTableRowTooltipText": "Текст для отображения, если в таблице нет данных.",
    "expandableRowsText": "Расширяемые строки:",
    "expandableRowsTooltipText": "Позволяет пользователю расширить строки таблицы, чтобы показать больше текста.",
    "renderVerticalText": "Вертикальная отрисовка:",
    "renderVerticalTooltipText": "Показывать строки как столбцы.",
    "showSortIconText": "Показать значок сортировки:",
    "showSortIconTooltipText": "Показать значок сортировки на сортируемых столбцах.",
    "visibleText": "Видимый:",
    "visibleTooltipText": "Показать или скрыть этот элемент управления в форме."
});