define("Sage/QuickForms/Design/Editors/nls/ru/PickListAdvancedPropertyEditor", {
    "titleText": "Дополнительно",
    "appearanceText": "Внешний вид",
    "behaviorText": "Поведение",
    "controlInfoText": "Информация об элементе управления",
    "dataText": "Данные",
    "allowMultiplesText": "Разрешить множественный выбор:",
    "allowMultiplesTooltipText": "Позволяет пользователю выбрать более одного элемента.",
    "canEditTextText": "Можно редактировать текст:",
    "canEditTextTooltipText": "Позволяет пользователю вводить значение.",
    "controlIdText": "ИД элемента управления:",
    "controlIdTooltipText": "Идентификатор для этого элемента управления.",
    "controlLabelPlacementText": "Расположение метки:",
    "controlLabelPlacementTooltipText": "Позиция метки по отношению к элементу управления.",
    "controlTypeText": "Тип элемента управления:",
    "controlTypeTooltipText": "Тип управляющего элемента Saleslogix.",
    "defaultDataBindingText": "Привязка данных:",
    "defaultDataBindingTooltipText": "Поле (поля) в базе данных, используемое этим элементом управления.",
    "displayModeText": "Режим отображения:",
    "displayModeTooltipText": "Режим отображения элемента управления: текстовое поле, гиперссылка или обычный текст.",
    "enabledText": "Активировано:",
    "enabledTooltipText": "Позволяет пользователю взаимодействовать с этим элементом управления.",
    "maxLengthText": "Макс. длина:",
    "maxLengthTooltipText": "Максимальное количество символов, которое может ввести пользователь",
    "mustExistInListText": "Элемент должен существовать:",
    "mustExistInListTooltipText": "Введенное значение должно быть в списке.",
    "pickListNameText": "Имя списка выбора:",
    "pickListNameTooltipText": "Имя списка значений, которые пользователь может выбрать при вводе данных.",
    "requiredText": "Требуется:",
    "requiredTooltipText": "Требуется значение при сохранении данных.",
    "storageModeText": "Режим хранения:",
    "storageModeTooltipText": "Как значение сохраняется: текст, ИД или код.",
    "visibleText": "Видимый:",
    "visibleTooltipText": "Показать или скрыть этот элемент управления в форме.",
    "labelPlacementText": {
        "left": "По левому краю",
        "right": "По правому краю",
        "top": "Верхнее",
        "none": "Нет"
    },
    "displayModeTypeText": {
        "AsControl": "Как элемент управления",
        "AsText": "Как текст",
        "AsHyperlink": "Как гиперссылка"
    },
    "storageModeTypeText": {
        "Text": "Текст",
        "Id": "ИД",
        "Code": "Код"
    },
    "pickListRequestErrorText": "Невозможно получить списки выбора от сервера."
});