define("Sage/MainView/EntityMgr/EntityWizard/nls/it/_EntityWizardDialog", {
    "lblNewEntityWizard": "Procedura guidata Nuova entità",
    "lblCreateEntity": "Crea entità",
    "lblCreateEntityFromTable": "Crea una nuova entità da una tabella",
    "lblEntityName": "Nome",
    "lblDisplayName": "Visualizza",
    "lblPackage": "Pacchetto",
    "lblEntityUsed": "Nome entità già in uso.",
    "lblNext": "Avanti",
    "lblCancel": "Annulla",
    "lblBack": "Indietro",
    "lblEnterProperties": "Immetti campo",
    "lblAddNewProperty": "Fare clic sul pulsante Aggiungi (+) per aggiungere nuovi campi all'entità",
    "lblPropertyName": "Nome campo",
    "lblDataType": "Tipo dati",
    "lblLength": "Lunghezza",
    "lblSure": "Continuare?",
    "lblThisStepCreateEntity": "Completando questo passaggio verranno creati le entità e lo schema necessario",
    "lblEntity": "Entità",
    "lblProperties": "Campi",
    "lblStatus": "Stato",
    "lblSuccess": "Completato",
    "lblSuccessMsg": "Operazione riuscita. Entità creata correttamente.",
    "lblError": "Errore",
    "lblFailed": "Non riuscito",
    "lblErrorMsg": "Errore. Creazione entità non riuscita.",
    "lblFinish": "Fine",
    "lblInvalidEntry": "Una voce valida inizia con una lettera maiuscola e può contenere valori alfanumerici e caratteri di sottolineatura.",
    "lblRequired": "Obbligatorio",
    "lblErrorRelation": "Errore nella creazione della relazione con",
    "lblRelationship": "Relazione primaria",
    "lblSelectEntity": "Specificare se questa entità ha una relazione primaria con un’altra entità.",
    "lblExistingEntity": "Correla a un'entità esistente",
    "lblRelatedEntity": "Entità correlata",
    "lblRelationType": "Tipo relazione",
    "addFieldDialogTitle": "Aggiungi campo",
    "editFieldDialogTitle": "Modifica campo",
    "noDeleteSysProps": "Impossibile eliminare le proprietà di sistema",
    "noEditSysProps": "Impossibile modificare le proprietà di sistema",
    "NoRecordsSelected": "Non ci sono record selezionati.",
    "lblNullable": "Ammette valori Null",
    "CreateUser": "Creato da",
    "CreateDate": "Data di creazione",
    "ModifyUser": "Modificato da",
    "ModifyDate": "Data di modifica"
});