define("Sage/MainView/EntityMgr/nls/ru/EntityListPanelConfig", {
    "colNameEntityName": "Имя",
    "colNameType": "Тип",
    "colNameTable": "Таблица",
    "colNameCreateUser": "Автор",
    "colNameCreateDate": "Дата создания",
    "colNameLastExecutionDate": "Последнее выполнение",
    "colNameLastExecutionUser": "Последнее выполнение от имени",
    "colNameModifyUser": "Автор изменения",
    "colNameModifyDate": "Дата изменения",
    "colNameEntityDisplayName": "Отображаемое имя",
    "colNameEntityTableName": "Таблица",
    "colNamePropertyCount": "Счетчик свойств",
    "colNameFilterCount": "Счетчик фильтров",
    "colNameMetricCount": "Счетчик метров",
    "colNamePackage": "Пакет",
    "owner": "Владелец",
    "assignTo": "Назначить",
    "newACI": "Новая область/категория/проблема",
    "insertACI": "Вставить область/категорию/проблему",
    "autoAssign": "Автоназначение",
    "areaCatIssue": "Область/категория/проблема",
    "lookupACI": "Поиск области/категории/проблемы",
    "displayName": "Отображаемое имя",
    "displayPluralName": "Отображение имени во множественном числе",
    "Title": "Название",
    "IsExtension": "IsExtension",
    "Audited": "Аудит выполнен",
    "OK": "OК",
    "Cancel": "Отмена"
});