define("Sage/QuickForms/Design/Editors/nls/zh-cn/NumericAdvancedPropertyEditor", {
    "titleText": "高级",
    "appearanceText": "外观",
    "behaviorText": "行为",
    "controlInfoText": "控件信息",
    "dataText": "数据",
    "controlIdText": "控件 ID:",
    "controlIdTooltipText": "此控件的标识。",
    "controlLabelPlacementText": "标签位置:",
    "controlLabelPlacementTooltipText": "相对于控件的标签位置。",
    "controlTypeText": "控件类型:",
    "controlTypeTooltipText": "Saleslogix 控件类型。",
    "decimalDigitsText": "小数位数:",
    "decimalDigitsTooltipText": "要针对数据条目显示且允许的小数点后的位数。",
    "defaultDataBindingText": "数据绑定:",
    "defaultDataBindingTooltipText": "此控件使用的数据库中的数据字段。",
    "enabledText": "已启用:",
    "enabledTooltipText": "允许用户与此控件交互。",
    "formatTypeText": "格式类型:",
    "formatTypeTooltipText": "在将数字转换为字符串时使用的格式类型。",
    "maxLengthText": "最大长度:",
    "maxLengthTooltipText": "用户可输入的最多字符数。",
    "requiredText": "必需:",
    "requiredTooltipText": "保存数据时必须提供值。",
    "strictText": "严格:",
    "strictTooltipText": "根据需要带有尾部零的数字的填充显示。",
    "visibleText": "可见:",
    "visibleTooltipText": "在窗体上显示或隐藏此控件。",
    "numberFormatText": {
        "Number": "数字",
        "Percent": "百分比",
        "Decimal": "小数",
        "Scientific": "科学计数法"
    },
    "labelPlacementText": {
        "left": "左侧",
        "right": "右侧",
        "top": "顶部",
        "none": "无"
    }
});