define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/fr/AddEditDialog", {
    "dialogTitleAddField": "Ajouter un champ à l'entité ${0}",
    "dialogTitleAddFilter": "Ajouter un filtre à l'entité ${0}",
    "dialogTitleAddMetric": "Ajouter une mesure à l'entité ${0}",
    "dialogTitleAddRelationship": "Ajouter une relation à l'entité ${0}",
    "editDialogTitle": "Modifier ${0} dans l'entité ${1}",
    "lblFilter": "Filtrer",
    "lblMetric": "Mesure",
    "lblFilters": "Filtres",
    "lblMetrics": "Mesures",
    "lblDistinct": "Distinct",
    "lblRange": "Plage",
    "lblUserLookup": "Rechercher un utilisateur",
    "lblAdd": "Ajouter",
    "lblEdit": "Modifier",
    "lblRemove": "Supprimer",
    "lblHelp": "Aide",
    "lblFilterName": "Nom du filtre",
    "lblMetricName": "Nom de la mesure",
    "lblDisplayName": "Nom d'affichage",
    "lblName": "Nom",
    "lblDisplay": "Affichage",
    "lblCalculated": "Calculé(e)(s)",
    "lblCalculation": "Calcul",
    "lblDescription": "Description",
    "lblFieldsName": "Nom des champs",
    "lblCalculatedFieldsName": "Nom des champs calculés",
    "lblFilterDp": "Champs",
    "lblTypeDp": "Type",
    "lblCharacter": "Caractères",
    "lblFrom": "De",
    "lblTo": "A",
    "lblOperators": "Opérateurs",
    "lblAggregation": "Agrégations",
    "lblTypeSpecificContentBox": "Zone de contenu spécifique de type",
    "lblSaveButton": "OK",
    "lblCancelButton": "Annuler",
    "DateDiffCheckerValue": "Mesure de différence de date",
    "InvalidFilterName": "Nom de filtre non valide",
    "InvalidRangeName": "Nom de plage non valide",
    "RequiredFilterName": "Nom de filtre obligatoire",
    "RequiredRangeName": "Nom de plage obligatoire",
    "FieldMustBeANumber": "Le champ Caractère doit être un nombre entier",
    "SelectAnItem": "Veuillez sélectionner un élément",
    "ItemRequired": "Elément obligatoire",
    "ItemInvalid": "Elément non valide",
    "LowerMustBeLessThanUpper": "La valeur la plus basse doit être inférieure à la valeur la plus haute.",
    "defaultRangeRowValue": "Saisissez une valeur",
    "totalRecordCountLabel": "Nombre total d'enregistrements : ${0}",
    "lblNew": "Nouveau",
    "lblExisting": "Existant",
    "lblExistingCalc": "Champ calculé existant",
    "validNameMsg": "Pour être valide, l'entrée doit commencer par une lettre majuscule. Elle <br> peut contenir des valeurs alphanumériques et des traits de soulignement.",
    "propertyName": "Nom",
    "displayName": "Affichage",
    "dataTypeId": "Type",
    "dataTypeData": "Attributs du type",
    "length": "Longueur",
    "scale": "Echelle",
    "precision": "Précision",
    "isIncluded": "Inclus",
    "isReadOnly": "Lecture seule",
    "displayCategory": "Afficher la catégorie",
    "sdata": "Sdata",
    "bulkAction": "Action en bloc",
    "canBulkUpdate": "Peut effectuer une mise à jour en bloc",
    "canImport": "Importer",
    "canMatch": "Faire correspondre",
    "generate": "Générer",
    "audited": "Audité",
    "notUniqueFor": "N'est pas unique pour",
    "notUnique": "n'est pas unique",
    "nlsCode": "Code NLS",
    "nlsName": "Nom NLS",
    "showTranslations": "Afficher les traductions",
    "hideTranslations": "Masquer les traductions",
    "standardIds": "ID standard",
    "others": "Autre",
    "SelectField": "Sélectionnez un champ !",
    "SelectOneField": "Veuillez sélectionner un seul champ",
    "parent": "Entité parent et champ Jointure",
    "child": "Entité enfant et champ Jointure",
    "cardinality": "Relation",
    "cascade": "Cascade",
    "includeParent": "Inclure une propriété de relation parente dans l'entité enfant",
    "includeChild": "Inclure une propriété de relation enfant dans l'entité parent",
    "existingRelaton": "Cette relation existe déjà !"
});