define("Sage/Services/nls/de/ActivityService", {
    "txtErrorActionMsg": "Die Aktion war leider nicht erfolgreich, da ein Fehler aufgetreten ist.",
    "txtActivity": "Aktivität",
    "txtActivities": "Aktivitäten",
    "txtActionDeleteActivites": "Aktivitäten löschen",
    "txtActionDeleteActivitiesQuestion": "Es werden nur Aktivitäten gelöscht, für die Sie löschberechtigt sind. <P> Möchten Sie die Auswahl wirklich löschen? ({0} {1})",
    "txtAlarm": "Alarm",
    "txtAlarms": "Alarme",
    "txtActionSnoozeAlarm": "Alarm für die Wiedervorlage",
    "txtActionSnoozeQuestion": "Möchten Sie die Auswahl wirklich wiedervorlegen? ({0} {1} nach {2})",
    "txtActionSnoozeAllQuestion": "Möchten Sie wirklich alle {0} nach {1} wieder vorlegen?",
    "txtActionDismissAlarms": "Alarme ablehnen",
    "txtActionDismissAlarmsQuestion": "Möchten Sie die Auswahl wirklich ablehnen? ({0} {1})",
    "txtEvent": "Ereignis",
    "txtEvents": "Ereignisse",
    "txtActionDeleteEvents": "Ereignisse löschen",
    "txtActionDeleteEventsQuestion": "Es werden nur Ereignisse gelöscht, für die Sie löschberechtigt sind. <P> Möchten Sie die Auswahl wirklich löschen? ({0} {1})",
    "txtConfirmation": "Bestätigung",
    "txtConfirmations": "Bestätigungen",
    "txtActionAcceptConfirmations": "Bestätigungen akzeptieren",
    "txtActionAcceptConfirmQuestion": "Möchten Sie die Auswahl wirklich akzeptieren? ({0} {1}) Diese Aktion kann nur für neue oder geänderte Bestätigungen durchgeführt werden. Alle anderen Bestätigungen werden ignoriert.",
    "txtDeclineConfirmations": "Bestätigungen ablehnen",
    "txtActionDeclineConfrimQuestion": "Möchten Sie die Auswahl wirklich ablehnen? ({0} {1}) Diese Aktion kann nur für neue oder geänderte Bestätigungen durchgeführt werden. Alle anderen Bestätigungen werden ignoriert.",
    "txtActionRemoveConfirmations": "Bestätigungen löschen",
    "txtActionRemoveConfirmationsQuestion": "Möchten Sie die Auswahl wirklich löschen? ({0} {1}) Diese Aktion kann nur für Interessentenbestätigungen, abgelehnte oder gelöschte Bestätigungen durchgeführt werden. Alle anderen werden ignoriert.",
    "txtLiteratureRequest": "Literaturanfrage",
    "txtLiteratureRequests": "Literaturanfragen",
    "txtActionDeleteLiteratureRequests": "Literaturanfragen löschen",
    "txtActionDeleteLiteratureRequestsQuestion": "Es werden nur Literaturanfragen gelöscht, für die Sie löschberechtigt sind. <P> Möchten Sie die Auswahl wirklich löschen? ({0} {1})"
});