define("Sage/UI/Forms/nls/zh-tw/FormFromSData", {
    "addText": "新增",
    "deleteText": "刪除",
    "saveText": "儲存",
    "cancelText": "取消",
    "editText": "編輯",
    "helpText": "說明",
    "yesText": "是",
    "noText": "否",
    "okText": "確定",
    "newPickList": "新挑選清單",
    "items": "挑選清單項目",
    "number": "順序",
    "enterValue": "輸入值",
    "lblMore": "更多",
    "picklistAlreadyExists": "Picklist「${0}」已經存在。",
    "messageOnSave": "已經儲存挑選清單 ${0}。請繼續新增或編輯欄位資訊。",
    "permissionsToView": "您沒有檢視權限。",
    "required": "必要項目",
    "allowMultiples": "允許多個選取項目",
    "valueMustExist": "文字必須與清單項目相符",
    "alphaSorted": "依照英文字母順序排序",
    "noneEditable": "使用者無法編輯項目"
});