define("Sage/UI/Controls/nls/ru/FieldAttributeControlFactory", {
    "IsEncrypted": "Является зашифрованным",
    "Length": "Длина",
    "Precision": "Точность",
    "Scale": "Шкала",
    "LookupEntityName": "Поиск имени сущности",
    "LookupGroup": "Группа поиска",
    "IsPercentage": "Является процентом",
    "Items": "Элементы",
    "MultiSelect": "Множественный выбор",
    "OverriddenName": "Отмененное имя",
    "Storage": "Хранилище",
    "EnableHyperLinking": "Включить гиперссылки",
    "LookupPreFilters": "Предварительные фильтры поиска",
    "EqualTo": "Равно",
    "NotEqualTo": "Не равно",
    "GreaterThanOrEqual": "Больше или равно",
    "GreaterThan": "Больше",
    "LessThanOrEqual": "Меньше или равно",
    "LessThan": "Меньше",
    "CondOperator": "Оператор условия",
    "FilterValue": "Значение фильтра",
    "PropertyName": "Имя свойства",
    "LookupProperties": "Свойства поиска",
    "ExcludeFromFilters": "Исключить из фильтров",
    "HideCondition": "Условие скрытия",
    "IsSortable": "Возможна сортировка",
    "PropertyFormat": "Формат свойства",
    "None": "Нет",
    "Phone": "Телефон",
    "User": "Пользователь",
    "PickList": "Список выбора",
    "DateTime": "Дата и время",
    "PropertyFormatString": "Строка формата свойства",
    "PropertyHeader": "Заголовок свойства",
    "PropertyType": "Тип свойства",
    "UseAsResult": "Использовать как результат",
    "ReturnPrimaryKey": "Возврат основного ключа",
    "AllowMultiples": "Разрешить множественность",
    "AlphaSort": "Алфавитная сортировка",
    "MustExistInList": "Должен быть в списке",
    "NoneEditable": "Нередактируемый",
    "PickListFilter": "Фильтр списка выбора",
    "ValueStoredAsText": "Значение сохранено как текст",
    "Value": "Значение",
    "Display": "Отображение",
    "Code": "Код",
    "Name": "Имя",
    "DisplayName": "Отображаемое имя",
    "Template": "Вычисление",
    "Description": "Описание",
    "SortOrder": "Порядок сортировки",
    "lblNoFieldsInTemplate": "Добавьте свойство сущности в шаблон, прежде чем применить порядок сортировки.",
    "AddField": "Добавить поле",
    "InUse": "Используется",
    "NotInUse": "Не используется",
    "CalculatedNumberInputError": "<p>Ввод данных возможен в имена полей, выбранных в раскрывающемся списке<br/> с использованием следующих символов:<br/>&nbsp;&nbsp;&nbsp;&nbsp;\"+\",\"-\",\"*\",\"/\",\"(\", или \")\".<br/>&nbsp;&nbsp;&nbsp;&nbsp;Они соответствуют значениям кнопок выше текстовой области.</p>",
    "newPickList": "Новый список выбора",
    "add": "добавить",
    "substract": "вычесть",
    "multiply": "умножить",
    "divide": "разделить",
    "openParens": "открыть скобку",
    "closeParens": "закрыть скобку"
});