define("Sage/UI/Dashboard/nls/ru/DashboardTabController", {
    "newTabText": "Новая вкладка",
    "addContentText": "Добавить содержимое",
    "editOptionsText": "Редактировать свойства",
    "hideTabText": "Скрыть вкладку",
    "closeText": "Закрыть",
    "copyTabText": "Копировать вкладку",
    "showTabText": "Показать вкладку",
    "shareTabText": "Общий доступ к вкладке",
    "deleteTabText": "Удалить вкладку",
    "deleteTabConfirmText": "Действительно удалить эту вкладку?",
    "descriptionText": "Описание",
    "everyoneText": "Все",
    "saveTabText": "Сохранить вкладку",
    "helpText": "Справка",
    "addText": "Добавить",
    "invalidMessage": "Недопустимый символ",
    "invalidDuplicateMessage": "Название должно быть уникальным.",
    "deleteText": "Удалить",
    "titleText": "Название:",
    "chooseTemplateText": "Выберите шаблон, который требуется использовать:",
    "oneColumnText": "Один столбец",
    "twoColumnText": "Разделить на две столбцы",
    "fatLeftText": "Две столбцы, большая левая",
    "fatRightText": "Две столбцы, большая правая",
    "makeDefaultText": "Использовать по умолчанию",
    "releaseFetchErrorText": "Ошибка выборки списка релизов",
    "releaseDeleteNoneSelected": "Элементы не выбраны.",
    "releasedToText": "Разблокировано для:",
    "typeText": "Тип",
    "addLookup": "Добавить",
    "okButton": "OК",
    "errorText": "Ошибка",
    "warningText": "Предупреждение",
    "permissionErrorText": "Ошибка: пользователь не имеет права на выполнение этого действия.",
    "permissionErrorPerformCopyText": "Создать собственную копию этой страницы?",
    "yesText": "Да",
    "noText": "Нет",
    "DeletingReleasedWidget": "Действительно удалить эту вкладку информационной панели? Количество пользователей, также использующих эту вкладку: ${0}. Удаление этой вкладки сделает ее недоступной для всех пользователей.",
    "Welcome": "Добро пожаловать"
});