define("Sage/Groups/nls/fr/GroupManager", {
    "ConfirmDeleteMessage": "Voulez-vous vraiment supprimer le groupe actuel ?",
    "ConfirmDeleteFmtMessage": "Voulez-vous vraiment supprimer ce groupe : ${0}",
    "InvalidSortStringMessage": "Erreur : chaîne de tri non valide - ",
    "InvalidConditionStringMessage": "Erreur : chaîne de condition non valide - ",
    "InvalidLayoutConditionStringMessage": "Erreur : chaîne de présentation non valide - ",
    "noneSelectedTitle": "Aucun enregistrement sélectionné",
    "noneSelectedPromptFmt": "Aucun enregistrement sélectionné. Le groupe entier, ${0} enregistrement(s), sera ajouté. Continuer ?",
    "noneSelectedRemovePromptFmt": "Aucun enregistrement sélectionné. Le groupe entier, ${0} enregistrement(s), sera supprimé. Continuer ?",
    "noRecordsInGroup": "Aucun enregistrement ne peut être sélectionné dans ce groupe.",
    "newGroupTitle": "Ajouter des enregistrements au nouveau groupe",
    "newGroupNamePrompt": "${0} enregistrement(s) sélectionné(s) est (seront) ajouté(s) à ce nouveau groupe.<br><br>Nom du groupe :<br>${1}",
    "newGroupRePrompt": "&nbsp;&nbsp;<i>Veuillez saisir un nom de groupe.</i>",
    "invalidCharMsg": "Le nom ne peut pas contenir : / \\ : * ? \" <> | ni '",
    "groupNameText": "Nom du groupe :",
    "saveLookupDlgTitle": "Enregistrer les résultats de la recherche en tant que nouveau groupe",
    "yesCaption": "Oui",
    "noCaption": "Non",
    "cancelCaption": "Annuler",
    "okCaption": "OK",
    "LOCALSTORE_NAMESPACE": "SageGroups",
    "exportToExcel": "Cette méthode n'est plus disponible, consultez Sage.TaskPane.CommonTasksTasklet.exportToExcel.",
    "createAdHocGroupJob_Description": "Groupe : ${0}",
    "createAdHocGroupJob_Title": "Création du groupe",
    "createAdHocGroupJobError": "Une erreur s'est produite lors de la création du groupe : ${0}",
    "createAdHocGroupJobProcessingJobMsg": "Vous pouvez continuer à attendre la fin de l'opération ou fermer ce message. Vous recevrez une notification lorsque le groupe sera créé."
});