define("Sage/UI/Dashboard/nls/it/DashboardTabController", {
    "newTabText": "Nuova scheda",
    "addContentText": "Aggiungi contenuto",
    "editOptionsText": "Modifica opzioni",
    "hideTabText": "Nascondi scheda",
    "closeText": "Chiudi",
    "copyTabText": "Copia scheda",
    "showTabText": "Visualizza scheda",
    "shareTabText": "Condividi scheda",
    "deleteTabText": "Elimina scheda",
    "deleteTabConfirmText": "Eliminare questa scheda?",
    "descriptionText": "Descrizione",
    "everyoneText": "Tutti",
    "saveTabText": "Salva scheda",
    "helpText": "Guida",
    "addText": "Aggiungi",
    "invalidMessage": "Carattere non valido",
    "invalidDuplicateMessage": "Il titolo deve essere univoco.",
    "deleteText": "Elimina",
    "titleText": "Titolo:",
    "chooseTemplateText": "Scegliere il modello che si desidera utilizzare:",
    "oneColumnText": "Una colonna",
    "twoColumnText": "Dividi in due colonne",
    "fatLeftText": "Due colonne più larghe a sinistra",
    "fatRightText": "Due colonne più larghe a destra",
    "makeDefaultText": "Predefinito",
    "releaseFetchErrorText": "Errore nel recupero dell'elenco dei rilasci.",
    "releaseDeleteNoneSelected": "Nessun elemento selezionato.",
    "releasedToText": "Rilasciato a:",
    "typeText": "Tipo",
    "addLookup": "Aggiungi",
    "okButton": "OK",
    "errorText": "Errore",
    "warningText": "Avviso",
    "permissionErrorText": "Errore: l'utente non possiede i diritti per eseguire questa azione.",
    "permissionErrorPerformCopyText": "Si desidera creare una copia personale della pagina?",
    "yesText": "Sì",
    "noText": "No",
    "DeletingReleasedWidget": "Eliminare questa scheda del dashboard? La scheda è condivisa con ${0} utente/i e verrà eliminata per tutti gli utenti.",
    "Welcome": "Benvenuto"
});