define("Sage/UI/Dashboard/nls/fr/DashboardTabController", {
    "newTabText": "Nouvel onglet",
    "addContentText": "Ajouter du contenu",
    "editOptionsText": "Modifier les options",
    "hideTabText": "Masquer l'onglet",
    "closeText": "Fermer",
    "copyTabText": "Copier l'onglet",
    "showTabText": "Afficher l'onglet",
    "shareTabText": "Partager l'onglet",
    "deleteTabText": "Supprimer un onglet",
    "deleteTabConfirmText": "Voulez-vous vraiment supprimer cet onglet ?",
    "descriptionText": "Description",
    "everyoneText": "Tous les utilisateurs",
    "saveTabText": "Enregistrer l'onglet",
    "helpText": "Aide",
    "addText": "Ajouter",
    "invalidMessage": "Caractère non valide",
    "invalidDuplicateMessage": "Le titre doit être unique.",
    "deleteText": "Supprimer",
    "titleText": "Titre :",
    "chooseTemplateText": "Choisir le modèle à utiliser :",
    "oneColumnText": "Une colonne",
    "twoColumnText": "Partage en deux colonnes",
    "fatLeftText": "Deux colonnes plus grandes à gauche",
    "fatRightText": "Deux colonnes plus grandes à droite",
    "makeDefaultText": "Utiliser par défaut",
    "releaseFetchErrorText": "Erreur lors de la récupération de la liste de diffusion.",
    "releaseDeleteNoneSelected": "Aucun élément sélectionné.",
    "releasedToText": "Diffusé à :",
    "typeText": "Type",
    "addLookup": "Ajouter",
    "okButton": "OK",
    "errorText": "Erreur",
    "warningText": "Avertissement",
    "permissionErrorText": "Erreur : l'utilisateur ne dispose pas des droits suffisants pour effectuer cette action.",
    "permissionErrorPerformCopyText": "Voulez-vous créer une copie personnelle de cette page ?",
    "yesText": "Oui",
    "noText": "Non",
    "DeletingReleasedWidget": "Voulez-vous vraiment supprimer cet onglet Tableau de bord ? Cet onglet est partagé avec un (des) utilisateur(s) ${0}. La suppression de cet onglet sera effective pour tous les utilisateurs.",
    "Welcome": "Bienvenue"
});