define(
"dojo/cldr/nls/rm/currency", //begin v1.x content
{
	"COP_displayName": "peso columbian",
	"CZK_displayName": "cruna tscheca",
	"TND_displayName": "dinar tunesian",
	"JMD_displayName": "dollar giamaican",
	"PHP_displayName": "peso filippin",
	"ALL_displayName": "lek",
	"LBP_displayName": "glivra libanaisa",
	"VND_displayName": "dong vietnamais",
	"LYD_displayName": "dinar libic",
	"RON_displayName": "leu rumen",
	"MKD_displayName": "dinar da la Macedonia",
	"SEK_displayName": "cruna svedaisa",
	"CNY_displayName": "yuan renminbi chinais",
	"IDR_displayName": "rupia indonaisa",
	"ILS_displayName": "sheqel",
	"YER_displayName": "rial dal Jemen",
	"TJS_displayName": "somoni dal Tadschikistan",
	"TTD_displayName": "dollar da Trinidad e Tobago",
	"TRY_displayName": "nova lira tirca",
	"EUR_displayName": "euro",
	"AED_displayName": "dirham dals Emirats Arabs Unids",
	"KZT_displayName": "tenge casac",
	"BHD_displayName": "dinar dal Bahrain",
	"RUB_displayName": "rubel russ (nov)",
	"NZD_displayName": "dollar da la Nova Zelanda",
	"IQD_displayName": "dinar iracais",
	"KGS_displayName": "som kirghis",
	"KWD_displayName": "dinar dal Kuwait",
	"AFN_displayName": "afghani",
	"ARS_displayName": "peso argentin",
	"MAD_displayName": "dirham marocan",
	"BAM_displayName": "marc convertibel bosniac",
	"BOB_displayName": "boliviano",
	"BND_displayName": "dollar dal Brunei",
	"SGD_displayName": "dollar dal Singapur",
	"MVR_displayName": "rufiyaa da las Maledivas",
	"MXN_displayName": "peso mexican",
	"DZD_displayName": "dinar algerian",
	"JOD_displayName": "dinar jordanic",
	"PEN_displayName": "nov sol peruan",
	"GTQ_displayName": "quetzal da la Guatemala",
	"BYR_displayName": "rubel bieloruss",
	"CAD_displayName": "dollar canadais",
	"BZD_displayName": "dollar dal Belize",
	"CLP_displayName": "peso chilen",
	"XOF_displayName": "franc CFA BCEAO",
	"NOK_displayName": "cruna norvegiaisa",
	"DOP_displayName": "peso dominican",
	"KRW_displayName": "won da la Corea dal Sid",
	"USD_displayName": "dollar dals Stadis Unids da l'America",
	"UYU_displayName": "peso da l'Uruguay",
	"UZS_displayName": "sum usbec",
	"QAR_displayName": "riyal da Katar",
	"SAR_displayName": "riyal saudit",
	"SYP_displayName": "glivra siriana",
	"EGP_displayName": "glivra egipziana",
	"AMD_displayName": "dram armen",
	"GBP_displayName": "glivra sterlina",
	"HUF_displayName": "forint ungarais",
	"CSD_displayName": "vegl dinar serb",
	"ISK_displayName": "cruna islandaisa",
	"IRR_displayName": "rial iranais",
	"OMR_displayName": "rial da l'Oman",
	"TWD_displayName": "nov dollar taiwanais",
	"PAB_displayName": "balboa dal Panama",
	"UAH_displayName": "hryvnia ucranais",
	"ETB_displayName": "birr etiopic",
	"PLN_displayName": "zloty polac",
	"VEF_displayName": "bolivar venezuelan",
	"BRL_displayName": "real brasilian",
	"HKD_displayName": "dollar da Hongkong",
	"NIO_displayName": "cordoba oro nicaraguan",
	"NPR_displayName": "rupia nepalaisa",
	"CHF_symbol": "CHF",
	"PKR_displayName": "rupia pakistana",
	"GEL_displayName": "lari georgian",
	"AZN_displayName": "manat aserbaidschanic",
	"MYR_displayName": "ringgit da la Malaisia",
	"DKK_displayName": "cruna danaisa",
	"THB_displayName": "baht tailandais",
	"JPY_displayName": "yen giapunais",
	"KES_displayName": "schilling kenian",
	"KHR_displayName": "riel cambodschan",
	"PYG_displayName": "guarani paraguaian",
	"LKR_displayName": "rupia da la Sri Lanka",
	"BGN_displayName": "nov lev bulgar",
	"BDT_displayName": "taka bangladais",
	"MOP_displayName": "pataca dal Macao",
	"HNL_displayName": "lempira hondurian",
	"RWF_displayName": "franc ruandais",
	"CHF_displayName": "franc svizzer",
	"CRC_displayName": "colon da la Costa Rica",
	"INR_displayName": "rupia indica",
	"ZAR_displayName": "rand sidafrican",
	"AUD_displayName": "dollar australian",
	"LAK_displayName": "kip laot",
	"MNT_displayName": "tugrik mongolic",
	"RSD_displayName": "dinar serb",
	"HRK_displayName": "kuna croata"
}
//end v1.x content
);