define(
"dojo/cldr/nls/ja/currency", //begin v1.x content
{
	"COP_displayName": "コロンビア ペソ",
	"CZK_displayName": "チェコ コルナ",
	"TND_displayName": "チュニジア ディナール",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ジャマイカ ドル",
	"PHP_displayName": "フィリピン ペソ",
	"ALL_displayName": "アルバニア レク",
	"USD_symbol": "$",
	"LBP_displayName": "レバノン ポンド",
	"VND_displayName": "ベトナム ドン",
	"LYD_displayName": "リビア ディナール",
	"RON_displayName": "ルーマニア レイ",
	"MKD_displayName": "マケドニア デナル",
	"SEK_displayName": "スウェーデン クローナ",
	"CNY_displayName": "中国人民元",
	"IDR_displayName": "インドネシア ルピア",
	"ILS_displayName": "イスラエル新シェケル",
	"YER_displayName": "イエメン リアル",
	"TJS_displayName": "タジキスタン ソモニ",
	"TTD_displayName": "トリニダードトバゴ ドル",
	"CNY_symbol": "元",
	"TRY_displayName": "新トルコリラ",
	"EUR_displayName": "ユーロ",
	"AED_displayName": "アラブ首長国連邦ディルハム",
	"KZT_displayName": "カザフスタン テンゲ",
	"BHD_displayName": "バーレーン ディナール",
	"RUB_displayName": "ロシア ルーブル",
	"NZD_displayName": "ニュージーランド ドル",
	"IQD_displayName": "イラク ディナール",
	"TMT_displayName": "トルクメニスタン マナト",
	"ZWL_displayName": "ジンバブエ ドル (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "キルギスタン ソム",
	"KWD_displayName": "クウェート ディナール",
	"AFN_displayName": "アフガニー",
	"ARS_displayName": "アルゼンチン ペソ",
	"MAD_displayName": "モロッコ ディルハム",
	"BAM_displayName": "ボスニア マルク (BAM)",
	"BOB_displayName": "ボリビア ボリビアーノ",
	"BND_displayName": "ブルネイ ドル",
	"SGD_displayName": "シンガポール ドル",
	"MVR_displayName": "モルディブ諸島 ルフィア",
	"MXN_displayName": "メキシコ ペソ",
	"DZD_displayName": "アルジェリア ディナール",
	"MXN_symbol": "MX$",
	"JOD_displayName": "ヨルダン ディナール",
	"PEN_displayName": "ペルー 新ソル",
	"GTQ_displayName": "グアテマラ ケツァル",
	"BYR_displayName": "ベラルーシ ルーブル",
	"CAD_displayName": "カナダ ドル",
	"BZD_displayName": "ベリーズ ドル",
	"CLP_displayName": "チリ ペソ",
	"XOF_displayName": "CFA フラン（BCEAO）",
	"NOK_displayName": "ノルウェー クローネ",
	"DOP_displayName": "ドミニカ ペソ",
	"JPY_symbol": "￥",
	"KRW_displayName": "韓国 ウォン",
	"USD_displayName": "米ドル",
	"UYU_displayName": "ウルグアイ ペソ",
	"UZS_displayName": "ウズベキスタン スム",
	"XOF_symbol": "CFA",
	"QAR_displayName": "カタール リアル",
	"SAR_displayName": "サウジ リヤル",
	"SYP_displayName": "シリア ポンド",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "エジプト ポンド",
	"AMD_displayName": "アルメニア ドラム",
	"GBP_displayName": "英国ポンド",
	"HUF_displayName": "ハンガリー フォリント",
	"CSD_displayName": "セルビア ディナール (2002–2006)",
	"ISK_displayName": "アイスランド クローナ",
	"IRR_displayName": "イラン リアル",
	"OMR_displayName": "オマーン リアル",
	"TWD_displayName": "新台湾ドル",
	"PAB_displayName": "パナマ バルボア",
	"UAH_displayName": "ウクライナ グリブナ",
	"ETB_displayName": "エチオピア ブル",
	"PLN_displayName": "ポーランド ズウォティ",
	"VEF_displayName": "ベネズエラ ボリバル",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "ブラジル レアル",
	"HKD_symbol": "HK$",
	"HKD_displayName": "香港ドル",
	"NIO_displayName": "ニカラグア コルドバ オロ",
	"THB_symbol": "฿",
	"NPR_displayName": "ネパール ルピー",
	"PKR_displayName": "パキスタン ルピー",
	"TWD_symbol": "NT$",
	"GEL_displayName": "グルジア ラリ",
	"AZN_displayName": "アゼルバイジャン マナト",
	"GBP_symbol": "£",
	"MYR_displayName": "マレーシア リンギット",
	"DKK_displayName": "デンマーク クローネ",
	"THB_displayName": "タイ バーツ",
	"BRL_symbol": "R$",
	"JPY_displayName": "日本円",
	"KES_displayName": "ケニア シリング",
	"KHR_displayName": "カンボジア リエル",
	"PYG_displayName": "パラグアイ グアラニ",
	"VND_symbol": "₫",
	"LKR_displayName": "スリランカ ルピー",
	"BGN_displayName": "ブルガリア 新レフ",
	"BDT_displayName": "バングラデシュ タカ",
	"MOP_displayName": "マカオ パタカ",
	"HNL_displayName": "ホンジュラス レンピラ",
	"RWF_displayName": "ルワンダ フラン",
	"CHF_displayName": "スイス フラン",
	"CRC_displayName": "コスタリカ コロン",
	"INR_displayName": "インド ルピー",
	"KRW_symbol": "￦",
	"ZAR_displayName": "南アフリカ ランド",
	"AUD_displayName": "オーストラリア ドル",
	"LAK_displayName": "ラオス キープ",
	"MNT_displayName": "モンゴル トグログ",
	"RSD_displayName": "ディナール (セルビア)",
	"HRK_displayName": "クロアチア クーナ"
}
//end v1.x content
);