define(
"dojo/cldr/nls/ne/currency", //begin v1.x content
{
	"COP_displayName": "कोलम्वियन पेसो",
	"CZK_displayName": "चेख गणतञ्त्र कोरूना",
	"TND_displayName": "टुनिसियाली डिनार",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "जमाइकाली डलर",
	"PHP_displayName": "फिलिपिनी पेसो",
	"ALL_displayName": "अल्बानियन लेक",
	"USD_symbol": "US$",
	"LBP_displayName": "लेबनाली पाउन्ड",
	"VND_displayName": "भियतनामी डङ्",
	"LYD_displayName": "लिवियाली डिनार",
	"RON_displayName": "रोमानियाली लेऊ",
	"MKD_displayName": "म्यासेडोनियाली डेनार",
	"SEK_displayName": "स्विडिश क्रोना",
	"CNY_displayName": "चिनिँया युआन",
	"IDR_displayName": "इण्डोनेशियाली रूपियाँ",
	"ILS_displayName": "इजरायली नयाँ शेकेल",
	"YER_displayName": "येमेनी रियाल",
	"TJS_displayName": "ताजिक्स्तानी सोमोनी",
	"TTD_displayName": "त्रिनिडाड र टोबागो डलर",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "टर्किश लिरा",
	"EUR_displayName": "युरो",
	"AED_displayName": "संयुक्त अरब एमिराट्स डिर्हाम",
	"KZT_displayName": "काजाखस्तानी टेन्ज",
	"BHD_displayName": "बाहारैनी डिनार",
	"RUB_displayName": "रूसी रूबल",
	"NZD_displayName": "न्यूजिल्याण्ड डलर",
	"IQD_displayName": "इराकी डिनार",
	"TMT_displayName": "टुर्क्मेनिस्तानी मानात",
	"INR_symbol": "₹",
	"KGS_displayName": "किर्गिस्तानी सोम",
	"KWD_displayName": "कुवेती डिनार",
	"AFN_displayName": "अफ्गान अफ्गानी",
	"ARS_displayName": "अर्जेन्टिनी पेसो",
	"MAD_displayName": "मोरोक्काली डिर्हाम",
	"BAM_displayName": "बोस्निया-हर्जगोभिनिया रूपान्तरयोग्य मार्क",
	"BOB_displayName": "बोलिभियन बोलिभियानो",
	"BND_displayName": "ब्रुनाई डलर",
	"SGD_displayName": "सिङ्गापुर डलर",
	"MVR_displayName": "मालडिभियाली रूफियाँ",
	"MXN_displayName": "मेक्सिकन पेसो",
	"DZD_displayName": "अल्जेरियाली डिनार",
	"MXN_symbol": "MX$",
	"JOD_displayName": "जोर्डानियाली डलर",
	"PEN_displayName": "पेरूभियाली न्यूभो सोल",
	"GTQ_displayName": "ग्वाटेमाला क्वेट्जाल",
	"BYR_displayName": "बेलारूसी रूबल",
	"CAD_displayName": "क्यानाडियाली डलर",
	"BZD_displayName": "वेलिज डलर",
	"CLP_displayName": "चिलियन पेसो",
	"XOF_displayName": "सीएफ्ए फ्रान्क बीसीइएओ",
	"NOK_displayName": "नर्वेजियाली क्रोन",
	"DOP_displayName": "डोमिनिकन पेसो",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "दक्षिण कोरियाली वन",
	"USD_displayName": "संयुक्त राज्य डलर",
	"UYU_displayName": "उरूग्वेयन पेसो",
	"UZS_displayName": "उज्बेकिस्तान सोम",
	"XOF_symbol": "CFA",
	"QAR_displayName": "कतारी रियल",
	"SAR_displayName": "साउदी रियालहरू",
	"SYP_displayName": "सिरियाली पाउन्ड",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "इजिप्सियन पाउन्ड",
	"AMD_displayName": "आर्मेनियाली ड्राम",
	"GBP_displayName": "बेलायती पाउण्ड स्टर्लिङ",
	"NPR_symbol": "नेरू",
	"HUF_displayName": "हङ्गेरियन फोरिन्ट",
	"ISK_displayName": "आइसल्याण्डिक क्रोना",
	"IRR_displayName": "इरानियाली रियाल",
	"OMR_displayName": "ओमनी रियल",
	"TWD_displayName": "नयाँ ताइवान डलर",
	"PAB_displayName": "पानामानियाली बाल्बोआ",
	"UAH_displayName": "युक्रेनी हिर्भिनिया",
	"ETB_displayName": "इथियोपियाली बिर",
	"PLN_displayName": "पोलिश ज्लोटाई",
	"VEF_displayName": "भेनेजुएलन बोलिभर",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ब्राजिलियन रियल",
	"HKD_symbol": "HK$",
	"HKD_displayName": "हङकङ डलर",
	"NIO_displayName": "निकारागुवान कोर्डोवा",
	"THB_symbol": "฿",
	"NPR_displayName": "नेपाली रूपैयाँ",
	"PKR_displayName": "पाकिस्तानी रूपियाँ",
	"TWD_symbol": "NT$",
	"GEL_displayName": "जर्जियन लारी",
	"AZN_displayName": "अजरबैजानी मानात",
	"GBP_symbol": "£",
	"MYR_displayName": "मलेशियाली रिङ्गेट",
	"DKK_displayName": "ड्यानिश क्रोन",
	"THB_displayName": "थाई भाट",
	"BRL_symbol": "R$",
	"JPY_displayName": "जापानी येन",
	"KES_displayName": "केन्याली शिलिङ",
	"KHR_displayName": "कम्बोडिनेयाली रियल",
	"PYG_displayName": "पारागुयाली गुरानी",
	"VND_symbol": "₫",
	"LKR_displayName": "श्रीलङ्काली रूपिया",
	"BGN_displayName": "बुल्गारियाली लेभ",
	"BDT_displayName": "बङ्गलादेशी टाका",
	"MOP_displayName": "माकानिज पटाका",
	"HNL_displayName": "होन्डुरान लेम्पिरा",
	"RWF_displayName": "र्वाण्डाली फ्रान्क",
	"CHF_displayName": "स्विस् फ्रैङ्क",
	"CRC_displayName": "कोष्टारिकन कोलोन",
	"INR_displayName": "भारती रूपिँया",
	"KRW_symbol": "₩",
	"ZAR_displayName": "दक्षिण अफ्रिकी र्यान्ड",
	"AUD_displayName": "अष्ट्रेलियन डलर",
	"LAK_displayName": "लाओशियन किप",
	"MNT_displayName": "मङ्गोलियाली टुग्रिक",
	"RSD_displayName": "सर्बियाली डिनार",
	"HRK_displayName": "क्रोएशियाली कुना"
}
//end v1.x content
);