define("Sage/QuickForms/Design/Editors/nls/zh-cn/ComboBoxAdvancedPropertyEditor", {
    "titleText": "高级",
    "appearanceText": "外观",
    "behaviorText": "行为",
    "controlInfoText": "控件信息",
    "dataText": "数据",
    "itemGroupText": "项目",
    "controlIdText": "控件 ID:",
    "controlIdTooltipText": "此控件的标识。",
    "controlLabelPlacementText": "标签位置:",
    "controlLabelPlacementTooltipText": "相对于控件的标签位置。",
    "controlTypeText": "控件类型:",
    "controlTypeTooltipText": "Saleslogix 控件类型。",
    "dataSourceText": "数据源:",
    "dataSourceTooltipText": "此控件的数据源，例如，另一个控件或实体。",
    "defaultDataBindingText": "数据绑定:",
    "defaultDataBindingTooltipText": "此控件使用的数据库中的数据字段。",
    "enabledText": "已启用:",
    "enabledTooltipText": "允许用户与此控件交互。",
    "itemsText": "项目:",
    "itemsTooltipText": "用户可选择的值。",
    "textFieldText": "文本字段:",
    "textFieldTooltipText": "用于填充列表项的可见文本部分的数据源字段名称。",
    "valueFieldText": "值字段:",
    "valueFieldTooltipText": "用于填充列表项的值部分的数据源字段名称。",
    "visibleText": "可见:",
    "visibleTooltipText": "在窗体上显示或隐藏此控件。",
    "labelPlacementText": {
        "left": "左侧",
        "right": "右侧",
        "top": "顶部",
        "none": "无"
    },
    "hasItemsText": "设置",
    "noItemsText": "未设置"
});