define("Sage/QuickForms/Design/Editors/nls/zh-tw/DataGridAdvancedPropertyEditor", {
    "titleText": "進階",
    "appearanceText": "外觀",
    "behaviorText": "行為",
    "controlInfoText": "控制項資訊",
    "dataText": "資料",
    "controlIdText": "控制項 ID:",
    "controlIdTooltipText": "這個控制項的 ID。",
    "controlTypeText": "控制項類型:",
    "controlTypeTooltipText": "Saleslogix 控制項類型。",
    "dataSourceText": "資料來源:",
    "dataSourceTooltipText": "這個控制項的資料來源，例如其他控制項或實體。",
    "emptyTableRowText": "空白表格列文字:",
    "emptyTableRowTooltipText": "如果資料格未顯示資料時，要顯示的文字。",
    "expandableRowsText": "可展開的列:",
    "expandableRowsTooltipText": "允許使用者展開格線列來顯示更多文字。",
    "renderVerticalText": "垂直轉譯:",
    "renderVerticalTooltipText": "將資料格列顯示為欄。",
    "showSortIconText": "顯示排序圖示:",
    "showSortIconTooltipText": "在可排序的欄上顯示排序圖示。",
    "visibleText": "可見:",
    "visibleTooltipText": "在表單上顯示或隱藏這個控制項。"
});