define("Sage/QuickForms/Design/Editors/nls/zh-tw/PickListAdvancedPropertyEditor", {
    "titleText": "進階",
    "appearanceText": "外觀",
    "behaviorText": "行為",
    "controlInfoText": "控制項資訊",
    "dataText": "資料",
    "allowMultiplesText": "允許多個選取項目:",
    "allowMultiplesTooltipText": "允許使用者選取一個以上的項目。",
    "canEditTextText": "可編輯文字:",
    "canEditTextTooltipText": "允許使用者輸入值。",
    "controlIdText": "控制項 ID:",
    "controlIdTooltipText": "這個控制項的 ID。",
    "controlLabelPlacementText": "標籤位置:",
    "controlLabelPlacementTooltipText": "標籤與控制項的相對位置。",
    "controlTypeText": "控制項類型:",
    "controlTypeTooltipText": "Saleslogix 控制項類型。",
    "defaultDataBindingText": "資料繫結:",
    "defaultDataBindingTooltipText": "這個控制項所使用的資料庫的資料欄位。",
    "displayModeText": "顯示模式:",
    "displayModeTooltipText": "控制項的顯示模式: 文字方塊、超連結或純文字。",
    "enabledText": "已啟用:",
    "enabledTooltipText": "允許使用者與這個控制項互動。",
    "maxLengthText": "長度上限:",
    "maxLengthTooltipText": "使用者可輸入的字元數上限。",
    "mustExistInListText": "項目必須在:",
    "mustExistInListTooltipText": "輸入的值必須在清單中。",
    "pickListNameText": "挑選清單名稱:",
    "pickListNameTooltipText": "使用者輸入資料時可以選取的值清單名稱。",
    "requiredText": "必要:",
    "requiredTooltipText": "儲存資料時需要一個值。",
    "storageModeText": "儲存空間模式:",
    "storageModeTooltipText": "值的排序方式: 文字、ID 或代碼。",
    "visibleText": "可見:",
    "visibleTooltipText": "在表單上顯示或隱藏這個控制項。",
    "labelPlacementText": {
        "left": "靠左",
        "right": "靠右",
        "top": "靠上",
        "none": "無"
    },
    "displayModeTypeText": {
        "AsControl": "做為控制項",
        "AsText": "做為文字",
        "AsHyperlink": "做為超連結"
    },
    "storageModeTypeText": {
        "Text": "文字",
        "Id": "ID",
        "Code": "代碼"
    },
    "pickListRequestErrorText": "無法從伺服器擷取挑選清單。"
});