define("Sage/MainView/GroupMgr/templates/nls/it/GroupDetailSummary", {
    "txtGroupFamily_Caption": "Famiglia:",
    "txtGroupName_Caption": "Nome:",
    "txtGroupDisplayName_Caption": "Nome visualizzato:",
    "txtGroupDescription_Caption": "Descrizione:",
    "txtGroupId_Caption": "ID:",
    "txtGroupMainTable_Caption": "Tabella principale:",
    "txtGroupEntityName_Caption": "Nome entità:",
    "txtGroupCreateDate_Caption": "Data di creazione:",
    "txtGroupCreateUser_Caption": "Creato da:",
    "txtGroupModifyDate_Caption": "Data di modifica:",
    "txtGroupModifyUser_Caption": "Modificato da:",
    "txtGroupInstallationDate_Caption": "Data installazione:",
    "txtGroupShared_Caption": "Condiviso:",
    "txtGroupSharedDate_Caption": "Data condivisione:",
    "txtGroupOwner_Caption": "Proprietario:",
    "txtGroupUserId_Caption": "ID utente:",
    "txtGroupAdhoc_Caption": "Ad hoc:",
    "txtGroupHidden_Caption": "Nascosto:",
    "txtGroupAuthor_Caption": "Autore:",
    "txtGroupCompany_Caption": "Società:",
    "txtGroupCompanyVersion_Caption": "Versione società:",
    "txtGroupDev_Caption": "Dev:",
    "txtGroupDataCode_Caption": "Codice dati:",
    "txtGroupType_Caption": "Tipo gruppo:",
    "txtGroupUserDefault_Caption": "Impostazione predefinita utente:"
});