define("Sage/UI/Controls/nls/de/FieldAttributeControlFactory", {
    "IsEncrypted": "Ist verschlüsselt",
    "Length": "Länge",
    "Precision": "Genauigkeit",
    "Scale": "Skalieren",
    "LookupEntityName": "Entität suchen",
    "LookupGroup": "Gruppe suchen",
    "IsPercentage": "Ist Prozentsatz",
    "Items": "Elemente",
    "MultiSelect": "Mehrfachauswahl",
    "OverriddenName": "Überschriebener Name",
    "Storage": "Speicherung",
    "EnableHyperLinking": "Erstellung von Hyperlinks aktivieren",
    "LookupPreFilters": "Vorfilter für Suche",
    "EqualTo": "Gleich",
    "NotEqualTo": "Ungleich",
    "GreaterThanOrEqual": "Größer gleich",
    "GreaterThan": "Größer als",
    "LessThanOrEqual": "Kleiner gleich",
    "LessThan": "Kleiner als",
    "CondOperator": "Bedingungsoperator",
    "FilterValue": "Filterwert",
    "PropertyName": "Eigenschaftsname",
    "LookupProperties": "Sucheigenschaften",
    "ExcludeFromFilters": "Von Filtern ausschließen",
    "HideCondition": "Ausblende-Bedingung",
    "IsSortable": "Ist sortierbar",
    "PropertyFormat": "Eigenschaftsformat",
    "None": "Keine",
    "Phone": "Telefon",
    "User": "Benutzer",
    "PickList": "Auswahlliste",
    "DateTime": "Datum/Uhrzeit",
    "PropertyFormatString": "Eigenschaftsformatzeichenfolge",
    "PropertyHeader": "Eigenschaftsüberschrift",
    "PropertyType": "Eigenschaftstyp",
    "UseAsResult": "Als Ergebnis verwenden",
    "ReturnPrimaryKey": "Primärschlüssel zurückgeben",
    "AllowMultiples": "Mehrfachauswahl zulassen",
    "AlphaSort": "Alphabetische Sortierung",
    "MustExistInList": "Muss in Liste enthalten sein",
    "NoneEditable": "Nichts bearbeitbar",
    "PickListFilter": "Auswahllistenfilter",
    "ValueStoredAsText": "Als Text gespeicherter Wert",
    "Value": "Wert",
    "Display": "Anzeigen",
    "Code": "Code",
    "Name": "Name",
    "DisplayName": "Anzeigename",
    "Template": "Berechnung",
    "Description": "Beschreibung",
    "SortOrder": "Sortierreihenfolge",
    "lblNoFieldsInTemplate": "Fügen Sie eine Entitätseigenschaft zur Vorlage hinzu, bevor Sie eine Sortierreihenfolge übernehmen.",
    "AddField": "Feld hinzufügen",
    "InUse": "In Benutzung",
    "NotInUse": "Nicht in Benutzung",
    "CalculatedNumberInputError": "<p>Die Eingaben sind auf die Feldnamen beschränkt, die über die Dropdown-Liste ausgewählt werden können,<br/> sowie auf folgende Zeichen:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+', '-', '*', '/', '(', oder ')';<br/>&nbsp;&nbsp;&nbsp;&nbsp;. Die Zeichen entsprechen den Tasten rund um das Buchstabenfeld auf der Tastatur.</p>",
    "newPickList": "Neue Auswahlliste",
    "add": "addieren",
    "substract": "subtrahieren",
    "multiply": "multiplizieren",
    "divide": "dividieren",
    "openParens": "geöffnete Klammer",
    "closeParens": "geschlossene Klammer"
});