define("Sage/TaskPane/nls/zh-tw/ActivityTaskConfigurationProvider", {
    "scheduleText": "排程",
    "eventText": "事件",
    "phoneCallText": "電話",
    "toDoText": "待辦事項",
    "meetingText": "會議",
    "personalActivityText": "個人活動",
    "deleteConfirmationText": "刪除確認",
    "acceptConfirmationText": "接受確認",
    "declineConfirmationText": "拒絕確認",
    "completeActivityText": "完成活動",
    "deleteActivityText": "刪除活動",
    "deleteEventText": "刪除事件",
    "scheduleEventText": "排程事件",
    "scheduleRequestText": "排程要求",
    "deleteRequestText": "刪除要求",
    "recordsSelectedText": "筆選取的記錄",
    "clearText": "清除"
});