define("Sage/TaskPane/nls/zh-tw/CommonTasksTasklet", {
    "okButtonText": "確定",
    "loadingText": "載入中...",
    "noPrimaryEmail": "沒有可用的主要電子郵件",
    "selectFileFormat": "選取檔案格式:",
    "exportToFile_OptionCSV": "標準 CSV",
    "exportToFile_OptionTab": "Tab 鍵分隔 (建議用於 Microsoft Excel)",
    "exportToFile_OptionSaveFormat": "記住我的選擇，不要再詢問。",
    "exportToFile_OK": "確定",
    "exportToFile_Cancel": "取消",
    "exportToFile_DialogTitle": "匯出",
    "exportToExcel_Caption": "匯出",
    "errorRequestingJobMgr": "要求工作管理者時發生錯誤: ${0}",
    "errorExecutionAction": "執行動作 ${0} 時發生錯誤",
    "exportProcessingJobMsg": "匯出處理中，您可能需要繼續等候完成，或到報告檢視中開啟您的檔案。",
    "errorBulkActionNotSupported": "${0} 不支援大量動作更新，請聯絡系統管理員。",
    "errorBulkActionRequest": "要求大量更新選項時發生錯誤，請聯絡系統管理員。",
    "copyProfileNoneSelected": "至少必須選取一位使用者!",
    "deleteJob_Description": "發生大量刪除錯誤",
    "errorRequestEntityImportable": "取得實體屬性時發生錯誤。${0}",
    "entityNotImportable": "${0} 不支援匯入，請聯絡系統管理員。"
});