define(
"dojo/cldr/nls/mo/currency", //begin v1.x content
{
	"COP_displayName": "peso columbian",
	"CZK_displayName": "coroană cehă",
	"TND_displayName": "dinar tunisian",
	"$locale": "ro-md",
	"PHP_displayName": "peso filipinez",
	"CAD_symbol": "CAD",
	"JMD_displayName": "dolar jamaican",
	"ALL_displayName": "leka albanez",
	"USD_symbol": "USD",
	"LBP_displayName": "liră libaneză",
	"VND_displayName": "dong vietnamez",
	"LYD_displayName": "dinar libian",
	"RON_displayName": "leu românesc",
	"MKD_displayName": "dinar macedonean",
	"SEK_displayName": "coroană suedeză",
	"CNY_displayName": "yuan renminbi chinezesc",
	"IDR_displayName": "rupie indoneziană",
	"YER_displayName": "rial yemenit",
	"ILS_displayName": "șechel israelian nou",
	"TJS_displayName": "somoni tadjic",
	"TTD_displayName": "dolar din Trinidad-Tobago",
	"TRY_displayName": "liră turcească",
	"CNY_symbol": "CNY",
	"EUR_displayName": "euro",
	"AED_displayName": "dirham din Emiratele Arabe Unite",
	"KZT_displayName": "tenge kazahă",
	"BHD_displayName": "dinar din Bahrain",
	"RUB_displayName": "rublă rusească",
	"NZD_displayName": "dolar neozeelandez",
	"IQD_displayName": "dinar irakian",
	"TMT_displayName": "manat turkmen",
	"ZWL_displayName": "dolar Zimbabwe (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "som kârgâz",
	"KWD_displayName": "dinar kuweitian",
	"AFN_displayName": "afgani afgan",
	"ARS_displayName": "peso argentinian",
	"MAD_displayName": "dirham marocan",
	"BAM_displayName": "marcă convertibilă bosniacă",
	"BOB_displayName": "boliviano bolivian",
	"BND_displayName": "dolar din Brunei",
	"SGD_displayName": "dolar Singapore",
	"MVR_displayName": "rufiyaa maldiviană",
	"MXN_displayName": "peso mexican",
	"MXN_symbol": "MXN",
	"DZD_displayName": "dinar algerian",
	"JOD_displayName": "dinar iordanian",
	"PEN_displayName": "sol nou peruvian",
	"GTQ_displayName": "quetzal guatemalez",
	"BYR_displayName": "rublă belarusă",
	"CAD_displayName": "dolar canadian",
	"BZD_displayName": "dolar din Belize",
	"CLP_displayName": "peso chilian",
	"XOF_displayName": "franc CFA BCEAO",
	"NOK_displayName": "coroană norvegiană",
	"DOP_displayName": "peso dominican",
	"JPY_symbol": "JPY",
	"UYU_displayName": "peso uruguayan",
	"KRW_displayName": "won sud-coreean",
	"UZS_displayName": "sum Uzbekistan",
	"USD_displayName": "dolar american",
	"QAR_displayName": "rial qatarian",
	"SAR_displayName": "rial saudit",
	"SYP_displayName": "liră siriană",
	"NZD_symbol": "NZD",
	"EGP_displayName": "liră egipteană",
	"AMD_displayName": "dram armenesc",
	"GBP_displayName": "liră sterlină",
	"HUF_displayName": "forint maghiar",
	"CSD_displayName": "dinar Serbia și Muntenegru (2002–2006)",
	"ISK_displayName": "coroană islandeză",
	"IRR_displayName": "rial iranian",
	"OMR_displayName": "rial omanez",
	"TWD_displayName": "dolar nou din Taiwan",
	"PAB_displayName": "balboa panameză",
	"UAH_displayName": "hryvna ucraineană",
	"ETB_displayName": "birr etiopian",
	"PLN_displayName": "zlot polonez",
	"VEF_displayName": "bolivar venezuelean",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "real brazilian",
	"HKD_symbol": "HKD",
	"HKD_displayName": "dolar din Hong Kong",
	"THB_symbol": "THB",
	"NIO_displayName": "cordoba nicaraguană",
	"NPR_displayName": "rupie nepaleză",
	"PKR_displayName": "rupie pakistaneză",
	"TWD_symbol": "TWD",
	"GEL_displayName": "lari georgian",
	"AZN_displayName": "manat azer",
	"GBP_symbol": "GBP",
	"MYR_displayName": "ringgit malaiezian",
	"DKK_displayName": "coroană daneză",
	"THB_displayName": "baht thailandez",
	"BRL_symbol": "BRL",
	"JPY_displayName": "yen japonez",
	"KES_displayName": "șiling kenyan",
	"KHR_displayName": "riel cambodgian",
	"VND_symbol": "VND",
	"PYG_displayName": "guarani paraguayan",
	"LKR_displayName": "rupie din Sri Lanka",
	"BGN_displayName": "leva bulgărească",
	"BDT_displayName": "taka din Bangladesh",
	"MOP_displayName": "pataca din Macao",
	"HNL_displayName": "lempira honduriană",
	"RWF_displayName": "franc rwandez",
	"CHF_displayName": "franc elvețian",
	"CRC_displayName": "colón costarican",
	"INR_displayName": "rupie indiană",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "rand sud-african",
	"AUD_displayName": "dolar australian",
	"LAK_displayName": "kip din Laos",
	"MNT_displayName": "tugrik mongol",
	"RSD_displayName": "dinar sârbesc",
	"HRK_displayName": "kuna croată"
}
//end v1.x content
);