define("Sage/UI/nls/fr/BulkUpdateWidget", {
    "dlgBulkActionUpdate_Title": "Mise à jour d'action en bloc",
    "pageLoading_Caption": "Chargement des options de propriété...",
    "header_Caption": "Sélectionnez une propriété à mettre à jour.",
    "header_NoPropertiesEnabled": "L'entité ${0} est activée pour les mises à jour en bloc. Cependant, aucune propriété n'a été activée. Veuillez contacter votre administrateur système pour plus d'informations",
    "errorRequestPropertyOptions": "Une erreur s'est produite lors de la lecture des métadonnées pour l'entité ${0}. ${1}",
    "errorEntityNotSupported": "L'entité ${0} ne prend pas en charge les mises à jour en bloc",
    "update_Property_Caption": "Mettre à jour :",
    "addProperty_Tooltip": "Ajouter une propriété",
    "removeProperty_Tooltip": "Supprimer la propriété",
    "no_Caption": "Non",
    "yes_Caption": "Oui",
    "days_Caption": "jours",
    "moveOut_Caption": "Déplacer",
    "moveTo_Caption": "A",
    "moveDate_Backward": "En arrière",
    "moveDate_Forward": "Suivant",
    "update_To_Caption": "A :",
    "lookupHeaderText": "Rechercher ${0}",
    "lookupNameColText": "Nom",
    "lookupTitleColText": "Titre",
    "lookupDepartmentColText": "Service",
    "lookupRegionColText": "Région",
    "lookupTypeColText": "Type",
    "lookupDescriptionColText": "Description",
    "btnOK_Caption": "OK",
    "btnCancel_Caption": "Annuler",
    "errorUnspecifiedValue": "Veuillez indiquer une valeur avant de poursuivre ou supprimer la ligne non valide.",
    "errorRequestingJobMgr": "Une erreur s'est produite lors de la mise à jour : ${0}",
    "selectOption_Caption": "Sélectionnez une option...",
    "updateRecords_Caption": "Mise à jour des enregistrements sélectionnés",
    "chkScheduleJob_Caption": "Planifier cette mise à jour à une date/heure spécifiques.",
    "lookup_Caption": "Recherche",
    "job_Description": "Erreur(s) de mise à jour en bloc",
    "errorDuplicateValue": "Propriété déjà sélectionnée",
    "errorInvalidPropertyType": "Le type de propriété '${0}' n'est pas accepté pour les mises à jour en bloc.",
    "calculatedField": "Champ calculé",
    "standardId": "ID standard",
    "unknownPropertyType": "Inconnu"
});