define("Sage/UI/nls/fr/JobSchedulingWidget", {
    "lblCreateSchedule": "Créer une planification des tâches à exécuter",
    "lblEveryText": "Chaque",
    "lblOnText": "sur",
    "lblOnTheText": "le",
    "lblAtText": "à",
    "lblMinutesPastHour": "minutes après l'heure",
    "lblFromTimeText": "Exécuter du",
    "lblToTimeText": "au",
    "lblMinutesFrequency": "minutes",
    "lblHourlyFrequency": "heure(s)",
    "lblDailyFrequency": "jour",
    "lblWeekDayFrequency": "jour de la semaine",
    "lblWeeklyFrequency": "semaine",
    "lblMonthlyFrequency": "mois",
    "lblYearlyFrequency": "année",
    "lblSunday": "Dimanche",
    "lblMonday": "Lundi",
    "lblTuesday": "Mardi",
    "lblWednesday": "Mercredi",
    "lblThursday": "Jeudi",
    "lblFriday": "Vendredi",
    "lblSaturday": "Samedi",
    "lblFirstDay": "Premier",
    "lblSecondDay": "Deuxième",
    "lblThirdDay": "Troisième",
    "lblFourthDay": "Quatrième",
    "lblCronExpressionText": "Expression Cron",
    "txtInvalidScheduleTitle": "Planification non valide",
    "txtInvalidDatesMessage": "La date de fin doit être postérieure à la date de début. Veuillez la corriger avant de continuer.",
    "txtInvalidScheduleTime": "Les dates de début et de fin spécifiées ne permettront pas à cette planification de s'exécuter. Veuillez les corriger avant de continuer.",
    "txtInvalidStartDate": "Une date de début est requise. Veuillez en indiquer une avant de continuer.",
    "txtInvalidEndDate": "Une date de fin est requise. Veuillez en indiquer une avant de continuer."
});