define("Sage/UI/nls/fr/NotesHistoryList", {
    "typeText": "Type",
    "showDbChangesText": "Afficher les modifications de la base de données",
    "selectAllText": "Sélectionner tout",
    "dateText": "Date",
    "dateTimeText": "Date/Heure",
    "dateRangeText": "Plage de dates",
    "userText": "Utilisateur",
    "accountText": "Compte",
    "contactText": "Contact",
    "opportunityText": "Opportunité",
    "regardingText": "Objet",
    "notesText": "Notes",
    "resultText": "Résultat",
    "categoryText": "Catégorie",
    "sendEmailText": "Envoyer par E-mail",
    "sendToWordText": "Envoyer vers Word",
    "addNoteText": "Ajouter une note",
    "completeAnActivityText": "Terminer une activité",
    "helpText": "Aide",
    "pleaseSelectRecordsText": "Veuillez sélectionner un ou plusieurs enregistrements",
    "UnableToFindWordMsg": "Impossible de démarrer Microsoft Word. Vérifiez vos paramètres de sécurité.",
    "printedOnText": "Imprimé le",
    "errorNoData": "Il n'y a pas de notes ou d'historique à partager dans Ming.le.",
    "yesButtonText": "Oui",
    "noButtonText": "Non",
    "salesLogixPageTitle": "Infor CRM",
    "noRecordsSelectedProcessAll": "Vous n'avez sélectionné aucun enregistrement. Tous les enregistrement ${0} de note ou d'historique seront partagés dans Ming.le. Voulez-vous continuer ?",
    "errorShareMingle": "Une erreur s'est produite lors du partage d'un ou de plusieurs enregistrements de note ou d'historique dans Ming.le.",
    "sharedToMingle": "Partage des notes/de l'historique dans Ming.le.",
    "sharingToMingle": "Partage dans Ming.le",
    "shared": "Partagé",
    "pleaseWait": "Veuillez patienter...",
    "failedToPost": "Echec de la publication : ${0} ; erreur : ${1}",
    "addressText": "Adresse",
    "mainPhoneText": "Téléphone principal",
    "tollFreeText": "Numéro vert",
    "contactPhoneText": "Téléphone du contact"
});