define(
"dojo/cldr/nls/et/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbia peeso",
	"CZK_displayName": "Tšehhi kroon",
	"TND_displayName": "Tuneesia dinaar",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaica dollar",
	"PHP_displayName": "Filipiinide peeso",
	"ALL_displayName": "Albaania lekk",
	"USD_symbol": "$",
	"LBP_displayName": "Liibanoni nael",
	"VND_displayName": "Vietnami dong",
	"LYD_displayName": "Liibüa dinaar",
	"RON_displayName": "Rumeenia lei",
	"MKD_displayName": "Makedoonia denaar",
	"SEK_displayName": "Rootsi kroon",
	"CNY_displayName": "Hiina jüaan",
	"IDR_displayName": "Indoneesia ruupia",
	"ILS_displayName": "Iisraeli uus seekel",
	"YER_displayName": "Jeemeni riaal",
	"TJS_displayName": "Tadžikistani somoni",
	"TTD_displayName": "Trinidadi ja Tobago dollar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Türgi uus liir",
	"EUR_displayName": "euro",
	"AED_displayName": "Araabia Ühendemiraatide dirhem",
	"KZT_displayName": "Kasahstani tenge",
	"BHD_displayName": "Bahreini dinaar",
	"RUB_displayName": "Venemaa rubla",
	"NZD_displayName": "Uus-Meremaa dollar",
	"IQD_displayName": "Iraagi dinaar",
	"TMT_displayName": "Türkmenistani manat",
	"INR_symbol": "₹",
	"KGS_displayName": "Kõrgõzstani somm",
	"KWD_displayName": "Kuveidi dinaar",
	"AFN_displayName": "Afganistani afgaani",
	"ARS_displayName": "Argentina peeso",
	"MAD_displayName": "Maroko dirhem",
	"BAM_displayName": "Bosnia-Hertsegoviina mark",
	"BOB_displayName": "Bolivia boliviaano",
	"BND_displayName": "Brunei dollar",
	"SGD_displayName": "Singapuri dollar",
	"MVR_displayName": "Maldiivide ruupia",
	"MXN_displayName": "Mehhiko peeso",
	"DZD_displayName": "Alžeeria dinaar",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Jordaania dinaar",
	"PEN_displayName": "Peruu uus soll",
	"GTQ_displayName": "Guatemala ketsal",
	"BYR_displayName": "Valgevene rubla",
	"CAD_displayName": "Kanada dollar",
	"BZD_displayName": "Belize dollar",
	"CLP_displayName": "Tšiili peeso",
	"XOF_displayName": "Aafrika ühisfrank BCEAO",
	"NOK_displayName": "Norra kroon",
	"DOP_displayName": "Dominikaani peeso",
	"JPY_symbol": "¥",
	"KRW_displayName": "Lõuna-Korea vonn",
	"USD_displayName": "USA dollar",
	"UYU_displayName": "Uruguai peeso",
	"UZS_displayName": "Usbekistani somm",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Quatari riaal",
	"SAR_displayName": "Saudi-Araabia riaal",
	"SYP_displayName": "Süüria nael",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Egiptuse nael",
	"AMD_displayName": "Armeenia dramm",
	"GBP_displayName": "Suurbritannia naelsterling",
	"HUF_displayName": "Ungari forint",
	"CSD_displayName": "Serbia vana dinaar",
	"ISK_displayName": "Islandi kroon",
	"IRR_displayName": "Iraani riaal",
	"OMR_displayName": "Omaani riaal",
	"TWD_displayName": "Taiwani dollar",
	"PAB_displayName": "Panama balboa",
	"UAH_displayName": "Ukraina grivna",
	"ETB_displayName": "Etioopia birr",
	"PLN_displayName": "Poola zlott",
	"VEF_displayName": "Venezuela bolívar",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Brasiilia reaal",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hongkongi dollar",
	"NIO_displayName": "Nicaragua kuldkordoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepali ruupia",
	"PKR_displayName": "Pakistani ruupia",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Gruusia lari",
	"AZN_displayName": "Aserbaidžaani manat",
	"GBP_symbol": "£",
	"MYR_displayName": "Malaisia ringgit",
	"DKK_displayName": "Taani kroon",
	"THB_displayName": "Tai baat",
	"BRL_symbol": "R$",
	"JPY_displayName": "Jaapani jeen",
	"KES_displayName": "Kenya šilling",
	"KHR_displayName": "Kambodža riaal",
	"PYG_displayName": "Paraguai guaranii",
	"VND_symbol": "₫",
	"LKR_displayName": "Sri Lanka ruupia",
	"BGN_displayName": "Bulgaaria leev",
	"BDT_displayName": "Bangladeshi taka",
	"MOP_displayName": "Macao pataka",
	"HNL_displayName": "Hondurase lempiira",
	"RWF_displayName": "Rwanda frank",
	"CHF_displayName": "Šveitsi frank",
	"CRC_displayName": "Costa Rica colón",
	"INR_displayName": "India ruupia",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Lõuna-Aafrika rand",
	"AUD_displayName": "Austraalia dollar",
	"LAK_displayName": "Laose kiip",
	"MNT_displayName": "Mongoolia tugrik",
	"RSD_displayName": "Serbia dinaar",
	"HRK_displayName": "Horvaatia kuna"
}
//end v1.x content
);