define("Sage/QuickForms/Design/Editors/nls/zh-tw/ComboBoxAdvancedPropertyEditor", {
    "titleText": "進階",
    "appearanceText": "外觀",
    "behaviorText": "行為",
    "controlInfoText": "控制項資訊",
    "dataText": "資料",
    "itemGroupText": "項目",
    "controlIdText": "控制項 ID:",
    "controlIdTooltipText": "這個控制項的 ID。",
    "controlLabelPlacementText": "標籤位置:",
    "controlLabelPlacementTooltipText": "標籤與控制項的相對位置。",
    "controlTypeText": "控制項類型:",
    "controlTypeTooltipText": "Saleslogix 控制項類型。",
    "dataSourceText": "資料來源:",
    "dataSourceTooltipText": "這個控制項的資料來源，例如其他控制項或實體。",
    "defaultDataBindingText": "資料繫結:",
    "defaultDataBindingTooltipText": "這個控制項所使用的資料庫的資料欄位。",
    "enabledText": "已啟用:",
    "enabledTooltipText": "允許使用者與這個控制項互動。",
    "itemsText": "項目:",
    "itemsTooltipText": "使用者可以選取的值。",
    "textFieldText": "文字欄位:",
    "textFieldTooltipText": "用來填入清單項目的可見文字部分的資料來源欄位名稱。",
    "valueFieldText": "值欄位:",
    "valueFieldTooltipText": "用來填入清單項目的值部分的資料來源欄位名稱。",
    "visibleText": "可見:",
    "visibleTooltipText": "在表單上顯示或隱藏這個控制項。",
    "labelPlacementText": {
        "left": "靠左",
        "right": "靠右",
        "top": "靠上",
        "none": "無"
    },
    "hasItemsText": "設定",
    "noItemsText": "未設定"
});