define("Sage/UI/Forms/nls/it/FormFromSData", {
    "addText": "Aggiungi",
    "deleteText": "Elimina",
    "saveText": "Salva",
    "cancelText": "Annulla",
    "editText": "Modifica",
    "helpText": "Guida",
    "yesText": "Sì",
    "noText": "No",
    "okText": "OK",
    "newPickList": "Nuovo elenco di selezione",
    "items": "Elementi elenco di selezione",
    "number": "Ordine",
    "enterValue": "Immetti valore",
    "lblMore": "Altro",
    "picklistAlreadyExists": "Il ruolo Picklist '${0}' esiste già.",
    "messageOnSave": "Elenco di selezione ${0} salvato. Continuare ad aggiungere o a modificare le informazioni di campo.",
    "permissionsToView": "Non si hanno i diritti per visualizzare.",
    "required": "Voce obbligatoria",
    "allowMultiples": "Consenti selezioni multiple",
    "valueMustExist": "Il testo deve corrispondere a un elemento dell'elenco",
    "alphaSorted": "In ordine alfabetico",
    "noneEditable": "Gli utenti non possono modificare elementi"
});