define("Sage/MainView/EntityMgr/nls/fr/_BaseEntityDetailContent", {
    "FilterTabTitle": "Filtres",
    "MetricTabTitle": "Mesures",
    "PropertyTabTitle": "Champs",
    "CalcFieldTabTitle": "Champs calculés",
    "EntityTabTitle": "Entités",
    "RelationTabTitle": "Relations",
    "dialogTitleAddField": "Ajouter un champ à l'entité ${0}",
    "dialogTitleAddFilter": "Ajouter un filtre à l'entité ${0}",
    "dialogTitleAddMetric": "Ajouter une mesure à l'entité ${0}",
    "dialogTitleAddRelationship": "Ajouter une relation à l'entité ${0}",
    "editDialogTitle": "Modifier ${0} dans l'entité ${1}",
    "FilterDialogTitle": "Filtrer",
    "MetricDialogTitle": "Mesure",
    "PropertyDialogTitle": "Champ",
    "RelationDialogTitle": "Relation",
    "FilterGridColumnFilter": "Nom du filtre",
    "MetricGridColumnMetric": "Nom de la mesure",
    "FilterGridColumnDisplay": "Nom d'affichage",
    "FilterGridColumnProperty": "Champ",
    "FilterGridColumnType": "Mesure ou filtre",
    "FilterGridColumnIsMetric": "Dans le tableau de bord",
    "FilterGridColumnLastUpdated": "Dernière modification",
    "FilterGridColumnDetails": "Type",
    "FilterGridDetailsDistinctFilter": "Distinct",
    "FilterGridDetailsDateDiffMetricFilter": "Mesure de différence de date",
    "FilterGridDetailsRangeFilter": "Plage",
    "FilterGridDetailsMetricFilter": "Mesure",
    "FilterGridDetailsUserLookupFilter": "Rechercher un utilisateur",
    "FilterGridDetailsLookupFilter": "Recherche",
    "FilterGridDetailsCustom": "Personnalisé",
    "GridHelp": "Aide",
    "FilterGridAdd": "Ajouter un filtre",
    "FilterGridRemove": "Supprimer le filtre",
    "FilterGridEdit": "Modifier le filtre",
    "MetricGridAdd": "Ajouter une mesure",
    "MetricGridRemove": "Supprimer la mesure",
    "MetricGridEdit": "Modifier la mesure",
    "PropertyGridAdd": "Ajouter un champ",
    "PropertyGridRemove": "Supprimer le champ",
    "PropertyGridEdit": "Modifier le champ",
    "CalculatedGridAdd": "Ajouter un champ calculé",
    "CalculatedGridRemove": "Supprimer le champ calculé",
    "CalculatedGridEdit": "Modifier le champ calculé",
    "lblFilterName": "Nom du filtre",
    "lblDisplayName": "Nom d'affichage",
    "lblFilterDp": "Champs",
    "lblTypeDp": "Type",
    "lblCharacter": "Caractères",
    "lblTypeSpecificContentBox": "Zone de contenu spécifique de type",
    "lblSaveButton": "Enregistrer",
    "lblCancelButton": "Annuler",
    "lblOkButton": "OK",
    "lblWarning": "Sélectionnez un élément.",
    "confirmDeleteFmtTxt": "Voulez-vous vraiment supprimer ces ${0} éléments ?",
    "filtersFor": "Filtres pour",
    "metricsFor": "Mesures pour",
    "propertyFor": "Champs pour",
    "calculatedFor": "Champs calculés pour",
    "defaultRangeRowValue": "Saisissez une valeur",
    "customSql": "SQL personnalisé",
    "displayName": "Nom d'affichage",
    "lower": "Inférieur",
    "rangeId": "ID de la plage",
    "rangeName": "Nom de la plage",
    "upper": "Supérieur",
    "SUM": "Total (somme)",
    "Contains": "Contient",
    "StartsWith": "Commence par",
    "EndsWith": "Finit par",
    "LessThan": "Inférieur à",
    "GreaterThan": "Supérieur à",
    "LessThanEqual": "Inférieur ou égal à",
    "GreaterThanEqual": "Supérieur ou égal à",
    "Equal": "Est égal à",
    "NotEqual": "Différent de",
    "COUNT": "Nombre",
    "AVG": "Moyenne",
    "MIN": "Valeur minimale",
    "MAX": "Valeur maximale",
    "totalRecordCountLabel": "Nombre total d'enregistrements : ${0}",
    "propertyName": "Nom",
    "Description": "Description",
    "propertyType": "Type",
    "included": "Inclus",
    "calculatedFields": "Calculé(e)(s)",
    "generate": "Générer",
    "key": "Clé",
    "relationFor": "Relation pour",
    "childEntity": "Enfant",
    "childProperty": "Champ enfant",
    "parentEntity": "Parent",
    "parentProperty": "Champ parent",
    "editable": "Modifiable",
    "cardinality": "Cardinalité",
    "relationship": "Relation",
    "parentImport": "Importation parent",
    "parentMatch": "Correspondance parent",
    "parentAudit": "Audit parent",
    "parentIncluded": "Inclus parent",
    "childImport": "Importation enfant",
    "childMatch": "Correspondance enfant",
    "childAudit": "Audit enfant",
    "childIncluded": "Enfant inclus",
    "text": "Texte",
    "memo": "Mémo",
    "unicodeText": "Texte unicode",
    "unicodeMemo": "Mémo unicode",
    "integer": "Entier",
    "double": "Double",
    "single": "Unique",
    "decimal": "Décimal",
    "short": "Court",
    "standardId": "ID standard",
    "trueFalse": "Vrai / Faux",
    "yesNo": "Oui/Non",
    "boolean": "Booléen",
    "dateTime": "Date/Heure",
    "email": "E-mail",
    "phone": "Téléphone",
    "pickList": "Liste de sélection",
    "owner": "Propriétaire",
    "lookup": "Recherche",
    "dependencyLookup": "Recherche de dépendance",
    "char": "Caractère",
    "enum_": "Enum",
    "guid": "guid",
    "byte": "Octet",
    "binary": "Binaire",
    "url": "Url",
    "string": "Chaîne",
    "number": "Nombre",
    "notUniqueFor": "N'est pas unique pour",
    "lblPluralName": "Afficher le nom au pluriel",
    "lblTitle": "Titre",
    "IsExtension": "Est une extension",
    "AdvOptions": "Options avancées",
    "lblImport": "Importer",
    "lblMatch": "Faire correspondre",
    "lblBulkUpdate": "Mise à jour en bloc",
    "lblAudited": "Audité",
    "lblPut": "Soumettre",
    "lblPost": "Publication",
    "lblDelete": "Supprimer",
    "lblHistory": "Effectuer le suivi de l'historique jusqu'à",
    "metricNotEditable": "Cette mesure n'est pas modifiable."
});