define("Sage/Reporting/nls/ru/Enumerations", {
    "txtGroup": "Группа",
    "txtDateRange": "Диапазон дат",
    "txtUser": "Пользователь",
    "txtQuery": "Запрос",
    "txtIsGreaterThan": "Больше",
    "txtIsLessThan": "Меньше",
    "txtIsInTheRange": "В диапазоне",
    "txtIsAfter": "После",
    "txtIsBefore": "До",
    "txtContains": "Содержит",
    "txtStartsWith": "Начинается с",
    "txtEndsWith": "Заканчивается на",
    "txtIs": "Это",
    "txtIsNot": "Не",
    "txtOnDemand": "По запросу",
    "txtScheduled": "Запланировано",
    "txtCrystalReport": "Отчет Crystal",
    "txtExportToFileReportType": "Экспорт в файл",
    "txtUnknownReportType": "Неизвестно",
    "txtNoFormat": "Без формата",
    "txtPdf": "PDF",
    "txtExcel": "Excel",
    "txtExcelDataOnly": "Данные Excel",
    "txtCsv": "CSV",
    "txtWord": "Word",
    "txtXml": "XML"
});