define("Sage/MainView/nls/ru/ActivityManager", {
    "titleFmtString": "${0}",
    "tabDisplayNameActivity": "Действия",
    "tabDisplayNameLit": "Литература",
    "tabDisplayNameEvent": "События",
    "tabDisplayNameConfirm": "Подтверждения",
    "activityColNameComplete": "Завершить",
    "activityColNameAttachment": "Вложение",
    "activityColNameRecurring": "Повторение",
    "activityColNameAlarm": "Оповещение",
    "activityColNameType": "ActivityType",
    "activityColNameStartDate": "StartDate",
    "activityColNameDuration": "Длительность",
    "activityColNameContact": "Контакт",
    "activityColNameLead": "Заинтересованное лицо",
    "activityColNameAccount": "Клиент",
    "activityColNameRegarding": "Тема",
    "activityColNamePriority": "Приоритет",
    "activityColNameUserId": "организатор",
    "activityTypePhone": "Телефон",
    "activityTypeCall": "Вызов",
    "activityTypeMeeting": "Встреча",
    "activityTypePersonal": "Личное"
});