define("Sage/MainView/nls/ru/FormMgrDetailPane", {
    "layoutTabText": "Макет",
    "propertiesTabText": "Свойства",
    "toolsTabText": "Панель инструментов",
    "usageTabText": "Использование страницами",
    "columnText": "Столбец",
    "rowText": "Строка",
    "fieldNameText": "Имя поля",
    "displayNameText": "Отображаемое имя",
    "visibleText": "Видимый",
    "rowspanText": "Строка управления",
    "colspanText": "Расстояние между столбцами",
    "controlTypeText": "Тип элемента управления",
    "buttonAlignmentText": "Выравнивание кнопки:",
    "rightText": "По правому краю",
    "centerText": "По центру",
    "leftText": "По левому краю",
    "helpText": "Справка",
    "positionText": "Позиция",
    "portalText": "Портал",
    "pageText": "Страница",
    "entityText": "Сущность",
    "workspaceText": "Целевая рабочая область",
    "modeText": "Режим показа",
    "rolesText": "Роли доступа"
});