define("Sage/MainView/GroupMgr/templates/nls/fr/ReleasesDetailSummary", {
    "txtGroupFamily_Caption": "Famille :",
    "txtGroupName_Caption": "Nom :",
    "txtGroupDisplayName_Caption": "Nom d'affichage :",
    "txtGroupDescription_Caption": "Description :",
    "txtGroupId_Caption": "ID :",
    "txtGroupMainTable_Caption": "Table principale :",
    "txtGroupEntityName_Caption": "Nom de l'entité :",
    "txtGroupCreateDate_Caption": "Date de création :",
    "txtGroupCreateUser_Caption": "Créé par :",
    "txtGroupModifyDate_Caption": "Date de modification :",
    "txtGroupModifyUser_Caption": "Modifié par :",
    "txtGroupInstallationDate_Caption": "Date d'installation :",
    "txtGroupShared_Caption": "Partagé :",
    "txtGroupSharedDate_Caption": "Date de partage :",
    "txtGroupOwner_Caption": "Propriétaire :",
    "txtGroupUserId_Caption": "ID utilisateur :",
    "txtGroupAdhoc_Caption": "Ad hoc :",
    "txtGroupHidden_Caption": "Masqué :",
    "txtGroupAuthor_Caption": "Auteur :",
    "txtGroupCompany_Caption": "Société :",
    "txtGroupCompanyVersion_Caption": "Version de la société :",
    "txtGroupDev_Caption": "Dev :",
    "txtGroupDataCode_Caption": "Code de données :",
    "txtGroupType_Caption": "Type de groupe :",
    "txtGroupBasedOn_Caption": "Basé sur ID du groupe :",
    "txtGroupReleasedToType_Caption": "Partagé par Type :",
    "txtGroupReleasedTo_Caption": "Partagé par Nom :",
    "txtGroupReleasedToTitle_Caption": "Partagé par Titre :",
    "txtGroupReleasedToUserType_Caption": "Partagé avec type d'utilisateur :"
});