define(
"dojo/cldr/nls/lo/currency", //begin v1.x content
{
	"COP_displayName": "ເປໂຊໂຄລຳເບຍ",
	"CZK_displayName": "ໂຄຣູນາ ສາທາລະນະລັດເຊັກ",
	"TND_displayName": "ດີນາ ຕູນີເຊຍ",
	"LAK_symbol": "₭",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ດອນລາ ຈາເມກາ",
	"PHP_displayName": "ເປໂຊ ຟີລິປິນ",
	"ALL_displayName": "ແລັກ ອານບາເນຍ",
	"USD_symbol": "US$",
	"LBP_displayName": "ປອນ ເລບານອນ",
	"VND_displayName": "ດົງ ຫວຽດນາມ",
	"LYD_displayName": "ດີນາ ລິເບຍ",
	"RON_displayName": "ເລອູ ໂຣມາເນຍ",
	"MKD_displayName": "ເດນາ ມາຊິໂດເນຍ",
	"SEK_displayName": "ໂຄຣນາ ສະວີເດັນ",
	"CNY_displayName": "ຢວນ ຈີນ",
	"IDR_displayName": "ຣູປີ ອິນໂດເນເຊຍ",
	"ILS_displayName": "ນິວເຊເກນ ອີສະລາແອນ",
	"YER_displayName": "ຣຽວ ເຢເມນ",
	"TJS_displayName": "ໂຊໂມນີ ທາຈິກິສຖານ",
	"TTD_displayName": "ດອນລາທຣິນິແດດ ແລະ ໂທເບໂກ",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "ລິຣາ ເທີກີ",
	"EUR_displayName": "ເອີໂຣ",
	"AED_displayName": "ດີແຮມ ສະຫະລັດອາຣັບ ເອມີເຣດ",
	"KZT_displayName": "ເຕັງເຈ ກາຊັກສະຖານ",
	"BHD_displayName": "ດີນາ ບາເຣນ",
	"RUB_displayName": "ຣູໂລ ຣັດເຊຍ",
	"NZD_displayName": "ໂດລາ ນີວຊີແລນ",
	"IQD_displayName": "ດີນາ ອີຣັກ",
	"TMT_displayName": "ເມນັດ ຕວກເມນິດສະຖານ",
	"ZWL_displayName": "ດອນລາ ຊິມບັບເວ (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "ໂຊມ ຄຣີກິສະຖານ",
	"KWD_displayName": "ດີນາ ຄູເວດ",
	"AFN_displayName": "ອັບການິ ອັບກັນນິສະຖານ",
	"ARS_displayName": "ເປໂຊ ອາເຈນຕີນາ",
	"MAD_displayName": "ດີຮາມ ໂມລອກໂກ",
	"BAM_displayName": "ມາກບອສເນຍ ເຮເຊໂກເວນາ",
	"BOB_displayName": "ໂບລິເວຍໂນ ໂລລິເວຍ",
	"BND_displayName": "ໂດລາ ບຣູໄນ",
	"SGD_displayName": "ໂດລາ ສິງກະໂປ",
	"MVR_displayName": "ຣູຟີຢາ ມາດີເວຍ",
	"MXN_displayName": "ເມັກຊິກັນ ເປໂຊ",
	"DZD_displayName": "ດີນາ ອາຍຈີເຣຍ",
	"MXN_symbol": "MX$",
	"JOD_displayName": "ດີນາ ຈໍແດນ",
	"PEN_displayName": "ນູໂວຊໍ ເປຣູ",
	"GTQ_displayName": "ກົວເຕມາລານ ເຄັດຊອນ",
	"BYR_displayName": "ຣູໂບ ເບຣາຣູສ",
	"CAD_displayName": "ໂດລ່າຄານາດາ",
	"BZD_displayName": "ໂດລ່າ ເບວລິຊ",
	"CLP_displayName": "ເປໂຊ ຊິລີ",
	"XOF_displayName": "ຟັງເຊຟານ ອາຟຣິກາຕາເວັນຕົກ",
	"NOK_displayName": "ໂຄຣນ ນອກເວ",
	"DOP_displayName": "ເປໂຊໂດມິນິການ",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "ວອນ ເກົາຫຼີໃຕ້",
	"USD_displayName": "ໂດລ່າ ສະຫະລັດຯ",
	"UYU_displayName": "ເປໂຊ ອູຣູກວາຍ",
	"UZS_displayName": "ໂຊມ ອຸສເບກິສຖາານ",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ຣຽວ ກາຕາ",
	"SAR_displayName": "ຣີຢອນ ຊາອຸດິດອາຣາບີ",
	"SYP_displayName": "ປອນ ຊິເຣຍ",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "ປອນ ອີຢິບ",
	"AMD_displayName": "ດຣມອາເມເນຍ",
	"GBP_displayName": "ປອນສະເຕີຣິງ (ອັງກິດ)",
	"HUF_displayName": "ຟໍຣິນ ຮົງກາຣີ",
	"CSD_displayName": "ດີນາ ເຊີເບຍ (2002–2006)",
	"ISK_displayName": "ໂຄຣນາ ໄອສແລນ",
	"IRR_displayName": "ຣີວ ອີຣ່ານ",
	"OMR_displayName": "ຣຽວ ໂອມານ",
	"TWD_displayName": "ໂດລາ ໄຕຫວັນ",
	"PAB_displayName": "ພານາມານຽນ ບອນບົວ",
	"UAH_displayName": "ຮາຣິບເນຍ ຢູເຄຣນ",
	"ETB_displayName": "ເບີ ເອທີໂອເປຍ",
	"PLN_displayName": "ຊລໍຕີ ໂປແລນ",
	"VEF_displayName": "ໂບລິວາ ເວເນຊູເອລາ",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ຣຽນ ບຣາຊິນ",
	"HKD_symbol": "HK$",
	"HKD_displayName": "ດອນລາ ຮົງກົງ",
	"NIO_displayName": "ນິກາຣາກວນ ໂຄໂດບາ",
	"THB_symbol": "฿",
	"NPR_displayName": "ຣູປີ ເນປານ",
	"PKR_displayName": "ຣູປີ ປາກີສະຖານ",
	"TWD_symbol": "NT$",
	"GEL_displayName": "ລາຣິ ຈໍເຈຍ",
	"AZN_displayName": "ມານັດ ອາຊັກບາຍຊານ",
	"GBP_symbol": "£",
	"MYR_displayName": "ຣິງກິດ ມາເລເຂຍ",
	"DKK_displayName": "ໂຄຣນ ເດັນມາກ",
	"THB_displayName": "ບາດ ໄທ",
	"BRL_symbol": "R$",
	"JPY_displayName": "ເຢນ ຍີ່ປຸ່ນ",
	"KES_displayName": "ຊິລລິງ ເຄນຢາ",
	"KHR_displayName": "ຫຼຽນກຳປູເຈ້ຍ",
	"PYG_displayName": "ກວາຣານີ ປາຣາກວາຍ",
	"VND_symbol": "₫",
	"LKR_displayName": "ຣູປີ ສີຣັງກາ",
	"BGN_displayName": "ເລບ ບັງແກເຣຍ",
	"BDT_displayName": "ຕາກາ ບັງກາເດດ",
	"HNL_displayName": "ຮອນດູແຣນ ເລມພິຣາ",
	"MOP_displayName": "ປາຕາກາ ມາເກົາ",
	"RWF_displayName": "ຟຣັງ ວັນດາ",
	"CHF_displayName": "ຟຣັງ ສະວິດເຊີແລນ",
	"CRC_displayName": "ໂຄສຕາ ຣິກັນ ໂຄລອນ",
	"INR_displayName": "ຣູປີ ອິນເດຍ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "ແຣນ ອາຟຣິກາໃຕ້",
	"AUD_displayName": "ໂດລາ ອອດສະເຕເລຍ",
	"LAK_displayName": "ກີບ ລາວ",
	"MNT_displayName": "ຕຸກຣີ ມົງໂກເລຍ",
	"RSD_displayName": "ດີນາ ເຊີເບຍ",
	"HRK_displayName": "ຄູນາ ໂກຣເອເຊຍ"
}
//end v1.x content
);