define(
"dojo/cldr/nls/nl/currency", //begin v1.x content
{
	"COP_displayName": "Colombiaanse peso",
	"CZK_displayName": "Tsjechische kroon",
	"TND_displayName": "Tunesische dinar",
	"EUR_symbol": "€",
	"CAD_symbol": "C$",
	"JMD_displayName": "Jamaicaanse dollar",
	"PHP_displayName": "Filipijnse peso",
	"ALL_displayName": "Albanese lek",
	"USD_symbol": "US$",
	"LBP_displayName": "Libanees pond",
	"VND_displayName": "Vietnamese dong",
	"LYD_displayName": "Libische dinar",
	"RON_displayName": "Roemeense leu",
	"MKD_displayName": "Macedonische denar",
	"SEK_displayName": "Zweedse kroon",
	"CNY_displayName": "Chinese yuan renminbi",
	"IDR_displayName": "Indonesische roepia",
	"ILS_displayName": "Israëlische nieuwe shekel",
	"YER_displayName": "Jemenitische rial",
	"TJS_displayName": "Tadzjikistaanse somoni",
	"TTD_displayName": "Trinidad en Tobago-dollar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Turkse lira",
	"EUR_displayName": "Euro",
	"AED_displayName": "Verenigde Arabische Emiraten-dirham",
	"KZT_displayName": "Kazachstaanse tenge",
	"BHD_displayName": "Bahreinse dinar",
	"RUB_displayName": "Russische roebel",
	"NZD_displayName": "Nieuw-Zeelandse dollar",
	"IQD_displayName": "Iraakse dinar",
	"TMT_displayName": "Turkmeense manat",
	"ZWL_displayName": "Zimbabwaanse dollar (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgizische som",
	"KWD_displayName": "Koeweitse dinar",
	"AFN_displayName": "Afghaanse afghani",
	"ARS_displayName": "Argentijnse peso",
	"MAD_displayName": "Marokkaanse dirham",
	"BAM_displayName": "Bosnische convertibele mark",
	"BOB_displayName": "Boliviaanse boliviano",
	"BND_displayName": "Bruneise dollar",
	"SGD_displayName": "Singaporese dollar",
	"MVR_displayName": "Maldivische rufiyaa",
	"MXN_displayName": "Mexicaanse peso",
	"DZD_displayName": "Algerijnse dinar",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Jordaanse dinar",
	"PEN_displayName": "Peruaanse nieuwe sol",
	"GTQ_displayName": "Guatemalteekse quetzal",
	"BYR_displayName": "Wit-Russische roebel",
	"CAD_displayName": "Canadese dollar",
	"BZD_displayName": "Belizaanse dollar",
	"CLP_displayName": "Chileense peso",
	"XOF_displayName": "CFA-franc BCEAO",
	"NOK_displayName": "Noorse kroon",
	"DOP_displayName": "Dominicaanse peso",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Zuid-Koreaanse won",
	"USD_displayName": "Amerikaanse dollar",
	"UYU_displayName": "Uruguayaanse peso",
	"UZS_displayName": "Oezbekistaanse sum",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Qatarese rial",
	"SAR_displayName": "Saoedi-Arabische riyal",
	"SYP_displayName": "Syrisch pond",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Egyptisch pond",
	"AMD_displayName": "Armeense dram",
	"GBP_displayName": "Brits pond sterling",
	"HUF_displayName": "Hongaarse forint",
	"CSD_displayName": "Oude Servische dinar",
	"ISK_displayName": "IJslandse kroon",
	"IRR_displayName": "Iraanse rial",
	"OMR_displayName": "Omaanse rial",
	"TWD_displayName": "Nieuwe Taiwanese dollar",
	"PAB_displayName": "Panamese balboa",
	"UAH_displayName": "Oekraïense hryvnia",
	"ETB_displayName": "Ethiopische birr",
	"PLN_displayName": "Poolse zloty",
	"VEF_displayName": "Venezolaanse bolivar",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Braziliaanse real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hongkongse dollar",
	"NIO_displayName": "Nicaraguaanse córdoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepalese roepie",
	"PKR_displayName": "Pakistaanse roepie",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Georgische lari",
	"AZN_displayName": "Azerbeidzjaanse manat",
	"GBP_symbol": "£",
	"MYR_displayName": "Maleisische ringgit",
	"DKK_displayName": "Deense kroon",
	"THB_displayName": "Thaise baht",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japanse yen",
	"KES_displayName": "Keniaanse shilling",
	"KHR_displayName": "Cambodjaanse riel",
	"PYG_displayName": "Paraguayaanse guarani",
	"VND_symbol": "₫",
	"LKR_displayName": "Sri Lankaanse roepie",
	"BGN_displayName": "Bulgaarse lev",
	"BDT_displayName": "Bengalese taka",
	"MOP_displayName": "Macause pataca",
	"HNL_displayName": "Hondurese lempira",
	"RWF_displayName": "Rwandese frank",
	"CHF_displayName": "Zwitserse frank",
	"CRC_displayName": "Costaricaanse colón",
	"INR_displayName": "Indiase roepie",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Zuid-Afrikaanse rand",
	"AUD_displayName": "Australische dollar",
	"LAK_displayName": "Laotiaanse kip",
	"MNT_displayName": "Mongoolse tugrik",
	"RSD_displayName": "Servische dinar",
	"HRK_displayName": "Kroatische kuna"
}
//end v1.x content
);