define("Sage/UI/Controls/nls/en/PropertyStore", {
    // data types
    "text": 'Text',
    memo: 'Memo',
    unicodeText: 'Unicode Text',
    unicodeMemo: 'Unicode Memo',
    "integer": 'Integer',
    "double": 'Double',
    single: 'Single',
    "decimal": 'Decimal',
    "short": 'Short',
    standardId: 'Standard Id',
    trueFalse: 'True/False',
    yesNo: 'Yes/No',
    "boolean": 'Boolean',
    dateTime: 'Date/Time',
    email: 'Email',
    phone: 'Phone',
    pickList: 'Pick List',
    owner: 'Owner',
    lookup: 'Lookup',
    dependencyLookup: 'Dependency Lookup',
    "char": 'Char',
    enum_: 'Enum',
    "guid": 'Guid',
    "byte": 'Byte',
    "binary": 'Binary',
    "url": 'Url',
    "string": 'String',
    "number": 'Number',
    id: 'Id',
    code: 'Code',
    name: 'Name',
    value: 'Value',
    "native": 'Native',
    calc: 'Calculated Field',
    calcSF: 'Calculated String',
    calcNF: 'Calculated Number'

});
