define(
"dojo/cldr/nls/br/currency", //begin v1.x content
{
	"COP_displayName": "peso Kolombia",
	"CZK_displayName": "kurunenn Tchek",
	"TND_displayName": "dinar Tunizia",
	"PHP_displayName": "peso Filipinez",
	"JMD_displayName": "dollar Jamaika",
	"ALL_displayName": "lek Albania",
	"LBP_displayName": "lur Liban",
	"VND_displayName": "dong Viêt Nam",
	"LYD_displayName": "dinar Libia",
	"RON_displayName": "leu Roumania",
	"MKD_displayName": "denar Makedonia",
	"SEK_displayName": "kurunenn Sveden",
	"CNY_displayName": "yuan Sina",
	"IDR_displayName": "roupi Indonezia",
	"ILS_displayName": "shekel nevez Israel",
	"YER_displayName": "rial Yemen",
	"TJS_displayName": "somoni Tadjikistan",
	"TTD_displayName": "dollar Trinidad ha Tobago",
	"TRY_displayName": "lur Turkia",
	"EUR_displayName": "euro",
	"AED_displayName": "dirham EAU",
	"KZT_displayName": "tenge Kazakstan",
	"BHD_displayName": "dinar Bahrein",
	"RUB_displayName": "roubl Rusia",
	"NZD_displayName": "dollar Zeland-Nevez",
	"IQD_displayName": "dinar Iraq",
	"TMT_displayName": "manat Turkmenistan",
	"ZWL_displayName": "dollar Zimbabwe (2009)",
	"KGS_displayName": "som Kyrgyzstan",
	"KWD_displayName": "dinar Koweit",
	"AFN_displayName": "afghani Afghanistan",
	"ARS_displayName": "peso Arcʼhantina",
	"MAD_displayName": "dirham Maroko",
	"BAM_displayName": "mark kemmadus Bosnia ha Herzegovina",
	"BOB_displayName": "boliviano Bolivia",
	"BND_displayName": "dollar Brunei",
	"SGD_displayName": "dollar Singapour",
	"MVR_displayName": "rufiyaa Maldivez",
	"MXN_displayName": "peso Mecʼhiko",
	"DZD_displayName": "dinar Aljeria",
	"JOD_displayName": "dinar Jordania",
	"PEN_displayName": "nuevo sol Perou",
	"GTQ_displayName": "quetzal Guatemala",
	"BYR_displayName": "roubl Belarus",
	"CAD_displayName": "dollar Kanada",
	"BZD_displayName": "dollar Belize",
	"CLP_displayName": "peso Chile",
	"XOF_displayName": "lur CFA BCEAO",
	"NOK_displayName": "kurunenn Norvegia",
	"DOP_displayName": "peso Dominikan",
	"KRW_displayName": "won Korea ar Su",
	"USD_displayName": "dollar SU",
	"UYU_displayName": "peso Uruguay",
	"UZS_displayName": "som Ouzbekistan",
	"QAR_displayName": "rial Qatar",
	"SAR_displayName": "riyal Arabia Saoudat",
	"SYP_displayName": "lur Siria",
	"EGP_displayName": "lur Egipt",
	"AMD_displayName": "dram Armenia",
	"GBP_displayName": "lur sterling Breizh-Veur",
	"HUF_displayName": "forint Hungaria",
	"ISK_displayName": "kurunenn Island",
	"IRR_displayName": "rial Iran",
	"OMR_displayName": "rial Oman",
	"TWD_displayName": "dollar nevez Taiwan",
	"PAB_displayName": "balboa Panamá",
	"UAH_displayName": "hryvnia Ukraina",
	"ETB_displayName": "birr Etiopia",
	"PLN_displayName": "zloty Polonia",
	"VEF_displayName": "bolivar Venezuela",
	"BRL_displayName": "real Brazil",
	"HKD_displayName": "dollar Hong Kong",
	"NIO_displayName": "cordoba Nicaragua",
	"NPR_displayName": "roupi Nepal",
	"PKR_displayName": "roupi Pakistan",
	"GEL_displayName": "lari Jorjia",
	"AZN_displayName": "manat Azerbaidjan",
	"MYR_displayName": "ringgit Malaysia",
	"DKK_displayName": "kurunenn Danmark",
	"THB_displayName": "baht Thailand",
	"JPY_displayName": "yen Japan",
	"KES_displayName": "shilling Kenya",
	"KHR_displayName": "riel Kambodja",
	"PYG_displayName": "guarani Paraguay",
	"LKR_displayName": "roupi Sri Lanka",
	"BGN_displayName": "lev Bulgaria",
	"BDT_displayName": "taka Bangladesh",
	"MOP_displayName": "pataca Macau",
	"HNL_displayName": "lempira Honduras",
	"RWF_displayName": "lur Rwanda",
	"CHF_displayName": "lur Suis",
	"CRC_displayName": "colón Costa Rica",
	"INR_displayName": "roupi India",
	"ZAR_displayName": "rand Suafrika",
	"AUD_displayName": "dollar Aostralia",
	"LAK_displayName": "kip Laos",
	"MNT_displayName": "tugrik Mongolia",
	"RSD_displayName": "dinar Serbia",
	"HRK_displayName": "kuna Kroatia"
}
//end v1.x content
);