define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/zh-cn/AddEditDialog", {
    "dialogTitleAddField": "向 ${0} 实体添加字段",
    "dialogTitleAddFilter": "向 ${0} 实体添加筛选器",
    "dialogTitleAddMetric": "向 ${0} 实体添加度量",
    "dialogTitleAddRelationship": "向 ${0} 实体添加关系",
    "editDialogTitle": "在 ${1} 实体中编辑 ${0}",
    "lblFilter": "筛选器",
    "lblMetric": "度量",
    "lblFilters": "筛选器",
    "lblMetrics": "度量",
    "lblDistinct": "不相同",
    "lblRange": "范围",
    "lblUserLookup": "用户查找",
    "lblAdd": "添加",
    "lblEdit": "编辑",
    "lblRemove": "移除",
    "lblHelp": "帮助",
    "lblFilterName": "筛选器名称",
    "lblMetricName": "度量名称",
    "lblDisplayName": "显示名称",
    "lblName": "名称",
    "lblDisplay": "显示",
    "lblCalculated": "已计算",
    "lblCalculation": "计算",
    "lblDescription": "描述",
    "lblFieldsName": "字段名称",
    "lblCalculatedFieldsName": "已计算字段名称",
    "lblFilterDp": "字段",
    "lblTypeDp": "类型",
    "lblCharacter": "字符",
    "lblFrom": "从",
    "lblTo": "至",
    "lblOperators": "运算符",
    "lblAggregation": "聚合",
    "lblTypeSpecificContentBox": "特定于类型的内容框",
    "lblSaveButton": "确定",
    "lblCancelButton": "取消",
    "DateDiffCheckerValue": "日期差异度量",
    "InvalidFilterName": "筛选器名称无效",
    "InvalidRangeName": "范围名称无效",
    "RequiredFilterName": "必须提供筛选器名称",
    "RequiredRangeName": "必须提供范围名称",
    "FieldMustBeANumber": "字符字段必须是整数",
    "SelectAnItem": "请选择一个项目",
    "ItemRequired": "必需提供项目",
    "ItemInvalid": "项目无效",
    "LowerMustBeLessThanUpper": "下限值必须小于上限值。",
    "defaultRangeRowValue": "输入值",
    "totalRecordCountLabel": "记录总数: ${0}",
    "lblNew": "新建",
    "lblExisting": "现有",
    "lblExistingCalc": "现有已计算字段",
    "validNameMsg": "有效条目以大写字母开头且<br>可以包含字母数字值和下划线。",
    "propertyName": "名称",
    "displayName": "显示",
    "dataTypeId": "类型",
    "dataTypeData": "类型属性",
    "length": "长度",
    "scale": "缩放",
    "precision": "精度",
    "isIncluded": "已包括",
    "isReadOnly": "只读",
    "displayCategory": "显示类别",
    "sdata": "Sdata",
    "bulkAction": "批量操作",
    "canBulkUpdate": "可批量更新",
    "canImport": "导入",
    "canMatch": "匹配",
    "generate": "生成",
    "audited": "已审核",
    "notUniqueFor": "对以下内容不唯一",
    "notUnique": "不唯一",
    "nlsCode": "NLS 代码",
    "nlsName": "NLS 名称",
    "showTranslations": "显示翻译",
    "hideTranslations": "隐藏翻译",
    "standardIds": "标准 ID",
    "others": "其他",
    "SelectField": "请选择字段!",
    "SelectOneField": "请仅选择一个字段!",
    "parent": "父级实体和联接字段",
    "child": "子实体和联接字段",
    "cardinality": "关系",
    "cascade": "层叠",
    "includeParent": "在子级实体中包含父级关系属性",
    "includeChild": "在父级实体中包含子级关系属性",
    "existingRelaton": "此关系已存在!"
});