define("Sage/Groups/nls/de/GroupManager", {
    "ConfirmDeleteMessage": "Möchten Sie die aktuelle Gruppe wirklich löschen?",
    "ConfirmDeleteFmtMessage": "Möchten Sie diese Gruppe wirklich löschen: ${0}",
    "InvalidSortStringMessage": "Fehler: Ungültige Zeichenfolge für Sortierung - ",
    "InvalidConditionStringMessage": "Fehler: Ungültige Zeichenfolge für Bedingung - ",
    "InvalidLayoutConditionStringMessage": "Fehler: Ungültige Zeichenfolge für Layout - ",
    "noneSelectedTitle": "Keine Datensätze ausgewählt",
    "noneSelectedPromptFmt": "Da keine Datensätze ausgewählt wurden, wird die gesamte Gruppe aus ${0} Datensätzen hinzugefügt. Möchten Sie fortfahren?",
    "noneSelectedRemovePromptFmt": "Da keine Datensätze ausgewählt wurden, wird die gesamte Gruppe aus ${0} Datensätzen entfernt. Möchten Sie fortfahren?",
    "noRecordsInGroup": "In dieser Gruppe gibt es keine auszuwählenden Datensätze.",
    "newGroupTitle": "Datensätze zu neuer Gruppe hinzufügen",
    "newGroupNamePrompt": "Ausgewählte Datensätze (Anzahl: ${0}) werden zu dieser neuen Gruppe hinzugefügt.<br><br>Gruppenname:<br>${1}",
    "newGroupRePrompt": "&nbsp;&nbsp;<i>Geben Sie einen Gruppennamen ein.</i>",
    "invalidCharMsg": "Name darf folgende Zeichen nicht enthalten: / \\ : * ? \" <> | und '",
    "groupNameText": "Gruppenname:",
    "saveLookupDlgTitle": "Suchergebnisse als neue Gruppe speichern",
    "yesCaption": "Ja",
    "noCaption": "Nein",
    "cancelCaption": "Abbrechen",
    "okCaption": "OK",
    "LOCALSTORE_NAMESPACE": "SageGroups",
    "exportToExcel": "Diese Methode ist veraltet, siehe Sage.TaskPane.CommonTasksTasklet.exportToExcel.",
    "createAdHocGroupJob_Description": "Gruppe: ${0}",
    "createAdHocGroupJob_Title": "Gruppe wird erstellt",
    "createAdHocGroupJobError": "Beim Erstellen der Gruppe ist leider ein Fehler aufgetreten: ${0}",
    "createAdHocGroupJobProcessingJobMsg": "Sie können warten, bis der Vorgang abgeschlossen ist, oder Sie können diese Meldung schließen. Sie werden benachrichtigt, wenn die Gruppe vollständig ist."
});