define("Sage/TaskPane/nls/zh-tw/_BaseTaskPaneTasklet", {
    "selectRecordsTitle": "無效的選取項目",
    "selectRecords": "請選取一筆記錄，才能繼續進行。",
    "selectSingleRecord": "請選取一筆記錄，才能繼續進行。",
    "noRecordsSelectedProcessAll": "未選取記錄。將會處理整個群組的記錄(如果已設定限制，則直到達到限制為止)。要繼續嗎?",
    "invalidSelectionTitle": "無效的選取項目",
    "errorSelectionInfo": "擷取選取記錄的相關資訊時發生錯誤。",
    "errorNoData": "沒有可用的資料。",
    "yesButtonText": "是",
    "noButtonText": "否",
    "salesLogixPageTitle": "Infor CRM",
    "okButtonText": "確定",
    "cancelButtonText": "取消",
    "confirmBulkDeleteJob": "您確定要刪除選取的記錄?",
    "deleteSelectedRecords": "刪除 ${0}",
    "deleteJobError": "抱歉，刪除 ${0} 工作時發生錯誤: ${1}",
    "deleteBulkJobTitle": "刪除 ${0}",
    "promoteTitle": "升級",
    "getOrderTotalTitle": "取得訂單總計",
    "integrationNotEnabled": "Back Office Extension 未啟用",
    "error_PricingRequest": "要求定價服務時發生錯誤：${0}"
});