define("Sage/MainView/CopyUserProfile/nls/fr/CopyUserProfile", {
    "dlg_Title": "Copier le profil",
    "dlg_Instructions": "Sélectionnez un profil utilisateur ou un modèle à copier vers d'autres utilisateurs. Le fait de copier le profil va écraser les paramètres actuels.",
    "rad_SelectionLabel": "Copier le profil à partir de :",
    "rad_UserBtn": "Utilisateur existant",
    "rad_TemplateBtn": "Modèle",
    "user_LookupLabel": "Utilisateur",
    "template_LookupLabel": "Modèle",
    "lookupUserNameColText": "Nom d'utilisateur",
    "lookupTitleColText": "Titre",
    "lookupDepartmentColText": "Service",
    "lookupRegionColText": "Région",
    "lookupUser_Caption": "L'utilisateur peut copier le profil à partir de :",
    "lookupUserNameTemplateColText": "Modèle",
    "chkGeneralLabel": "Général",
    "chkCalendarLabel": "Agenda",
    "chkEmployeeLabel": "Employé",
    "chkClientLabel": "Options client (système client)",
    "chkSecurityLabel": "Sécurité",
    "chkServiceLabel": "Service/Assistance technique",
    "chkTeamsLabel": "Equipes",
    "txtJobDescriptor": "Copier le profil utilisateur",
    "jobFailer": "Une erreur critique s'est produite"
});