define("Sage/MainView/Contact/nls/ru/ContactSearchForDuplicates", {
    "svAccount_Caption": "Клиент:",
    "svCompany_Caption": "Компания:",
    "svEmail_Caption": "Электронная почта:",
    "svName_Caption": "Имя:",
    "svTitle_Caption": "Название:",
    "svType_Caption": "Тип:",
    "svSubType_Caption": "Подтип",
    "svAccMgr_Caption": "Менеджер по клиентам:",
    "svHomePhone_Caption": "Домашний телефон:",
    "svWorkPhone_Caption": "Рабочий телефон:",
    "svMobilePhone_Caption": "Мобильный телефон:",
    "svStatus_Caption": "Статус:",
    "svWebAddress_Caption": "Интернет:",
    "svEntityAccount_Caption": "Клиент",
    "svEntityLead_Caption": "Заинтересованное лицо",
    "svEntityContact_Contact": "Контакт",
    "svTollFree_Caption": "Бесплатный справочный телефон:",
    "svIndustry_Caption": "Отрасль:",
    "svDivision_Caption": "Подразделение:",
    "svMainPhone_Caption": "Основной телефон",
    "LeadSummaryView_Title": "Сводная информация — заинтересованное лицо",
    "ContactSummaryView_Title": "Сводная информация — контакт",
    "AccountSummaryView_Title": "Сводная информация — клиент",
    "closeText": "Закрыть",
    "errorLoadingSummaryView": "Ошибка при загрузке сводного представления: ${0}"
});