define("Sage/UI/nls/zh-tw/ActivityScheduler", {
    "tooltipTime": "時間",
    "tooltipContactName": "聯絡人",
    "tooltipAccountName": "客戶",
    "tooltipCompanyName": "公司",
    "tooltipLeadName": "銷售線索",
    "tooltipPhoneNumber": "電話",
    "tooltipRegarding": "關於",
    "tooltipPriority": "優先順序",
    "tooltipNotes": "備註",
    "tooltipType": "類型",
    "tooltipDayType": "日類型",
    "tooltipStartDate": "開始日期",
    "tooltipEndDate": "結束日期",
    "tooltipLocation": "位置",
    "tooltipDescription": "描述",
    "completedText": "(已完成)",
    "tooltipMoreActivities": "按一下以取得更多活動",
    "scheduler_dates": {
        "month_full": [
            "一月",
            "二月",
            "三月",
            "四月",
            "5 月",
            "六月",
            "七月",
            "八月",
            "九月",
            "十月",
            "十一月",
            "十二月"
        ],
        "month_short": [
            "1 月",
            "2 月",
            "3 月",
            "4 月",
            "5 月",
            "6 月",
            "7 月",
            "8 月",
            "9 月",
            "10 月",
            "11 月",
            "12 月"
        ],
        "day_full": [
            "週日",
            "週一",
            "週二",
            "週三",
            "週四",
            "週五",
            "週六"
        ],
        "day_short": [
            "日",
            "一",
            "二",
            "三",
            "四",
            "五",
            "六"
        ]
    },
    "scheduler_labels": {
        "dhx_cal_today_button": "今天",
        "day_tab": "天",
        "week_tab": "週",
        "workweek_tab": "工作週",
        "month_tab": "月",
        "new_event": "新增事件",
        "icon_save": "儲存",
        "icon_cancel": "取消",
        "icon_details": "詳細資料",
        "icon_edit": "編輯",
        "icon_delete": "刪除",
        "confirm_closing": "",
        "confirm_deleting": "事件將會永久刪除，您確定嗎?",
        "section_description": "描述",
        "section_time": "時間間隔",
        "full_day": "全天",
        "confirm_recurring": "您要編輯整組重複的事件?",
        "section_recurring": "重複事件",
        "button_recurring": "已停用",
        "button_recurring_open": "已啟用",
        "agenda_tab": "議程",
        "date": "日期",
        "description": "描述",
        "year_tab": "年",
        "week_agenda_tab": "議程"
    }
});