define("Sage/UI/nls/zh-tw/BulkUpdateWidget", {
    "dlgBulkActionUpdate_Title": "大量動作更新",
    "pageLoading_Caption": "載入內容選項中...",
    "header_Caption": "選取您想更新的內容。",
    "header_NoPropertiesEnabled": "已經啟用 ${0} 實體用於大量更新，但是並未有已經啟用的內容。請聯絡系統管理員以瞭解更多資訊",
    "errorRequestPropertyOptions": "讀取 ${0} 實體的中繼資料時發生錯誤。${1}",
    "errorEntityNotSupported": "${0} 實體不支援大量更新",
    "update_Property_Caption": "更新:",
    "addProperty_Tooltip": "新增內容",
    "removeProperty_Tooltip": "移除內容",
    "no_Caption": "否",
    "yes_Caption": "是",
    "days_Caption": "天",
    "moveOut_Caption": "移動",
    "moveTo_Caption": "至",
    "moveDate_Backward": "往後",
    "moveDate_Forward": "下一頁",
    "update_To_Caption": "至:",
    "lookupHeaderText": "查閱 ${0}",
    "lookupNameColText": "名稱",
    "lookupTitleColText": "標題",
    "lookupDepartmentColText": "部門",
    "lookupRegionColText": "地區",
    "lookupTypeColText": "類型",
    "lookupDescriptionColText": "描述",
    "btnOK_Caption": "確定",
    "btnCancel_Caption": "取消",
    "errorUnspecifiedValue": "請先指定一個值，再繼續或移除無效列。",
    "errorRequestingJobMgr": "執行更新時發生錯誤: ${0}",
    "selectOption_Caption": "選取一個選項...",
    "updateRecords_Caption": "更新選取的記錄",
    "chkScheduleJob_Caption": "安排此更新在特定日期/時間執行。",
    "lookup_Caption": "查閱",
    "job_Description": "發生大量更新錯誤",
    "errorDuplicateValue": "內容已選取",
    "errorInvalidPropertyType": "大量更新中不支援內容類型「${0}」。",
    "calculatedField": "計算欄位",
    "standardId": "標準 ID",
    "unknownPropertyType": "不明"
});