define("Sage/UI/nls/zh-tw/SDataFeed", {
    "contractText": "合約",
    "contractRequiredText": "必須提供合約",
    "sdataUrlText": "SData URL",
    "titleText": "標題",
    "usernameText": "使用者名稱",
    "passwordText": "密碼",
    "logOnText": "登入",
    "urlRequiredText": "必須提供 SData URL",
    "urlImproperFormatText": "SData URL 格式無效。範例: http://localhost/sdata/slx/dynamic/-/",
    "customNoAuthText1": "造成您的不便，我們深感抱歉，您的要求無法完成。這個摘要的授權資訊不正確或遺失。",
    "customNoAuthText2": "請更新下列項目的使用者名稱和密碼:",
    "feedText": "SData 摘要",
    "urlAuthenticationText": "輸入自訂的 SData 摘要",
    "selectFeedText": "選取摘要",
    "nextText": "下一步&gt;",
    "warningText": "資訊",
    "invalidWhereText": "抱歉，Where 子句無效。請檢閱 Where 子句的格式是否有任何錯誤。如需詳細資訊，請參閱「建立 Where 子句」說明主題。",
    "failedToLoadUrlText": "抱歉，無法載入要求的摘要。請選取其他摘要或聯絡系統管理員。",
    "noFeedSelectedText": "未選取摘要類型",
    "resourceText": "資源",
    "whereText": "Where 子句",
    "previousText": "&lt;上一步",
    "noResourceSelectedText": "選取資源",
    "noColumnsSelectedText": "請選取一或多個要顯示在小組件中的欄。",
    "limitRangeText": "輸入 1 到 100 之間的值",
    "testText": "測試",
    "cancelText": "取消",
    "finishText": "完成",
    "exampleQueryText1": "範例:",
    "exampleQueryText2": "機器 IP 位址",
    "exampleQueryText3": "連接埠號碼",
    "exampleWhereText": "深入了解",
    "numberRecordsText": "可見的記錄",
    "sageSalesLogixDynamic": "Saleslogix 動態實體",
    "sageSalesLogixSystem": "Saleslogix 系統",
    "selectColumnsFromText": "可用的欄:",
    "selectedColumnsFromText": "選取的欄:"
});