define("Sage/MainView/EntityMgr/nls/it/EntityListPanelConfig", {
    "colNameEntityName": "Nome",
    "colNameType": "Tipo",
    "colNameTable": "Tabella",
    "colNameCreateUser": "Creato da",
    "colNameCreateDate": "Data di creazione",
    "colNameLastExecutionDate": "Ultima esecuzione",
    "colNameLastExecutionUser": "Ultima esecuzione di",
    "colNameModifyUser": "Modificato da",
    "colNameModifyDate": "Data di modifica",
    "colNameEntityDisplayName": "Nome visualizzato",
    "colNameEntityTableName": "Tabella",
    "colNamePropertyCount": "Conteggio proprietà",
    "colNameFilterCount": "Conteggio filtrati",
    "colNameMetricCount": "Conteggio metrica",
    "colNamePackage": "Pacchetto",
    "owner": "Proprietario",
    "assignTo": "Assegna a",
    "newACI": "Nuova area/categoria/problema",
    "insertACI": "Inserisci area/categoria/problema",
    "autoAssign": "Assegnazione automatica",
    "areaCatIssue": "Area/categoria/problema",
    "lookupACI": "Ricerca area/categoria/problema",
    "displayName": "Nome visualizzato",
    "displayPluralName": "Nome visualizzato al plurale",
    "Title": "Titolo",
    "IsExtension": "IsExtension",
    "Audited": "Controllato",
    "OK": "OK",
    "Cancel": "Annulla"
});