define("Sage/MainView/EntityMgr/nls/it/_BaseEntityDetailContent", {
    "FilterTabTitle": "Filtri",
    "MetricTabTitle": "Metriche",
    "PropertyTabTitle": "Campi",
    "CalcFieldTabTitle": "Campi calcolati",
    "EntityTabTitle": "Entità",
    "RelationTabTitle": "Relazioni",
    "dialogTitleAddField": "Aggiungi campo a entità ${0}",
    "dialogTitleAddFilter": "Aggiungi filtro a entità ${0}",
    "dialogTitleAddMetric": "Aggiungi metrica a entità ${0}",
    "dialogTitleAddRelationship": "Aggiungi relazione a entità ${0}",
    "editDialogTitle": "Modifica ${0} in entità ${1}",
    "FilterDialogTitle": "Filtro",
    "MetricDialogTitle": "Metrica",
    "PropertyDialogTitle": "Campo",
    "RelationDialogTitle": "Relazione",
    "FilterGridColumnFilter": "Nome filtro",
    "MetricGridColumnMetric": "Nome metrica",
    "FilterGridColumnDisplay": "Nome visualizzato",
    "FilterGridColumnProperty": "Campo",
    "FilterGridColumnType": "Metrica o filtro",
    "FilterGridColumnIsMetric": "Nel dashboard",
    "FilterGridColumnLastUpdated": "Ultima modifica",
    "FilterGridColumnDetails": "Tipo",
    "FilterGridDetailsDistinctFilter": "Singolo",
    "FilterGridDetailsDateDiffMetricFilter": "Metrica differenza data",
    "FilterGridDetailsRangeFilter": "Intervallo",
    "FilterGridDetailsMetricFilter": "Metrica",
    "FilterGridDetailsUserLookupFilter": "Ricerca utenti",
    "FilterGridDetailsLookupFilter": "Ricerca",
    "FilterGridDetailsCustom": "Personalizzato",
    "GridHelp": "Guida",
    "FilterGridAdd": "Aggiungi filtro",
    "FilterGridRemove": "Rimuovi filtro",
    "FilterGridEdit": "Modifica filtro",
    "MetricGridAdd": "Aggiungi metrica",
    "MetricGridRemove": "Rimuovi metrica",
    "MetricGridEdit": "Modifica metrica",
    "PropertyGridAdd": "Aggiungi campo",
    "PropertyGridRemove": "Rimuovi campo",
    "PropertyGridEdit": "Modifica campo",
    "CalculatedGridAdd": "Aggiungi campo calcolato",
    "CalculatedGridRemove": "Rimuovi campo calcolato",
    "CalculatedGridEdit": "Modifica campo calcolato",
    "lblFilterName": "Nome filtro",
    "lblDisplayName": "Nome visualizzato",
    "lblFilterDp": "Campi",
    "lblTypeDp": "Tipo",
    "lblCharacter": "Caratteri",
    "lblTypeSpecificContentBox": "Casella contenuto di tipo specifico",
    "lblSaveButton": "Salva",
    "lblCancelButton": "Annulla",
    "lblOkButton": "OK",
    "lblWarning": "Selezionare un elemento.",
    "confirmDeleteFmtTxt": "Eliminare questi ${0} elementi?",
    "filtersFor": "Filtri per",
    "metricsFor": "Metriche per",
    "propertyFor": "Campi per",
    "calculatedFor": "Campi calcolati per",
    "defaultRangeRowValue": "Immettere un valore",
    "customSql": "SQL personalizzato",
    "displayName": "Nome visualizzato",
    "lower": "Inferiore",
    "rangeId": "ID intervallo",
    "rangeName": "Nome intervallo",
    "upper": "Superiore",
    "SUM": "Totale (somma)",
    "Contains": "Contiene",
    "StartsWith": "Inizia con",
    "EndsWith": "Termina con",
    "LessThan": "Minore di",
    "GreaterThan": "Maggiore di",
    "LessThanEqual": "Minore o uguale a",
    "GreaterThanEqual": "Maggiore di o uguale",
    "Equal": "È uguale a",
    "NotEqual": "Non è uguale a",
    "COUNT": "Conteggio",
    "AVG": "Media",
    "MIN": "Valore minimo",
    "MAX": "Valore massimo",
    "totalRecordCountLabel": "Record totali: ${0}",
    "propertyName": "Nome",
    "Description": "Descrizione",
    "propertyType": "Tipo",
    "included": "Incluso",
    "calculatedFields": "Calcolato",
    "generate": "Genera",
    "key": "Chiave",
    "relationFor": "Relazione per",
    "childEntity": "Figlio",
    "childProperty": "Campo figlio",
    "parentEntity": "Padre",
    "parentProperty": "Campo padre",
    "editable": "Modificabile",
    "cardinality": "Cardinalità",
    "relationship": "Relazione",
    "parentImport": "Importazione padre",
    "parentMatch": "Corrispondenza padre",
    "parentAudit": "Controllo padre",
    "parentIncluded": "Padre incluso",
    "childImport": "Importazione figlio",
    "childMatch": "Corrispondenza figlio",
    "childAudit": "Controllo figlio",
    "childIncluded": "Figlio incluso",
    "text": "testo",
    "memo": "memo",
    "unicodeText": "testo unicode",
    "unicodeMemo": "memo unicode",
    "integer": "intero",
    "double": "doppio",
    "single": "singolo",
    "decimal": "decimale",
    "short": "breve",
    "standardId": "ID standard",
    "trueFalse": "vero/falso",
    "yesNo": "sì/no",
    "boolean": "booleano",
    "dateTime": "data/ora",
    "email": "e-mail",
    "phone": "telefono",
    "pickList": "elenco di selezione",
    "owner": "proprietario",
    "lookup": "ricerca",
    "dependencyLookup": "ricerca dipendenze",
    "char": "carattere",
    "enum_": "enumerazione",
    "guid": "guid",
    "byte": "byte",
    "binary": "binario",
    "url": "URL",
    "string": "stringa",
    "number": "numero",
    "notUniqueFor": "non è unico per",
    "lblPluralName": "Nome visualizzato al plurale",
    "lblTitle": "Titolo",
    "IsExtension": "È l'estensione",
    "AdvOptions": "Opzioni avanzate",
    "lblImport": "Importa",
    "lblMatch": "Corrispondenza",
    "lblBulkUpdate": "Aggiornamento in blocco",
    "lblAudited": "Controllato",
    "lblPut": "Colloca",
    "lblPost": "Pubblica",
    "lblDelete": "Elimina",
    "lblHistory": "Registra cronologia in",
    "metricNotEditable": "Questa metrica non è modificabile."
});