define("Sage/MainView/Lead/nls/zh-cn/ImportLeadsWizard", {
    "yestText": "是",
    "noText": "否",
    "confirmOverwriteFileMsg": "您当前已选中一个导入文件。是否想要覆盖此文件?",
    "importProgressCaption": "导入流程结果",
    "lblPrimaryProgress": "正在处理导入文件，请稍候...",
    "lblTotalRecords": "记录总数:",
    "lblTotalRecordsProcessed": "已处理:",
    "lblTotalRecordsImported": "已导入:",
    "lblTotalRecordsMerged": "已合并:",
    "lblTotalDuplicates": "重复项:",
    "lblTotalProjectedDuplicates": "预计重复:",
    "lblDuplicateRate": "重复比率:",
    "lblTotalErrors": "错误:",
    "calculatingText": "正在计算，请稍候...",
    "importStatusProcessing": "正在处理",
    "importStatusCompleted": "已完成",
    "abortImportProcessStatus": "中止",
    "btnCancelText": "中止",
    "btnCloseText": "关闭",
    "lblImportHistoryLinkText": "要查看导入历史结果，请单击下面的导入编号:",
    "lblImportLinkNumber": "导入编号: ",
    "errorRequestImportHistory": "对端点 importHistory 执行 sdata 申请时出现错误。"
});