define("Sage/MainView/EntityMgr/nls/EntityListPanelConfig", {
    root: {
        colNameEntityName: 'Name',
        colNameType: 'Type',
        colNameTable: 'Table',
        colNameCreateUser: 'Create User',
        colNameCreateDate: 'Create Date',
        colNameLastExecutionDate: 'Last Run',
        colNameLastExecutionUser: 'Last Run By',
        colNameModifyUser: 'Modify User',
        colNameModifyDate: 'Modify Date',
        colNameEntityDisplayName: 'Display Name',
        colNameEntityTableName: 'Table',
        colNamePropertyCount: 'Property Count',
        colNameFilterCount: 'Filter Count',
        colNameMetricCount: 'Metric Count',
        colNamePackage: 'Package',
        owner: 'Owner',
        assignTo: 'Assign To',
        newACI: 'New Area/Category/Issue',
        insertACI: 'Insert Area/Category/Issue',
        autoAssign: 'Auto Assignment',
        areaCatIssue: 'Area/Category/Issue',
        lookupACI: 'Lookup Area/Category/Issue',
        displayName: 'Display Name',
        displayPluralName: 'Display Plural Name',
        Title: 'Title',
        IsExtension: 'IsExtension',
        Audited: 'Audited',
        OK: 'OK',
        Cancel: 'Cancel'
    },
    "de": true,
    "en": true,
    "fr": true,
    "it": true,
    "ru": true
});

