define("Sage/MainView/ExchangeRate/nls/zh-cn/ExchangeRateDialog", {
    "lblUpdateCurrency": "更新货币",
    "lblSelectEntity": "将更新后的货币应用于",
    "lblSalesOrders": "销售订单",
    "lblOpportunities": "销售机会",
    "lblQuotes": "报价单",
    "lblOK": "确定",
    "lblCancel": "取消",
    "lblClose": "关闭",
    "updateRecords_Caption": "正在更新实体汇率",
    "job_Description": "更新实体汇率时出现错误",
    "errorRequestingJobMgr": "执行更新时出现错误: ${0}",
    "lblRecordsToUpdate": "要更新的记录数",
    "lblLockedUpdate": "不会更新已锁定费率的记录",
    "lblNote": "备注",
    "OpenOrder": "未结订单",
    "SalesOrder": "销售订单",
    "Open": "未结",
    "New": "新建"
});