define("Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-cn/ContactLookupConfig", {
    "contactText": "联系人",
    "accountText": "客户",
    "lookupContactText": "查找联系人",
    "nameText": "名称",
    "cityText": "城市",
    "stateText": "省/州",
    "workphoneText": "单位电话",
    "emailText": "电子邮件",
    "dialogButtonText": "添加所选项",
    "cancelText": "关闭",
    "colFirstName": "名字",
    "colLastName": "姓氏",
    "colTitle": "标题",
    "colAccount": "客户",
    "colWorkPhone": "单位电话",
    "colEmail": "电子邮件",
    "dialogTitleText": "查找联系人"
});