define(
"dojo/cldr/nls/bs/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbijski pezo",
	"CZK_displayName": "Češka kruna",
	"TND_displayName": "Tunizijski dinar",
	"JMD_displayName": "Jamajski dolar",
	"PHP_displayName": "Filipinski peso",
	"ALL_displayName": "Albanski lek",
	"LBP_displayName": "Lebanska funta",
	"VND_displayName": "Vijetnamski dong",
	"LYD_displayName": "Libijski dinar",
	"RON_displayName": "Rumunski leu",
	"MKD_displayName": "Makedonski denar",
	"SEK_displayName": "Švedska kruna",
	"CNY_displayName": "Kineski Juan Renminbi",
	"IDR_displayName": "Indonezijska rupiah",
	"ILS_displayName": "Izraelski šekel",
	"YER_displayName": "Jemenski rial",
	"TJS_displayName": "Tadžikistanski somoni",
	"TTD_displayName": "Trinidad i Tobago dolar",
	"TRY_displayName": "Turska lira",
	"EUR_displayName": "Evro",
	"AED_displayName": "Ujedinjeni arapski emirati dirham",
	"KZT_displayName": "Kazahstanski tendž",
	"BHD_displayName": "Bahreinski dinar",
	"RUB_displayName": "Ruska rublja",
	"NZD_displayName": "Novozelandski dolar",
	"IQD_displayName": "Irački dinar",
	"TMT_displayName": "Turkmenistanski manat",
	"ZWL_displayName": "Zimbabvejski dolar (2009)",
	"KGS_displayName": "Kirgistanski som",
	"KWD_displayName": "Kuvajtski dinar",
	"AFN_displayName": "Avganistanski avgani",
	"ARS_displayName": "Argentinski pezo",
	"MAD_displayName": "Marokanski dirham",
	"BAM_displayName": "Bosansko-Hercegovačka konvertibilna marka",
	"BOB_displayName": "Bolivijski boliviano",
	"BND_displayName": "Brunejski dolar",
	"SGD_displayName": "Singapurski dolar",
	"MVR_displayName": "Maldivijska rufija",
	"MXN_displayName": "Meksički peso",
	"DZD_displayName": "Alžirski dinar",
	"BAM_symbol": "KM",
	"JOD_displayName": "Jordanski dinar",
	"PEN_displayName": "Peruanski nuevo sol",
	"GTQ_displayName": "Gvatemalski kvetzal",
	"BYR_displayName": "Beloruska rublja",
	"CAD_displayName": "Kanadski dolar",
	"BZD_displayName": "Belize dolar",
	"CLP_displayName": "Čileanski pezo",
	"XOF_displayName": "CFA franak BCEAO",
	"NOK_displayName": "Norveška kruna",
	"DOP_displayName": "DOminikanski pezo",
	"KRW_displayName": "Južno-korejski Von",
	"USD_displayName": "Američki dolar",
	"UYU_displayName": "Urugvajski pezo",
	"UZS_displayName": "Uzbekistanski som",
	"QAR_displayName": "Katarski rial",
	"SAR_displayName": "Saudijski rijal",
	"SYP_displayName": "Sirijska funta",
	"EGP_displayName": "Egipatska funta",
	"AMD_displayName": "Jermenski dram",
	"GBP_displayName": "Britanska funta sterlinga",
	"HUF_displayName": "Mađarska forinta",
	"CSD_displayName": "Srpski dinar (2002–2006)",
	"ISK_displayName": "Islandska kruna",
	"RSD_symbol": "din.",
	"IRR_displayName": "Iranijski rial",
	"OMR_displayName": "Omanski rial",
	"TWD_displayName": "Novi tajvanski dolar",
	"PAB_displayName": "Panamanska balboa",
	"UAH_displayName": "Ukrajinska hrivnja",
	"ETB_displayName": "Etopijski bir",
	"PLN_displayName": "Poljski zlot",
	"VEF_displayName": "Venecuelanski bolivar",
	"BRL_displayName": "Brazilski real",
	"HKD_displayName": "Honkonški dolar",
	"NIO_displayName": "Nikaragvanška kordoba",
	"NPR_displayName": "Nepalska ruplja",
	"PKR_displayName": "Pakistanski rupi",
	"GEL_displayName": "Džordžijski lari",
	"AZN_displayName": "Azerbejdžanski manat",
	"MYR_displayName": "Malezijski ringit",
	"DKK_displayName": "Danska kruna",
	"THB_displayName": "Tai baht",
	"JPY_displayName": "Japanski jen",
	"KES_displayName": "Kenijski šiling",
	"KHR_displayName": "Kambodžijski riel",
	"PYG_displayName": "Paragvajski guarni",
	"LKR_displayName": "Šrilankanski rupi",
	"BGN_displayName": "Bugarski lev",
	"BDT_displayName": "Bangladeška taka",
	"MOP_displayName": "Makaniška pataka",
	"HNL_displayName": "Honduranska lempira",
	"RWF_displayName": "Ruandski franak",
	"CHF_displayName": "Švajcarski franak",
	"CRC_displayName": "Kostarikanski kolon",
	"INR_displayName": "Indijski rupi",
	"ZAR_displayName": "Južna Afrika Rand",
	"AUD_displayName": "Australijski dolar",
	"LAK_displayName": "Laoški kip",
	"MNT_displayName": "Mongolski tugrik",
	"RSD_displayName": "Srpski dinar",
	"HRK_displayName": "Hrvatska kuna"
}
//end v1.x content
);