define("Sage/MainView/EntityMgr/EntityWizard/nls/en/_EntityWizardDialog", {
    lblNewEntityWizard: 'New Entity Wizard',
    lblCreateEntity: 'Create Entity',
    lblCreateEntityFromTable: 'Create a new entity from a table',
    lblEntityName: 'Name',
    lblDisplayName: 'Display',
    lblPackage: 'Package',
    lblEntityUsed: 'Entity Name is already used !',
    lblNext: 'Next',
    lblCancel: 'Cancel',
    lblBack: 'Back',
    lblEnterProperties: 'Enter Fields',
    lblAddNewProperty: 'Click the add(+) button to add new fields to the entity',
    lblPropertyName: 'Field Name',
    lblDataType: 'Data Type',
    lblLength: 'Length',
    lblSure: 'Are you sure ?',
    lblThisStepCreateEntity: 'Completing this step will create the entities and necessary schema',
    lblEntity: 'Entity',
    lblProperties: 'Fields',
    lblStatus: 'Status',
    lblSuccess: 'Success',
    lblSuccessMsg: 'Success, Entity created Successfully.',
    lblError: 'Error',
    lblFailed: 'Failed',
    lblErrorMsg: 'Error, Entity creation failed !',
    lblFinish: 'Finish',
    lblInvalidEntry: 'A valid entry starts with a capital letter and can contain alphanumeric values',
    lblRequired: 'Required',
    lblErrorRelation: 'Error while creating relationship with',
    lblRelationship: 'Primary Relationship',
    lblSelectEntity: 'Choose whether this entity has a primary relationship to another entity',
    lblExistingEntity: 'Relate to an existing Entity',
    lblRelatedEntity: 'Related Entity',
    lblRelationType: 'Relation Type',
    addFieldDialogTitle: 'Add Field',
    editFieldDialogTitle: 'Edit Field',
    noDeleteSysProps: 'Can not delete the system properties',
    noEditSysProps: 'Can not edit the system properties',
    NoRecordsSelected: 'There are no records selected.',
    lblNullable: 'Is Nullable',
	ExtensionEntity:'1:1 - Extension Entity',
	ChildEntity:'1:M - Child Entity',
    CreateUser: 'Create User',
    CreateDate: 'Create Date',
    ModifyUser: 'Modify User',
    ModifyDate: 'Modify Date'
});