define("Sage/TaskPane/nls/de/_BaseTaskPaneTasklet", {
    "selectRecordsTitle": "Auswahl ungültig",
    "selectRecords": "Bitte wählen Sie einen Datensatz aus, bevor Sie fortfahren.",
    "selectSingleRecord": "Bitte wählen Sie einen einzelnen Datensatz aus, bevor Sie fortfahren.",
    "noRecordsSelectedProcessAll": "Es sind keine Datensätze ausgewählt. Es wird die gesamte Gruppe bis zum vom Systemadministrator festgelegten Limit (falls vorhanden) verarbeitet. Möchten Sie fortfahren?",
    "invalidSelectionTitle": "Auswahl ungültig",
    "errorSelectionInfo": "Beim Abrufen von Informationen über die ausgewählten Datensätze ist ein Fehler aufgetreten.",
    "errorNoData": "Keine Daten verfügbar.",
    "yesButtonText": "Ja",
    "noButtonText": "Nein",
    "salesLogixPageTitle": "Infor CRM",
    "okButtonText": "OK",
    "cancelButtonText": "Abbrechen",
    "confirmBulkDeleteJob": "Möchten Sie die ausgewählten Datensätze wirklich löschen?",
    "deleteSelectedRecords": "${0} löschen",
    "deleteJobError": "Beim Löschen von Auftrag ${0} ist ein Fehler aufgetreten: ${1}",
    "deleteBulkJobTitle": "${0} löschen",
    "promoteTitle": "Hochstufen",
    "getOrderTotalTitle": "Auftragssumme abrufen",
    "integrationNotEnabled": "Back Office Extension ist nicht aktiviert",
    "error_PricingRequest": "Beim Anfordern des Preisfestsetzungsdiensts ist ein Fehler aufgetreten: ${0}"
});