define(
"dojo/cldr/nls/eu/currency", //begin v1.x content
{
	"COP_displayName": "Kolonbiako pesoa",
	"CZK_displayName": "Txekiar Errepublikako koroa",
	"TND_displayName": "Tunisiako dinarra",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaikako dolarra",
	"PHP_displayName": "Filipinetako pesoa",
	"ALL_displayName": "Albaniako leka",
	"USD_symbol": "US$",
	"LBP_displayName": "Libanoko libera",
	"VND_displayName": "Vietnameko donga",
	"LYD_displayName": "Libiako dinarra",
	"RON_displayName": "Errumaniako leua",
	"MKD_displayName": "Mazedoniako denara",
	"SEK_displayName": "Suediako koroa",
	"CNY_displayName": "Txinako yuana",
	"IDR_displayName": "Indonesiako errupia",
	"ILS_displayName": "Israeleko sheqel berria",
	"YER_displayName": "Yemengo riala",
	"TJS_displayName": "Tajikistango somonia",
	"TTD_displayName": "Trinidadeko eta Tobagoko dolarra",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Turkiako lira",
	"EUR_displayName": "Euroa",
	"AED_displayName": "Arabiar Emirerri Batuetako dirhama",
	"KZT_displayName": "Kazakhstango tengea",
	"BHD_displayName": "Bahraingo dinarra",
	"RUB_displayName": "Errusiako errubloa",
	"NZD_displayName": "Zeelanda Berriko dolarra",
	"IQD_displayName": "Irakeko dinarra",
	"TMT_displayName": "Turkmenistango manata",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgizistango soma",
	"KWD_displayName": "Kuwaiteko dinarra",
	"AFN_displayName": "Afganistango afghania",
	"ARS_displayName": "Argentinako pesoa",
	"MAD_displayName": "Marokoko dirhama",
	"BAM_displayName": "Bosnia-Herzegovinako marko trukakorra",
	"BOB_displayName": "Boliviako bolivianoa",
	"BND_displayName": "Bruneiko dolarra",
	"SGD_displayName": "Singapurreko dolarra",
	"MVR_displayName": "Maldivetako rufiyaa",
	"MXN_displayName": "Mexikoko pesoa",
	"DZD_displayName": "Algeriako dinarra",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Jordaniako dinarra",
	"PEN_displayName": "Peruko sol berria",
	"GTQ_displayName": "Guatemalako quetzala",
	"BYR_displayName": "Bielorrusiako errubloa",
	"CAD_displayName": "Kanadako dolarra",
	"BZD_displayName": "Belizeko dolarra",
	"CLP_displayName": "Txileko pesoa",
	"XOF_displayName": "Afrika ekialdeko frankoa BCEAO",
	"NOK_displayName": "Norvegiako koroa",
	"DOP_displayName": "Dominikar Errepublikako pesoa",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Hego Koreako wona",
	"USD_displayName": "AEBetako dolarra",
	"UYU_displayName": "Uruguaiko pesoa",
	"UZS_displayName": "Uzbekistango soma",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Qatarreko riala",
	"SAR_displayName": "Saudiko riala",
	"SYP_displayName": "Siriako libera",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Egiptoko libera",
	"AMD_displayName": "Armeniako drama",
	"GBP_displayName": "Libera esterlina",
	"HUF_displayName": "Hungariako florina",
	"ISK_displayName": "Islandiako koroa",
	"IRR_displayName": "Irango riala",
	"OMR_displayName": "Omango riala",
	"TWD_displayName": "Taiwango dolar berria",
	"PAB_displayName": "Panamako balboa",
	"UAH_displayName": "Ukrainako hryvnia",
	"ETB_displayName": "Etiopiako birra",
	"PLN_displayName": "Poloniako zlotya",
	"VEF_displayName": "Venezuelako bolivarra",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Brasilgo erreala",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hong Kongeko dolarra",
	"NIO_displayName": "Nikaraguako cordoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepalgo errupia",
	"PKR_displayName": "Pakistango errupia",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Georgiako laria",
	"AZN_displayName": "Azerbaijango manata",
	"GBP_symbol": "£",
	"MYR_displayName": "Malaysiako ringgita",
	"DKK_displayName": "Danimarkako koroa",
	"THB_displayName": "Thailandiako bahta",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japoniako yena",
	"KES_displayName": "Kenyako txelina",
	"KHR_displayName": "Kanbodiako riela",
	"PYG_displayName": "Paraguaiko guarania",
	"VND_symbol": "₫",
	"LKR_displayName": "Sri Lankako errupia",
	"BGN_displayName": "Bulgariako leva",
	"BDT_displayName": "Bangladesheko taka",
	"MOP_displayName": "Macanako pataca",
	"HNL_displayName": "Hondurasko lempira",
	"RWF_displayName": "Ruandako frankoa",
	"CHF_displayName": "Suitzako frankoa",
	"CRC_displayName": "Costa Ricako colona",
	"INR_displayName": "Indiako errupia",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Hegoafrikako randa",
	"AUD_displayName": "Australiako dolarra",
	"LAK_displayName": "Laoseko kipa",
	"MNT_displayName": "Mongoliako tugrika",
	"RSD_displayName": "Serbiako dinarra",
	"HRK_displayName": "Kroaziako kuna"
}
//end v1.x content
);