define("Sage/MainView/ReportMgr/Crystal/nls/it/CrystalReportConditionEditor", {
    "dlgCrystalReportConditionDetails_Title": "Aggiungi/modifica condizione",
    "cmdOK_Caption": "OK",
    "cmdCancel_Caption": "Annulla",
    "cmbConditionType_Caption": "Corrispondenza per",
    "txtInvalidParameterTitle": "Parametro non valido",
    "txtInvalidParameterMessage": "Parametro non valido: ${0}",
    "lkpUser_Caption": "Utente",
    "lkpGroup_Caption": "Gruppo",
    "txtSelectUser": "Seleziona utente",
    "chkCurrentUser_Caption": "Utente corrente",
    "txtName": "Nome",
    "txtOK": "OK",
    "txtSelectGroup": "Seleziona gruppo",
    "cmbDateRange_Caption": "Intervallo di date",
    "cmbDateRange_SpecificDates_Caption": "Date specifiche",
    "cmbDateRange_ThisWeek_Caption": "Questa settimana",
    "cmbDateRange_ThisMonth_Caption": "Questo mese",
    "cmbDateRange_ThisQuarter_Caption": "Questo trimestre",
    "cmbDateRange_ThisYear_Caption": "Quest'anno",
    "cmbDateRange_LastWeek_Caption": "Ultima settimana",
    "cmbDateRange_LastMonth_Caption": "Ultimo mese",
    "cmbDateRange_LastQuarter_Caption": "Ultimo trimestre",
    "cmbDateRange_LastYear_Caption": "Ultimo anno",
    "cmbDateRange_MonthToDate_Caption": "Da inizio mese",
    "cmbDateRange_QuarterToDate_Caption": "Da inizio trimestre",
    "cmbDateRange_YearToDate_Caption": "Da inizio anno",
    "dtFromDate_Caption": "Da",
    "dtToDate_Caption": "A",
    "cmbTable_Caption": "Tabella",
    "cmbField_Caption": "Campo",
    "cmbOperator_Caption": "Operatore",
    "txtValue_Caption": "Valore",
    "txtNumericValueFrom_Caption": "Da",
    "txtNumericValueTo_Caption": "A"
});