define("Sage/MainView/Lead/nls/zh-tw/ImportLeadsWizard", {
    "yestText": "是",
    "noText": "否",
    "confirmOverwriteFileMsg": "您目前已選取一個匯入檔案，要覆寫這個檔案?",
    "importProgressCaption": "匯入程序結果",
    "lblPrimaryProgress": "正在處理匯入檔案，請稍候...",
    "lblTotalRecords": "記錄總數:",
    "lblTotalRecordsProcessed": "已處理:",
    "lblTotalRecordsImported": "已匯入:",
    "lblTotalRecordsMerged": "已合併:",
    "lblTotalDuplicates": "重複項目:",
    "lblTotalProjectedDuplicates": "預計的重複項目:",
    "lblDuplicateRate": "重複率:",
    "lblTotalErrors": "錯誤:",
    "calculatingText": "正在計算，請稍候...",
    "importStatusProcessing": "處理",
    "importStatusCompleted": "已完成",
    "abortImportProcessStatus": "中止",
    "btnCancelText": "中止",
    "btnCloseText": "關閉",
    "lblImportHistoryLinkText": "若要查看匯入歷程記錄結果，請按一下下方的匯入編號:",
    "lblImportLinkNumber": "匯入編號: ",
    "errorRequestImportHistory": "為結束點 importHistory 執行 sdata 要求時發生錯誤。"
});