define(
"dojo/cldr/nls/kk/currency", //begin v1.x content
{
	"COP_displayName": "Колумбия песосы",
	"CZK_displayName": "Чех кронасы",
	"TND_displayName": "Тунис динары",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Ямайка доллары",
	"PHP_displayName": "Филиппин песосы",
	"ALL_displayName": "Албания лекі",
	"USD_symbol": "US$",
	"LBP_displayName": "Ливан фунты",
	"VND_displayName": "Вьетнам донгы",
	"LYD_displayName": "Ливия динары",
	"RON_displayName": "Румыния лейі",
	"MKD_displayName": "Македония динары",
	"SEK_displayName": "Швед кроны",
	"CNY_displayName": "Қытай юаны",
	"IDR_displayName": "Индонезия рупиі",
	"ILS_displayName": "Израиль жаңа шекелі",
	"YER_displayName": "Йемен риалы",
	"TJS_displayName": "Тәжікстан сомониі",
	"TTD_displayName": "Тринидад пен Тобаго доллары",
	"TRY_displayName": "Түрік лирасы",
	"EUR_displayName": "Еуро",
	"AED_displayName": "Дихрам (БАЭ)",
	"KZT_displayName": "Қазақстан теңгесі",
	"BHD_displayName": "Бахрейн динары",
	"RUB_displayName": "Ресей рубль",
	"NZD_displayName": "Жаңа Зеландия доллары",
	"IQD_displayName": "Ирак динары",
	"TMT_displayName": "Түрікменстан манаты",
	"KGS_displayName": "Қырғызстан сомы",
	"KWD_displayName": "Кувейт динары",
	"AFN_displayName": "Ауғаныстан афганиі",
	"ARS_displayName": "Аргентина песосы",
	"MAD_displayName": "Марокко дирхамы",
	"BAM_displayName": "Босния және Герцеговина айырбасталмалы маркасы",
	"BOB_displayName": "Боливия боливианосы",
	"BND_displayName": "Бруней доллары",
	"SGD_displayName": "Сингапур доллары",
	"MVR_displayName": "Мальдив руфиясы",
	"MXN_displayName": "Мексика пессосы",
	"MXN_symbol": "MX$",
	"DZD_displayName": "Алжир динары",
	"JOD_displayName": "Йордания динары",
	"PEN_displayName": "Перу жаңа солі",
	"GTQ_displayName": "Гватемала кетсалі",
	"BYR_displayName": "Беларус рублі",
	"CAD_displayName": "Канада доллары",
	"BZD_displayName": "Белиз доллары",
	"CLP_displayName": "Чили песосы",
	"XOF_displayName": "КФА ВСЕАО франкы",
	"NOK_displayName": "Норвегия кроны",
	"DOP_displayName": "Доминикан песосы",
	"KRW_displayName": "Оңтүстік Корея воны",
	"USD_displayName": "АҚШ доллары",
	"UYU_displayName": "Уругвай песосы",
	"UZS_displayName": "Өзбекстан сомы",
	"QAR_displayName": "Катар риалы",
	"SAR_displayName": "Сауд Арабия риалы",
	"SYP_displayName": "Сирия фунты",
	"EGP_displayName": "Мысыр фунты",
	"AMD_displayName": "Армения драмы",
	"GBP_displayName": "Британия фунты",
	"KZT_symbol": "₸",
	"HUF_displayName": "Венгер форинты",
	"ISK_displayName": "Исландия кронасы",
	"IRR_displayName": "Иран риалы",
	"OMR_displayName": "Оман риалы",
	"TWD_displayName": "Жаңа Тайван доллары",
	"PAB_displayName": "Панама бальбоасы",
	"UAH_displayName": "Украина гривнасы",
	"ETB_displayName": "Эфиопия быры",
	"RUB_symbol": "руб.",
	"PLN_displayName": "Польша злотасы",
	"VEF_displayName": "Венесуэла боливары",
	"BRL_displayName": "Бразилия реалы",
	"HKD_displayName": "Гонконг доллары",
	"NIO_displayName": "Никарагуа кордобасы",
	"NPR_displayName": "Непал рупиі",
	"PKR_displayName": "Пәкістан рупиі",
	"GEL_displayName": "Грузия лариі",
	"AZN_displayName": "Әзірбайжан манаты",
	"MYR_displayName": "Малайзия ринггиті",
	"DKK_displayName": "Дат кроны",
	"THB_displayName": "Тай баты",
	"JPY_displayName": "Жапон иені",
	"KES_displayName": "Кения шиллингі",
	"KHR_displayName": "Камбоджа риелі",
	"PYG_displayName": "Парагвай гуараниі",
	"LKR_displayName": "Шри-Ланка рупиясы",
	"BGN_displayName": "Болгар леві",
	"BDT_displayName": "Бангладеш такасы",
	"MOP_displayName": "Макао патакасы",
	"HNL_displayName": "Гондурас лемпираcы",
	"RWF_displayName": "Руанда франкы",
	"CHF_displayName": "Швейцария франкы",
	"CRC_displayName": "Коста-рика колоны",
	"INR_displayName": "Үнді рупиясы",
	"ZAR_displayName": "Оңтүстік Африка рэнді",
	"AUD_displayName": "Австралия доллары",
	"LAK_displayName": "Лаос кипі",
	"MNT_displayName": "Моңғолия тугрикасы",
	"RSD_displayName": "Сербия динары",
	"HRK_displayName": "Хорватия кунасы"
}
//end v1.x content
);