CREATE STATISTICS [_dta_stat_329768232_1_14] ON [sysdba].[PICKINGLIST]([PICKINGLISTID], [LISTTYPE])
CREATE NONCLUSTERED INDEX [_dta_index_PICKINGLIST_6_329768232__K14_K1] ON [sysdba].[PICKINGLIST] 
(
	[LISTTYPE] ASC,
	[PICKINGLISTID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_361768346_20_2] ON [sysdba].[PICKINGLISTITEM]([SALESORDERITEMID], [PICKINGLISTID])

CREATE NONCLUSTERED INDEX [_dta_index_PICKINGLISTITEM_6_361768346__K2_K20_10] ON [sysdba].[PICKINGLISTITEM] 
(
	[PICKINGLISTID] ASC,
	[SALESORDERITEMID] ASC
)
INCLUDE ( [QTYSHIP]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


CREATE NONCLUSTERED INDEX [_dta_index_PRODUCT_6_1764201335__K1_2_4_12_13_43_44_47] ON [sysdba].[PRODUCT] 
(
	[PRODUCTID] ASC
)
INCLUDE ( [NAME],
[ACTUALID],
[STATUS],
[UNIT],
[UPC],
[WAREHOUSEID],
[QTYAVAILABLE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


CREATE STATISTICS [_dta_stat_1579152671_37_10_2] ON [sysdba].[SALESORDERITEMS]([TACSTOCKCARDITEMID], [QUANTITY], [SALESORDERID])


CREATE STATISTICS [_dta_stat_1579152671_9_10_2] ON [sysdba].[SALESORDERITEMS]([PRICE], [QUANTITY], [SALESORDERID])

CREATE STATISTICS [_dta_stat_1579152671_14_10_2] ON [sysdba].[SALESORDERITEMS]([PRODUCTID], [QUANTITY], [SALESORDERID])

CREATE NONCLUSTERED INDEX [_dta_index_SALESORDERITEMS_6_1579152671__K2_K10_K1_K37_K14_K9_6_11_12_15_17_19_21_33_38_39_40_41_42_44_45_46] ON [sysdba].[SALESORDERITEMS] 
(
	[SALESORDERID] ASC,
	[QUANTITY] ASC,
	[SALESORDERITEMSID] ASC,
	[TACSTOCKCARDITEMID] ASC,
	[PRODUCTID] ASC,
	[PRICE] ASC
)
INCLUDE ( [MODIFYDATE],
[DISCOUNT],
[FAMILY],
[ACTUALID],
[EXTENDEDPRICE],
[CALCULATEDPRICE],
[LINENUMBER],
[MAX_STOCKLEVEL],
[LASTORDER],
[LASTORDER2],
[LASTORDER3],
[PREVIOUSYEARSALESQTY],
[CURRENTYEARSALESQTY],
[MASSHIPPEDDATE],
[MASQTYSHIPPED],
[MASSCHDSHIPDATE]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1579152671_10_2_1_37_14_9] ON [sysdba].[SALESORDERITEMS]([QUANTITY], [SALESORDERID], [SALESORDERITEMSID], [TACSTOCKCARDITEMID], [PRODUCTID], [PRICE])



CREATE NONCLUSTERED INDEX [_dta_index_PICKINGLISTITEM_6_361768346__K20_K2_10] ON [sysdba].[PICKINGLISTITEM] 
(
	[SALESORDERITEMID] ASC,
	[PICKINGLISTID] ASC
)
INCLUDE ( [QTYSHIP]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1579152671_9_1_10_2] ON [sysdba].[SALESORDERITEMS]([PRICE], [SALESORDERITEMSID], [QUANTITY], [SALESORDERID])


