-- OPtimizations
CREATE STATISTICS [_dta_stat_1764201335_4_1_44_42_2] ON [sysdba].[PRODUCT]([ACTUALID], [PRODUCTID], [WAREHOUSEID], [MASITEMKEY], [NAME])


CREATE STATISTICS [_dta_stat_1764201335_4_2_44] ON [sysdba].[PRODUCT]([ACTUALID], [NAME], [WAREHOUSEID])

CREATE STATISTICS [_dta_stat_1764201335_42_44_4] ON [sysdba].[PRODUCT]([MASITEMKEY], [WAREHOUSEID], [ACTUALID])

CREATE NONCLUSTERED INDEX [_dta_index_PRODUCT_5_1764201335__K1_K44_K4_K42_K2_46] ON [sysdba].[PRODUCT] 
(
	[PRODUCTID] ASC,
	[WAREHOUSEID] ASC,
	[ACTUALID] ASC,
	[MASITEMKEY] ASC,
	[NAME] ASC
)
INCLUDE ( [QTYONHAND]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [_dta_index_PRODUCT_5_1764201335__K4_K44_K2_1_42_46] ON [sysdba].[PRODUCT] 
(
	[ACTUALID] ASC,
	[WAREHOUSEID] ASC,
	[NAME] ASC
)
INCLUDE ( [PRODUCTID],
[MASITEMKEY],
[QTYONHAND]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1764201335_1_4_42] ON [sysdba].[PRODUCT]([PRODUCTID], [ACTUALID], [MASITEMKEY])

CREATE STATISTICS [_dta_stat_1579152671_2_10_1] ON [sysdba].[SALESORDERITEMS]([SALESORDERID], [QUANTITY], [SALESORDERITEMSID])
CREATE STATISTICS [_dta_stat_1579152671_2_1_14_15_10] ON [sysdba].[SALESORDERITEMS]([SALESORDERID], [SALESORDERITEMSID], [PRODUCTID], [ACTUALID], [QUANTITY])

CREATE STATISTICS [_dta_stat_1579152671_2_44] ON [sysdba].[SALESORDERITEMS]([SALESORDERID], [MASSHIPPEDDATE])

CREATE STATISTICS [_dta_stat_1579152671_44_10_1] ON [sysdba].[SALESORDERITEMS]([MASSHIPPEDDATE], [QUANTITY], [SALESORDERITEMSID])

CREATE STATISTICS [_dta_stat_1579152671_44_1_2_10_14_15] ON [sysdba].[SALESORDERITEMS]([MASSHIPPEDDATE], [SALESORDERITEMSID], [SALESORDERID], [QUANTITY], [PRODUCTID], [ACTUALID])

CREATE STATISTICS [_dta_stat_1579152671_14_44_1_2] ON [sysdba].[SALESORDERITEMS]([PRODUCTID], [MASSHIPPEDDATE], [SALESORDERITEMSID], [SALESORDERID])

CREATE NONCLUSTERED INDEX [_dta_index_SALESORDERITEMS_5_1579152671__K44_K2_K1_K14] ON [sysdba].[SALESORDERITEMS] 
(
	[MASSHIPPEDDATE] ASC,
	[SALESORDERID] ASC,
	[SALESORDERITEMSID] ASC,
	[PRODUCTID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]


CREATE NONCLUSTERED INDEX [_dta_index_SALESORDERITEMS_5_1579152671__K14_K10_K1_K2_K44_K15] ON [sysdba].[SALESORDERITEMS] 
(
	[PRODUCTID] ASC,
	[QUANTITY] ASC,
	[SALESORDERITEMSID] ASC,
	[SALESORDERID] ASC,
	[MASSHIPPEDDATE] ASC,
	[ACTUALID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [_dta_index_SALESORDERITEMS_5_1579152671__K44_K1_K14_K2_K10_K15] ON [sysdba].[SALESORDERITEMS] 
(
	[MASSHIPPEDDATE] ASC,
	[SALESORDERITEMSID] ASC,
	[PRODUCTID] ASC,
	[SALESORDERID] ASC,
	[QUANTITY] ASC,
	[ACTUALID] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1579152671_10_44_2] ON [sysdba].[SALESORDERITEMS]([QUANTITY], [MASSHIPPEDDATE], [SALESORDERID])

CREATE STATISTICS [_dta_stat_1579152671_10_1_14_2] ON [sysdba].[SALESORDERITEMS]([QUANTITY], [SALESORDERITEMSID], [PRODUCTID], [SALESORDERID])

CREATE NONCLUSTERED INDEX [_dta_index_STOCKCARDITEMS_5_777769828__K7_15_36] ON [sysdba].[STOCKCARDITEMS] 
(
	[PRODUCTID] ASC
)
INCLUDE ( [MAX_STOCKLEVEL],
[MIN_STOCKLEVEL]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1627868866_12_11] ON [sysdba].[TACDISTRIBUTORPRICING]([MOQ], [DISTRIBUTORPRICE])

CREATE NONCLUSTERED INDEX [_dta_index_TACDISTRIBUTORPRICING_5_1627868866__K7_K12_K11] ON [sysdba].[TACDISTRIBUTORPRICING] 
(
	[ITEMKEY] ASC,
	[MOQ] ASC,
	[DISTRIBUTORPRICE] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
