CREATE NONCLUSTERED INDEX [_dta_index_PRODUCT_5_1764201335__K44_K4_46] ON [sysdba].[PRODUCT] 
(
	[WAREHOUSEID] ASC,
	[ACTUALID] ASC
)
INCLUDE ( [QTYONHAND]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [_dta_index_PRODUCT_5_1764201335__K44_K4_K2] ON [sysdba].[PRODUCT] 
(
	[WAREHOUSEID] ASC,
	[ACTUALID] ASC,
	[NAME] ASC
)WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1579152671_44_15_10] ON [sysdba].[SALESORDERITEMS]([MASSHIPPEDDATE], [ACTUALID], [QUANTITY])
CREATE STATISTICS [_dta_stat_1579152671_15_10] ON [sysdba].[SALESORDERITEMS]([ACTUALID], [QUANTITY])
CREATE STATISTICS [_dta_stat_777769828_7_2_1] ON [sysdba].[STOCKCARDITEMS]([PRODUCTID], [ACCOUNTID], [STOCKCARDITEMSID])
CREATE STATISTICS [_dta_stat_777769828_1_2] ON [sysdba].[STOCKCARDITEMS]([STOCKCARDITEMSID], [ACCOUNTID])

CREATE NONCLUSTERED INDEX [_dta_index_STOCKCARDITEMS_5_777769828__K2_K7_K1_15_36] ON [sysdba].[STOCKCARDITEMS] 
(
	[ACCOUNTID] ASC,
	[PRODUCTID] ASC,
	[STOCKCARDITEMSID] ASC
)
INCLUDE ( [MAX_STOCKLEVEL],
[MIN_STOCKLEVEL]) WITH (SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [_dta_stat_1627868866_8_12_11] ON [sysdba].[TACDISTRIBUTORPRICING]([ITEMID], [MOQ], [DISTRIBUTORPRICE])
