Select * from sysdba.PICKINGLIST
Order By CREATEDATE desc

Select * from sysdba.SALESORDER Where SALESORDERID = 'QEAB3A02G59X'
Select * from sysdba.ACCOUNT Where ACCOUNTID = 'AEAB3A0007S0'
Select * From sysdba.TARCUSTOMER Where CustKey = '12219' --A1.MASCUSTKEY
Select * From sysdba.ACCOUNTFINANCIAL AS NationalAcctFin Where NationalAcctFin.CUSTOMERID = Null --A1.MASNATIONALACCTID 
	AND NationalAcctFin.COMPANYCODE = 'EAB' --OrderCustomer.CompanyID
Select * From sysdba.ACCOUNTFINANCIAL AS AcctFin Where AcctFin.ACCOUNTID = 'AEAB3A0007S0' --A1.AccountID --A1.MASNATIONALACCTID 
	AND AcctFin.COMPANYCODE = 'EAB' --OrderCustomer.CompanyID
	
	 
--Select * from sysdba.STGSALESORDER_TAC 

Select * from sysdba.TARCUSTOMER

Select OrderCustomer.CompanyID from sysdba.SALESORDER As S1
LEFT OUTER JOIN sysdba.ACCOUNT AS A1 ON A1.ACCOUNTID = S1.ACCOUNTID 
LEFT OUTER JOIN sysdba.TARCUSTOMER AS OrderCustomer ON OrderCustomer.CustKey = A1.MASCUSTKEY 
Where SALESORDERID = 'QEAB3A01UVQA'

--Delete from sysdba.PICKINGLIST Where SALESORDERID = 'QEAB3A01UVQA'

SELECT A1.PICKINGLISTID, A1.COMPANYID, A1.STATUS, A1.TRANDATE, A1.TRANNO, A1.TRANTYPE 
FROM sysdba.PICKINGLIST A1 WHERE A1.SALESORDERID = 'QEAB3A01UVQA' --:BindID 

Select * From sysdba.SALESORDERITEMS Where SALESORDERITEMSID = 'QEAB3A01UVSM'
Select * From sysdba.PICKINGLISTITEM 
Order By CREATEDATE desc
Where SALESORDERITEMID = 'QEAB3A01UVSM'
Select * From sysdba.PICKINGLISTITEM Where SALESORDERITEMSID = 'QEAB3A01UVSM'


Select * From sysdba.TACGRIDTEMPLATE

Insert Into sysdba.TACGRIDTEMPLATE (CREATEUSER, CREATEDATE, MODIFYUSER, MODIFYDATE, GRIDNAME)
Values ('ADMIN       ', GETDATE(), 'ADMIN       ', GETDATE(), 'PickingListItems')