Select * from sysdba.TACGRIDTEMPLATE

Select * from sysdba.TACGRIDTEMPLATEFIELDS As TF
inner join sysdba.TACGRIDTEMPLATE As T On t.TACGRIDTEMPLATEID = TF.TACGRIDTEMPLATEID 
Where T.GRIDNAME = 'ReturnOrderItems'

Select * from sysdba.TACGRIDTEMPLATEFIELDS As TF
inner join sysdba.TACGRIDTEMPLATE As T On t.TACGRIDTEMPLATEID = TF.TACGRIDTEMPLATEID 
Where T.GRIDNAME = 'AccountStockCardItems'

Insert INTO sysdba.TACGRIDTEMPLATEFIELDS (TACGRIDTEMPLATEFIELDSID, TACGRIDTEMPLATEID, CREATEUSER, CREATEDATE
,MODIFYUSER, MODIFYDATE, FIELDNAME, CAPTION, FIELDSIZE )
Values ('QEAB3A01836D', 'QEAB3A0022QT', 'ADMIN', GETDATE(), 'ADMIN', GETDATE(), 'CALCULATEDPRICE', 'Credit Amount', 75)

Update sysdba.TACGRIDTEMPLATEFIELDS
Set CAPTION = 'Credit Amount'
Where TACGRIDTEMPLATEFIELDSID IN (select TACGRIDTEMPLATEFIELDSID From sysdba.TACGRIDTEMPLATEFIELDS As TF
inner join sysdba.TACGRIDTEMPLATE As T On t.TACGRIDTEMPLATEID = TF.TACGRIDTEMPLATEID 
Where T.GRIDNAME = 'ReturnOrderItems'
and TF.FIELDNAME = 'CALCULATEDPRICE')


Update sysdba.TACGRIDTEMPLATEFIELDS
Set CAPTION = 'List Price'
Where TACGRIDTEMPLATEFIELDSID IN (select TACGRIDTEMPLATEFIELDSID From sysdba.TACGRIDTEMPLATEFIELDS As TF
inner join sysdba.TACGRIDTEMPLATE As T On t.TACGRIDTEMPLATEID = TF.TACGRIDTEMPLATEID 
Where T.GRIDNAME = 'ReturnOrderItems'
and TF.FIELDNAME = 'PRICE')

Update sysdba.TACGRIDTEMPLATEFIELDS
Set CAPTION = 'Orig Price'
Where TACGRIDTEMPLATEFIELDSID IN (select TACGRIDTEMPLATEFIELDSID From sysdba.TACGRIDTEMPLATEFIELDS As TF
inner join sysdba.TACGRIDTEMPLATE As T On t.TACGRIDTEMPLATEID = TF.TACGRIDTEMPLATEID 
Where T.GRIDNAME = 'ReturnOrderItems'
and TF.FIELDNAME = 'ORIGPRODUCTPRICE')