SELECT DISTINCT A1.SALESORDERID, A1.ACCOUNTMANAGERID
, A1.ALTERNATEKEYPREFIX + '-' + A1.ALTERNATEKEYSUFFIX 
, A2.DESCRIPTION A2_DESCRIPTION, A3.ACCOUNT A3_ACCOUNT
, A1.CUSTOMERPURCHASEORDERNUMBER, A1.ORDERTYPE, A1.STATUS, A1.ORDERDATE
, A1.GRANDTOTAL, A1.MASNUMBER, A1.MASSTATUS, A3.MASSALESPERSONID A3_MASSALESPERSONID
, A1.TRANSMITDATE 
FROM sysdba.SALESORDER A1 
INNER JOIN sysdba.ACCOUNT A3 ON (A1.ACCOUNTID=A3.ACCOUNTID) 
LEFT OUTER JOIN sysdba.SALESORDERADDRESS A2 ON (A1.SALESORDERID=A2.SALESORDERID) 
WHERE  
 (UPPER(A1.STATUS) = 'Transmitted to Accounting '
AND ( (A1.MASSTATUS IS NULL) OR (A1.MASSTATUS = ''))) 
AND ((UPPER(A3.MASSALESPERSONID)<> 'EPM')) 
AND (UPPER(A3.MASSALESPERSONID)<>'MBD') 
ORDER BY A1.TRANSMITDATE ASC