define("Sage/UI/Filters/nls/it/CheckBoxFilter", {
    "loadingText": "Caricamento in corso...",
    "moreText": "Modifica elementi",
    "clearText": "Cancella",
    "emptyText": "(Vuoto)",
    "nullText": "(Null)",
    "ofText": "/",
    "filterHasMetric": "Con metrica",
    "filterHasFilter": "Con filtro",
    "filteroptionYesterday": "Ieri",
    "filteroptionToday": "Oggi",
    "filteroptionThisWeek": "Questa settimana",
    "filteroptionThisMonth": "Questo mese",
    "filteroptionThisQuarter": "Questo trimestre",
    "filteroptionThisYear": "Quest'anno",
    "filteroptionLastWeek": "Ultima settimana",
    "filteroptionLastMonth": "Ultimo mese",
    "filteroptionLastQuarter": "Ultimo trimestre",
    "filteroptionLastYear": "Ultimo anno",
    "filteroptionWeektoStart": "Da inizio settimana",
    "filteroptionMonthtoStart": "Da inizio mese",
    "filteroptionQtrtoStart": "Da inizio trimestre",
    "filteroptionYeartoStart": "Da inizio anno",
    "filteroptionOlder": "Più vecchio",
    "filteroption0To999": "Da 0 a 999",
    "filteroption1000To9999": "Da 1000 a 9999",
    "filteroption10000To99999": "Da 10.000 a 99.999",
    "filteroption100000To499999": "Da 100.000 a 499.999",
    "filteroption500000To999999": "Da 500.000 a 999.999",
    "filteroption1000000AndHigher": "Da 1.000.000 in poi",
    "filteroptionT": "T"
});