define("Sage/Services/nls/zh-cn/ActivityService", {
    "txtErrorActionMsg": "很抱歉，操作不成功，发生了错误。",
    "txtActivity": "活动",
    "txtActivities": "活动",
    "txtActionDeleteActivites": "删除活动",
    "txtActionDeleteActivitiesQuestion": "将只删除您有权删除的活动。<P>确定要删除 {0} 个选中的“{1}”吗?",
    "txtAlarm": "提醒",
    "txtAlarms": "提醒",
    "txtActionSnoozeAlarm": "推迟提醒",
    "txtActionSnoozeQuestion": "确定要针对“{2}”推迟 {0} 个选中的“{1}”吗?",
    "txtActionSnoozeAllQuestion": "确定要推迟“{1}”的所有“{0}”吗?",
    "txtActionDismissAlarms": "消除提醒",
    "txtActionDismissAlarmsQuestion": "确定要消除 {0} 个选中的“{1}”吗?",
    "txtEvent": "事件",
    "txtEvents": "事件",
    "txtActionDeleteEvents": "删除事件",
    "txtActionDeleteEventsQuestion": "将只删除您有权删除的事件。<P>确定要删除 {0} 个选中的“{1}”吗?",
    "txtConfirmation": "确认",
    "txtConfirmations": "确认",
    "txtActionAcceptConfirmations": "接受确认",
    "txtActionAcceptConfirmQuestion": "确定要接受 {0} 个选中的“{1}”吗?仅对新建或更改的确认执行此操作。将忽略所有其他情况。",
    "txtDeclineConfirmations": "拒绝确认",
    "txtActionDeclineConfrimQuestion": "确定要拒绝 {0} 个选中的“{1}”吗? 仅对新建或更改的确认执行此操作。将忽略所有其他情况。",
    "txtActionRemoveConfirmations": "删除确认",
    "txtActionRemoveConfirmationsQuestion": "确定要删除 {0} 个选中的“{1}”吗? 仅对负责人、已拒绝或已删除的确认执行此操作。将忽略所有其他情况。",
    "txtLiteratureRequest": "营销材料申请",
    "txtLiteratureRequests": "营销材料申请",
    "txtActionDeleteLiteratureRequests": "删除营销材料申请",
    "txtActionDeleteLiteratureRequestsQuestion": "将只删除您有权删除的营销材料申请。<P>确定要删除 {0} 个选中的“{1}”吗?"
});