define(
"dojo/cldr/nls/az/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbiya Pesosu",
	"CZK_displayName": "Çexiya Korunası",
	"TND_displayName": "Tunis Dinarı",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Yamayka Dolları",
	"PHP_displayName": "Filippin Pesosu",
	"ALL_displayName": "Albaniya Leki",
	"USD_symbol": "US$",
	"LBP_displayName": "Livan Funtu",
	"VND_displayName": "Vyetnam Donqu",
	"LYD_displayName": "Liviya Dinarı",
	"RON_displayName": "Rumıniya Leyi",
	"MKD_displayName": "Makedoniya Dinarı",
	"SEK_displayName": "İsveç Kronu",
	"CNY_displayName": "Çin Yuanı",
	"IDR_displayName": "İndoneziya Rupisi",
	"ILS_displayName": "İsrail Yeni Şekeli",
	"YER_displayName": "Yəmən Rialı",
	"TJS_displayName": "Tacikistan Somonisi",
	"TTD_displayName": "Trinidad və Tobaqo Dolları",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Türkiyə Lirəsi",
	"EUR_displayName": "Avro",
	"AED_displayName": "Birləşmiş Ərəb Əmirlikləri Dirhəmi",
	"KZT_displayName": "Qazaxıstan Tengesi",
	"BHD_displayName": "Bəhreyn Dinarı",
	"RUB_displayName": "Rusiya Rublu",
	"NZD_displayName": "Yeni Zelandiya Dolları",
	"IQD_displayName": "İraq Dinarı",
	"TMT_displayName": "Türkmənistan Manatı",
	"ZWL_displayName": "Zimbabve Dolları (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kırğızıstan Somu",
	"KWD_displayName": "Küveyt Dinarı",
	"AFN_displayName": "Əfqanıstan Əfqanisi",
	"ARS_displayName": "Argentina Pesosu",
	"MAD_displayName": "Mərakeş Dirhəmi",
	"BAM_displayName": "Bosniya-Herseqovina Markası",
	"BOB_displayName": "Boliviya Bolivianosu",
	"BND_displayName": "Bruney Dolları",
	"SGD_displayName": "Sinqapur Dolları",
	"MVR_displayName": "Maldiv Rufiyası",
	"MXN_displayName": "Meksika Pesosu",
	"DZD_displayName": "Əlcəzair Dinarı",
	"MXN_symbol": "MX$",
	"JOD_displayName": "İordaniya Dinarı",
	"PEN_displayName": "Peru Nuevo Solu",
	"GTQ_displayName": "Qvatemala Küetzalı",
	"BYR_displayName": "Belarus Rublu",
	"CAD_displayName": "Kanada Dolları",
	"BZD_displayName": "Beliz Dolları",
	"CLP_displayName": "Çili Pesosu",
	"XOF_displayName": "Fil Dişi Sahili Frankı",
	"NOK_displayName": "Norveç Kronu",
	"DOP_displayName": "Dominika Pesosu",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Cənubi Koreya Vonu",
	"USD_displayName": "ABŞ Dolları",
	"UYU_displayName": "Uruqvay Pesosu",
	"UZS_displayName": "Özbəkistan Somu",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Qatar Rialı",
	"SAR_displayName": "Səudiyyə Riyalı",
	"SYP_displayName": "Suriya Funtu",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Misir Funtu",
	"AMD_displayName": "Ermənistan Dramı",
	"GBP_displayName": "Britaniya Funt Sterlinqi",
	"HUF_displayName": "Macarıstan Forinti",
	"CSD_displayName": "Serbiya Dinarı (2002–2006)",
	"ISK_displayName": "İslandiya Kronu",
	"IRR_displayName": "İran Rialı",
	"OMR_displayName": "Oman Rialı",
	"TWD_displayName": "Tayvan Yeni Dolları",
	"PAB_displayName": "Panama Balboası",
	"UAH_displayName": "Ukrayna Qrivnası",
	"ETB_displayName": "Efiopiya Bırrı",
	"PLN_displayName": "Polşa Zlotısı",
	"VEF_displayName": "Venesuela Bolivarı",
	"ILS_symbol": "₪",
	"AZN_symbol": "man.",
	"AUD_symbol": "A$",
	"BRL_displayName": "Braziliya Realı",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Honq Konq Dolları",
	"NIO_displayName": "Nikaraqua Kordobası",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepal Rupisi",
	"PKR_displayName": "Pakistan Rupisi",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Gürcüstan Larisi",
	"AZN_displayName": "Azərbaycan Manatı",
	"GBP_symbol": "£",
	"MYR_displayName": "Malayziya Ringiti",
	"DKK_displayName": "Danimarka Kronu",
	"THB_displayName": "Tayland Batı",
	"BRL_symbol": "R$",
	"JPY_displayName": "Yaponiya Yeni",
	"KES_displayName": "Keniya Şillinqi",
	"KHR_displayName": "Kamboca Rieli",
	"PYG_displayName": "Paraqvay Quaranisi",
	"VND_symbol": "₫",
	"LKR_displayName": "Şri Lanka Rupisi",
	"BGN_displayName": "Bolqarıstan Levi",
	"BDT_displayName": "Banqladeş Takası",
	"HNL_displayName": "Honduras Lempirası",
	"MOP_displayName": "Makao Patakası",
	"RWF_displayName": "Ruanda Frankı",
	"CHF_displayName": "İsveçrə Frankı",
	"CRC_displayName": "Kosta Rika Kolonu",
	"INR_displayName": "Hindistan Rupisi",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Cənubi Afrika Randı",
	"AUD_displayName": "Avstraliya Dolları",
	"LAK_displayName": "Laos Kipi",
	"MNT_displayName": "Monqoliya Tuqriki",
	"RSD_displayName": "Serbiya Dinarı",
	"HRK_displayName": "Xorvatiya Kunası"
}
//end v1.x content
);