define("Sage/MainView/ActivityMgr/AttendeeLookup/nls/zh-tw/LeadLookupConfig", {
    "contactText": "聯絡人",
    "accountText": "客戶",
    "lookupContactText": "查閱聯絡人",
    "nameText": "名稱",
    "cityText": "城市",
    "stateText": "省/州",
    "workphoneText": "公司電話",
    "emailText": "電子郵件",
    "dialogButtonText": "新增選取項目",
    "cancelText": "關閉",
    "colFirstName": "名字",
    "colLastName": "姓氏",
    "colTitle": "標題",
    "colCompany": "公司",
    "colWorkPhone": "公司電話",
    "colEmail": "電子郵件",
    "dialogTitleText": "查閱銷售線索"
});