define(
"dojo/cldr/nls/ar/currency", //begin v1.x content
{
	"COP_displayName": "بيزو كولومبي",
	"CZK_displayName": "كرونة تشيكية",
	"TND_displayName": "دينارتونسي",
	"EUR_symbol": "€",
	"LYD_symbol": "د.ل.‏",
	"CAD_symbol": "CA$",
	"JMD_displayName": "دولار جامايكي",
	"PHP_displayName": "بيزو فلبيني",
	"ALL_displayName": "ليك ألباني",
	"SAR_symbol": "ر.س.‏",
	"USD_symbol": "US$",
	"LBP_displayName": "جنية لبناني",
	"VND_displayName": "دونج فيتنامي",
	"LYD_displayName": "دينار ليبي",
	"RON_displayName": "ليو روماني",
	"MKD_displayName": "دينار مقدوني",
	"QAR_symbol": "ر.ق.‏",
	"SEK_displayName": "كرونة سويدية",
	"CNY_displayName": "يوان صيني",
	"IDR_displayName": "روبية إندونيسية",
	"ILS_displayName": "شيكل إسرائيلي جديد",
	"YER_displayName": "ريال يمني",
	"TJS_displayName": "سوموني طاجيكستاني",
	"TTD_displayName": "دولار ترينداد وتوباجو",
	"CNY_symbol": "ي.ص",
	"TRY_displayName": "ليرة تركية",
	"EUR_displayName": "يورو",
	"AED_displayName": "درهم إماراتي",
	"KZT_displayName": "تينغ كازاخستاني",
	"BHD_displayName": "دينار بحريني",
	"RUB_displayName": "روبل روسي",
	"LBP_symbol": "ل.ل.‏",
	"NZD_displayName": "دولار نيوزيلندي",
	"IQD_displayName": "دينار عراقي",
	"TMT_displayName": "مانات تركمانستان",
	"ZWL_displayName": "دولار زمبابوي 2009",
	"AED_symbol": "د.إ.‏",
	"INR_symbol": "ر.ه.‏",
	"KGS_displayName": "سوم قيرغستاني",
	"KWD_displayName": "دينار كويتي",
	"BHD_symbol": "د.ب.‏",
	"AFN_displayName": "أفغاني",
	"ARS_displayName": "بيزو أرجنتيني",
	"MAD_displayName": "درهم مغربي",
	"BAM_displayName": "مارك البوسنة والهرسك قابل للتحويل",
	"BOB_displayName": "بوليفيانو بوليفي",
	"BND_displayName": "دولار بروناي",
	"SGD_displayName": "دولار سنغافوري",
	"MVR_displayName": "روفيه جزر المالديف",
	"MXN_displayName": "بيزو مكسيكي",
	"DZD_displayName": "دينار جزائري",
	"MXN_symbol": "MX$",
	"JOD_displayName": "دينار أردني",
	"PEN_displayName": "سول جديد البيرو",
	"IQD_symbol": "د.ع.‏",
	"GTQ_displayName": "كوتزال جواتيمالا",
	"BYR_displayName": "روبل بيلاروسي",
	"CAD_displayName": "دولار كندي",
	"BZD_displayName": "دولار بليزي",
	"CLP_displayName": "بيزو شيلي",
	"XOF_displayName": "فرنك سي إف إيه غرب إفريقيا",
	"KWD_symbol": "د.ك.‏",
	"NOK_displayName": "كرونة نرويجية",
	"DOP_displayName": "بيزو الدومنيكان",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "وون كوريا الجنوبية",
	"USD_displayName": "دولار أمريكي",
	"UYU_displayName": "بيزو اوروغواي",
	"UZS_displayName": "سوم أوزبكستاني",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ريال قطري",
	"SAR_displayName": "ريال سعودي",
	"SYP_displayName": "ليرة سورية",
	"EGP_symbol": "ج.م.‏",
	"NZD_symbol": "NZ$",
	"OMR_symbol": "ر.ع.‏",
	"EGP_displayName": "جنيه مصري",
	"AMD_displayName": "درام أرميني",
	"GBP_displayName": "جنيه إسترليني",
	"HUF_displayName": "فورينت مجري",
	"CSD_displayName": "دينار صربي قديم",
	"ISK_displayName": "كرونه أيسلندي",
	"IRR_displayName": "ريال إيراني",
	"OMR_displayName": "ريال عماني",
	"TWD_displayName": "دولار تايواني",
	"PAB_displayName": "بالبوا بنمي",
	"UAH_displayName": "هريفنيا أوكراني",
	"ETB_displayName": "بير أثيوبي",
	"PLN_displayName": "زلوتي بولندي",
	"VEF_displayName": "بوليفار فنزويلي",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "ريال برازيلي",
	"HKD_symbol": "HK$",
	"HKD_displayName": "دولار هونج كونج",
	"JOD_symbol": "د.أ.‏",
	"NIO_displayName": "قرطبة نيكاراغوا",
	"THB_symbol": "฿",
	"NPR_displayName": "روبية نيبالي",
	"SYP_symbol": "ل.س.‏",
	"MAD_symbol": "د.م.‏",
	"PKR_displayName": "روبية باكستاني",
	"TWD_symbol": "NT$",
	"GEL_displayName": "لارى جورجي",
	"AZN_displayName": "مانات أذربيجان",
	"GBP_symbol": "£",
	"MYR_displayName": "رينغيت ماليزي",
	"DZD_symbol": "د.ج.‏",
	"DKK_displayName": "كرونة دانماركي",
	"THB_displayName": "باخت تايلاندي",
	"BRL_symbol": "R$",
	"JPY_displayName": "ين ياباني",
	"KES_displayName": "شلن كينيي",
	"KHR_displayName": "رييال كمبودي",
	"PYG_displayName": "جواراني باراجواي",
	"VND_symbol": "₫",
	"BGN_displayName": "ليف بلغاري",
	"BDT_displayName": "تاكا بنجلاديشي",
	"LKR_displayName": "روبية سريلانكية",
	"HNL_displayName": "ليمبيرا هنداروس",
	"MOP_displayName": "باتاكا ماكاوي",
	"RWF_displayName": "فرنك رواندي",
	"TND_symbol": "د.ت.‏",
	"CHF_displayName": "فرنك سويسري",
	"CRC_displayName": "كولن كوستا ريكي",
	"INR_displayName": "روبيه هندي",
	"KRW_symbol": "₩",
	"ZAR_displayName": "راند جنوب أفريقيا",
	"AUD_displayName": "دولار أسترالي",
	"LAK_displayName": "كيب لاوسي",
	"MNT_displayName": "توغروغ منغولي",
	"RSD_displayName": "دينار صربي",
	"HRK_displayName": "كونا كرواتي",
	"YER_symbol": "ر.ي.‏"
}
//end v1.x content
);