define(
"dojo/cldr/nls/hy/currency", //begin v1.x content
{
	"COP_displayName": "Կոլումբիական պեսո",
	"CZK_displayName": "Չեխական կրոնա",
	"TND_displayName": "Թունիսական դինար",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Ջամայկական դոլար",
	"PHP_displayName": "Ֆիլիպինական պեսո",
	"ALL_displayName": "Ալբանական լեկ",
	"USD_symbol": "$",
	"LBP_displayName": "Լիբանանական ֆունտ",
	"VND_displayName": "Վիետնամական դոնգ",
	"LYD_displayName": "Լիբիական դինար",
	"RON_displayName": "Ռումինական լեյ",
	"MKD_displayName": "Մակեդոնական դենար",
	"SEK_displayName": "Շվեդական կրոնա",
	"CNY_displayName": "Չինական յուան",
	"IDR_displayName": "Ինդոնեզական ռուփի",
	"ILS_displayName": "Իսրայելի նոր շեկել",
	"YER_displayName": "Եմենական ռիալ",
	"TJS_displayName": "Տաջիկական սոմոնի",
	"TTD_displayName": "Տրինիդադ և Տոբագոյի դոլար",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Թուրքական լիրա",
	"EUR_displayName": "Եվրո",
	"AED_displayName": "Արաբական Միացյալ Էմիրությունների դիրհամ",
	"KZT_displayName": "Ղազախական տենգե",
	"BHD_displayName": "Բահրեյնական դինար",
	"RUB_displayName": "Ռուսական ռուբլի",
	"NZD_displayName": "Նորզելանդական դոլար",
	"IQD_displayName": "Իրաքյան դինար",
	"TMT_displayName": "Թուրքմենական մանաթ",
	"INR_symbol": "₹",
	"KGS_displayName": "Ղրղզական սոմ",
	"KWD_displayName": "Քուվեյթական դինար",
	"AFN_displayName": "Աֆղանական աֆղանի",
	"ARS_displayName": "Արգենտինական պեսո",
	"MAD_displayName": "Մարոկական դիրհամ",
	"BAM_displayName": "Բոսնիա և Հերցեգովինայի փոխարկելի մարկա",
	"BOB_displayName": "Բոլիվիական բոլիվիանո",
	"BND_displayName": "Բրունեյական դոլար",
	"SGD_displayName": "Սինգապուրյան դոլար",
	"MVR_displayName": "Մալդիվյան ռուֆիա",
	"MXN_displayName": "Մեքսիկական պեսո",
	"DZD_displayName": "Ալժիրական դինար",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Հորդանանական դինար",
	"PEN_displayName": "Պերուի նոր սոլ",
	"GTQ_displayName": "Գվատեմալական կետսալ",
	"BYR_displayName": "Բելառուսական ռուբլի",
	"CAD_displayName": "Կանադական դոլար",
	"BZD_displayName": "Բելիզի դոլար",
	"CLP_displayName": "Չիլիական պեսո",
	"XOF_displayName": "Աֆրիկական ֆինանսական համայնքի ֆրանկ BCEAO",
	"NOK_displayName": "Նորվեգական կրոնա",
	"DOP_displayName": "Դոմինիկական պեսո",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Հարավկորեական վոնա",
	"USD_displayName": "ԱՄՆ դոլար",
	"UYU_displayName": "Ուրուգվայական պեսո",
	"UZS_displayName": "Ուզբեկական սում",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Քաթարական ռիալ",
	"AMD_symbol": "դր.",
	"SAR_displayName": "Սաուդյան Արաբիայի ռիալ",
	"SYP_displayName": "Սիրիական ֆունտ",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Եգիպտական ֆունտ",
	"AMD_displayName": "Հայկական դրամ",
	"GBP_displayName": "Բրիտանական ֆունտ ստեռլինգ",
	"HUF_displayName": "Հունգարական ֆորինտ",
	"ISK_displayName": "Իսլանդական կրոնա",
	"IRR_displayName": "Իրանական ռիալ",
	"OMR_displayName": "Օմանական ռիալ",
	"TWD_displayName": "Թայվանական նոր դոլար",
	"PAB_displayName": "Պանամական բալբոա",
	"UAH_displayName": "Ուկրաինական գրիվնա",
	"ETB_displayName": "Եթովպական բիր",
	"PLN_displayName": "Լեհական զլոտի",
	"VEF_displayName": "Վենեսուելական բոլիվար",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Բրազիլական ռեալ",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Հոնկոնգի դոլար",
	"NIO_displayName": "Նիկարագուական կորդոբա",
	"THB_symbol": "฿",
	"NPR_displayName": "Նեպալական ռուփի",
	"PKR_displayName": "Պակիստանական ռուփի",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Վրացական լարի",
	"AZN_displayName": "Ադրբեջանական մանաթ",
	"GBP_symbol": "£",
	"MYR_displayName": "Մալայզիական ռինգիտ",
	"DKK_displayName": "Դանիական կրոնա",
	"THB_displayName": "Թաիլանդական բատ",
	"BRL_symbol": "R$",
	"JPY_displayName": "Ճապոնական իեն",
	"KES_displayName": "Քենիական շիլինգ",
	"KHR_displayName": "Կամբոջական ռիել",
	"PYG_displayName": "Պարագվայական գուարանի",
	"VND_symbol": "₫",
	"LKR_displayName": "Լանկիական ռուփի",
	"BGN_displayName": "Բուլղարական լև",
	"BDT_displayName": "Բանգլադեշի տակա",
	"MOP_displayName": "Մակաոյի պատակա",
	"HNL_displayName": "Հոնդուրասական լեմպրիա",
	"RWF_displayName": "Ռուանդական ֆրանկ",
	"CHF_displayName": "Շվեյցարական ֆրանկ",
	"CRC_displayName": "Կոստա Ռիկայի կոլոն",
	"INR_displayName": "Հնդկական ռուփի",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Հարավաֆրիկական ռենդ",
	"AUD_displayName": "Ավստրալական դոլար",
	"LAK_displayName": "Լաոսական կիպ",
	"MNT_displayName": "Մոնղոլական տուգրիկ",
	"RSD_displayName": "Սերբական դինար",
	"HRK_displayName": "Խորվաթական կունա"
}
//end v1.x content
);