define(
"dojo/cldr/nls/mr/currency", //begin v1.x content
{
	"COP_displayName": "कोलंबियन पेसो",
	"CZK_displayName": "झेक प्रजासत्ताक कोरुना",
	"TND_displayName": "ट्यूनिसियन दिनार",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "जमैकन डॉलर",
	"PHP_displayName": "फिलिपिनी पेसो",
	"ALL_displayName": "अल्बानियन लेक",
	"USD_symbol": "$",
	"LBP_displayName": "लेबनीज पाउंड",
	"VND_displayName": "व्हिएतनामी डोंग",
	"LYD_displayName": "लिबियाचा दिनार",
	"RON_displayName": "रोमानियन लेऊ",
	"MKD_displayName": "मॅसेडोनियन दिनार",
	"SEK_displayName": "स्वीडिश क्रोन",
	"CNY_displayName": "चीनी युआन",
	"IDR_displayName": "इंडोनेशियन रुपैयाह",
	"ILS_displayName": "ईस्त्रायली न्यू शेकेल",
	"YER_displayName": "येमेनी रियाल",
	"TJS_displayName": "ताजकीस्तानी सोमोनी",
	"TTD_displayName": "त्रिनिदाद आणि टोबॅगो डॉलर",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "तुर्की लिरा",
	"EUR_displayName": "यूरो",
	"AED_displayName": "संयुक्त अरब अमीरात दिरहॅम",
	"KZT_displayName": "कझाकिस्तानी तेंगे",
	"BHD_displayName": "बाहरिनी दिनार",
	"RUB_displayName": "रशियन रुबल",
	"NZD_displayName": "न्यूझीलँड डॉलर",
	"IQD_displayName": "इराकी दिनार",
	"TMT_displayName": "तुर्कमेनिस्तानी मानाट",
	"INR_symbol": "₹",
	"KGS_displayName": "किरगिस्तानी सॉम",
	"KWD_displayName": "कुवैती दिनार",
	"AFN_displayName": "अफगाण अफगाणी",
	"ARS_displayName": "अर्जेंटाइन पेसो",
	"MAD_displayName": "मोरोक्को दिरहॅम",
	"BAM_displayName": "बोस्निया-हर्जेगोविना कन्व्हर्टिबल मार्क",
	"BOB_displayName": "बोलिव्हियन बोलिव्हियानो",
	"BND_displayName": "ब्रुनेई डॉलर",
	"SGD_displayName": "सिंगापूर डॉलर",
	"MVR_displayName": "मालदीवियन रुफिया",
	"MXN_displayName": "मेक्सिको पेसो",
	"DZD_displayName": "अल्जेरियन दिनार",
	"MXN_symbol": "MX$",
	"JOD_displayName": "जॉर्डनियन दिनार",
	"PEN_displayName": "पेरुवियन नुइव्हो सोल",
	"GTQ_displayName": "ग्वाटेमालाचे क्वेत्झाल",
	"BYR_displayName": "बेलारुशियन रुबल",
	"CAD_displayName": "कॅनडियन डॉलर",
	"BZD_displayName": "बेलीझ डॉलर",
	"CLP_displayName": "चिली पेसो",
	"XOF_displayName": "[CFA] फ्रँक [BCEAO]",
	"NOK_displayName": "नॉर्वेजियन क्रोन",
	"DOP_displayName": "डोमिनिकन पेसो",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "दक्षिण कोरियन वॉन",
	"USD_displayName": "यूएस डॉलर",
	"UYU_displayName": "उरुग्वेचा पेसो",
	"UZS_displayName": "उझबेकिस्तान सॉम",
	"XOF_symbol": "CFA",
	"QAR_displayName": "कतारी रियाल",
	"SAR_displayName": "सौदी रियाल",
	"SYP_displayName": "सीरियन पाउंड",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "इजिप्शियन पाउंड",
	"AMD_displayName": "आर्मेनियन द्रॅम",
	"GBP_displayName": "ब्रिटिश पाऊंड स्टर्लिंग",
	"HUF_displayName": "हंगेरियन फॉरिन्ट",
	"ISK_displayName": "आइसलँडिक क्रोन",
	"IRR_displayName": "इराणी रियाल",
	"OMR_displayName": "ओमानी रियाल",
	"TWD_displayName": "न्यू तैवान डॉलर",
	"PAB_displayName": "पनामा बाल्बोआ",
	"UAH_displayName": "यूक्रेनियन हरिन्या",
	"ETB_displayName": "इथिओपियन बिर",
	"PLN_displayName": "पोलिश झ्लॉटी",
	"VEF_displayName": "व्हेनेझुएला बोलिव्हार",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ब्राझिलियन रेयाल",
	"HKD_symbol": "HK$",
	"HKD_displayName": "हाँगकाँग डॉलर",
	"NIO_displayName": "निकाराग्वेचा कोर्डोबा",
	"THB_symbol": "฿",
	"NPR_displayName": "नेपाळी रुपया",
	"PKR_displayName": "पाकिस्तानी रुपया",
	"TWD_symbol": "NT$",
	"GEL_displayName": "जॉर्जियन लारी",
	"AZN_displayName": "अझरबैझानी मानाट",
	"GBP_symbol": "£",
	"MYR_displayName": "मलेशियन रिंगिट",
	"DKK_displayName": "डॅनिश क्रोन",
	"THB_displayName": "थाई बाहत",
	"BRL_symbol": "R$",
	"JPY_displayName": "जपानी येन",
	"KES_displayName": "केनियन शिलिंग",
	"KHR_displayName": "कंबोडियन रियेल",
	"PYG_displayName": "पराग्वे ग्वारानी",
	"VND_symbol": "₫",
	"LKR_displayName": "श्रीलंकन रुपी",
	"BGN_displayName": "बल्गेरियन लेव",
	"BDT_displayName": "बांगलादेशी टका",
	"MOP_displayName": "मॅकॅनीज् पटाका",
	"HNL_displayName": "होंडुरा लेम्पियरा",
	"RWF_displayName": "रवांडा फ्रँक",
	"CHF_displayName": "स्विस फ्रँक",
	"CRC_displayName": "कोस्टा रिका कोलोन",
	"INR_displayName": "भारतीय रुपया",
	"KRW_symbol": "₩",
	"ZAR_displayName": "दक्षिण आफ्रिकी रँड",
	"AUD_displayName": "ऑस्ट्रेलियन डॉलर",
	"LAK_displayName": "लेओशियन किप",
	"MNT_displayName": "मंगोलियन टुग्रिक",
	"RSD_displayName": "सर्बियन दिनार",
	"HRK_displayName": "क्रोएशियन कूना"
}
//end v1.x content
);