define("Sage/Utility/nls/fr/Activity", {
    "ToDo": "Tâche à faire",
    "PhoneCall": "Appel téléphonique",
    "Meeting": "Rendez-vous",
    "Personal": "Activité personnelle",
    "Literature": "Documentation",
    "Fax": "Fax",
    "Letter": "Lettre",
    "Note": "Note",
    "Email": "E-mail",
    "Document": "Document",
    "DatabaseChange": "Modification de la base de données",
    "Event": "Evénement",
    "ScheduledEvent": "Evénement planifié",
    "Contact": "Contact",
    "Lead": "Lead",
    "New": "Nouveau",
    "Change": "Modifier",
    "Deleted": "Supprimé",
    "Confirm": "Confirmer",
    "Decline": "Refuser",
    "Unknown": "Inconnu",
    "Leader": "Responsable",
    "Complete": "Terminer",
    "confirmTypeChanged": "Modifié",
    "confirmTypeConfirmed": "Confirmé",
    "confirmTypeDeleted": "Supprimé",
    "timelessText": "Heure indéfinie"
});