define(
"dojo/cldr/nls/mk/currency", //begin v1.x content
{
	"COP_displayName": "Колумбиски Пезос",
	"CZK_displayName": "Чешка корона",
	"TND_displayName": "Тунизиски динар",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Јамајкански долар",
	"PHP_displayName": "Филипински пезос",
	"ALL_displayName": "Албански Лек",
	"USD_symbol": "US$",
	"LBP_displayName": "Либанска фунта",
	"VND_displayName": "Виетнамски донг",
	"LYD_displayName": "Либијски динар",
	"RON_displayName": "Романска леи",
	"MKD_displayName": "Македонски денар",
	"SEK_displayName": "Шведска круна",
	"CNY_displayName": "Кинески јуан",
	"IDR_displayName": "Индонезиска рупија",
	"ILS_displayName": "Израелски нов шекел",
	"YER_displayName": "Јеменски риал",
	"TJS_displayName": "Таџикистански сомони",
	"CNY_symbol": "CNY",
	"TRY_displayName": "Турска лира",
	"EUR_displayName": "Евро",
	"AED_displayName": "Обединети Арапски Емирати Дирхам",
	"KZT_displayName": "Казахстанска тенга",
	"BHD_displayName": "Бахреински Динар",
	"RUB_displayName": "Руска рубља",
	"NZD_displayName": "Новозеландски долар",
	"IQD_displayName": "Ирачки динар",
	"INR_symbol": "INR",
	"KGS_displayName": "Киргистански сом",
	"KWD_displayName": "Кувајтски динар",
	"AFN_displayName": "Авгани",
	"ARS_displayName": "Аргентински Пезос",
	"MAD_displayName": "Марокански Дирхам",
	"BAM_displayName": "Босанско-Херцеговска конвертибилна марка",
	"BND_displayName": "Брунејски долар",
	"SGD_displayName": "Сингапурски долар",
	"MVR_displayName": "Малдивиска руфија",
	"MXN_displayName": "Мексикански пезос",
	"DZD_displayName": "Алжирски Динар",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Јордански динар",
	"PEN_displayName": "Перуански нов сол",
	"GTQ_displayName": "Гватемалски кветцал",
	"BYR_displayName": "Белоруска рубља",
	"CAD_displayName": "Канадски долар",
	"BZD_displayName": "Белизиски Долар",
	"CLP_displayName": "Чилеански пезос",
	"NOK_displayName": "Норвешка круна",
	"DOP_displayName": "Доминикански Пезос",
	"JPY_symbol": "JPY",
	"KRW_displayName": "Јужно корејски вон",
	"USD_displayName": "Американски долар",
	"UYU_displayName": "Уругвајски пезос",
	"UZS_displayName": "Узбекистански сом",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Катарски риал",
	"SAR_displayName": "Саудиски ријал",
	"SYP_displayName": "Сиријска фунта",
	"NZD_symbol": "NZD",
	"EGP_displayName": "Египетска Фунта",
	"AMD_displayName": "Ермениски Драм",
	"GBP_displayName": "Британска Фунта",
	"HUF_displayName": "Унгарска форинта",
	"ISK_displayName": "Исландска крона",
	"IRR_displayName": "Ирански риал",
	"OMR_displayName": "Омански риал",
	"TWD_displayName": "Тајвански нов долар",
	"PAB_displayName": "Панамска балбоа",
	"UAH_displayName": "Украинска хривнија",
	"ETB_displayName": "Етиописки Бир",
	"PLN_displayName": "Полска злота",
	"VEF_displayName": "Венецуелски боливар",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "Бразилски реал",
	"HKD_symbol": "HKD",
	"HKD_displayName": "Хонгконшки долар",
	"NIO_displayName": "Никарагванска кордоба",
	"THB_symbol": "THB",
	"NPR_displayName": "Непалска рупија",
	"PKR_displayName": "Пакистанска рупија",
	"TWD_symbol": "TWD",
	"GEL_displayName": "Грузиски лари",
	"AZN_displayName": "Азербејџански манат",
	"GBP_symbol": "GBP",
	"MYR_displayName": "Малазиски рингит",
	"DKK_displayName": "Данска круна",
	"THB_displayName": "Таи бат",
	"BRL_symbol": "R$",
	"JPY_displayName": "Јапонски јен",
	"KES_displayName": "Кениски шилинг",
	"KHR_displayName": "Камбоџиски рел",
	"PYG_displayName": "Парагвајска гуарана",
	"VND_symbol": "VND",
	"LKR_displayName": "Шриланканска рупија",
	"BGN_displayName": "Бугарски лев",
	"BDT_displayName": "Бангладешка така",
	"MOP_displayName": "Макао патака",
	"HNL_displayName": "Хондурска лемпира",
	"RWF_displayName": "Руандски франк",
	"CHF_displayName": "Швајцарски Франк",
	"CRC_displayName": "Костарикански колон",
	"INR_displayName": "Индијска рупија",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "Јужно афрички ранд",
	"AUD_displayName": "Австралиски долар",
	"LAK_displayName": "Лаоски кип",
	"MNT_displayName": "Монголиски тугрик",
	"MKD_symbol": "ден",
	"RSD_displayName": "Српски динар",
	"HRK_displayName": "Хрватска Куна"
}
//end v1.x content
);