define("Sage/MainView/ActivityMgr/templates/nls/zh-tw/ConfirmationDetailSummary", {
    "txtPhone_Caption": "電話:",
    "lnkOpportunity_Caption": "商機:",
    "txtStartTime_Caption": "開始時間:",
    "lnkContactName_Caption": "聯絡人:",
    "lnkLeadName_Caption": "銷售線索:",
    "lnkTicket_Caption": "記錄單:",
    "txtLocation_Caption": "位置:",
    "txtLeader_Caption": "負責人:",
    "txtDuration_Caption": "持續時間:",
    "lnkAccountName_Caption": "客戶:",
    "lnkCompanyName_Caption": "公司:",
    "txtNotes_Caption": "備註:",
    "btnComplete_Caption": "完成",
    "txtFromUser_Caption": "從:",
    "btnDelete_Caption": "刪除",
    "btnDecline_Caption": "拒絕",
    "btnAccept_Caption": "接受"
});