define("Sage/MainView/ReportMgr/Crystal/nls/ru/_ParameterEditorBase", {
    "txtPleaseSpecifyValue": "Укажите значение.",
    "lblAvailableValues_Caption": "Доступные значения:",
    "lblSelectedValues_Caption": "Выбранные значения:",
    "lblEnterValue_Caption": "Введите значение",
    "btnOK_Caption": "OК",
    "txtTheValueMustBeBetween": "Длина значения должна составлять от {0} до {1} символов.",
    "txtTheMinimumLengthForThisField": "Минимальная длина этого поля: {0}.",
    "txtTheMaximumLengthForThisField": "Максимальная длина этого поля: {0}.",
    "txtPleaseSpecifyNumberBetween": "Укажите числовое значение от {0} до {1}.",
    "txtPleaseSpecifyNumberLesser": "Укажите числовое значение, меньшее или равное {0}.",
    "txtPleaseSpecifyNumberGreater": "Укажите числовое значение, большее или равное {0}.",
    "txtNoLowerValue": "Нет меньшего значения",
    "txtNoUpperValue": "Нет большего значения",
    "txtIncludeThisValue": "Включить это значение",
    "txtFrom": "От:",
    "txtTo": "До:",
    "txtPleaseSpecifyFromValue": "Укажите начальное значение диапазона",
    "txtPleaseSpecifyToValue": "Укажите конечное значение диапазона",
    "txtPleaseSpecifyDateBetween": "Укажите значение даты в диапазоне от {0} до {1}.",
    "txtPleaseSpecifyDateLesser": "Укажите значение даты, меньшее или равное {0}.",
    "txtPleaseSpecifyDateGreater": "Укажите значение даты, большее или равное {0}.",
    "txtFromMustBeLessThanOrEqualToTo": "Начальное значение диапазона должно быть меньше или равно конечному значению диапазона.",
    "txtStartOfRange": "Начало диапазона:",
    "txtEndOfRange": "Конец диапазона:",
    "txtAddRange": "Добавить диапазон",
    "lblSelectValue_Caption": "Выберите значение:",
    "lblOrValue_Caption": "Или"
});