define("Sage/UI/Controls/nls/de/PropertyStore", {
    "text": "Text",
    "memo": "Memo",
    "unicodeText": "Unicode-Text",
    "unicodeMemo": "Unicode-Memo",
    "integer": "Ganzzahl",
    "double": "Double",
    "single": "Single",
    "decimal": "Dezimal",
    "short": "Kurz",
    "standardId": "Standard-ID",
    "trueFalse": "Wahr/Falsch",
    "yesNo": "Ja/Nein",
    "boolean": "Boolesch",
    "dateTime": "Datum/Uhrzeit",
    "email": "E-Mail",
    "phone": "Telefon",
    "pickList": "Auswahlliste",
    "owner": "Zugriffsberechtigter",
    "lookup": "Suchen",
    "dependencyLookup": "Abhängigkeitensuche",
    "char": "Zeichen",
    "enum_": "Enum",
    "guid": "Guid",
    "byte": "Byte",
    "binary": "Binär",
    "url": "URL",
    "string": "Zeichenfolge",
    "number": "Zahl",
    "calc": "Berechnetes Feld",
    "calcSF": "Berechnete Zeichenfolge",
    "calcNF": "Berechnete Zahl"
});