define(
"dojo/cldr/nls/sl/currency", //begin v1.x content
{
	"COP_displayName": "kolumbijski peso",
	"CZK_displayName": "češka krona",
	"TND_displayName": "tunizijski dinar",
	"CAD_symbol": "CAD",
	"JMD_displayName": "jamajški dolar",
	"PHP_displayName": "filipinski peso",
	"ALL_displayName": "albanski lek",
	"USD_symbol": "$",
	"LBP_displayName": "libanonski funt",
	"VND_displayName": "vientnamski dong",
	"LYD_displayName": "libijski dinar",
	"RON_displayName": "romunski leu",
	"MKD_displayName": "makedonski denar",
	"SEK_displayName": "švedska krona",
	"CNY_displayName": "kitajski juan renminbi",
	"IDR_displayName": "indonezijska rupija",
	"ILS_displayName": "izraelski šekel",
	"YER_displayName": "jemenski rial",
	"TJS_displayName": "tadžikistanski somoni",
	"TTD_displayName": "dolar Trinidada in Tobaga",
	"TRY_displayName": "nova turška lira",
	"EUR_displayName": "evro",
	"AED_displayName": "dirham Združenih arabskih emiratov",
	"KZT_displayName": "kazahstanski tenge",
	"BHD_displayName": "bahranski dinar",
	"RUB_displayName": "ruski rubelj",
	"NZD_displayName": "novozelandski dolar",
	"IQD_displayName": "iraški dinar",
	"TMT_displayName": "turkmenistanski novi manat",
	"ZWL_displayName": "zimbabvejski dolar (2009)",
	"KGS_displayName": "kirgiški som",
	"KWD_displayName": "kuvajtski dinar",
	"AFN_displayName": "afgani",
	"ARS_displayName": "argentinski peso",
	"MAD_displayName": "maroški dirham",
	"BAM_displayName": "bosansko-hercegovska konvertibilna marka",
	"BOB_displayName": "bolivijski boliviano",
	"BND_displayName": "brunejski dolar",
	"SGD_displayName": "singapurski dolar",
	"MVR_displayName": "maldivska rufija",
	"MXN_displayName": "mehiški peso",
	"DZD_displayName": "alžirski dinar",
	"JOD_displayName": "jordanski dinar",
	"PEN_displayName": "perujski novi sol",
	"GTQ_displayName": "gvatemalski kecal",
	"BYR_displayName": "beloruski rubelj",
	"CAD_displayName": "kanadski dolar",
	"BZD_displayName": "belizejski dolar",
	"CLP_displayName": "čilski peso",
	"XOF_displayName": "CFA frank BCEAO",
	"NOK_displayName": "norveška krona",
	"DOP_displayName": "dominikanski peso",
	"JPY_symbol": "¥",
	"KRW_displayName": "južnokorejski von",
	"USD_displayName": "ameriški dolar",
	"UYU_displayName": "urugvajski peso",
	"UZS_displayName": "uzbeški sum",
	"QAR_displayName": "katarski rial",
	"SAR_displayName": "saudski rial",
	"SYP_displayName": "sirijski funt",
	"EGP_displayName": "egiptovski funt",
	"AMD_displayName": "armenski dram",
	"GBP_displayName": "britanski funt",
	"HUF_displayName": "madžarski forint",
	"CSD_displayName": "stari srbski dinar",
	"ISK_displayName": "islandska krona",
	"IRR_displayName": "iranski rial",
	"OMR_displayName": "omanski rial",
	"TWD_displayName": "novi tajvanski dolar",
	"PAB_displayName": "panamska balboa",
	"UAH_displayName": "ukrajinska grivna",
	"ETB_displayName": "etiopski bir",
	"PLN_displayName": "poljski novi zlot",
	"VEF_displayName": "venezuelski bolivar",
	"BRL_displayName": "brazilski real",
	"HKD_displayName": "hongkonški dolar",
	"NIO_displayName": "nikaraška zlata kordova",
	"NPR_displayName": "nepalska rupija",
	"PKR_displayName": "pakistanska rupija",
	"GEL_displayName": "gruzijski lari",
	"AZN_displayName": "azerbajdžanski manat",
	"MYR_displayName": "malezijski ringit",
	"DKK_displayName": "danska krona",
	"THB_displayName": "tajski baht",
	"JPY_displayName": "japonski jen",
	"KES_displayName": "kenijski šiling",
	"KHR_displayName": "kamboški riel",
	"PYG_displayName": "paragvajski gvarani",
	"LKR_displayName": "šrilanška rupija",
	"BGN_displayName": "bolgarski lev",
	"BDT_displayName": "bangladeška taka",
	"MOP_displayName": "makavska pataka",
	"HNL_displayName": "honduraška lempira",
	"RWF_displayName": "ruandski frank",
	"CHF_displayName": "švicarski frank",
	"CRC_displayName": "kostariški kolon",
	"INR_displayName": "indijska rupija",
	"ZAR_displayName": "južnoafriški rand",
	"AUD_displayName": "avstralski dolar",
	"LAK_displayName": "laoški kip",
	"MNT_displayName": "mongolski tugrik",
	"RSD_displayName": "srbski dinar",
	"HRK_displayName": "hrvaška kuna"
}
//end v1.x content
);