define("Sage/MainView/ReportMgr/nls/fr/BaseReportScheduleEditor", {
    "dlgReportScheduleDetails_Schedule_Title": "Ajouter/modifier la planification",
    "dlgReportScheduleDetails_RunReport_Title": "Exécuter le rapport",
    "txtReportType_Caption": "Type de rapport",
    "txtReportName_Caption": "Nom du rapport",
    "txtOutputFormat_Caption": "Format",
    "txtRunAs_Caption": "Exécuter comme",
    "txtScheduleName_Caption": "Nom de la planification",
    "txtScheduleDescription_Caption": "Description",
    "cmbScheduleFrequency_Caption": "Fréquence",
    "cmbArchive_Caption": "Archiver les rapports de plus de",
    "dtStartTime_Caption": "Exécuter du",
    "dtEndTime_Caption": "Exécuter jusqu'au",
    "txtRepeatCount_Caption": "Nombre de répétitions",
    "txtRepeatInterval_Caption": "Intervalle de répétition",
    "cmdOK_Caption": "OK",
    "cmdCancel_Caption": "Annuler",
    "tabSchedule_Caption": "Détails de la planification",
    "txtOnDemandScheduleName": "A la demande",
    "txtReportSuccessfullyScheduled": "Rapport planifié.",
    "dlgScheduleReport_Title": "Planifier le rapport",
    "txtName": "Nom",
    "txtSelectUser": "Sélectionner un utilisateur",
    "txtOK": "OK"
});