define("Sage/MainView/ActivityMgr/nls/ru/ActivityEditor", {
    "labelWidth": "120",
    "tabNameGeneralText": "Общее",
    "tabNameAvailabilityText": "Доступность",
    "tabNameAssociationsText": "Связи",
    "tabNameRecurringText": "Повторение",
    "tabNameAttachmentsText": "Вложения",
    "tabNameNotesText": "Заметки",
    "scheduleText": "Расписание",
    "startTimeText": "Время начала",
    "timeLessText": "Без указания времени",
    "alarmText": "Оповещение",
    "durationText": "Длительность",
    "rolloverText": "Автоматически переносить на следующий день",
    "contactText": "Контакт",
    "accountText": "Клиент",
    "leadText": "Заинтересованное лицо",
    "opportunityText": "Возможность",
    "ticketText": "Заявка",
    "companyText": "Компания",
    "regardingText": "Тема",
    "notesText": "Заметки",
    "priorityText": "Приоритет",
    "leaderText": "Организатор",
    "categoryText": "Категория",
    "locationText": "Местоположение",
    "dialogHeaderFormatText": "${actionText} ${activityType} - ${description}",
    "scheduledByFormatText": "Запланировал ${user}, ${date}",
    "completeScheduledByFormatText": "Запланировал ${user}, ${date} первоначально на ${startDate}",
    "newConfirmationHeaderFormatText": "Подтвердить ${activityType}, запланированный ${user}",
    "otherConfimationHeaderFormatText": "${activityType} ${actionText} от ${user}",
    "acceptedText": "Принято",
    "declinedText": "Отклонено",
    "scheduledText": "Запланировано",
    "updatedText": "Обновлено",
    "deletedText": "Удалено",
    "cancelText": "Отмена",
    "okText": "OК",
    "completeText": "Завершить",
    "completeBtnText": "Завершить",
    "completedText": "Завершено",
    "deleteText": "Удалить",
    "lookupActText": "Поиск клиента",
    "lookupContactText": "Поиск контакта",
    "lookupOpportunityText": "Поиск возможности",
    "lookupTicketText": "Поиск заявки",
    "lookupLeadText": "Поиск заинтересованного лица",
    "lookupLeaderText": "Поиск организатора",
    "lookupResourcesText": "Добавить участников и ресурсы",
    "addResourceText": "Добавить выбранное",
    "mainPhoneText": "Основной телефон",
    "typeText": "Тип",
    "subTypeText": "Подтип",
    "nameText": "Имя",
    "cityText": "Город",
    "stateText": "Регион",
    "workphoneText": "Рабочий телефон",
    "emailText": "Электронная почта",
    "acctMgrText": "Менеджер по клиентам",
    "descriptionText": "Описание",
    "stageText": "Стадия",
    "statusText": "Статус",
    "ownerText": "Владелец",
    "ticketNumberText": "Номер заявки",
    "phoneText": "Телефон",
    "urgencyText": "Срочность",
    "areaText": "Область",
    "recurringText": "Повторение",
    "resultText": "Результат",
    "followupText": "Последующее действие",
    "noneText": "Нет",
    "carryOverAttachmentsText": "Перенести вложения",
    "carryOverNotesText": "Перенести заметки",
    "asScheduledText": "Как запланировано",
    "nowText": "Сейчас",
    "responseText": "Ответ",
    "acceptText": "Принять",
    "declineText": "Отклонить",
    "deleteConfText": "Удалить подтверждение",
    "closeText": "Закрыть",
    "leadFullNameText": "Имя",
    "postalText": "Почтовый индекс",
    "failedLoadingDataMsg": "Возникла ошибка при загрузке данных.",
    "removeText": "Удалить",
    "noText": "Нет",
    "yesText": "Да",
    "areYouSureText": "Данная запись будет удалена без возможности восстановления.",
    "couldNotSaveErrorText": "Не удалось сохранить действие из-за ошибки.",
    "couldNotDeleteErrorText": "Не удалось удалить действие из-за ошибки.",
    "couldNotCompleteErrorText": "Не удалось завершить действие из-за ошибки.",
    "scheduleFollowUpErrorText": "Не удалось запланировать последующее действие из-за ошибки определения HistoryId.",
    "tabNameParticipants": "Участники"
});