define("Sage/MainView/ActivityMgr/nls/ru/EditEventEditor", {
    "titleScheduleText": "Запланировать событие...",
    "titleEditText": "Редактировать событие",
    "lblDayTypeText": "Тип события:",
    "lblStartDateText": "Дата начала:",
    "lblEndDateText": "Дата окончания:",
    "lblUserText": "Пользователь:",
    "lookupUserText": "Поиск пользователя",
    "lblCategoryText": "Категория:",
    "lblLocationText": "Местоположение:",
    "lblDescriptionText": "Описание:",
    "btnOkayText": "OК",
    "btnCancelText": "Отмена",
    "btnHelpText": "Справка",
    "eventTypeActiveText": "Активно",
    "eventTypeBusinessTripText": "Командировка",
    "eventTypeConferenceText": "Конференция",
    "eventTypeHolidayText": "Праздник",
    "eventTypeOffText": "Офис",
    "eventTypeTradeShowText": "Выставка",
    "eventTypeUnavailableText": "Недоступно",
    "eventTypeVacationText": "Отпуск",
    "errorText": "Не удалось создать событие, так как возникла ошибка.",
    "invaildDatesText": "Дата окончания не может быть раньше даты начала.",
    "nameText": "Имя"
});