define("Sage/MainView/ActivityMgr/nls/ru/HistoryEditor", {
    "labelWidth": "120",
    "tabNameGeneralText": "Общее",
    "tabNameAttachmentsText": "Вложения",
    "scheduleText": "Расписание",
    "startTimeText": "Запланировано",
    "completedDateText": "Завершено",
    "timeLessText": "Без указания времени",
    "durationText": "Длительность",
    "contactText": "Контакт",
    "accountText": "Клиент",
    "leadText": "Заинтересованное лицо",
    "opportunityText": "Возможность",
    "ticketText": "Заявка",
    "companyText": "Компания",
    "regardingText": "Тема",
    "resultText": "Результат",
    "notesText": "Заметки",
    "priorityText": "Приоритет",
    "leaderText": "Организатор",
    "categoryText": "Категория",
    "locationText": "Местоположение",
    "scheduledByFormatText": "Запланировал ${user}, ${date}",
    "cancelText": "Отмена",
    "okText": "OК",
    "deleteText": "Удалить",
    "lookupActText": "Поиск клиента",
    "lookupContactText": "Поиск контакта",
    "lookupOpportunityText": "Поиск возможности",
    "lookupTicketText": "Поиск заявки",
    "lookupLeadText": "Поиск заинтересованного лица",
    "lookupLeaderText": "Поиск организатора",
    "lookupResourcesText": "Поиск",
    "mainPhoneText": "Основной телефон",
    "typeText": "Тип",
    "subTypeText": "Подтип",
    "nameText": "Имя",
    "cityText": "Город",
    "stateText": "Регион",
    "workphoneText": "Рабочий телефон",
    "emailText": "Электронная почта",
    "acctMgrText": "Менеджер по клиентам",
    "descriptionText": "Описание",
    "stageText": "Стадия",
    "statusText": "Статус",
    "ownerText": "Владелец",
    "ticketNumberText": "Номер заявки",
    "phoneText": "Телефон",
    "urgencyText": "Срочность",
    "areaText": "Область",
    "recurringText": "Повторение",
    "followupText": "Последующее действие",
    "noneText": "Нет",
    "carryOverAttachmentsText": "Перенести вложения",
    "carryOverNotesText": "Перенести заметки",
    "asScheduledText": "Как запланировано",
    "insertText": "Вставить",
    "couldNotSaveErrorText": "Не удалось сохранить историю из-за ошибки.",
    "deleteMessage": "Данная запись будет удалена без возможности восстановления.",
    "deleteTitle": "Удалить историю",
    "couldNotDeleteErrorText": "Не удалось удалить историю из-за ошибки.",
    "postalText": "Почтовый индекс",
    "tabNameParticipants": "Все участники"
});