define(
"dojo/cldr/nls/ru/currency", //begin v1.x content
{
	"COP_displayName": "Колумбийское песо",
	"CZK_displayName": "Чешская крона",
	"TND_displayName": "Тунисский динар",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Ямайский доллар",
	"PHP_displayName": "Филиппинское песо",
	"ALL_displayName": "Албанский лек",
	"USD_symbol": "$",
	"LBP_displayName": "Ливанский фунт",
	"VND_displayName": "Вьетнамский донг",
	"LYD_displayName": "Ливийский динар",
	"RON_displayName": "Румынский лей",
	"MKD_displayName": "Македонский динар",
	"SEK_displayName": "Шведская крона",
	"CNY_displayName": "Юань Ренминби",
	"IDR_displayName": "Индонезийская рупия",
	"ILS_displayName": "Новый израильский шекель",
	"YER_displayName": "Йеменский риал",
	"TJS_displayName": "Таджикский сомони",
	"TTD_displayName": "Доллар Тринидада и Тобаго",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Турецкая лира",
	"EUR_displayName": "Евро",
	"AED_displayName": "Дирхам (ОАЭ)",
	"KZT_displayName": "Казахский тенге",
	"BHD_displayName": "Бахрейнский динар",
	"RUB_displayName": "Российский рубль",
	"NZD_displayName": "Новозеландский доллар",
	"IQD_displayName": "Иракский динар",
	"TMT_displayName": "Туркменский новый манат",
	"ZWL_displayName": "Доллар Зимбабве (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Киргизский сом",
	"KWD_displayName": "Кувейтский динар",
	"AFN_displayName": "Афганский афгани",
	"ARS_displayName": "Аргентинское песо",
	"MAD_displayName": "Марокканский дирхам",
	"BAM_displayName": "Конвертируемая марка Боснии и Герцеговины",
	"BOB_displayName": "Боливийский боливиано",
	"BND_displayName": "Брунейский доллар",
	"SGD_displayName": "Сингапурский доллар",
	"MVR_displayName": "Мальдивская руфия",
	"MXN_displayName": "Мексиканское новое песо",
	"DZD_displayName": "Алжирский динар",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Иорданский динар",
	"PEN_displayName": "Перуанский новый соль",
	"GTQ_displayName": "Гватемальский кетсаль",
	"BYR_displayName": "Белорусский рубль",
	"CAD_displayName": "Канадский доллар",
	"BZD_displayName": "Белизский доллар",
	"CLP_displayName": "Чилийское песо",
	"XOF_displayName": "Франк КФА ВСЕАО",
	"NOK_displayName": "Норвежская крона",
	"DOP_displayName": "Доминиканское песо",
	"JPY_symbol": "¥",
	"KRW_displayName": "Вона Республики Кореи",
	"USD_displayName": "Доллар США",
	"UYU_displayName": "Уругвайское песо",
	"UZS_displayName": "Узбекский сум",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Катарский риал",
	"SAR_displayName": "Саудовский риал",
	"SYP_displayName": "Сирийский фунт",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Египетский фунт",
	"AMD_displayName": "Армянский драм",
	"GBP_displayName": "Английский фунт стерлингов",
	"UAH_symbol": "₴",
	"HUF_displayName": "Венгерский форинт",
	"CSD_displayName": "Старый Сербский динар",
	"ISK_displayName": "Исландская крона",
	"IRR_displayName": "Иранский риал",
	"OMR_displayName": "Оманский риал",
	"TWD_displayName": "Новый тайваньский доллар",
	"PAB_displayName": "Панамское бальбоа",
	"UAH_displayName": "Украинская гривна",
	"ETB_displayName": "Эфиопский быр",
	"RUB_symbol": "руб.",
	"PLN_displayName": "Польский злотый",
	"VEF_displayName": "Венесуэльский боливар",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Бразильский реал",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Гонконгский доллар",
	"NIO_displayName": "Никарагуанская кордоба",
	"THB_symbol": "฿",
	"NPR_displayName": "Непальская рупия",
	"PKR_displayName": "Пакистанская рупия",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Грузинский лари",
	"AZN_displayName": "Азербайджанский манат",
	"GBP_symbol": "£",
	"MYR_displayName": "Малайзийский ринггит",
	"DKK_displayName": "Датская крона",
	"THB_displayName": "Таиландский бат",
	"BRL_symbol": "R$",
	"JPY_displayName": "Японская иена",
	"KES_displayName": "Кенийский шиллинг",
	"KHR_displayName": "Камбоджийский риель",
	"PYG_displayName": "Парагвайский гуарани",
	"VND_symbol": "₫",
	"LKR_displayName": "Шри-Ланкийская рупия",
	"BGN_displayName": "Болгарский лев",
	"BDT_displayName": "Бангладешская така",
	"MOP_displayName": "Патака Макао",
	"HNL_displayName": "Гондурасская лемпира",
	"RWF_displayName": "Франк Руанды",
	"CHF_displayName": "Швейцарский франк",
	"CRC_displayName": "Костариканский колон",
	"INR_displayName": "Индийская рупия",
	"TMT_symbol": "ТМТ",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Южноафриканский рэнд",
	"AUD_displayName": "Австралийский доллар",
	"LAK_displayName": "Кип ЛНДР",
	"MNT_displayName": "Монгольский тугрик",
	"RSD_displayName": "Сербский динар",
	"HRK_displayName": "Хорватская куна"
}
//end v1.x content
);