define(
"dojo/cldr/nls/lt/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbijos pesas",
	"CZK_displayName": "Čekijos krona",
	"TND_displayName": "Tuniso dinaras",
	"CAD_symbol": "CAD",
	"JMD_displayName": "Jamaikos doleris",
	"PHP_displayName": "Filipinų pesas",
	"ALL_displayName": "Albanijos lekas",
	"USD_symbol": "USD",
	"LBP_displayName": "Libano svaras",
	"VND_displayName": "Vietnamo dongas",
	"LYD_displayName": "Libijos dinaras",
	"RON_displayName": "Rumunijos lėja",
	"MKD_displayName": "Makedonijos denaras",
	"SEK_displayName": "Švedijos krona",
	"CNY_displayName": "Kinijos ženminbi juanis",
	"IDR_displayName": "Indonezijos rupija",
	"ILS_displayName": "Izraelio naujasis šekelis",
	"YER_displayName": "Jemeno rialas",
	"TJS_displayName": "Tadžikistano somonis",
	"TTD_displayName": "Trinidado ir Tobago doleris",
	"CNY_symbol": "CNY",
	"TRY_displayName": "Turkijos lira",
	"EUR_displayName": "Euras",
	"AED_displayName": "Jungtinių Arabų Emyratų dirhamas",
	"KZT_displayName": "Kazachstano tengė",
	"BHD_displayName": "Bahreino dinaras",
	"RUB_displayName": "Rusijos rublis",
	"NZD_displayName": "Naujosios Zelandijos doleris",
	"IQD_displayName": "Irako dinaras",
	"TMT_displayName": "Turkmėnistano manatas",
	"ZWL_displayName": "Zimbabvės doleris (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "Kirgizijos somas",
	"KWD_displayName": "Kuveito dinaras",
	"AFN_displayName": "Afganistano afganis",
	"ARS_displayName": "Argentinos pesas",
	"MAD_displayName": "Maroko dirhamas",
	"BAM_displayName": "Bosnijos ir Hercegovinos konvertuojamoji markė",
	"BOB_displayName": "Bolivijos bolivijanas",
	"BND_displayName": "Brunėjaus doleris",
	"SGD_displayName": "Singapūro doleris",
	"MVR_displayName": "Maldyvų rufija",
	"MXN_displayName": "Meksikos pesas",
	"DZD_displayName": "Alžyro dinaras",
	"MXN_symbol": "MXN",
	"JOD_displayName": "Jordanijos dinaras",
	"PEN_displayName": "Peru naujasis solis",
	"GTQ_displayName": "Gvatemalos ketcalis",
	"BYR_displayName": "Baltarusijos rublis",
	"CAD_displayName": "Kanados doleris",
	"BZD_displayName": "Belizo doleris",
	"CLP_displayName": "Čilės pesas",
	"XOF_displayName": "CFA BCEAO frankas",
	"NOK_displayName": "Norvegijos krona",
	"DOP_displayName": "Dominikos pesas",
	"JPY_symbol": "JPY",
	"KRW_displayName": "Pietų Korėjos vonas",
	"USD_displayName": "JAV doleris",
	"UYU_displayName": "Urugvajaus pesas",
	"UZS_displayName": "Uzbekistano sumas",
	"XOF_symbol": "XOF",
	"QAR_displayName": "Kataro rialas",
	"SAR_displayName": "Saudo Arabijos rijalas",
	"SYP_displayName": "Sirijos svaras",
	"NZD_symbol": "NZD",
	"EGP_displayName": "Egipto svaras",
	"AMD_displayName": "Armėnijos dramas",
	"GBP_displayName": "Didžiosios Britanijos svaras sterlingų",
	"HUF_displayName": "Vengrijos forintas",
	"CSD_displayName": "Serbijos dinaras (2002–2006)",
	"ISK_displayName": "Islandijos krona",
	"IRR_displayName": "Irano rialas",
	"OMR_displayName": "Omano rialas",
	"TWD_displayName": "Taivano naujasis doleris",
	"PAB_displayName": "Panamos balboja",
	"UAH_displayName": "Ukrainos grivina",
	"ETB_displayName": "Etiopijos biras",
	"PLN_displayName": "Lenkijos zlotas",
	"VEF_displayName": "Venesuelos bolivaras",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "Brazilijos realas",
	"HKD_symbol": "HKD",
	"HKD_displayName": "Honkongo doleris",
	"NIO_displayName": "Nikaragvos kordoba",
	"THB_symbol": "THB",
	"NPR_displayName": "Nepalo rupija",
	"PKR_displayName": "Pakistano rupija",
	"TWD_symbol": "TWD",
	"GEL_displayName": "Gruzijos laris",
	"AZN_displayName": "Azerbaidžano manatas",
	"GBP_symbol": "GBP",
	"MYR_displayName": "Malaizijos ringitas",
	"DKK_displayName": "Danijos krona",
	"THB_displayName": "Tailando batas",
	"BRL_symbol": "BRL",
	"JPY_displayName": "Japonijos jena",
	"KES_displayName": "Kenijos šilingas",
	"KHR_displayName": "Kambodžos rielis",
	"PYG_displayName": "Paragvajaus guaranis",
	"VND_symbol": "VND",
	"LKR_displayName": "Šri Lankos rupija",
	"BGN_displayName": "Bulgarijos levas",
	"BDT_displayName": "Bangladešo taka",
	"MOP_displayName": "Makao pataka",
	"HNL_displayName": "Hondūro lempira",
	"RWF_displayName": "Ruandos frankas",
	"CHF_displayName": "Šveicarijos frankas",
	"CRC_displayName": "Kosta Rikos kolonas",
	"INR_displayName": "Indijos rupija",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "Pietų Afrikos Respublikos randas",
	"AUD_displayName": "Australijos doleris",
	"LAK_displayName": "Laoso kipas",
	"MNT_displayName": "Mongolijos tugrikas",
	"RSD_displayName": "Serbijos dinaras",
	"HRK_displayName": "Kroatijos kuna"
}
//end v1.x content
);