define(
"dojo/cldr/nls/hi/currency", //begin v1.x content
{
	"COP_displayName": "कोलंबियाई पीसो",
	"CZK_displayName": "चेक गणराज्य कोरुना",
	"TND_displayName": "ट्यूनीशियाई दिनार",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "जमैकन डॉलर",
	"PHP_displayName": "फ़िलिपीनी पीसो",
	"ALL_displayName": "अल्बानियाई लेक",
	"USD_symbol": "$",
	"LBP_displayName": "लेबनानी पाउंड",
	"VND_displayName": "वियतनामी डोंग",
	"LYD_displayName": "लीबियाई दिनार",
	"RON_displayName": "रोमानियाई ल्यू",
	"MKD_displayName": "मैसीडोनियन दिनार",
	"SEK_displayName": "स्वीडीश क्रोना",
	"CNY_displayName": "चीनी युआन",
	"IDR_displayName": "इंडोनेशियाई रुपिया",
	"ILS_displayName": "इसराइली न्यू शेकेल",
	"YER_displayName": "यमनी रियाल",
	"TJS_displayName": "ताजिकिस्तानी सोमोनी",
	"TTD_displayName": "त्रिनिदाद और टोबैगो डॉलर",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "तुर्की लीरा",
	"EUR_displayName": "यूरो",
	"AED_displayName": "संयुक्त अरब अमीरात दिरहाम",
	"KZT_displayName": "कज़ाखिस्तानी टेंज़",
	"BHD_displayName": "बहरीनी दिनार",
	"RUB_displayName": "रूसी रूबल",
	"NZD_displayName": "न्यूज़ीलैंड डॉलर",
	"IQD_displayName": "इराकी दिनार",
	"TMT_displayName": "तुर्कमेनिस्तानी मैनत",
	"INR_symbol": "₹",
	"KGS_displayName": "किर्गिस्तानी सोम",
	"KWD_displayName": "कुवैती दिनार",
	"AFN_displayName": "अफ़गान अफ़गानी",
	"ARS_displayName": "अर्जेंटीनी पीसो",
	"MAD_displayName": "मोरक्को दिरहम",
	"BAM_displayName": "बोस्निया हर्ज़ेगोविना परिवर्तनीय मार्क",
	"BOB_displayName": "बोलिवियाई बोलिवियानो",
	"BND_displayName": "ब्रूनेई डॉलर",
	"SGD_displayName": "सिंगापुर डॉलर",
	"MVR_displayName": "मालदीवी रुफ़िया",
	"MXN_displayName": "मैक्सिकन पीसो",
	"DZD_displayName": "अल्जीरियाई दिनार",
	"MXN_symbol": "MX$",
	"JOD_displayName": "जॉर्डनियन दिनार",
	"PEN_displayName": "पेरूवियन नुएवो सोल",
	"GTQ_displayName": "ग्वाटेमाला क्वेटज़ल",
	"BYR_displayName": "बेलारूसी रूबल",
	"CAD_displayName": "कनाडाई डॉलर",
	"BZD_displayName": "बेलीज़ डॉलर",
	"CLP_displayName": "चिली पीसो",
	"XOF_displayName": "CFA फ़्रैंक BCEAO",
	"NOK_displayName": "नॉर्वेजियन क्रोन",
	"DOP_displayName": "डोमिनिकन पीसो",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "दक्षिण कोरियाई वॉन",
	"USD_displayName": "यूएस डॉलर",
	"UYU_displayName": "उरुग्वियन पीसो",
	"UZS_displayName": "उज़्बेकिस्तान सोम",
	"XOF_symbol": "CFA",
	"QAR_displayName": "क़तरी रियाल",
	"SAR_displayName": "सउदी रियाल",
	"SYP_displayName": "सीरियाई पाउंड",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "मिस्र पाउंड",
	"AMD_displayName": "आर्मेनियाई द्राम",
	"GBP_displayName": "ब्रिटिश पाउंड स्टर्लिंग",
	"HUF_displayName": "हंगेरियन फ़ोरिंट",
	"CSD_displayName": "सर्बिय का ढीनार",
	"ISK_displayName": "आइसलैंडिक क्रोना",
	"IRR_displayName": "ईरानी रियाल",
	"OMR_displayName": "ओमानी रियाल",
	"TWD_displayName": "नया ताईवानी डॉलर",
	"PAB_displayName": "पनामेनियन बैल्बोआ",
	"UAH_displayName": "यूक्रेनियन रिव्निया",
	"ETB_displayName": "इथियोपियन बिर",
	"PLN_displayName": "पोलिश ज़्लॉटी",
	"VEF_displayName": "वेनेज़ुएला बोलिवर",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "ब्राज़ीली रियाल",
	"HKD_symbol": "HK$",
	"HKD_displayName": "हाँगकाँग डॉलर",
	"NIO_displayName": "निकारागुअन कोरडोबा",
	"THB_symbol": "฿",
	"NPR_displayName": "नेपाली रुपया",
	"PKR_displayName": "पाकिस्तानी रुपया",
	"TWD_symbol": "NT$",
	"GEL_displayName": "जॉर्जियन लारी",
	"AZN_displayName": "अज़रबैजानी मैनेट",
	"GBP_symbol": "£",
	"MYR_displayName": "मलेशियाई रिंगित",
	"DKK_displayName": "डेनमार्क क्रोन",
	"THB_displayName": "थाई बहत",
	"BRL_symbol": "R$",
	"JPY_displayName": "जापानी येन",
	"KES_displayName": "केन्याई शिलिंग",
	"KHR_displayName": "कंबोडियाई रियाल",
	"PYG_displayName": "पैराग्वियन गुआरानी",
	"VND_symbol": "₫",
	"LKR_displayName": "श्रीलंकाई रुपया",
	"BGN_displayName": "बुल्गारियाई लेव",
	"BDT_displayName": "बांग्लादेशी टका",
	"MOP_displayName": "मेकानीज़ पाटाका",
	"HNL_displayName": "होंडुरन लेम्पिरा",
	"RWF_displayName": "रवांडाई फ़्रैंक",
	"CHF_displayName": "स्विस फ़्रैंक",
	"CRC_displayName": "कोस्टा रिका कोलोन",
	"INR_displayName": "भारतीय रुपया",
	"KRW_symbol": "₩",
	"ZAR_displayName": "दक्षिण अफ़्रीकी रैंड",
	"AUD_displayName": "ऑस्ट्रेलियाई डॉलर",
	"LAK_displayName": "लाओशियन किप",
	"MNT_displayName": "मंगोलियाई टगरिक",
	"RSD_displayName": "सर्बियन दिनार",
	"HRK_displayName": "क्रोएशियाई कुना"
}
//end v1.x content
);