define("Sage/MainView/Lead/nls/ru/ImportLeadsWizard", {
    "yestText": "Да",
    "noText": "Нет",
    "confirmOverwriteFileMsg": "На данный момент уже выбран файл импорта. Заменить этот файл?",
    "importProgressCaption": "Результаты процесса импорта",
    "lblPrimaryProgress": "Обработка файла импорта, подождите...",
    "lblTotalRecords": "Итого записей:",
    "lblTotalRecordsProcessed": "Обработано:",
    "lblTotalRecordsImported": "Импортировано:",
    "lblTotalRecordsMerged": "Объединено:",
    "lblTotalDuplicates": "Дубликаты:",
    "lblTotalProjectedDuplicates": "Ожидается дубликатов:",
    "lblDuplicateRate": "Доля дубликатов:",
    "lblTotalErrors": "Ошибки:",
    "calculatingText": "Выполняется вычисление, подождите...",
    "importStatusProcessing": "Обработка",
    "importStatusCompleted": "Завершено",
    "abortImportProcessStatus": "Прервать",
    "btnCancelText": "Прервать",
    "btnCloseText": "Закрыть",
    "lblImportHistoryLinkText": "Чтобы увидеть результаты импорта, нажмите номер импорта в поле ниже:",
    "lblImportLinkNumber": "Номер импорта: ",
    "errorRequestImportHistory": "Возникла ошибка при выполнении запроса sdata для конечной точки importHistory."
});