define(
"dojo/cldr/nls/sv/currency", //begin v1.x content
{
	"COP_displayName": "colombiansk peso",
	"CZK_displayName": "tjeckisk koruna",
	"TND_displayName": "tunisisk dinar",
	"EUR_symbol": "€",
	"CAD_symbol": "CAN$",
	"JMD_displayName": "Jamaica-dollar",
	"PHP_displayName": "filippinsk peso",
	"ALL_displayName": "albansk lek",
	"USD_symbol": "US$",
	"LBP_displayName": "libanesiskt pund",
	"VND_displayName": "vietnamesisk dong",
	"LYD_displayName": "libysk dinar",
	"RON_displayName": "rumänsk leu",
	"MKD_displayName": "makedonisk denar",
	"SEK_displayName": "svensk krona",
	"CNY_displayName": "kinesisk yuan renminbi",
	"IDR_displayName": "indonesisk rupiah",
	"ILS_displayName": "israelisk ny shekel",
	"YER_displayName": "jemenitisk rial",
	"TJS_displayName": "tadzjikisk somoni",
	"TTD_displayName": "Trinidad och Tobago-dollar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "turkisk lire",
	"EUR_displayName": "euro",
	"AED_displayName": "Förenade Arabemiratens dirham",
	"KZT_displayName": "kazakisk tenge",
	"ISK_symbol": "Ikr",
	"BHD_displayName": "Bahrain-dinar",
	"RUB_displayName": "rysk rubel",
	"NZD_displayName": "nyzeeländsk dollar",
	"IQD_displayName": "irakisk dinar",
	"TMT_displayName": "turkmenistansk manat",
	"ZWL_displayName": "Zimbabwe-dollar (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "kirgizisk som",
	"KWD_displayName": "kuwaitisk dinar",
	"AFN_displayName": "afghansk afghani",
	"ARS_displayName": "argentinsk peso",
	"MAD_displayName": "marockansk dirham",
	"BAM_displayName": "bosnisk-hercegovinsk mark (konvertibel)",
	"BOB_displayName": "boliviansk boliviano",
	"BND_displayName": "Brunei-dollar",
	"SGD_displayName": "Singapore-dollar",
	"MVR_displayName": "maldivisk rufiyaa",
	"MXN_displayName": "mexikansk peso",
	"DZD_displayName": "algerisk dinar",
	"MXN_symbol": "MX$",
	"JOD_displayName": "jordansk dinar",
	"PEN_displayName": "peruansk nuevo sol",
	"DOP_symbol": "RD$",
	"GTQ_displayName": "guatemalansk quetzal",
	"BYR_displayName": "vitrysk rubel",
	"CAD_displayName": "kanadensisk dollar",
	"BZD_displayName": "belizisk dollar",
	"CLP_displayName": "chilensk peso",
	"NOK_symbol": "NKr",
	"XOF_displayName": "västafrikansk franc",
	"NOK_displayName": "norsk krona",
	"DOP_displayName": "dominikansk peso",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "sydkoreansk won",
	"USD_displayName": "US-dollar",
	"UYU_displayName": "uruguayansk peso",
	"UZS_displayName": "uzbekisk sum",
	"QAR_displayName": "qatarisk rial",
	"SEK_symbol": "kr",
	"BND_symbol": "BN$",
	"SAR_displayName": "saudisk riyal",
	"SYP_displayName": "syriskt pund",
	"EGP_symbol": "EG£",
	"NZD_symbol": "NZ$",
	"DKK_symbol": "Dkr",
	"EGP_displayName": "egyptiskt pund",
	"AMD_displayName": "armenisk dram",
	"GBP_displayName": "brittiskt pund sterling",
	"HUF_displayName": "ungersk forint",
	"CSD_displayName": "serbisk dinar (2002–2006)",
	"ISK_displayName": "isländsk krona",
	"IRR_displayName": "iransk rial",
	"OMR_displayName": "omansk rial",
	"TWD_displayName": "taiwanesisk ny dollar",
	"BDT_symbol": "Tk",
	"PAB_displayName": "panamansk balboa",
	"UAH_displayName": "ukrainsk hryvnia",
	"ETB_displayName": "etiopisk birr",
	"PLN_displayName": "polsk zloty",
	"VEF_displayName": "venezuelansk bolivar",
	"ILS_symbol": "₪",
	"JMD_symbol": "JM$",
	"AUD_symbol": "AU$",
	"BRL_displayName": "brasiliansk real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hongkong-dollar",
	"NIO_displayName": "nicaraguansk córdoba",
	"THB_symbol": "TH฿",
	"NPR_displayName": "nepalesisk rupie",
	"SYP_symbol": "SY£",
	"PKR_displayName": "pakistansk rupie",
	"TWD_symbol": "TW$",
	"GEL_displayName": "georgisk lari",
	"AZN_displayName": "azerbajdzjansk manat",
	"GBP_symbol": "GB£",
	"MYR_displayName": "malaysisk ringgit",
	"DKK_displayName": "dansk krona",
	"THB_displayName": "thailändsk baht",
	"BRL_symbol": "BR$",
	"JPY_displayName": "japansk yen",
	"KES_displayName": "kenyansk shilling",
	"BZD_symbol": "BZ$",
	"KHR_displayName": "kambodjansk riel",
	"PYG_displayName": "paraguayansk guarani",
	"VND_symbol": "VN₫",
	"BGN_displayName": "bulgarisk lev",
	"BDT_displayName": "bangladeshisk taka",
	"LKR_displayName": "srilankesisk rupie",
	"HNL_displayName": "honduransk lempira",
	"MOP_displayName": "Macao-pataca",
	"RWF_displayName": "rwandisk franc",
	"CHF_displayName": "schweizisk franc",
	"CRC_displayName": "costarikansk colón",
	"INR_displayName": "indisk rupie",
	"ZAR_displayName": "sydafrikansk rand",
	"AUD_displayName": "australisk dollar",
	"LAK_displayName": "laotisk kip",
	"MNT_displayName": "mongolisk tögrög",
	"RSD_displayName": "serbisk dinar",
	"HRK_displayName": "kroatisk kuna"
}
//end v1.x content
);