define("Sage/Reporting/nls/fr/Enumerations", {
    "txtGroup": "Groupe",
    "txtDateRange": "Plage de dates",
    "txtUser": "Utilisateur",
    "txtQuery": "Requête",
    "txtIsGreaterThan": "Est supérieur à",
    "txtIsLessThan": "Est inférieur à",
    "txtIsInTheRange": "Est dans la plage",
    "txtIsAfter": "Est après",
    "txtIsBefore": "Est avant",
    "txtContains": "Contient",
    "txtStartsWith": "Commence par",
    "txtEndsWith": "Finit par",
    "txtIs": "Est",
    "txtIsNot": "N'est pas",
    "txtOnDemand": "A la demande",
    "txtScheduled": "Planifié",
    "txtCrystalReport": "Rapport Crystal",
    "txtExportToFileReportType": "Exporter dans un fichier",
    "txtUnknownReportType": "Inconnu",
    "txtNoFormat": "Aucun format",
    "txtPdf": "PDF",
    "txtExcel": "Excel",
    "txtExcelDataOnly": "Données Excel",
    "txtCsv": "CSV",
    "txtWord": "Word",
    "txtXml": "XML"
});