define("Sage/UI/Controls/nls/FieldAttributeControlFactory", {
    root: {
        IsEncrypted: 'Is Encrypted',
        Length: 'Length',
        Precision: 'Precision',
        Scale: 'Scale',
        LookupEntityName: 'Lookup Entity Name',
        LookupGroup: 'Lookup Group',
        IsPercentage: 'Is Percentage',
        Items: 'Items',
        MultiSelect: 'MultiSelect',
        OverriddenName: 'Overridden Name',
        Storage: 'Storage',
        EnableHyperLinking: 'Enable Hyper-Linking',
        LookupPreFilters: 'Lookup PreFilters',
        EqualTo: 'Equal To',
        NotEqualTo: 'Not Equal To',
        GreaterThanOrEqual: 'Greater Than or Equal',
        GreaterThan: 'Greater Than',
        LessThanOrEqual: 'Less Than or Equal',
        LessThan: 'Less Than',
        CondOperator: 'Condition Operator',
        FilterValue: 'Filter Value',
        PropertyName: 'Property Name',
        LookupProperties: 'Lookup Properties',
        ExcludeFromFilters: 'Exclude From Filters',
        HideCondition: 'Hide Condition',
        IsSortable: 'Is Sortable',
        PropertyFormat: 'Property Format',
        None: 'None',
        Phone: 'Phone',
        User: 'User',
        PickList: 'Pick List',
        DateTime: 'Date Time',
        PropertyFormatString: 'Property Format String',
        PropertyHeader: 'Property Header',
        PropertyType: 'Property Type',
        UseAsResult: 'Use As Result',
        ReturnPrimaryKey: 'Return Primary Key',
        AllowMultiples: 'Allow Multiples',
        AlphaSort: 'Alpha Sort',
        MustExistInList: 'Must Exist In List',
        NoneEditable: 'None Editable',
        PickListFilter: 'Pick List Filter',
        ValueStoredAsText: 'Value Stored As Text',
        Value: 'Value',
        Display: 'Display',
        Code: 'Code',
        Name: 'Name',
        DisplayName: 'Display Name',
        Template: 'Calculation',
        Description: 'Description',
        SortOrder: 'Sort Order',
        lblNoFieldsInTemplate: 'Please add an entity property to the template before applying a sort order.',
        AddField: 'Add Field',
        InUse: 'In Use',
        NotInUse: 'Not In Use',
        CalculatedNumberInputError: "<p>Inputs are limited to Field Names selected from the drop down,<br/> and to the following characters:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', or ')'.<br/>&nbsp;&nbsp;&nbsp;&nbsp;These match up with the button values above the text area.</p>",
        newPickList: 'New Pick List',
        add: 'add',
        substract: 'subtract',
        multiply: 'multiply',
        divide: 'divide',
        openParens: 'open parenthesis',
        closeParens: 'close parenthesis'

    },
    "de": true,
    "en": true,
    "fr": true,
    "it": true,
    "ru": true
});
