define(
"dojo/cldr/nls/sk/currency", //begin v1.x content
{
	"COP_displayName": "Kolumbijské peso",
	"CZK_displayName": "Česká koruna",
	"TND_displayName": "Tuniský dinár",
	"EUR_symbol": "€",
	"CAD_symbol": "CAD",
	"JMD_displayName": "Jamajský dolár",
	"PHP_displayName": "Filipínske peso",
	"ALL_displayName": "Albánsky lek",
	"USD_symbol": "USD",
	"LBP_displayName": "Libanonská libra",
	"VND_displayName": "Vietnamský dong",
	"LYD_displayName": "Libyjský dinár",
	"RON_displayName": "Rumunský leu",
	"MKD_displayName": "Macedónsky denár",
	"SEK_displayName": "Švédska koruna",
	"CNY_displayName": "Čínsky jüan",
	"IDR_displayName": "Indonézska rupia",
	"ILS_displayName": "Izraelský šekel",
	"YER_displayName": "Jemenský rial",
	"TJS_displayName": "Tadžické somoni",
	"TTD_displayName": "Trinidadsko-tobažský dolár",
	"CNY_symbol": "CNY",
	"TRY_displayName": "Turecká líra",
	"EUR_displayName": "Euro",
	"AED_displayName": "SAE dirham",
	"KZT_displayName": "Kazašské tenge",
	"BHD_displayName": "Bahrajnský dinár",
	"RUB_displayName": "Ruský rubeľ",
	"NZD_displayName": "Novozélandský dolár",
	"IQD_displayName": "Iracký dinár",
	"TMT_displayName": "Turkménsky manat",
	"ZWL_displayName": "Zimbabwiansky dolár (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "Kirgizský som",
	"KWD_displayName": "Kuvajtský dinár",
	"AFN_displayName": "Afganský afgání",
	"ARS_displayName": "Argentinské peso",
	"PLN_symbol": "zl",
	"MAD_displayName": "Marocký dirham",
	"BAM_displayName": "Bosnianska konvertibilná marka",
	"BOB_displayName": "Bolívijské boliviano",
	"BND_displayName": "Brunejský dolár",
	"SGD_displayName": "Singapúrsky dolár",
	"MVR_displayName": "Maldivská rufiyaa",
	"MXN_displayName": "Mexické peso",
	"DZD_displayName": "Alžírsky dinár",
	"MXN_symbol": "Mex$",
	"JOD_displayName": "Jordánsky dinár",
	"PEN_displayName": "Peruvský sol Nuevo",
	"GTQ_displayName": "Guatemalský quetzal",
	"BYR_displayName": "Bieloruský rubeľ",
	"CAD_displayName": "Kanadský dolár",
	"BZD_displayName": "Belizský dolár",
	"CLP_displayName": "Čílske peso",
	"XOF_displayName": "CFA frank BCEAO",
	"NOK_displayName": "Nórska koruna",
	"DOP_displayName": "Dominikánske peso",
	"JPY_symbol": "JPY",
	"KRW_displayName": "Juhokórejský won",
	"USD_displayName": "Americký dolár",
	"UYU_displayName": "Uruguajské peso Uruguayo",
	"UZS_displayName": "Uzbecký sum",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Katarský rial",
	"SAR_displayName": "Saudskoarabský rial",
	"SYP_displayName": "Syrská libra",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Egyptská libra",
	"AMD_displayName": "Armenský dram",
	"GBP_displayName": "Britská libra",
	"HUF_displayName": "Maďarský forint",
	"ISK_displayName": "Islandská krona",
	"IRR_displayName": "Iránsky rial",
	"OMR_displayName": "Ománský rial",
	"TWD_displayName": "Nový taiwanský dolár",
	"PAB_displayName": "Panamská balboa",
	"UAH_displayName": "Ukrainská hrivna",
	"ETB_displayName": "Ethiopský birr",
	"PLN_displayName": "Poľský zlotý",
	"VEF_displayName": "Venezuelský bolívar",
	"ILS_symbol": "₪",
	"AUD_symbol": "AUD",
	"BRL_displayName": "Brazílsky real",
	"HKD_symbol": "HKD",
	"HKD_displayName": "Hongkonský dolár",
	"NIO_displayName": "Nikaragujská Cordoba",
	"THB_symbol": "THB",
	"NPR_displayName": "Nepálska rupia",
	"PKR_displayName": "Pakistanská rupia",
	"TWD_symbol": "TWD",
	"GEL_displayName": "Gruzínsky lari",
	"AZN_displayName": "Azerbajdžanský manat",
	"GBP_symbol": "GBP",
	"MYR_displayName": "Malajský ringgit",
	"DKK_displayName": "Dánska koruna",
	"THB_displayName": "Thajský baht",
	"BRL_symbol": "BRL",
	"JPY_displayName": "Japonský jen",
	"KES_displayName": "Keňský šiling",
	"KHR_displayName": "Kambodžský riel",
	"PYG_displayName": "Paraguayské guarani",
	"VND_symbol": "₫",
	"LKR_displayName": "Srílanská rupia",
	"BGN_displayName": "Bulharský lev",
	"BDT_displayName": "Bangladéšska taka",
	"MOP_displayName": "Macajská pataca",
	"HNL_displayName": "Hoduraská lempira",
	"RWF_displayName": "Rwandský frank",
	"CHF_displayName": "Švajčiarsky frank",
	"CRC_displayName": "Kostarický colón",
	"INR_displayName": "Indická rupia",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "Juhoafrický rand",
	"AUD_displayName": "Austrálsky dolár",
	"LAK_displayName": "Laoský kip",
	"MNT_displayName": "Mongolský tugrik",
	"RSD_displayName": "Srbský dinár",
	"HRK_displayName": "Chorvátska kuna"
}
//end v1.x content
);