define("Sage/MainView/ReportMgr/nls/en/ReportWizardController", {
    txtLoadingScheduleDetails: 'Loading Schedule Details',
    txtError: 'Error',
    txtCannotDetermineReportId: 'Cannot determine report id.',
    txtCannotDetermineReportNameOrFamily: 'Cannot determine report name or family.',
    txtLoading: 'Loading ',
    txtLoadingReport: 'Loading Report',
    txtSorryAnErrorOccuredLoadingReport: 'Sorry, an error occurred loading report: ${0} ${1}.',
    displayNameAccountDetail: 'Account Detail',
    displayNameContactDetail: 'Contact Detail',
    displayNameOpportunityDetail: 'Opportunity Detail',
    displayNameSupportDefect: 'Support Defect',
    displayNameSupportTicket: 'Support Ticket',
    displayNameSalesOrderDetail: 'Sales Order Detail',
    displayNameQuoteDetail: 'Quote Detail',
	displayNameQuotation:'Quotation',
});