INSERT INTO [LiveEAB_app].[dbo].[StgPurchaseOrder_TAC]
           ([ClosedForInvc]
           ,[ClosedForRcvg]           
           ,[CurrExchRate]
           ,[CurrID]
           ,[FreightAmt]
           ,[Hold]
           ,[IssueDate]           
           ,[OriginationDate]
           ,[RequirePOIssue]
           ,[Status]
           ,[STaxAmt]
           ,[TranCmnt]
           ,[TranDate]
           ,[TranNo]
           ,[UserFld1]           
           ,[VendClassID]
           ,[VendorID]
           ,[SessionKey]
           ,[ProcessStatus]
           ,[Submit_Date]
           ,[CompanyID]           
           )
     
     SELECT 
       [CLOSEDFORINVC]
      ,[CLOSEDFORRCVG]
      ,[CURREXCHRATE]
      ,[CURRID]
      ,[FREIGHTAMT]
      ,[HOLD]
      ,[ISSUEDATE]
      ,[ORIGINATIONDATE]
      ,[REQUIREPOISSUE]
      ,[STATUS]
      ,[STAXAMT]
      ,[TRANCMNT]
      ,[TRANDATE]
      ,[TRANNO]
      ,[USERFLD1]
      ,[VENDCLASSID]
      ,[VENDORID]
      ,0
      ,0
      ,[ModifyDate]
      ,[CompanyID]
  FROM [LiveEAB_slx].[sysdba].[STGPURCHASEORDER_TAC]
  Where tranno = 1
GO   
 