INSERT INTO [LiveEAB_app].[dbo].[StgPOLine_TAC]
           ([AmtInvcd]
           ,[ClosedForInvc]
           ,[ClosedForRcvg]
           ,[CmntOnly]
           ,[Description]
           ,[DropShip]
           ,[ExclLastCost]
           ,[Expedite]           
           ,[ExtAmt]
           ,[ExtCmnt]           
           ,[FreightAmt]
           ,[GLAcctNo]           
           ,[ItemID]           
           ,[OrigOrdered]
           ,[OrigPromiseDate]
           ,[POLineNo]
           ,[PromiseDate]           
           ,[QtyInvcd]
           ,[QtyOnBO]
           ,[QtyOpenToRcv]
           ,[QtyOrd]
           ,[QtyRcvd]
           ,[QtyRtrnCredit]           
           ,[RequestDate]           
           ,[Status]
           ,[TargetCompanyID]
           ,[TranNo]
           ,[UnitCost]
           ,[UnitMeasID]
           ,[UserFld1]           
           ,[QtyRtrnReplacement]
           ,[SessionKey]
           ,[ProcessStatus]
           ,[Submit_Date]
           ,[ShipToWhseID])
     
     SELECT 
       [AMTINVCD]
      ,[CLOSEDFORINVC]
      ,[CLOSEDFORRCVG]
      ,[CMNTONLY]
      ,[DESCRIPTION]
      ,[DROPSHIP]
      ,[EXCLLASTCOST]
      ,[EXPEDITE]
      ,[EXTAMT]
      ,[EXTCMNT]
      ,[FREIGHTAMT]
      ,[GLACCTNO]
      ,[ITEMID]
      ,[ORIGORDERED]
      ,[ORIGPROMISEDATE]
      ,[POLINENO]
      ,[PROMISEDATE]
      ,[QTYINVCD]
      ,[QTYONBO]
      ,[QTYOPENTORCV]
      ,[QTYORD]
      ,[QTYRCVD]
      ,[QTYRTRNCREDIT]
      ,[REQUESTDATE]
      ,[STATUS]
      ,[TARGETCOMPANYID]
      ,[TRANNO]
      ,[UNITCOST]
      ,[UNITMEASID]
      ,[USERFLD1]
      ,[QTYRTRNREPLACEMENT]
      ,0
      ,0
      ,[ModifyDate]
      ,[WarehouseID]
  FROM [LiveEAB_slx].[sysdba].[STGPOLINE_TAC]
  Where tranno = 1
GO




