define("Sage/TaskPane/nls/en/CommonTasksTasklet", {
    okButtonText: 'OK',
    loadingText: 'loading...',
    noPrimaryEmail: 'No primary email available',
    selectFileFormat: 'Select a file format:',
    exportToFile_OptionCSV: 'Standard CSV',
    exportToFile_OptionTab: 'Tab delimited (recommended for Microsoft Excel)',
	exportToFile_OptionExcel: 'Excel',
    exportToFile_OptionSaveFormat: 'Remember my selection and do not ask again.',
    exportToFile_OK: 'OK',
    exportToFile_Cancel: 'Cancel',
    exportToFile_DialogTitle: 'Export',
    exportToExcel_Caption: 'Exporting',
    errorRequestingJobMgr: 'An error occurred requesting job manager: ${0}',
    errorExecutionAction: 'An error occurred executing action ${0}',
    exportProcessingJobMsg: 'Processing export, you may continue waiting for completion, or go to the reports view to open your file.',
    errorBulkActionNotSupported: '${0} does not support bulk action updates, please contact your system administrator.',
    errorBulkActionRequest: 'An error occurred requesting bulk update options, please contact your system administrator.',
    deleteJob_Description: 'Bulk Delete Error(s) Occurred'
});