define("Sage/UI/Dashboard/nls/zh-cn/WidgetDefinition", {
    "defaultWidgetText": "编辑小组件设置",
    "settingsText": "设置",
    "viewGroupText": "查看组",
    "Bar_Chart": "条形图",
    "Column_Chart": "柱状图",
    "Group_List": "组列表",
    "Pie_Chart": "饼图",
    "Funnel_Chart": "漏斗图",
    "Line_Chart": "折线图",
    "SData_Feed": "SData 消息源",
    "Web_Feed": "Web 消息源",
    "Website": "网站",
    "Default": "默认值",
    "Links": "链接",
    "Recently_Viewed": "最近查看",
    "Todays_Activities": "今天的活动",
    "Today_s_Activities": "今天的活动",
    "Welcome": "欢迎",
    "Closing_Opportunities": "结束销售机会",
    "Quick_Actions": "快速操作",
    "Do_You_Know___": "您是否知道...",
    "All_Leads": "所有销售线索",
    "My_Notes": "我的备注",
    "Open_Opportunities": "未结销售机会",
    "My_Top_Opportunities": "我的排名靠前的销售机会",
    "My_Pipeline": "我的渠道",
    "Recent_Lead_Creation_History": "最近销售线索创建历史",
    "My_Activity_trend": "我的活动趋势",
    "My_Completed_Activities_by_Type": "我已完成的活动(按类型)",
    "Active_Campaigns": "正在进行的销售活动",
    "All_Open_Opportunities": "所有未结销售机会",
    "Top_Opportunities": "排名靠前的销售机会",
    "Open_Defect_Distribution": "未结缺陷分布",
    "My_Dashboard": "我的仪表板",
    "Sales": "销售",
    "Group_List_Description": "按实体显示组记录列表。例如，一组正在进行的销售活动。",
    "Welcome_Description": "显示 Saleslogix 介绍，以及“介绍用于 Web 的 Saleslogix”的帮助主题链接。",
    "Line_Chart_Description": "以一系列由线连接的数据点的形式显示数据。在数据表示许多组或类别时，此图表很有用。",
    "Bar_Chart_Description": "以一系列水平条形的形式显示数据。在比较多组数据时，此图表很有用。",
    "Column_Chart_Description": "以一系列按类别分组的垂直条形的形式显示数据。在显示一段时间内的数据变化或者演示不同项目的对比时，此图表很有用。",
    "Funnel_Chart_Description": "以漏斗状的渐进式比例形式显示数据。数据以 100% 的比例形式显示，此图表没有轴线。",
    "Pie_Chart_Description": "以占整体的比例形式显示数据。以占整体的百分比形式计算每个值。此图表没有轴线。",
    "Recently_Viewed_Description": "显示指向最近查看的记录(带有用于标识类型的图标)的链接。例如，客户或联系人。",
    "Todays_Activities_Description": "显示指向今日活动的链接。",
    "Links_Description": "显示您创建的链接。例如，指向 Saleslogix 中的详细视图链接或指向外部网站的链接。",
    "SData_Feed_Description": "显示使用 SData (Sage Data)消息源的 Web 消息源。例如，来自会计集成或 Saleslogix 数据库的消息源。",
    "Web_Feed_Description": "显示 RSS 或 Atom 消息源信息。",
    "Website_Description": "显示选择的网站。"
});