define(
"dojo/cldr/nls/nn/currency", //begin v1.x content
{
	"COP_displayName": "colombiansk peso",
	"CZK_displayName": "tsjekkisk koruna",
	"TND_displayName": "tunisisk dinar",
	"JMD_displayName": "jamaikansk dollar",
	"PHP_displayName": "filippinsk peso",
	"ALL_displayName": "albansk lek",
	"LBP_displayName": "libanesisk pund",
	"VND_displayName": "vietnamesisk dong",
	"LYD_displayName": "libysk dinar",
	"RON_displayName": "rumensk leu",
	"MKD_displayName": "makedonsk denar",
	"SEK_displayName": "svensk krone",
	"CNY_displayName": "kinesisk yuan renminbi",
	"IDR_displayName": "indonesisk rupi",
	"ILS_displayName": "israelsk ny shekel",
	"YER_displayName": "jemenittisk rial",
	"TJS_displayName": "tadsjikisk somoni",
	"TTD_displayName": "trinidadisk dollar",
	"TRY_displayName": "tyrkisk lire",
	"EUR_displayName": "euro",
	"AED_displayName": "UAE dirham",
	"KZT_displayName": "kasakhstansk tenge",
	"BHD_displayName": "bahrainsk dinar",
	"RUB_displayName": "russisk rubel",
	"NZD_displayName": "new zealandsk dollar",
	"IQD_displayName": "iraksk dinar",
	"KGS_displayName": "kirgisisk som",
	"KWD_displayName": "kuwaitisk dinar",
	"AFN_displayName": "afghani",
	"ARS_displayName": "argentinsk peso",
	"MAD_displayName": "marokkansk dirham",
	"BAM_displayName": "bosnisk-hercegovinsk mark (konvertibel)",
	"BOB_displayName": "boliviano",
	"BND_displayName": "bruneisk dollar",
	"SGD_displayName": "singaporsk dollar",
	"MVR_displayName": "maldivisk rufiyaa",
	"MXN_displayName": "meksikansk peso",
	"DZD_displayName": "algerisk dinar",
	"JOD_displayName": "jordansk dinar",
	"PEN_displayName": "peruansk nuevo sol",
	"GTQ_displayName": "guatemalansk quetzal",
	"BYR_displayName": "kviterussisk rubel",
	"CAD_displayName": "kanadisk dollar",
	"BZD_displayName": "belizisk dollar",
	"CLP_displayName": "chilensk peso",
	"NOK_symbol": "kr",
	"XOF_displayName": "CFA franc BCEAO",
	"NOK_displayName": "norsk krone",
	"DOP_displayName": "dominikansk peso",
	"KRW_displayName": "sørkoreansk won",
	"USD_displayName": "amerikansk dollar",
	"UYU_displayName": "uruguayansk peso",
	"UZS_displayName": "usbekisk sum",
	"QAR_displayName": "qatarsk rial",
	"SAR_displayName": "saudiarabisk rial",
	"SYP_displayName": "syrisk pund",
	"EGP_displayName": "egyptisk pund",
	"AMD_displayName": "armensk dram",
	"GBP_displayName": "britisk pund sterling",
	"HUF_displayName": "ungarsk forint",
	"CSD_displayName": "gammal serbisk dinar",
	"ISK_displayName": "islandsk krone",
	"IRR_displayName": "iransk rial",
	"OMR_displayName": "omansk rial",
	"TWD_displayName": "taiwansk ny dollar",
	"PAB_displayName": "panamansk balboa",
	"UAH_displayName": "ukrainsk hryvnia",
	"ETB_displayName": "etiopisk birr",
	"PLN_displayName": "polsk zloty",
	"VEF_displayName": "venezuelansk bolivar",
	"BRL_displayName": "brasiliansk real",
	"HKD_displayName": "Hongkong-dollar",
	"NIO_displayName": "nicaraguansk cordoba oro",
	"NPR_displayName": "nepalsk rupi",
	"PKR_displayName": "pakistansk rupi",
	"GEL_displayName": "georgisk lari",
	"AZN_displayName": "aserbajdsjansk manat",
	"MYR_displayName": "malaysisk ringgit",
	"DKK_displayName": "dansk krone",
	"THB_displayName": "thailandsk baht",
	"JPY_displayName": "japansk yen",
	"KES_displayName": "kenyansk shilling",
	"KHR_displayName": "kambodsjansk riel",
	"PYG_displayName": "paraguayansk guarani",
	"LKR_displayName": "srilankisk rupi",
	"BGN_displayName": "bulgarsk ny lev",
	"BDT_displayName": "bangladeshisk taka",
	"MOP_displayName": "makaosk pataca",
	"HNL_displayName": "honduransk lempira",
	"RWF_displayName": "rwandisk franc",
	"CHF_displayName": "sveitsisk franc",
	"CRC_displayName": "costaricansk colon",
	"INR_displayName": "indisk rupi",
	"ZAR_displayName": "sørafrikansk rand",
	"AUD_displayName": "australsk dollar",
	"LAK_displayName": "laotisk kip",
	"MNT_displayName": "mongolsk tugrik",
	"RSD_displayName": "serbisk dinar",
	"HRK_displayName": "kroatisk kuna"
}
//end v1.x content
);