define(
"dojo/cldr/nls/ga/currency", //begin v1.x content
{
	"COP_displayName": "Peso na Colóime",
	"CZK_displayName": "Koruna Phoblacht na Seice",
	"TND_displayName": "Dínear na Túinéise",
	"PHP_displayName": "Peso Filipíneach",
	"JMD_displayName": "Dollar Iamácach",
	"ALL_displayName": "Lek Albánach",
	"LBP_displayName": "Punt na Liobáine",
	"VND_displayName": "Dong Vítneamach",
	"LYD_displayName": "Dínear Libia",
	"MKD_displayName": "Denar na Macadóine",
	"SEK_displayName": "Krona Sualannach",
	"CNY_displayName": "Yuan Renminbi Síneach",
	"IDR_displayName": "Rupiah Indinéiseach",
	"ILS_displayName": "Sheqel Nua Iosraelach",
	"YER_displayName": "Rial Éimin",
	"TJS_displayName": "Somoni na Táidsíceastáine",
	"TTD_displayName": "Dollar Oileáin na Tríonóide agus Tobága",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham Aontas na nÉimíríochtaí Arabacha",
	"KZT_displayName": "Tenge Casacstánach",
	"BHD_displayName": "Dínear na Bairéine",
	"RUB_displayName": "Rúbal Rúiseach",
	"NZD_displayName": "Dollar na Nua-Shéalainne",
	"IQD_displayName": "Dínear Irácach",
	"KGS_displayName": "Som na Cirgeastáine",
	"KWD_displayName": "Dínear Cuátach",
	"AFN_displayName": "Afgainí",
	"ARS_displayName": "Peso na Airgintíne",
	"MAD_displayName": "Dirham Mharacó",
	"BAM_displayName": "Marc Inathraithe Bhoisnia-Heirseagaivéin",
	"BOB_displayName": "Boliviano",
	"BND_displayName": "Dollar Bhrúiné",
	"SGD_displayName": "Dollar Singeapóir",
	"MVR_displayName": "Maldive Islands Rufiyaa",
	"MXN_displayName": "Peso Meicsiceo",
	"DZD_displayName": "Dínear na hAilgéire",
	"JOD_displayName": "Dínear Iordánach",
	"PEN_displayName": "Sol Nuevo Pheiriú",
	"GTQ_displayName": "Quetzal Guatamala",
	"BYR_displayName": "Rúbal Béalarúiseach",
	"CAD_displayName": "Dollar Ceanada",
	"BZD_displayName": "Dollar na Beilíse",
	"CLP_displayName": "Peso na Sile",
	"XOF_displayName": "CFA Franc BCEAO",
	"NOK_displayName": "Krone Ioruach",
	"DOP_displayName": "Peso Doimineacach",
	"KRW_displayName": "Won na Cóiré Theas",
	"USD_displayName": "Dollar S.A.M.",
	"UYU_displayName": "Peso Uruguayo Uragua",
	"UZS_displayName": "Sum na hÚisbéiceastáine",
	"QAR_displayName": "Rial Catarach",
	"SAR_displayName": "Riyal Sádach",
	"SYP_displayName": "Punt Siria",
	"EGP_displayName": "Punt na hÉigipte",
	"AMD_displayName": "Dram Airméanach",
	"GBP_displayName": "Punt Steirling",
	"HUF_displayName": "Forint Ungárach",
	"ISK_displayName": "Krona Íoslannach",
	"IRR_displayName": "Rial Iaránach",
	"OMR_displayName": "Rial Omain",
	"TWD_displayName": "Dollar Nua na Téaváine",
	"PAB_displayName": "Balboa Panamach",
	"UAH_displayName": "Hryvnia Úcránach",
	"ETB_displayName": "Birr na hAetóipe",
	"PLN_displayName": "Zloty Polannach",
	"VEF_displayName": "Bolivar Veiniséala",
	"BRL_displayName": "Real Brasaíleach",
	"HKD_displayName": "Dollar Hong Cong",
	"NIO_displayName": "Cordoba Oro Nicearagua",
	"NPR_displayName": "Rúipí Neipeáil",
	"PKR_displayName": "Rúipí na Pacastáine",
	"GEL_displayName": "Lari na Grúise",
	"MYR_displayName": "Ringgit Malaeisia",
	"DKK_displayName": "Krone Danmhargach",
	"THB_displayName": "Baht na Téalainne",
	"JPY_displayName": "Yen Seapánach",
	"KES_displayName": "Scilling Céiniach",
	"KHR_displayName": "Riel na Cambóide",
	"PYG_displayName": "Guarani Pharagua",
	"LKR_displayName": "Rúipí Srí Lanca",
	"BGN_displayName": "Lev Nua Bulgárach",
	"BDT_displayName": "Taka Bhanglaidéiseach",
	"MOP_displayName": "Pataca Macao",
	"HNL_displayName": "Lempira Hondúrais",
	"RWF_displayName": "Franc Ruanda",
	"CHF_displayName": "Franc na hEilvéise",
	"CRC_displayName": "Colon Chósta Ríce",
	"INR_displayName": "Rúipí India",
	"ZAR_displayName": "Rand na hAfraice Theas",
	"AUD_displayName": "Dollar Astrálach",
	"LAK_displayName": "Kip Laosach",
	"MNT_displayName": "Tugrik Mongólach",
	"HRK_displayName": "Kuna Crótach"
}
//end v1.x content
);