define(
"dojo/cldr/nls/pl/currency", //begin v1.x content
{
	"COP_displayName": "peso kolumbijskie",
	"CZK_displayName": "korona czeska",
	"TND_displayName": "dinar tunezyjski",
	"CAD_symbol": "CAD",
	"JMD_displayName": "dolar jamajski",
	"PHP_displayName": "peso filipińskie",
	"ALL_displayName": "lek albański",
	"USD_symbol": "USD",
	"LBP_displayName": "funt libański",
	"VND_displayName": "dong wietnamski",
	"LYD_displayName": "dinar libijski",
	"RON_displayName": "leja rumuńska",
	"MKD_displayName": "denar macedoński",
	"SEK_displayName": "korona szwedzka",
	"CNY_displayName": "juan chiński",
	"IDR_displayName": "rupia indonezyjska",
	"ILS_displayName": "nowy szekel izraelski",
	"YER_displayName": "rial jemeński",
	"TJS_displayName": "somoni tadżyckie",
	"TTD_displayName": "dolar Trynidadu i Tobago",
	"CNY_symbol": "CNY",
	"TRY_displayName": "lira turecka",
	"EUR_displayName": "euro",
	"AED_displayName": "dirham arabski",
	"KZT_displayName": "tenge kazachskie",
	"BHD_displayName": "dinar bahrański",
	"RUB_displayName": "rubel rosyjski",
	"NZD_displayName": "dolar nowozelandzki",
	"IQD_displayName": "dinar iracki",
	"TMT_displayName": "manat turkmeński",
	"ZWL_displayName": "dolar Zimbabwe (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "som kirgiski",
	"KWD_displayName": "dinar kuwejcki",
	"AFN_displayName": "afgani",
	"ARS_displayName": "peso argentyńskie",
	"PLN_symbol": "zł",
	"MAD_displayName": "dirham marokański",
	"BAM_displayName": "marka zamienna Bośni i Hercegowiny",
	"BOB_displayName": "boliviano",
	"BND_displayName": "dolar brunejski",
	"SGD_displayName": "dolar singapurski",
	"MVR_displayName": "rupia malediwska",
	"MXN_displayName": "peso meksykańskie",
	"DZD_displayName": "dinar algierski",
	"MXN_symbol": "MXN",
	"JOD_displayName": "dinar jordański",
	"PEN_displayName": "nowy sol peruwiański",
	"GTQ_displayName": "quetzal gwatemalski",
	"BYR_displayName": "rubel białoruski",
	"CAD_displayName": "dolar kanadyjski",
	"BZD_displayName": "dolar belizeński",
	"CLP_displayName": "peso chilijskie",
	"XOF_displayName": "frank CFA",
	"NOK_displayName": "korona norweska",
	"DOP_displayName": "peso dominikańskie",
	"JPY_symbol": "JPY",
	"KRW_displayName": "won południowokoreański",
	"USD_displayName": "dolar amerykański",
	"UYU_displayName": "peso urugwajskie",
	"UZS_displayName": "som uzbecki",
	"XOF_symbol": "CFA",
	"QAR_displayName": "rial katarski",
	"SAR_displayName": "rial saudyjski",
	"SYP_displayName": "funt syryjski",
	"NZD_symbol": "NZD",
	"EGP_displayName": "funt egipski",
	"AMD_displayName": "dram armeński",
	"GBP_displayName": "funt szterling",
	"HUF_displayName": "forint węgierski",
	"CSD_displayName": "stary dinar serbski",
	"ISK_displayName": "korona islandzka",
	"IRR_displayName": "rial irański",
	"OMR_displayName": "rial omański",
	"TWD_displayName": "nowy dolar tajwański",
	"PAB_displayName": "balboa panamski",
	"UAH_displayName": "hrywna ukraińska",
	"ETB_displayName": "birr etiopski",
	"PLN_displayName": "złoty polski",
	"VEF_displayName": "boliwar wenezuelski",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "real brazylijski",
	"HKD_symbol": "HKD",
	"HKD_displayName": "dolar hongkoński",
	"NIO_displayName": "cordoba nikaraguańska",
	"THB_symbol": "THB",
	"NPR_displayName": "rupia nepalska",
	"PKR_displayName": "rupia pakistańska",
	"TWD_symbol": "TWD",
	"GEL_displayName": "lari gruzińskie",
	"AZN_displayName": "manat azerski",
	"GBP_symbol": "GBP",
	"MYR_displayName": "ringgit malezyjski",
	"DKK_displayName": "korona duńska",
	"THB_displayName": "baht tajski",
	"BRL_symbol": "R$",
	"JPY_displayName": "jen japoński",
	"KES_displayName": "szyling kenijski",
	"KHR_displayName": "riel kambodżański",
	"PYG_displayName": "guarani paragwajskie",
	"VND_symbol": "VND",
	"LKR_displayName": "rupia lankijska",
	"BGN_displayName": "lew bułgarski",
	"BDT_displayName": "taka bengalska",
	"MOP_displayName": "pataca Makau",
	"HNL_displayName": "lempira honduraska",
	"RWF_displayName": "frank ruandyjski",
	"CHF_displayName": "frank szwajcarski",
	"CRC_displayName": "colon kostarykański",
	"INR_displayName": "rupia indyjska",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "rand południowoafrykański",
	"AUD_displayName": "dolar australijski",
	"LAK_displayName": "kip laotański",
	"MNT_displayName": "tugrik mongolski",
	"RSD_displayName": "dinar serbski",
	"HRK_displayName": "kuna chorwacka"
}
//end v1.x content
);