SELECT     sysdba.SALESORDERITEMS.SALESORDERITEMSID, tmp.TACACCOUNTID, tmp.LINENUMBER, tmp.SALESORDERID
FROM         sysdba.SALESORDERITEMS INNER JOIN
                          (SELECT     COUNT(*) AS Expr1, SALESORDERID, TACACCOUNTID, LINENUMBER
                            FROM          sysdba.SALESORDERITEMS AS SALESORDERITEMS_1
                            GROUP BY SALESORDERID, TACACCOUNTID, LINENUMBER
                            HAVING      (COUNT(*) > 1)) AS tmp ON sysdba.SALESORDERITEMS.SALESORDERID = tmp.SALESORDERID AND 
                      sysdba.SALESORDERITEMS.TACACCOUNTID = tmp.TACACCOUNTID AND sysdba.SALESORDERITEMS.LINENUMBER = tmp.LINENUMBER