update
dbo.MAS_TO_SLX_PRODUCT_Temp
set DESCRIPTION = 'TODELETE' 
FROM         dbo.MAS_TO_SLX_PRODUCT_Temp 
INNER JOIN
                      VProductsToReSync ON MAS_TO_SLX_PRODUCT_Temp.ACTUALID = VProductsToReSync.ACTUALID AND 
                      MAS_TO_SLX_PRODUCT_Temp.WAREHOUSEID = VProductsToReSync.WAREHOUSEID AND 
                      MAS_TO_SLX_PRODUCT_Temp.CompanyID = VProductsToReSync.CompanyID AND 
                      MAS_TO_SLX_PRODUCT_Temp.MASITEMKEY = VProductsToReSync.MASITEMKEY
                      
dELETE FROM DBO.MAS_TO_SLX_PRODUCT_Temp where DESCRIPTION = 'TODELETE'  

SELECT        NAME, cast(DESCRIPTION as nvarchar(max))as DESCP, ACTUALID, FAMILY, PRICE, PRODUCTGROUP, STATUS, UNIT, STOCKVOLUME, STOCKWEIGHT, STOCKITEM, PROGRAM, SUPPLIER, VENDOR, SITEID, WAREHOUSELOCATION, 
                         COMMISSIONABLE, TAXABLE, ACCOUNTINGPERIOD, GLACCOUNTNUMBER, GLSUBACCOUNTNUMBER, DATAOWNER, TYPE, FIXEDCOST, GLOBALSYNCID, APPID, TICK, COMMODITYGROUPID, ACTIVEFLAG, 
                         SELLINGALLOWEDFLAG, UNITOFMEASUREID, SELLINGUOMID, SELLINGUOMNUMBER, CLASSIFICATION, COMMODITYTYPE, MASITEMKEY, UPC, MASITEMID, WAREHOUSEID, CompanyID, QtyOnHand, 
                         QtyAvailable, SurplusQty, QtyOnHold, MaxStockLevel, ProdPriceGroupKey
FROM            MAS_TO_SLX_PRODUCT_Temp
where ACTUALID = '3SGN300E' and WAREHOUSEID = 'ONT' and COMPANYID ='EAB'
except

Select NAME, cast(DESCRIPTION as nvarchar(max))as DESCP, ACTUALID, FAMILY, PRICE, PRODUCTGROUP, STATUS, UNIT, STOCKVOLUME, STOCKWEIGHT, STOCKITEM, PROGRAM, SUPPLIER, VENDOR, SITEID, WAREHOUSELOCATION, 
                         COMMISSIONABLE, TAXABLE, ACCOUNTINGPERIOD, GLACCOUNTNUMBER, GLSUBACCOUNTNUMBER, DATAOWNER, TYPE, FIXEDCOST, GLOBALSYNCID, APPID, TICK, COMMODITYGROUPID, ACTIVEFLAG, 
                         SELLINGALLOWEDFLAG, UNITOFMEASUREID, SELLINGUOMID, SELLINGUOMNUMBER, CLASSIFICATION, COMMODITYTYPE, MASITEMKEY, UPC, MASITEMID, WAREHOUSEID, CompanyID, QtyOnHand, 
                         QtyAvailable, SurplusQty, QtyOnHold, MaxStockLevel, MASPRODPRICEGROUPKEY from sysdba.PRODUCT
where ACTUALID = '3SGN300E' and WAREHOUSEID = 'ONT' and COMPANYID ='EAB'

Select * from sysdba.product 
where ACTUALID = '3SGN300E' and WAREHOUSEID = 'ONT' and COMPANYID ='EAB'