SELECT     STGSALESORDER_TACID, CREATEUSER, CREATEDATE, MODIFYUSER, MODIFYDATE, TRANNO, TRANDATE, TRADEDISCAMT, STAXAMT, STATUS, SESSIONKEY, 
                      ROWKEY, REQUIRESOACK, RECURSOTRANNO, PROCESSSTATUS, OPENAMT, HOLD, FREIGHTAMT, DFLTSHIPTOCUSTADDRID, CUSTID, CUSTCLASSID, CURRID, 
                      CURREXCHRATE, CONTACTNAME, BILLTOCUSTADDRID, DFLTSHIPPRIORITY, PMTTERMSID, COMPANYID, UserFld1, CustPONO, DFLTSHIPMETHID, TRANCMNT, PrimarySperID, SalesOrderID
FROM         sysdba.STGSALESORDER_TAC
WHERE     (TRANNO = '0')