define(
"dojo/cldr/nls/mn/currency", //begin v1.x content
{
	"COP_displayName": "Колумбын песо",
	"CZK_displayName": "Чех коруна",
	"TND_displayName": "Тунис доллар",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Ямайк доллар",
	"PHP_displayName": "Филиппин песо",
	"ALL_displayName": "Албани лек",
	"USD_symbol": "$",
	"LBP_displayName": "Ливан паунд",
	"VND_displayName": "Вьетнам донг",
	"LYD_displayName": "Ливи доллар",
	"RON_displayName": "Румын леу",
	"MKD_displayName": "Македони денар",
	"SEK_displayName": "Швед крона",
	"CNY_displayName": "Хятад юань",
	"IDR_displayName": "Индонези рупи",
	"ILS_displayName": "Израиль шинэ шекел",
	"YER_displayName": "Йемен риал",
	"TJS_displayName": "Тажик сом",
	"TTD_displayName": "Тринидад ба Тобаго доллар",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Туркийн лира",
	"EUR_displayName": "Евро",
	"AED_displayName": "Арабын Нэгдсэн Эмиратын дирхам",
	"KZT_displayName": "Казах тэнгэ",
	"MNT_symbol": "₮",
	"BHD_displayName": "Бахрейн динар",
	"RUB_displayName": "Орос рубль",
	"NZD_displayName": "Шинэ Зеланд доллар",
	"IQD_displayName": "Ирак динар",
	"TMT_displayName": "Туркмен манат",
	"INR_symbol": "INR",
	"KGS_displayName": "Кыргыз сом",
	"KWD_displayName": "Кувейт динар",
	"AFN_displayName": "Афганистаний афгани",
	"ARS_displayName": "Аргентин песо",
	"MAD_displayName": "Марокко дирхам",
	"BAM_displayName": "Босни-Герцеговин хөрвөгч марк",
	"BOB_displayName": "Боливи боливиано",
	"BND_displayName": "Бруней доллар",
	"SGD_displayName": "Сингапур доллар",
	"MVR_displayName": "Мальдив руфия",
	"MXN_displayName": "Мексик песо",
	"DZD_displayName": "Алжир доллар",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Йордан динар",
	"PEN_displayName": "Перу шинэ соль",
	"GTQ_displayName": "Гватемал кецал",
	"BYR_displayName": "Беларус рубль",
	"CAD_displayName": "Канад доллар",
	"BZD_displayName": "Белиз доллар",
	"CLP_displayName": "Чили песо",
	"XOF_displayName": "Франк КФА BCЕАО",
	"NOK_displayName": "Норвеги кроне",
	"DOP_displayName": "Доминикан песо",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Өмнөд Солонгос вон",
	"USD_displayName": "Америк доллар",
	"UYU_displayName": "Уругвай песо",
	"UZS_displayName": "Узбек сом",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Катар риал",
	"SAR_displayName": "Саудын риял",
	"SYP_displayName": "Сири паунд",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "Египет паунд",
	"AMD_displayName": "Армени драм",
	"GBP_displayName": "Англи фунт стерлинг",
	"HUF_displayName": "Унгар форинт",
	"ISK_displayName": "Исланд крона",
	"IRR_displayName": "Иран риал",
	"OMR_displayName": "Омани риал",
	"TWD_displayName": "Шинэ Тайван доллар",
	"PAB_displayName": "Панам бальбоа",
	"UAH_displayName": "Украйн гривня",
	"ETB_displayName": "Этиоп бирр",
	"PLN_displayName": "Польш злот",
	"VEF_displayName": "Венесуэл боливар",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "Бразилийн рил",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Хонгконг доллар",
	"NIO_displayName": "Никарагуа кордоба",
	"THB_symbol": "฿",
	"NPR_displayName": "Балба рупи",
	"PKR_displayName": "Пакистан рупи",
	"TWD_symbol": "TWD",
	"GEL_displayName": "Гүрж лари",
	"AZN_displayName": "Азербайжан манат",
	"GBP_symbol": "£",
	"MYR_displayName": "Малайз ринггит",
	"DKK_displayName": "Данийн крон",
	"THB_displayName": "Тай бат",
	"BRL_symbol": "R$",
	"JPY_displayName": "Япон иен",
	"KES_displayName": "Кени шиллинг",
	"KHR_displayName": "Камбож риел",
	"PYG_displayName": "Парагвай гуарани",
	"VND_symbol": "₫",
	"LKR_displayName": "Шри-Ланк рупи",
	"BGN_displayName": "Болгар лев",
	"BDT_displayName": "Бангладеш така",
	"MOP_displayName": "Макао патака",
	"HNL_displayName": "Гондурас лемпира",
	"RWF_displayName": "Руанд франк",
	"CHF_displayName": "Швейцар франк",
	"CRC_displayName": "Коста Рика колон",
	"INR_displayName": "Энэтхэг рупи",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Өмнөд Африкийн ранд",
	"AUD_displayName": "Австралийн доллар",
	"LAK_displayName": "Лао кип",
	"MNT_displayName": "Төгрөг",
	"RSD_displayName": "Серб динар",
	"HRK_displayName": "Хорватын куна"
}
//end v1.x content
);