define("Sage/UI/Filters/nls/zh-cn/CheckBoxFilter", {
    "loadingText": "正在加载...",
    "moreText": "编辑项目",
    "clearText": "清除",
    "emptyText": "(空白)",
    "nullText": "(空值)",
    "ofText": "/",
    "filterHasMetric": "具有度量",
    "filterHasFilter": "具有筛选器",
    "filteroptionYesterday": "昨天",
    "filteroptionToday": "今天",
    "filteroptionThisWeek": "本周",
    "filteroptionThisMonth": "本月",
    "filteroptionThisQuarter": "本季度",
    "filteroptionThisYear": "本年",
    "filteroptionLastWeek": "上一周",
    "filteroptionLastMonth": "上个月",
    "filteroptionLastQuarter": "上一季度",
    "filteroptionLastYear": "上一年",
    "filteroptionWeektoStart": "本周至今",
    "filteroptionMonthtoStart": "本月至今",
    "filteroptionQtrtoStart": "本季度至今",
    "filteroptionYeartoStart": "本年至今",
    "filteroptionOlder": "早于",
    "filteroption0To999": "0 到 999",
    "filteroption1000To9999": "1000 到 9999",
    "filteroption10000To99999": "10,000 到 99,999",
    "filteroption100000To499999": "100,000 到 499,999",
    "filteroption500000To999999": "500,000 到 999,999",
    "filteroption1000000AndHigher": "1,000,000 及更高",
    "filteroptionT": "T"
});