define(
"dojo/cldr/nls/gu/currency", //begin v1.x content
{
	"COP_displayName": "કોલમ્બિયન પેસો",
	"CZK_displayName": "ચેક રીપબ્લિક કોરુના",
	"TND_displayName": "ટ્યુનિશિયન દિનાર",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "જમૈકિયન ડોલર",
	"PHP_displayName": "ફિલીપાઇન પેસો",
	"ALL_displayName": "અલ્બેનિયન લેક",
	"USD_symbol": "US$",
	"LBP_displayName": "લેબેનિઝ પાઉન્ડ",
	"VND_displayName": "વિયેતનામીસ ડોંગ",
	"LYD_displayName": "લિબ્યન દિનાર",
	"RON_displayName": "રોમાનિયન લેઉ",
	"MKD_displayName": "મેસેડોનિયન દિનાર",
	"SEK_displayName": "સ્વીડિશ ક્રોના",
	"CNY_displayName": "ચાઇનિઝ યુઆન",
	"IDR_displayName": "ઇન્ડોનેશિયન રૂપિયા",
	"ILS_displayName": "ઇઝરાયેલી ન્યુ શેકલ",
	"YER_displayName": "યેમેની રિઆલ",
	"TJS_displayName": "તાજિકિસ્તાની સોમોની",
	"TTD_displayName": "ત્રિનિદાદ અને ટોબેગો ડોલર",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "તુર્કિશ લિરા",
	"EUR_displayName": "યુરો",
	"AED_displayName": "યુનાઈટેડ આરબ અમિરાત દિરહામ",
	"KZT_displayName": "કઝાકિસ્તાની ટેંગ",
	"BHD_displayName": "બેહરિની દિનાર",
	"RUB_displayName": "રશિયન રબલ",
	"NZD_displayName": "ન્યૂઝિલેંડ ડૉલર",
	"IQD_displayName": "ઇરાકી દિનાર",
	"TMT_displayName": "તુર્કમેનિસ્તાની મનત",
	"INR_symbol": "₹",
	"KGS_displayName": "કિર્ગિસ્તાની સોમ",
	"KWD_displayName": "કુવૈતી દીનાર",
	"AFN_displayName": "અફ્ગાન અફ્ગાની",
	"ARS_displayName": "અર્જેન્ટીના પેસો",
	"MAD_displayName": "મોરોક્કન દિરામ",
	"BAM_displayName": "બોસ્નિયા અને હર્ઝેગોવિના રૂપાંતર યોગ્ય માર્ક",
	"BOB_displayName": "બોલિવિયન બોલિવિયાનો",
	"BND_displayName": "બ્રુનેઇ ડોલર",
	"SGD_displayName": "સિંગાપુર ડૉલર",
	"MVR_displayName": "માલ્દિવિયન રુફિયા",
	"MXN_displayName": "મેક્સિકન પેસો",
	"DZD_displayName": "અલ્જિરિયન દિનાર",
	"MXN_symbol": "MX$",
	"JOD_displayName": "જોર્ડનિયન દિનાર",
	"PEN_displayName": "પેરુવિયન ન્યુવો સોલ",
	"GTQ_displayName": "ગ્વાટેમાલા કુઇટ્ઝલ",
	"BYR_displayName": "બેલારુશિયન રબલ",
	"CAD_displayName": "કેનેડિયન ડૉલર",
	"BZD_displayName": "બેલિઝ ડોલર",
	"CLP_displayName": "ચિલિઅન પેસો",
	"XOF_displayName": "CFA ફ્રેંક BCEAO",
	"NOK_displayName": "નૉર્વેજિયન ક્રોન",
	"DOP_displayName": "ડોમિનિકન પેસો",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "દક્ષિણ કોરિયન વન",
	"USD_displayName": "યુઍસ ડોલર",
	"UYU_displayName": "ઉરુગ્વેયન પેસો",
	"UZS_displayName": "ઉઝ્બેકિસ્તાન સોમ",
	"XOF_symbol": "CFA",
	"QAR_displayName": "કતારી રિયાલ",
	"SAR_displayName": "સાઉદી રિયાલ",
	"SYP_displayName": "સાઇરિયન પાઉન્ડ",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "ઇજિપ્તિયન પાઉન્ડ",
	"AMD_displayName": "અર્મેનિયન ડ્રેમ",
	"GBP_displayName": "બ્રિટિશ પાઉન્ડ સ્ટર્લિંગ",
	"HUF_displayName": "હંગેરીયન ફોરિન્ત",
	"ISK_displayName": "આઇસ્લેંડિક ક્રોના",
	"IRR_displayName": "ઇરાનિયન રિયાલ",
	"OMR_displayName": "ઓમાની રિયાલ",
	"TWD_displayName": "ન્યુ તાઇવાન ડૉલર",
	"PAB_displayName": "પનામેનિયન બાલ્બોઆ",
	"UAH_displayName": "યુક્રેનિયન હ્રિવિનિયા",
	"ETB_displayName": "ઇથિયોપીયન બિર",
	"PLN_displayName": "પોલિસ ઝ્લોટી",
	"VEF_displayName": "વેનેઝ્વીલિયન બોલિવર",
	"ILS_symbol": "₪",
	"AUD_symbol": "A$",
	"BRL_displayName": "બ્રાઝિલીયન રિઆલ",
	"HKD_symbol": "HK$",
	"HKD_displayName": "હોંગ કોંગ ડૉલર",
	"NIO_displayName": "નિકારાગુઅન કોર્ડોબા",
	"THB_symbol": "฿",
	"NPR_displayName": "નેપાલિઝ રૂપી",
	"PKR_displayName": "પાકિસ્તાની રૂપી",
	"TWD_symbol": "NT$",
	"GEL_displayName": "જ્યોર્જિઅન લારી",
	"AZN_displayName": "અઝરબૈજાની મનાત",
	"GBP_symbol": "£",
	"MYR_displayName": "મલેશિયન રિંગ્ગેટ",
	"DKK_displayName": "ડેનિશ ક્રોન",
	"THB_displayName": "થાઇ બાહ્ત",
	"BRL_symbol": "R$",
	"JPY_displayName": "જાપાનીઝ યેન",
	"KES_displayName": "કેન્યેન શિલિંગ",
	"KHR_displayName": "કેમ્બોડિયન રીઅલ",
	"PYG_displayName": "પરાગ્વેયન ગૌરાની",
	"VND_symbol": "₫",
	"LKR_displayName": "શ્રી લંકન રૂપી",
	"BGN_displayName": "બલ્ગેરીયન લેવ",
	"BDT_displayName": "બાંગલાદેશી ટાકા",
	"MOP_displayName": "માકાનિઝ પતાકા",
	"HNL_displayName": "હોન્ડ્યુરન લેમ્પિરા",
	"RWF_displayName": "રવાંડન ફ્રેંક",
	"CHF_displayName": "સ્વિસ ફ્રેંક",
	"CRC_displayName": "કોસ્ટા રિકન કોલોન",
	"INR_displayName": "ભારતીય રૂપિયા",
	"KRW_symbol": "₩",
	"ZAR_displayName": "દક્ષિણ આફ્રિકી રેંડ",
	"AUD_displayName": "ઑસ્ટ્રેલિયન ડૉલર",
	"LAK_displayName": "લાઓશિયન કિપ",
	"MNT_displayName": "મોંગોલિયન ટગરિક",
	"RSD_displayName": "સર્બિયન દિનાર",
	"HRK_displayName": "ક્રોએશિયન ક્યુના"
}
//end v1.x content
);