define("Sage/UI/Filters/nls/fr/CheckBoxFilter", {
    "loadingText": "Chargement...",
    "moreText": "Modifier les éléments",
    "clearText": "Effacer",
    "emptyText": "(Vide)",
    "nullText": "(Nul)",
    "ofText": "/",
    "filterHasMetric": "A une mesure",
    "filterHasFilter": "A un filtre",
    "filteroptionYesterday": "Hier",
    "filteroptionToday": "Aujourd'hui",
    "filteroptionThisWeek": "Cette semaine",
    "filteroptionThisMonth": "Ce mois",
    "filteroptionThisQuarter": "Ce trimestre",
    "filteroptionThisYear": "Cette année",
    "filteroptionLastWeek": "Semaine dernière",
    "filteroptionLastMonth": "Mois dernier",
    "filteroptionLastQuarter": "Trimestre dernier",
    "filteroptionLastYear": "Année dernière",
    "filteroptionWeektoStart": "Semaine à ce jour",
    "filteroptionMonthtoStart": "Mois à ce jour",
    "filteroptionQtrtoStart": "Trimestre à ce jour",
    "filteroptionYeartoStart": "Année à ce jour",
    "filteroptionOlder": "Plus ancien",
    "filteroption0To999": "0 à 999",
    "filteroption1000To9999": "1 000 à 9 999",
    "filteroption10000To99999": "10 000 à 99 999",
    "filteroption100000To499999": "100 000 à 499 999",
    "filteroption500000To999999": "500 000 à 999 999",
    "filteroption1000000AndHigher": "1 000 000 et plus",
    "filteroptionT": "T"
});