define("Sage/UI/nls/zh-cn/ActivityScheduler", {
    "tooltipTime": "时间",
    "tooltipContactName": "联系人",
    "tooltipAccountName": "客户",
    "tooltipCompanyName": "公司",
    "tooltipLeadName": "销售线索",
    "tooltipPhoneNumber": "电话",
    "tooltipRegarding": "相关事项",
    "tooltipPriority": "优先级",
    "tooltipNotes": "备注",
    "tooltipType": "类型",
    "tooltipDayType": "日期类型",
    "tooltipStartDate": "开始日期",
    "tooltipEndDate": "结束日期",
    "tooltipLocation": "地点",
    "tooltipDescription": "描述",
    "completedText": "(已完成)",
    "tooltipMoreActivities": "单击以查看更多活动",
    "scheduler_dates": {
        "month_full": [
            "一月",
            "二月",
            "三月",
            "四月",
            "五月",
            "六月",
            "七月",
            "八月",
            "九月",
            "十月",
            "十一月",
            "十二月"
        ],
        "month_short": [
            "一月",
            "二月",
            "三月",
            "四月",
            "五月",
            "六月",
            "七月",
            "八月",
            "九月",
            "十月",
            "十一月",
            "十二月"
        ],
        "day_full": [
            "星期日",
            "星期一",
            "星期二",
            "星期三",
            "星期四",
            "星期五",
            "星期六"
        ],
        "day_short": [
            "周日",
            "周一",
            "周二",
            "周三",
            "周四",
            "周五",
            "周六"
        ]
    },
    "scheduler_labels": {
        "dhx_cal_today_button": "今天",
        "day_tab": "日",
        "week_tab": "周",
        "workweek_tab": "工作周",
        "month_tab": "月",
        "new_event": "新建事件",
        "icon_save": "保存",
        "icon_cancel": "取消",
        "icon_details": "明细",
        "icon_edit": "编辑",
        "icon_delete": "删除",
        "confirm_closing": "",
        "confirm_deleting": "将永久删除事件，确定吗?",
        "section_description": "描述",
        "section_time": "时间段",
        "full_day": "全天",
        "confirm_recurring": "是否想要编辑整组重复事件?",
        "section_recurring": "重复事件",
        "button_recurring": "已禁用",
        "button_recurring_open": "已启用",
        "agenda_tab": "议程",
        "date": "日期",
        "description": "描述",
        "year_tab": "年",
        "week_agenda_tab": "议程"
    }
});