define("Sage/UI/nls/zh-cn/SDataFeed", {
    "contractText": "合同",
    "contractRequiredText": "必须提供合同",
    "sdataUrlText": "SData URL",
    "titleText": "标题",
    "usernameText": "用户名",
    "passwordText": "密码",
    "logOnText": "登录",
    "urlRequiredText": "必须提供 SData URL",
    "urlImproperFormatText": "SData URL 格式无效。示例: http://localhost/sdata/slx/dynamic/-/",
    "customNoAuthText1": "对于由此造成的不便，我们深表歉意，但是无法完成您的申请。该消息源的授权信息不正确或缺失。",
    "customNoAuthText2": "请更新用户名和密码:",
    "feedText": "SData 消息源",
    "urlAuthenticationText": "请输入自定义 SData 消息源",
    "selectFeedText": "选择消息源",
    "nextText": "下一步 &gt;",
    "warningText": "信息",
    "invalidWhereText": "抱歉，Where 子句无效。请检查 where 子句以查找任何格式错误。有关更多信息，请参阅帮助主题“创建 Where 子句”。",
    "failedToLoadUrlText": "抱歉，申请的消息源加载失败。请选择其他消息源或联系系统管理员。",
    "noFeedSelectedText": "未选择任何消息源类型",
    "resourceText": "资源",
    "whereText": "Where 子句",
    "previousText": "&lt; 返回",
    "noResourceSelectedText": "选择资源",
    "noColumnsSelectedText": "请选择一个或多个要在小组件中显示的列。",
    "limitRangeText": "请输入 1-100 之间的值",
    "testText": "测试",
    "cancelText": "取消",
    "finishText": "完成",
    "exampleQueryText1": "示例:",
    "exampleQueryText2": "机器 IP 地址",
    "exampleQueryText3": "端口号",
    "exampleWhereText": "了解更多信息",
    "numberRecordsText": "可见记录",
    "sageSalesLogixDynamic": "Saleslogix 动态实体",
    "sageSalesLogixSystem": "Saleslogix 系统",
    "selectColumnsFromText": "可用列:",
    "selectedColumnsFromText": "选定列:"
});