define("Sage/UI/nls/zh-tw/NotesHistoryList", {
    "typeText": "類型",
    "showDbChangesText": "顯示資料庫變更",
    "selectAllText": "全選",
    "dateText": "日期",
    "dateTimeText": "日期/時間",
    "dateRangeText": "日期範圍",
    "userText": "使用者",
    "accountText": "客戶",
    "contactText": "聯絡人",
    "opportunityText": "商機",
    "regardingText": "關於",
    "notesText": "備註",
    "resultText": "結果",
    "categoryText": "類別",
    "sendEmailText": "透過電子郵件傳送",
    "sendToWordText": "傳送至 Word",
    "addNoteText": "新增備註",
    "completeAnActivityText": "完成活動",
    "helpText": "說明",
    "pleaseSelectRecordsText": "請選取一或多個記錄",
    "UnableToFindWordMsg": "無法啟動 Microsoft Word。請檢查您的安全性設定。",
    "printedOnText": "列印日期",
    "errorNoData": "沒有可共用至 Ming.le 的備註/歷程記錄。",
    "yesButtonText": "是",
    "noButtonText": "否",
    "salesLogixPageTitle": "Infor CRM",
    "noRecordsSelectedProcessAll": "未選取任何記錄。所有備註/歷程記錄，共 ${0} 個記錄將共用至 Ming.le。",
    "errorShareMingle": "嘗試將一或多個備註/歷程記錄共用至 Ming.le 時發生錯誤。",
    "sharedToMingle": "備註/歷程記錄已共用至 Ming.le。",
    "sharingToMingle": "共用至 Ming.le",
    "shared": "共用",
    "pleaseWait": "請稍候...",
    "failedToPost": "無法張貼: ${0}；錯誤: ${1}",
    "addressText": "地址",
    "mainPhoneText": "主要電話",
    "tollFreeText": "免付費",
    "contactPhoneText": "聯絡人電話"
});