define("Sage/UI/Controls/nls/zh-tw/PropertyStore", {
    "text": "文字",
    "memo": "備忘",
    "unicodeText": "Unicode 文字",
    "unicodeMemo": "Unicode 備忘",
    "integer": "整數",
    "double": "雙倍",
    "single": "單一",
    "decimal": "小數點",
    "short": "簡短",
    "standardId": "標準 ID",
    "trueFalse": "真/假",
    "yesNo": "是/否",
    "boolean": "布林值",
    "dateTime": "日期/時間",
    "email": "電子郵件",
    "phone": "電話",
    "pickList": "挑選清單",
    "owner": "擁有者",
    "lookup": "查閱",
    "dependencyLookup": "相依性查閱",
    "char": "圖表",
    "enum_": "列舉",
    "guid": "Guid",
    "byte": "位元組",
    "binary": "二進位",
    "url": "URL",
    "string": "字串",
    "number": "數字",
    "calc": "計算欄位",
    "calcSF": "計算字串",
    "calcNF": "計算數字"
});