define("Sage/MainView/CopyUserProfile/nls/it/CopyUserProfile", {
    "dlg_Title": "Copia profilo",
    "dlg_Instructions": "Seleziona un profilo utente o modello da copiare per tutti gli altri utenti. Copiando il profilo verranno sovrascritte tutte le impostazioni correnti.",
    "rad_SelectionLabel": "Copia profilo da:",
    "rad_UserBtn": "Utente esistente",
    "rad_TemplateBtn": "Modello",
    "user_LookupLabel": "Utente",
    "template_LookupLabel": "Modello",
    "lookupUserNameColText": "Nome utente",
    "lookupTitleColText": "Titolo",
    "lookupDepartmentColText": "Reparto",
    "lookupRegionColText": "Regione",
    "lookupUser_Caption": "Utente da cui copiare il profilo",
    "lookupUserNameTemplateColText": "Modello",
    "chkGeneralLabel": "Generale",
    "chkCalendarLabel": "Calendario",
    "chkEmployeeLabel": "Dipendente",
    "chkClientLabel": "Opzioni client (sistema client)",
    "chkSecurityLabel": "Sicurezza",
    "chkServiceLabel": "Servizio/supporto",
    "chkTeamsLabel": "Team",
    "txtJobDescriptor": "Copia il profilo utente",
    "jobFailer": "Si è verificato un errore critico"
});