define("Sage/MainView/ReportMgr/Crystal/nls/zh-tw/_ParameterEditorBase", {
    "txtPleaseSpecifyValue": "請指定一個值。",
    "lblAvailableValues_Caption": "可用的值:",
    "lblSelectedValues_Caption": "選取的值:",
    "lblEnterValue_Caption": "輸入一個值:",
    "btnOK_Caption": "確定",
    "txtTheValueMustBeBetween": "值的長度必須在 {0} 和 {1} 個字元之間。",
    "txtTheMinimumLengthForThisField": "這個欄位的長度最小值為 {0}。",
    "txtTheMaximumLengthForThisField": "這個欄位的長度最大值為 {0}。",
    "txtPleaseSpecifyNumberBetween": "請指定 {0} 到 {1} 之間的數值。",
    "txtPleaseSpecifyNumberLesser": "請指定小於或等於 {0} 的數值。",
    "txtPleaseSpecifyNumberGreater": "請指定大於或等於 {0} 的數值。",
    "txtNoLowerValue": "沒有下限值",
    "txtNoUpperValue": "沒有上限值",
    "txtIncludeThisValue": "包含這個值",
    "txtFrom": "從:",
    "txtTo": "至:",
    "txtPleaseSpecifyFromValue": "請指定開始範圍值",
    "txtPleaseSpecifyToValue": "請指定結束範圍值",
    "txtPleaseSpecifyDateBetween": "請指定 {0} 到 {1} 之間的日期值。",
    "txtPleaseSpecifyDateLesser": "請指定小於或等於 {0} 的日期值。",
    "txtPleaseSpecifyDateGreater": "請指定大於或等於 {0} 的日期值。",
    "txtFromMustBeLessThanOrEqualToTo": "開始範圍值必須小於或等於結束範圍值。",
    "txtStartOfRange": "範圍開始:",
    "txtEndOfRange": "範圍結束:",
    "txtAddRange": "新增範圍",
    "lblSelectValue_Caption": "選取一個值:",
    "lblOrValue_Caption": "或"
});