define("Sage/Reporting/nls/it/Enumerations", {
    "txtGroup": "Gruppo",
    "txtDateRange": "Intervallo di date",
    "txtUser": "Utente",
    "txtQuery": "Query",
    "txtIsGreaterThan": "È maggiore di",
    "txtIsLessThan": "È minore di",
    "txtIsInTheRange": "È nell'intervallo",
    "txtIsAfter": "È dopo",
    "txtIsBefore": "È prima di",
    "txtContains": "Contiene",
    "txtStartsWith": "Inizia con",
    "txtEndsWith": "Termina con",
    "txtIs": "È",
    "txtIsNot": "È diverso da",
    "txtOnDemand": "Su richiesta",
    "txtScheduled": "Pianificato",
    "txtCrystalReport": "Report Crystal",
    "txtExportToFileReportType": "Esporta nel file",
    "txtUnknownReportType": "Sconosciuto",
    "txtNoFormat": "Nessun formato",
    "txtPdf": "PDF",
    "txtExcel": "Excel",
    "txtExcelDataOnly": "Excel-dati",
    "txtCsv": "CSV",
    "txtWord": "Word",
    "txtXml": "XML"
});