define(
"dojo/cldr/nls/ta/currency", //begin v1.x content
{
	"COP_displayName": "கொலம்பியன் பெசோ",
	"CZK_displayName": "செக் குடியரசு கொருனா",
	"TND_displayName": "துனிஷியன் தினார்",
	"CAD_symbol": "CA$",
	"JMD_displayName": "ஜமைக்கான் டாலர்",
	"PHP_displayName": "ஃபிலிபைன் பேசோ",
	"ALL_displayName": "அல்பேனியன் லெக்",
	"USD_symbol": "$",
	"LBP_displayName": "லபனீஸ் பவுண்டு",
	"VND_displayName": "வியட்நாமீஸ் டாங்",
	"LYD_displayName": "லிபியன் தினார்",
	"RON_displayName": "ரோமானியன் லியூ",
	"MKD_displayName": "மெசிடோனியன் தினார்",
	"SEK_displayName": "ஸ்வீடிஷ் க்ரோனா",
	"CNY_displayName": "சீன யுவான்",
	"IDR_displayName": "இந்தோனேஷியன் ருபியா",
	"ILS_displayName": "இஸ்ரேலி நியூ ஷிகேல்",
	"YER_displayName": "யெமினி ரியால்",
	"TJS_displayName": "தஜிகிஸ்தானி சோமோனி",
	"TTD_displayName": "டிரினாட் மற்றும் டோபாகோ டாலர்",
	"TRY_displayName": "துர்க்கிஸ் லீரா",
	"EUR_displayName": "யூரோ",
	"AED_displayName": "ஐக்கிய அரபு எமிரேட்டு டிர்ஹம்",
	"KZT_displayName": "கஸகஸ்தானி டென்கே",
	"BHD_displayName": "பஹ்ரைனி தினார்",
	"RUB_displayName": "ரஷ்யன் ரூபல்",
	"NZD_displayName": "நியூசிலாந்து டாலர்",
	"IQD_displayName": "ஈராக்கி தினார்",
	"TMT_displayName": "துர்க்மேனிஸ்தானி மனத்",
	"KGS_displayName": "கிரிகிஸ்தானி சோம்",
	"KWD_displayName": "குவைத்தி தினார்",
	"AFN_displayName": "ஆஃப்கான் ஆப்கானி",
	"ARS_displayName": "அர்ஜென்டினா பேசோ",
	"MAD_displayName": "மொரோக்கோ திர்ஹாம்",
	"BAM_displayName": "போஸ்னியா-ஹெர்ஸேகோவினா கன்வெர்டிபில் மார்க்",
	"BOB_displayName": "பொலிவியன் பொலிவியானோ",
	"BND_displayName": "புரூனை டாலர்",
	"SGD_displayName": "சிங்கப்பூர் டாலர்",
	"MVR_displayName": "மால்தீவியன் ருஃபியா",
	"MXN_displayName": "மெக்ஸிகன் பெசோ",
	"MXN_symbol": "MX$",
	"DZD_displayName": "அல்ஜேரியன் தினார்",
	"JOD_displayName": "ஜோர்டானியன் டைனர்",
	"PEN_displayName": "பெருவியன் நியூவோ சோல்",
	"GTQ_displayName": "குவாடெமெலன் குயூட்ஸல்",
	"BYR_displayName": "பெலருஷியன் ரூபில்",
	"CAD_displayName": "கனடியன் டாலர்",
	"BZD_displayName": "பெலீஷ் டாலர்",
	"CLP_displayName": "சிலியன் பெசோ",
	"XOF_displayName": "CFA ஃப்ராங்க் BCEAO",
	"NOK_displayName": "நார்வேஜியன் க்ரோன்",
	"DOP_displayName": "டொமினிக்கன் பேசோ",
	"KRW_displayName": "தென் கொரிய வான்",
	"USD_displayName": "யூ.எஸ். டாலர்",
	"UYU_displayName": "உருகுவேயன் பேசோ",
	"UZS_displayName": "உஜ்பெகிஸ்தான் சோம்",
	"XOF_symbol": "CFA",
	"QAR_displayName": "கத்தாரி ரியால்",
	"SAR_displayName": "சவுதி ரியால்",
	"SYP_displayName": "சிரியன் பவுன்ட்",
	"EGP_displayName": "எகிப்திய பவுண்டு",
	"AMD_displayName": "அர்மேனியன் ட்ராம்",
	"GBP_displayName": "பிரிட்டிஷ் பவுன்ட் ஸ்டெர்லிங்",
	"HUF_displayName": "ஹங்கேரியன் ஃபோரின்ட்",
	"ISK_displayName": "ஐஸ்லாண்டிக் க்ரோனா",
	"IRR_displayName": "இரானியன் ரியால்",
	"OMR_displayName": "ஓமானி ரியால்",
	"TWD_displayName": "புதிய தைவான் டாலர்",
	"PAB_displayName": "பனாமானியன் பால்போபா",
	"UAH_displayName": "உக்ரைனியன் ஹிரைவ்னியா",
	"ETB_displayName": "எத்தியோப்பியன் பிர்",
	"PLN_displayName": "போலிஷ் ஸ்லாட்டி",
	"VEF_displayName": "வெனிசுலியன் போலிவர்",
	"BRL_displayName": "பிரேசிலியன் ரியால்",
	"HKD_displayName": "ஹாங்காங் டாலர்",
	"NIO_displayName": "நிகாராகுவான் கோர்டோபா",
	"NPR_displayName": "நேபாளீஸ் ருபீ",
	"PKR_displayName": "பாக்கிஸ்தானி ருபீ",
	"GEL_displayName": "ஜியார்ஜியன் லாரி",
	"AZN_displayName": "அஜர்பைசானி மனத்",
	"MYR_displayName": "மலேஷியன் ரிங்கித்",
	"DKK_displayName": "டானிஷ் க்ரோன்",
	"THB_displayName": "தாய் பாட்",
	"JPY_displayName": "ஜாப்பனிய யென்",
	"KES_displayName": "கெனியன் ஷில்லிங்",
	"KHR_displayName": "கம்போடியன் ரியெல்",
	"PYG_displayName": "பராகுயான் குவாரானி",
	"LKR_displayName": "இலங்கை ரூபாய்",
	"BGN_displayName": "புல்கேரியன் லெவ்",
	"BDT_displayName": "பங்கலாதேஷி டாகா",
	"MOP_displayName": "மெகனீஸ் படாகா",
	"HNL_displayName": "ஹோன்டூரன் லெம்பீரா",
	"RWF_displayName": "ருவாண்டா ஃப்ராங்க்",
	"CHF_displayName": "சுவிஸ் ஃப்ராங்க்",
	"CRC_displayName": "கோஸ்டா ரிகன் கொலோன்",
	"INR_displayName": "ரூபாய்",
	"ZAR_displayName": "தென் ஆப்ரிக்க ராண்ட்",
	"AUD_displayName": "ஆஸ்திரேலிய டாலர்",
	"LAK_displayName": "லவுட்டியன் கிப்",
	"MNT_displayName": "மங்கோலியன் டுக்ரிக்",
	"RSD_displayName": "செர்பியன் தினார்",
	"HRK_displayName": "குரோஷியன் குனா"
}
//end v1.x content
);