define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/de/AddEditDialog", {
    "dialogTitleAddField": "Feld zu ${0}-Entität hinzufügen",
    "dialogTitleAddFilter": "Filter zu ${0}-Entität hinzufügen",
    "dialogTitleAddMetric": "Kennzahl zu ${0}-Entität hinzufügen",
    "dialogTitleAddRelationship": "Beziehung zu ${0}-Entität hinzufügen",
    "editDialogTitle": "${0} in ${1}-Entität bearbeiten",
    "lblFilter": "Filter",
    "lblMetric": "Kennzahl",
    "lblFilters": "Filter",
    "lblMetrics": "Kennzahlen",
    "lblDistinct": "Eindeutig",
    "lblRange": "Bereich",
    "lblUserLookup": "Benutzersuche",
    "lblAdd": "Hinzufügen",
    "lblEdit": "Bearbeiten",
    "lblRemove": "Entfernen",
    "lblHelp": "Hilfe",
    "lblFilterName": "Filtername",
    "lblMetricName": "Kennzahlname",
    "lblDisplayName": "Anzeigename",
    "lblName": "Name",
    "lblDisplay": "Anzeigen",
    "lblCalculated": "Berechnet",
    "lblCalculation": "Berechnung",
    "lblDescription": "Beschreibung",
    "lblFieldsName": "Feldername",
    "lblCalculatedFieldsName": "Name berechneter Felder",
    "lblFilterDp": "Felder",
    "lblTypeDp": "Typ",
    "lblCharacter": "Zeichen",
    "lblFrom": "Von",
    "lblTo": "Bis",
    "lblOperators": "Operatoren",
    "lblAggregation": "Aggregationen",
    "lblTypeSpecificContentBox": "Typspezifischer Inhaltsbereich",
    "lblSaveButton": "OK",
    "lblCancelButton": "Abbrechen",
    "DateDiffCheckerValue": "Kennzahl \"Datumsdifferenz\"",
    "InvalidFilterName": "Ungültiger Filtername",
    "InvalidRangeName": "Ungültiger Bereichsname",
    "RequiredFilterName": "Filtername ist erforderlich",
    "RequiredRangeName": "Bereichsname ist erforderlich",
    "FieldMustBeANumber": "Im Feld \"Zeichen\" muss eine Ganzzahl eingegeben werden.",
    "SelectAnItem": "Wählen Sie ein Element aus.",
    "ItemRequired": "Element erforderlich",
    "ItemInvalid": "Element ungültig",
    "LowerMustBeLessThanUpper": "Unterer Wert muss kleiner sein als oberer Wert.",
    "defaultRangeRowValue": "Wert eingeben",
    "totalRecordCountLabel": "Datensätze gesamt: ${0}",
    "lblNew": "Neu",
    "lblExisting": "Vorhanden",
    "lblExistingCalc": "Vorhandenes berechnetes Feld",
    "validNameMsg": "Ein gültiger Eintrag beginnt mit einem Großbuchstaben und <br> kann alphanumerische Werte und Unterstriche enthalten.",
    "propertyName": "Name",
    "displayName": "Anzeigen",
    "dataTypeId": "Typ",
    "dataTypeData": "Typattribute",
    "length": "Länge",
    "scale": "Skalieren",
    "precision": "Genauigkeit",
    "isIncluded": "Enthalten",
    "isReadOnly": "Schreibgeschützt",
    "displayCategory": "Kategorie anzeigen",
    "sdata": "Sdata",
    "bulkAction": "Massenvorgang",
    "canBulkUpdate": "Massenaktualisierung möglich",
    "canImport": "Importieren",
    "canMatch": "Abgleichen",
    "generate": "Erstellen",
    "audited": "Überwacht",
    "notUniqueFor": "ist nicht eindeutig für",
    "notUnique": "ist nicht eindeutig",
    "nlsCode": "NLS-Code",
    "nlsName": "NLS-Name",
    "showTranslations": "Übersetzungen anzeigen",
    "hideTranslations": "Übersetzungen ausblenden",
    "standardIds": "Standard-IDs",
    "others": "Sonstige",
    "SelectField": "Wählen Sie ein Feld aus!",
    "SelectOneField": "Wählen Sie nur ein Feld aus!",
    "parent": "Übergeordnete Entität und Join-Feld",
    "child": "Untergeordnete Entität und Join-Feld",
    "cardinality": "Beziehung",
    "cascade": "Kaskadieren",
    "includeParent": "Eigenschaft von übergeordneter Beziehung in untergeordnete Entität einschließen",
    "includeChild": "Eigenschaft von untergeordneter Beziehung in übergeordnete Entität einschließen",
    "existingRelaton": "Die Beziehung ist bereits vorhanden!"
});