define(
"dojo/cldr/nls/bg/currency", //begin v1.x content
{
	"COP_displayName": "Колумбийско песо",
	"CZK_displayName": "Чешка крона",
	"TND_displayName": "Тунизийски динар",
	"EUR_symbol": "€",
	"CAD_symbol": "CAD",
	"JMD_displayName": "Ямайски долар",
	"PHP_displayName": "Филипинско песо",
	"ALL_displayName": "Албански лек",
	"USD_symbol": "щ.д.",
	"LBP_displayName": "Ливанска лира",
	"VND_displayName": "Виетнамски донг",
	"BGN_symbol": "лв.",
	"LYD_displayName": "Либийски динар",
	"RON_displayName": "Румънска лея",
	"MKD_displayName": "Македонски денар",
	"SEK_displayName": "Шведска крона",
	"CNY_displayName": "Китайски юан",
	"IDR_displayName": "Индонезийска рупия",
	"ILS_displayName": "Израелски нов шекел",
	"YER_displayName": "Йеменски риал",
	"TJS_displayName": "Таджикистански сомони",
	"TTD_displayName": "Долар на Тринидад и Тобаго",
	"CNY_symbol": "CNY",
	"TRY_displayName": "Турска лира",
	"EUR_displayName": "Евро",
	"AED_displayName": "Дирхам на Обединените арабски емирства",
	"KZT_displayName": "Казахстанско тенге",
	"BHD_displayName": "Бахрейнски динар",
	"RUB_displayName": "Руска рубла",
	"NZD_displayName": "Новозеландски долар",
	"IQD_displayName": "Иракски динар",
	"TMT_displayName": "Туркменски манат",
	"ZWL_displayName": "Зимбабвийски долар (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "Киргизстански сом",
	"KWD_displayName": "Кувейтски динар",
	"AFN_displayName": "Афганистански афган",
	"ARS_displayName": "Аржентинско песо",
	"MAD_displayName": "Марокански дирхам",
	"BAM_displayName": "Босненска конвертируема марка",
	"BOB_displayName": "Боливийско боливиано",
	"BND_displayName": "Брунейски долар",
	"SGD_displayName": "Сингапурски долар",
	"MVR_displayName": "Малдивска руфия",
	"MXN_displayName": "Мексиканско песо",
	"DZD_displayName": "Алжирски динар",
	"MXN_symbol": "MXN",
	"JOD_displayName": "Йордански динар",
	"PEN_displayName": "Перуански нов сол",
	"GTQ_displayName": "Гватемалски кетцал",
	"BYR_displayName": "Беларуска рубла",
	"CAD_displayName": "Канадски долар",
	"BZD_displayName": "Белизийски долар",
	"CLP_displayName": "Чилийско песо",
	"XOF_displayName": "Западноафрикански CFA франк",
	"NOK_displayName": "Норвежка крона",
	"DOP_displayName": "Доминиканско песо",
	"JPY_symbol": "JPY",
	"KRW_displayName": "Южнокорейски вон",
	"USD_displayName": "Щатски долар",
	"UYU_displayName": "Уругвайско песо",
	"UZS_displayName": "Узбекски сум",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Катарски риал",
	"SAR_displayName": "Саудитскоарабски риал",
	"SYP_displayName": "Сирийска лира",
	"NZD_symbol": "NZD",
	"EGP_displayName": "Египетска лира",
	"AMD_displayName": "Арменски драм",
	"GBP_displayName": "Британска лира",
	"HUF_displayName": "Унгарски форинт",
	"CSD_displayName": "Стар сръбски динар",
	"ISK_displayName": "Исландска крона",
	"IRR_displayName": "Ирански риал",
	"OMR_displayName": "Омански риал",
	"TWD_displayName": "Тайвански долар",
	"PAB_displayName": "Панамска балбоа",
	"UAH_displayName": "Украинска хривня",
	"ETB_displayName": "Етиопски бир",
	"RUB_symbol": "руб.",
	"PLN_displayName": "Полска злота",
	"VEF_displayName": "Венецуелски боливар",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "Бразилски реал",
	"HKD_symbol": "HKD",
	"HKD_displayName": "Хонконгски долар",
	"NIO_displayName": "Никарагуанска кордоба",
	"THB_symbol": "THB",
	"NPR_displayName": "Непалска рупия",
	"PKR_displayName": "Пакистанска рупия",
	"TWD_symbol": "TWD",
	"GEL_displayName": "Грузински лари",
	"AZN_displayName": "Азербайджански манат",
	"GBP_symbol": "GBP",
	"MYR_displayName": "Малайзийски рингит",
	"DKK_displayName": "Датска крона",
	"THB_displayName": "Тайландски бат",
	"BRL_symbol": "BRL",
	"JPY_displayName": "Японска йена",
	"KES_displayName": "Кенийски шилинг",
	"KHR_displayName": "Камбоджански риел",
	"PYG_displayName": "Парагвайско гуарани",
	"VND_symbol": "VND",
	"LKR_displayName": "Шриланкска рупия",
	"BGN_displayName": "Български лев",
	"BDT_displayName": "Бангладешка така",
	"HNL_displayName": "Хондураска лемпира",
	"MOP_displayName": "Патака на Макао",
	"RWF_displayName": "Руандски франк",
	"CHF_displayName": "Швейцарски франк",
	"CRC_displayName": "Костарикански колон",
	"INR_displayName": "Индийска рупия",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "Южноафрикански ранд",
	"AUD_displayName": "Австралийски долар",
	"LAK_displayName": "Лаоски кип",
	"MNT_displayName": "Монголски тугрик",
	"RSD_displayName": "Сръбски динар",
	"HRK_displayName": "Хърватска куна"
}
//end v1.x content
);