define("Sage/MainView/ActivityMgr/nls/it/ActivityEditor", {
    "labelWidth": "100",
    "tabNameGeneralText": "Generale",
    "tabNameAvailabilityText": "Disponibilità",
    "tabNameAssociationsText": "Associazioni",
    "tabNameRecurringText": "Ricorrente",
    "tabNameAttachmentsText": "Allegati",
    "tabNameNotesText": "Note",
    "scheduleText": "Pianifica",
    "startTimeText": "Ora di inizio",
    "timeLessText": "Senza limiti di tempo",
    "alarmText": "Allarme",
    "durationText": "Durata",
    "rolloverText": "Riporta automaticamente al giorno successivo",
    "contactText": "Contatto",
    "accountText": "Azienda",
    "leadText": "Lead",
    "opportunityText": "Opportunità",
    "ticketText": "Ticket",
    "companyText": "Società",
    "regardingText": "In relazione a",
    "notesText": "Note",
    "priorityText": "Priorità",
    "leaderText": "Coordinatore",
    "categoryText": "Categoria",
    "locationText": "Ubicazione",
    "dialogHeaderFormatText": "${actionText} ${activityType} - ${description}",
    "scheduledByFormatText": "Pianificato da ${user} il ${date}",
    "completeScheduledByFormatText": "Pianificato da ${user} il ${date} in origine per ${startDate}",
    "newConfirmationHeaderFormatText": "Conferma ${activityType} pianificato da ${user}",
    "otherConfimationHeaderFormatText": "${activityType} ${actionText} da ${user}",
    "acceptedText": "Accettato",
    "declinedText": "Rifiutato",
    "scheduledText": "Pianificato",
    "updatedText": "Aggiornato",
    "deletedText": "Eliminato",
    "cancelText": "Annulla",
    "okText": "OK",
    "completeText": "Completa",
    "completeBtnText": "Completa...",
    "completedText": "Completato",
    "deleteText": "Elimina",
    "lookupActText": "Ricerca azienda",
    "lookupContactText": "Ricerca contatto",
    "lookupOpportunityText": "Ricerca opportunità",
    "lookupTicketText": "Ricerca ticket",
    "lookupLeadText": "Ricerca lead",
    "lookupLeaderText": "Ricerca coordinatore",
    "lookupResourcesText": "Aggiungi membri e risorse",
    "addResourceText": "Aggiungi selezionato",
    "mainPhoneText": "Telefono principale",
    "typeText": "Tipo",
    "subTypeText": "Sottotipo",
    "nameText": "Nome",
    "cityText": "Città",
    "stateText": "Provincia",
    "workphoneText": "Telefono ufficio",
    "emailText": "E-mail",
    "acctMgrText": "Acct manager",
    "descriptionText": "Descrizione",
    "stageText": "Fase",
    "statusText": "Stato",
    "ownerText": "Proprietario",
    "ticketNumberText": "Numero ticket",
    "phoneText": "Telefono",
    "urgencyText": "Urgenza",
    "areaText": "Area",
    "recurringText": "Ricorrente",
    "resultText": "Risultato",
    "followupText": "Follow-up",
    "noneText": "Nessuno",
    "carryOverAttachmentsText": "Riporta allegati",
    "carryOverNotesText": "Riporta note",
    "asScheduledText": "Come pianificato",
    "nowText": "Adesso",
    "responseText": "Risposta",
    "acceptText": "Accetta",
    "declineText": "Rifiuta",
    "deleteConfText": "Elimina conferma",
    "closeText": "Chiudi",
    "leadFullNameText": "Nome",
    "postalText": "Codice postale",
    "failedLoadingDataMsg": "Errore durante il caricamento dei dati.",
    "removeText": "Rimuovi",
    "noText": "No",
    "yesText": "Sì",
    "areYouSureText": "Si sta per eliminare definitivamente questo record.",
    "couldNotSaveErrorText": "Non è stato possibile salvare l'attività perché si è verificato un errore.",
    "couldNotDeleteErrorText": "Non è stato possibile eliminare l'attività perché si è verificato un errore.",
    "couldNotCompleteErrorText": "Non è stato possibile salvare l'attività perché si è verificato un errore.",
    "scheduleFollowUpErrorText": "Impossibile determinare il valore HistoryId. Follow-up non pianificato.",
    "tabNameParticipants": "Partecipanti"
});