define("Sage/MainView/ActivityMgr/nls/it/EditEventEditor", {
    "titleScheduleText": "Pianifica evento",
    "titleEditText": "Modifica evento",
    "lblDayTypeText": "Tipo giorno:",
    "lblStartDateText": "Data di inizio:",
    "lblEndDateText": "Data di fine:",
    "lblUserText": "Utente:",
    "lookupUserText": "Ricerca utente",
    "lblCategoryText": "Categoria:",
    "lblLocationText": "Ubicazione:",
    "lblDescriptionText": "Descrizione:",
    "btnOkayText": "OK",
    "btnCancelText": "Annulla",
    "btnHelpText": "Guida",
    "eventTypeActiveText": "Attivo",
    "eventTypeBusinessTripText": "Trasferta",
    "eventTypeConferenceText": "Conferenza",
    "eventTypeHolidayText": "Vacanza",
    "eventTypeOffText": "Non attivo",
    "eventTypeTradeShowText": "Fiera",
    "eventTypeUnavailableText": "Non disponibile",
    "eventTypeVacationText": "Ferie",
    "errorText": "L'evento non può essere creato perché si è verificato un errore.",
    "invaildDatesText": "La data di fine non può essere precedente alla data di inizio.",
    "nameText": "Nome"
});