define("Sage/MainView/ActivityMgr/nls/it/HistoryEditor", {
    "labelWidth": "100",
    "tabNameGeneralText": "Generale",
    "tabNameAttachmentsText": "Allegati",
    "scheduleText": "Pianifica",
    "startTimeText": "Pianificato",
    "completedDateText": "Completato",
    "timeLessText": "Senza limiti di tempo",
    "durationText": "Durata",
    "contactText": "Contatto",
    "accountText": "Azienda",
    "leadText": "Lead",
    "opportunityText": "Opportunità",
    "ticketText": "Ticket",
    "companyText": "Società",
    "regardingText": "In relazione a",
    "resultText": "Risultato",
    "notesText": "Note",
    "priorityText": "Priorità",
    "leaderText": "Coordinatore",
    "categoryText": "Categoria",
    "locationText": "Ubicazione",
    "scheduledByFormatText": "Pianificato da ${user} il ${date}",
    "cancelText": "Annulla",
    "okText": "OK",
    "deleteText": "Elimina",
    "lookupActText": "Ricerca azienda",
    "lookupContactText": "Ricerca contatto",
    "lookupOpportunityText": "Ricerca opportunità",
    "lookupTicketText": "Ricerca ticket",
    "lookupLeadText": "Ricerca lead",
    "lookupLeaderText": "Ricerca coordinatore",
    "lookupResourcesText": "Ricerca",
    "mainPhoneText": "Telefono principale",
    "typeText": "Tipo",
    "subTypeText": "Sottotipo",
    "nameText": "Nome",
    "cityText": "Città",
    "stateText": "Provincia",
    "workphoneText": "Telefono ufficio",
    "emailText": "E-mail",
    "acctMgrText": "Acct manager",
    "descriptionText": "Descrizione",
    "stageText": "Fase",
    "statusText": "Stato",
    "ownerText": "Proprietario",
    "ticketNumberText": "Numero ticket",
    "phoneText": "Telefono",
    "urgencyText": "Urgenza",
    "areaText": "Area",
    "recurringText": "Ricorrente",
    "followupText": "Follow-up",
    "noneText": "Nessuno",
    "carryOverAttachmentsText": "Riporta allegati",
    "carryOverNotesText": "Riporta note",
    "asScheduledText": "Come pianificato",
    "insertText": "Inserisci",
    "couldNotSaveErrorText": "Non è stato possibile salvare la cronologia perché si è verificato un errore.",
    "deleteMessage": "Si sta per eliminare definitivamente questo record.",
    "deleteTitle": "Elimina cronologia",
    "couldNotDeleteErrorText": "Non è stato possibile eliminare la cronologia perché si è verificato un errore.",
    "postalText": "Codice postale",
    "tabNameParticipants": "Tutti i partecipanti"
});