define("Sage/UI/nls/zh-cn/BulkUpdateWidget", {
    "dlgBulkActionUpdate_Title": "批量操作更新",
    "pageLoading_Caption": "正在加载属性选项...",
    "header_Caption": "选择要更新的属性。",
    "header_NoPropertiesEnabled": "已针对批量更新启用 ${0} 实体，但未启用任何属性。请联系您的系统管理员了解更多信息",
    "errorRequestPropertyOptions": "读取 ${0} 实体的元数据时出现错误: ${1}",
    "errorEntityNotSupported": "${0} 实体不支持批量更新",
    "update_Property_Caption": "更新:",
    "addProperty_Tooltip": "添加属性",
    "removeProperty_Tooltip": "移除属性",
    "no_Caption": "否",
    "yes_Caption": "是",
    "days_Caption": "天",
    "moveOut_Caption": "移动",
    "moveTo_Caption": "至",
    "moveDate_Backward": "后退",
    "moveDate_Forward": "前进",
    "update_To_Caption": "至:",
    "lookupHeaderText": "查找 ${0}",
    "lookupNameColText": "名称",
    "lookupTitleColText": "标题",
    "lookupDepartmentColText": "部门",
    "lookupRegionColText": "区域",
    "lookupTypeColText": "类型",
    "lookupDescriptionColText": "描述",
    "btnOK_Caption": "确定",
    "btnCancel_Caption": "取消",
    "errorUnspecifiedValue": "请先指定一个值，然后继续，或删除无效的行。",
    "errorRequestingJobMgr": "执行更新时出现错误: ${0}",
    "selectOption_Caption": "选择选项...",
    "updateRecords_Caption": "正在更新所选记录",
    "chkScheduleJob_Caption": "安排该更新在特定日期/时间执行。",
    "lookup_Caption": "查找",
    "job_Description": "出现批量更新错误",
    "errorDuplicateValue": "已选定属性",
    "errorInvalidPropertyType": "批量更新不支持属性类型“${0}”。",
    "calculatedField": "已计算字段",
    "standardId": "标准 ID",
    "unknownPropertyType": "未知"
});