define("Sage/UI/nls/zh-cn/NotesHistoryList", {
    "typeText": "类型",
    "showDbChangesText": "显示数据库变更",
    "selectAllText": "全选",
    "dateText": "日期",
    "dateTimeText": "日期/时间",
    "dateRangeText": "日期范围",
    "userText": "用户",
    "accountText": "客户",
    "contactText": "联系人",
    "opportunityText": "销售机会",
    "regardingText": "相关事项",
    "notesText": "备注",
    "resultText": "结果",
    "categoryText": "类别",
    "sendEmailText": "通过电子邮件发送",
    "sendToWordText": "发送到 Word",
    "addNoteText": "添加备注",
    "completeAnActivityText": "完成活动",
    "helpText": "帮助",
    "pleaseSelectRecordsText": "请选择一条或多条记录",
    "UnableToFindWordMsg": "无法启动 Microsoft Word。请检查安全设置。",
    "printedOnText": "打印时间",
    "errorNoData": "没有可共享到 Ming.le 的任何“备注/历史”。",
    "yesButtonText": "是",
    "noButtonText": "否",
    "salesLogixPageTitle": "Infor CRM",
    "noRecordsSelectedProcessAll": "您尚未选择任何记录。所有“备注/历史” ${0} 个记录将共享至 Ming.le。要继续吗?",
    "errorShareMingle": "共享一个或多个“备注/历史”记录到 Ming.le 时出现错误。",
    "sharedToMingle": "“备注/历史”已共享至 Ming.le。",
    "sharingToMingle": "正共享到 Ming.le",
    "shared": "已共享",
    "pleaseWait": "请稍候...",
    "failedToPost": "发布失败: ${0}；错误: ${1}",
    "addressText": "地址",
    "mainPhoneText": "主要电话",
    "tollFreeText": "免费电话",
    "contactPhoneText": "联系人电话"
});