define(
"dojo/cldr/nls/ko/currency", //begin v1.x content
{
	"COP_displayName": "콜롬비아 페소",
	"CZK_displayName": "체코 공화국 코루나",
	"TND_displayName": "튀니지 디나르",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "자메이카 달러",
	"PHP_displayName": "필리핀 페소",
	"ALL_displayName": "알바니아 레크",
	"USD_symbol": "US$",
	"LBP_displayName": "레바논 파운드",
	"VND_displayName": "베트남 동",
	"LYD_displayName": "리비아 디나르",
	"RON_displayName": "루마니아 레우",
	"MKD_displayName": "마케도니아 디나르",
	"SEK_displayName": "스웨덴 크로나",
	"CNY_displayName": "중국 위안화",
	"IDR_displayName": "인도네시아 루피아",
	"ILS_displayName": "이스라엘 신권 세켈",
	"YER_displayName": "예멘 리알",
	"TJS_displayName": "타지키스탄 소모니",
	"TTD_displayName": "트리니다드 토바고 달러",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "신 터키 리라",
	"EUR_displayName": "유로화",
	"AED_displayName": "아랍에미리트 디르함",
	"KZT_displayName": "카자흐스탄 텐게",
	"BHD_displayName": "바레인 디나르",
	"RUB_displayName": "러시아 루블",
	"NZD_displayName": "뉴질랜드 달러",
	"IQD_displayName": "이라크 디나르",
	"TMT_displayName": "투르크메니스탄 마나트",
	"ZWL_displayName": "짐바브웨 달러 (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "키르기스스탄 솜",
	"KWD_displayName": "쿠웨이트 디나르",
	"AFN_displayName": "아프가니스탄 아프가니",
	"ARS_displayName": "아르헨티나 페소",
	"MAD_displayName": "모로코 디렘",
	"BAM_displayName": "보스니아-헤르체고비나 태환 마르크",
	"BOB_displayName": "볼리비아노",
	"BND_displayName": "부루나이 달러",
	"SGD_displayName": "싱가폴 달러",
	"MVR_displayName": "몰디브 제도 루피아",
	"MXN_displayName": "멕시코 페소",
	"DZD_displayName": "알제리 디나르",
	"MXN_symbol": "MX$",
	"JOD_displayName": "요르단 디나르",
	"PEN_displayName": "페루 누에보 솔",
	"GTQ_displayName": "과테말라 케트살",
	"BYR_displayName": "벨라루스 루블",
	"CAD_displayName": "캐나다 달러",
	"BZD_displayName": "벨리즈 달러",
	"CLP_displayName": "칠레 페소",
	"XOF_displayName": "CFA 프랑 BCEAO",
	"NOK_displayName": "노르웨이 크로네",
	"DOP_displayName": "도미니카 페소",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "대한민국 원",
	"USD_displayName": "미국 달러",
	"UYU_displayName": "우루과이 페소 우루과요",
	"UZS_displayName": "우즈베키스탄 숨",
	"XOF_symbol": "CFA",
	"QAR_displayName": "카타르 리얄",
	"SAR_displayName": "사우디아라비아 리얄",
	"SYP_displayName": "시리아 파운드",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "이집트 파운드",
	"AMD_displayName": "아르메니아 드람",
	"GBP_displayName": "영국령 파운드 스털링",
	"HUF_displayName": "헝가리 포린트",
	"CSD_displayName": "고 세르비아 디나르",
	"ISK_displayName": "아이슬란드 크로나",
	"IRR_displayName": "이란 리얄",
	"OMR_displayName": "오만 리얄",
	"TWD_displayName": "신 타이완 달러",
	"PAB_displayName": "파나마 발보아",
	"UAH_displayName": "우크라이나 그리브나",
	"ETB_displayName": "이디오피아 비르",
	"PLN_displayName": "폴란드 즐로티",
	"VEF_displayName": "베네주엘라 볼리바르",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "브라질 레알",
	"HKD_symbol": "HK$",
	"HKD_displayName": "홍콩 달러",
	"NIO_displayName": "니카라과 코르도바 오로",
	"THB_symbol": "฿",
	"NPR_displayName": "네팔 루피",
	"PKR_displayName": "파키스탄 루피",
	"TWD_symbol": "NT$",
	"GEL_displayName": "조지아 라리",
	"AZN_displayName": "아제르바이잔 마나트",
	"GBP_symbol": "£",
	"MYR_displayName": "말레이시아 링깃",
	"DKK_displayName": "덴마크 크로네",
	"THB_displayName": "태국 바트",
	"BRL_symbol": "R$",
	"JPY_displayName": "일본 엔화",
	"KES_displayName": "케냐 실링",
	"KHR_displayName": "캄보디아 리얄",
	"PYG_displayName": "파라과이 과라니",
	"VND_symbol": "₫",
	"LKR_displayName": "스리랑카 루피",
	"BGN_displayName": "불가리아 레프",
	"BDT_displayName": "방글라데시 타카",
	"MOP_displayName": "마카오 파타카",
	"HNL_displayName": "온두라스 렘피라",
	"RWF_displayName": "르완다 프랑",
	"CHF_displayName": "스위스 프랑",
	"CRC_displayName": "코스타리카 콜론",
	"INR_displayName": "인도 루피",
	"KRW_symbol": "₩",
	"ZAR_displayName": "남아프리카 랜드",
	"AUD_displayName": "호주 달러",
	"LAK_displayName": "라오스 키프",
	"MNT_displayName": "몽골 투그릭",
	"RSD_displayName": "세르비아 디나르",
	"HRK_displayName": "크로아티아 쿠나"
}
//end v1.x content
);