define("Sage/UI/nls/en/AddressFormatConditionManager", {
	addimgalttext: 'Add Condition',
	hideimgalttext: 'Remove Condition',
	errorOperatorRequiresValue: 'The operator requires a value',
	Address: 'ADDRESS',
	City: 'CITY',
	State: 'STATE',
	County: 'COUNTY',
	PostalCode: 'POSTAL CODE',
	Text: 'TEXT',
	Space: 'space',
	NewLine: 'New Line',
	Comma: 'Comma',
	Hyphen: 'Hyphen',
	Slash: 'Slash',
	cancelBtnCaption: 'CANCEL',
	srchBtnCaption:'OK',
	Empty: 'EMPTY',
	Nothing: 'Nothing'
});