define(
"dojo/cldr/nls/ky/currency", //begin v1.x content
{
	"COP_displayName": "Колумбия песосу",
	"CZK_displayName": "Чехия корунасы",
	"TND_displayName": "Тунис динары",
	"CAD_symbol": "CAD",
	"JMD_displayName": "Жамайка доллары",
	"PHP_displayName": "Филиппин песосу",
	"ALL_displayName": "Албания леги",
	"USD_symbol": "USD",
	"LBP_displayName": "Ливан фунту",
	"VND_displayName": "Вьетнам доӊу",
	"LYD_displayName": "Ливия динары",
	"RON_displayName": "Румыния лейи",
	"MKD_displayName": "Македония денары",
	"SEK_displayName": "Швеция крону",
	"CNY_displayName": "Кытай юаны",
	"IDR_displayName": "Индонезия рупийасы",
	"ILS_displayName": "Израил жаӊы шегели",
	"YER_displayName": "Йемен риалы",
	"TJS_displayName": "Тажикстан сомониси",
	"TTD_displayName": "Тринидад жана Тобаго доллары",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Түркия лирасы",
	"EUR_displayName": "Евро",
	"AED_displayName": "Бириккен Араб Эмираттары дирхамы",
	"KZT_displayName": "Казакстан теӊгеси",
	"BHD_displayName": "Бахрейн динары",
	"RUB_displayName": "Орусия рублу",
	"NZD_displayName": "Жаӊы Зеландия доллары",
	"IQD_displayName": "Ирак динары",
	"TMT_displayName": "Түркмөнстан манаты",
	"INR_symbol": "INR",
	"KGS_displayName": "Кыргызстан сому",
	"KWD_displayName": "Кувейт динары",
	"AFN_displayName": "Афганстан афганиси",
	"ARS_displayName": "Аргентина песосу",
	"MAD_displayName": "Марокко дирхамы",
	"BAM_displayName": "Босния-Герцеговина оодарылма маркы",
	"BOB_displayName": "Боливия боливианосу",
	"BND_displayName": "Бруней доллары",
	"SGD_displayName": "Сингапур доллары",
	"MVR_displayName": "Малдив Руфийасы",
	"MXN_displayName": "Мексика песосу",
	"DZD_displayName": "Алжир динары",
	"MXN_symbol": "MXN",
	"JOD_displayName": "Йордания динары",
	"PEN_displayName": "Перу нуэво солу",
	"GTQ_displayName": "Гватемала кетсалы",
	"BYR_displayName": "Беларусь рублу",
	"CAD_displayName": "Канада доллары",
	"BZD_displayName": "Белиз доллары",
	"CLP_displayName": "Чили песосу",
	"XOF_displayName": "Батыш Африка CFA франкы",
	"NOK_displayName": "Норвегия крону",
	"DOP_displayName": "Доминика песосу",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Түштүк Корея уону",
	"USD_displayName": "АКШ доллары",
	"UYU_displayName": "Уругвай песосу",
	"UZS_displayName": "Өзбекстан сому",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Катар риалы",
	"SAR_displayName": "Сауд риалы",
	"SYP_displayName": "Сирия фунту",
	"NZD_symbol": "NZD",
	"EGP_displayName": "Мисир фунту",
	"AMD_displayName": "Армения драмы",
	"GBP_displayName": "Британия фунт стерлинги",
	"HUF_displayName": "Венгрия форинти",
	"ISK_displayName": "Исландия крону",
	"IRR_displayName": "Иран риалы",
	"OMR_displayName": "Оман риалы",
	"TWD_displayName": "Тайвань жаӊы доллары",
	"PAB_displayName": "Панама балбоасы",
	"UAH_displayName": "Украина гривени",
	"ETB_displayName": "Эфиопия бирри",
	"PLN_displayName": "Польша злотыйы",
	"VEF_displayName": "Венесуэла боливары",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "Бразилия реалы",
	"HKD_symbol": "HKD",
	"HKD_displayName": "Гоӊ Коӊ доллары",
	"NIO_displayName": "Никарагуа кордобасы",
	"THB_symbol": "฿",
	"NPR_displayName": "Непал руписи",
	"PKR_displayName": "Пакистан руписи",
	"TWD_symbol": "TWD",
	"GEL_displayName": "Грузия лариси",
	"AZN_displayName": "Азербайжан манаты",
	"GBP_symbol": "GBP",
	"MYR_displayName": "Малайзия ринггити",
	"DKK_displayName": "Дания крону",
	"THB_displayName": "Тай баты",
	"BRL_symbol": "BRL",
	"JPY_displayName": "Жапан йени",
	"KES_displayName": "Кения шиллинги",
	"KHR_displayName": "Камбожа риели",
	"PYG_displayName": "Парагвай гуараниси",
	"VND_symbol": "₫",
	"LKR_displayName": "Шри Ланка руписи",
	"BGN_displayName": "Болгария леви",
	"BDT_displayName": "Бангладеш такасы",
	"MOP_displayName": "Макау патакасы",
	"HNL_displayName": "Гондурас лемпирасы",
	"RWF_displayName": "Руанда франкы",
	"CHF_displayName": "Швейцария франкы",
	"CRC_displayName": "Коста Рика колону",
	"INR_displayName": "Индия руписи",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "Түштүк Африка ранды",
	"KGS_symbol": "сом",
	"AUD_displayName": "Австралия доллары",
	"LAK_displayName": "Лаос киби",
	"MNT_displayName": "Монгол тугриги",
	"RSD_displayName": "Сербия динары",
	"HRK_displayName": "Хорватия кунасы"
}
//end v1.x content
);