define("Sage/UI/Alarms/nls/fr/AlarmPane", {
    "dismissAllText": "Tout annuler",
    "dismissText": "Annuler",
    "fiveMinText": "5 minutes",
    "tenMinText": "10 minutes",
    "fifteenMinText": "15 minutes",
    "thirtyMinText": "30 minutes",
    "oneHourText": "1 heure",
    "twoHourText": "2 heures",
    "fourHourText": "4 heures",
    "eightHourText": "8 heures",
    "oneDayText": "1 jour",
    "twoDayText": "2 jours",
    "threeDayText": "3 jours",
    "oneWeekText": "1 semaine",
    "twoWeekText": "2 semaines",
    "snoozeText": "Mettre en veille",
    "snoozeByText": "Mettre en veille pour :",
    "snoozeAllText": "Mettre tout en veille",
    "showCalendarText": "Afficher l'agenda"
});