define(
"dojo/cldr/nls/cs/currency", //begin v1.x content
{
	"COP_displayName": "kolumbijské peso",
	"CZK_displayName": "česká koruna",
	"TND_displayName": "tuniský dinár",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "jamajský dolar",
	"PHP_displayName": "filipínské peso",
	"ALL_displayName": "albánský lek",
	"USD_symbol": "US$",
	"LBP_displayName": "libanonská libra",
	"VND_displayName": "vietnamský dong",
	"LYD_displayName": "libyjský dinár",
	"RON_displayName": "rumunské leu",
	"MKD_displayName": "makedonský denár",
	"SEK_displayName": "švédská koruna",
	"CNY_displayName": "čínský jüan",
	"IDR_displayName": "indonéská rupie",
	"ILS_displayName": "izraelský nový šekel",
	"YER_displayName": "jemenský rijál",
	"TJS_displayName": "tádžické somoni",
	"TTD_displayName": "trinidadský dolar",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "turecká lira",
	"EUR_displayName": "euro",
	"AED_displayName": "SAE dirham",
	"KZT_displayName": "kazašské tenge",
	"BHD_displayName": "bahrajnský dinár",
	"RUB_displayName": "ruský rubl",
	"NZD_displayName": "novozélandský dolar",
	"IQD_displayName": "irácký dinár",
	"TMT_displayName": "turkmenský manat",
	"ZWL_displayName": "zimbabwský dolar (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "kyrgyzský som",
	"KWD_displayName": "kuvajtský dinár",
	"AFN_displayName": "afghánský afghán",
	"ARS_displayName": "argentinské peso",
	"MAD_displayName": "marocký dinár",
	"BAM_displayName": "bosenská konvertibilní marka",
	"BOB_displayName": "bolivijský boliviano",
	"BND_displayName": "brunejský dolar",
	"SGD_displayName": "singapurský dolar",
	"MVR_displayName": "maledivská rupie",
	"MXN_displayName": "mexické peso",
	"DZD_displayName": "alžírský dinár",
	"MXN_symbol": "MX$",
	"JOD_displayName": "jordánský dinár",
	"PEN_displayName": "peruánský nový sol",
	"GTQ_displayName": "guatemalský quetzal",
	"BYR_displayName": "běloruský rubl",
	"CAD_displayName": "kanadský dolar",
	"BZD_displayName": "belizský dolar",
	"CLP_displayName": "chilské peso",
	"XOF_displayName": "CFA/BCEAO frank",
	"NOK_displayName": "norská koruna",
	"DOP_displayName": "dominikánské peso",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "jihokorejský won",
	"USD_displayName": "americký dolar",
	"UYU_displayName": "uruguayské peso",
	"UZS_displayName": "uzbecký sum",
	"XOF_symbol": "CFA",
	"QAR_displayName": "katarský rijál",
	"SAR_displayName": "saúdský rijál",
	"SYP_displayName": "syrská libra",
	"NZD_symbol": "NZ$",
	"EGP_displayName": "egyptská libra",
	"AMD_displayName": "arménský dram",
	"GBP_displayName": "britská libra",
	"HUF_displayName": "maďarský forint",
	"ISK_displayName": "islandská koruna",
	"IRR_displayName": "íránský rijál",
	"OMR_displayName": "ománský rijál",
	"TWD_displayName": "tchajwanský dolar",
	"PAB_displayName": "panamská balboa",
	"UAH_displayName": "ukrajinská hřivna",
	"ETB_displayName": "etiopský birr",
	"PLN_displayName": "polský zlotý",
	"VEF_displayName": "venezuelský bolívar",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "brazilský real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "hongkongský dolar",
	"NIO_displayName": "nikaragujská córdoba",
	"THB_symbol": "THB",
	"NPR_displayName": "nepálská rupie",
	"PKR_displayName": "pákistánská rupie",
	"TWD_symbol": "NT$",
	"GEL_displayName": "gruzínské lari",
	"AZN_displayName": "ázerbájdžánský manat",
	"GBP_symbol": "£",
	"MYR_displayName": "malajsijský ringgit",
	"DKK_displayName": "dánská koruna",
	"THB_displayName": "thajský baht",
	"BRL_symbol": "R$",
	"JPY_displayName": "japonský jen",
	"KES_displayName": "keňský šilink",
	"KHR_displayName": "kambodžský riel",
	"PYG_displayName": "paraguajské guarani",
	"VND_symbol": "VND",
	"LKR_displayName": "srílanská rupie",
	"BGN_displayName": "bulharský lev",
	"BDT_displayName": "bangladéšská taka",
	"MOP_displayName": "macajská pataca",
	"HNL_displayName": "honduraská lempira",
	"RWF_displayName": "rwandský frank",
	"CHF_displayName": "švýcarský frank",
	"CRC_displayName": "kostarický colón",
	"INR_displayName": "indická rupie",
	"KRW_symbol": "₩",
	"ZAR_displayName": "jihoafrický rand",
	"AUD_displayName": "australský dolar",
	"LAK_displayName": "laoský kip",
	"CZK_symbol": "Kč",
	"MNT_displayName": "mongolský tugrik",
	"RSD_displayName": "srbský dinár",
	"HRK_displayName": "chorvatská kuna"
}
//end v1.x content
);