define("Sage/UI/Controls/nls/fr/FieldAttributeControlFactory", {
    "IsEncrypted": "Est crypté",
    "Length": "Longueur",
    "Precision": "Précision",
    "Scale": "Echelle",
    "LookupEntityName": "Rechercher le nom de l’entité",
    "LookupGroup": "Rechercher le groupe",
    "IsPercentage": "Est un pourcentage",
    "Items": "Eléments",
    "MultiSelect": "Sélection multiple",
    "OverriddenName": "Nom remplacé",
    "Storage": "Stockage",
    "EnableHyperLinking": "Activer l'hyperlien",
    "LookupPreFilters": "Rechercher dans les pré-filtres",
    "EqualTo": "Egal à",
    "NotEqualTo": "Non égal à",
    "GreaterThanOrEqual": "Supérieur ou égal à",
    "GreaterThan": "Supérieur à",
    "LessThanOrEqual": "Inférieur ou égal à",
    "LessThan": "Inférieur à",
    "CondOperator": "Opérateur de condition",
    "FilterValue": "Valeur du filtre",
    "PropertyName": "Nom de propriété",
    "LookupProperties": "Propriétés de recherche",
    "ExcludeFromFilters": "Exclure des filtres",
    "HideCondition": "Masquer la condition",
    "IsSortable": "Peut être trié",
    "PropertyFormat": "Format de propriété",
    "None": "Aucun(e)",
    "Phone": "Téléphone",
    "User": "Utilisateur",
    "PickList": "Liste de sélection",
    "DateTime": "Date Heure",
    "PropertyFormatString": "Chaîne du format de propriété",
    "PropertyHeader": "En-tête de propriété",
    "PropertyType": "Type de propriété",
    "UseAsResult": "Utiliser comme résultat",
    "ReturnPrimaryKey": "Clé principale retournée",
    "AllowMultiples": "Autoriser les sélections multiples",
    "AlphaSort": "Trier par ordre alphabétique",
    "MustExistInList": "Doit exister dans la liste",
    "NoneEditable": "Aucun élément n'est modifiable",
    "PickListFilter": "Filtre de la liste de sélection",
    "ValueStoredAsText": "Valeur stockée comme texte",
    "Value": "Valeur",
    "Display": "Affichage",
    "Code": "Code",
    "Name": "Nom",
    "DisplayName": "Nom d'affichage",
    "Template": "Calcul",
    "Description": "Description",
    "SortOrder": "Ordre de tri",
    "lblNoFieldsInTemplate": "Veuillez ajouter une propriété d'entité au modèle avant d'appliquer un ordre de tri.",
    "AddField": "Ajouter un champ",
    "InUse": "En cours d'utilisation",
    "NotInUse": "Non utilisé",
    "CalculatedNumberInputError": "<p>Les entrées sont limitées aux noms de champs sélectionnés dans la liste déroulante<br/> et aux caractères suivants :<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', ni ')'<br/>&nbsp;&nbsp;&nbsp;&nbsp;qui correspondent aux valeurs de bouton au-dessus de la zone de texte.</p>",
    "newPickList": "Nouvelle liste de sélection",
    "add": "ajouter",
    "substract": "soustraire",
    "multiply": "multiplier",
    "divide": "diviser",
    "openParens": "Ouvrir la parenthèse",
    "closeParens": "fermer la parenthèse"
});