define(
"dojo/cldr/nls/da/currency", //begin v1.x content
{
	"COP_displayName": "Colombiansk peso",
	"CZK_displayName": "Tjekkisk koruna",
	"TND_displayName": "Tunesisk dinar",
	"EUR_symbol": "€",
	"CAD_symbol": "CA$",
	"JMD_displayName": "Jamaicansk dollar",
	"PHP_displayName": "Filippinsk peso",
	"ALL_displayName": "Albansk lek",
	"USD_symbol": "$",
	"LBP_displayName": "Libanesisk pund",
	"VND_displayName": "Vietnamesisk dong",
	"LYD_displayName": "Libysk dinar",
	"RON_displayName": "Rumænsk leu",
	"MKD_displayName": "Makedonsk denar",
	"SEK_displayName": "Svensk krone",
	"CNY_displayName": "Kinesisk yuan renminbi",
	"IDR_displayName": "Indonesisk pupiah",
	"ILS_displayName": "Ny israelsk shekel",
	"YER_displayName": "Yemenitisk rial",
	"TJS_displayName": "Tadsjikisk somoni",
	"TTD_displayName": "Dollar fra Trinidad og Tobago",
	"CNY_symbol": "CN¥",
	"TRY_displayName": "Tyrkisk lira",
	"EUR_displayName": "Euro",
	"AED_displayName": "Dirham fra de Forenede Arabiske Emirater",
	"KZT_displayName": "Kasakhisk tenge",
	"BHD_displayName": "Bahrainsk dinar",
	"RUB_displayName": "Russisk rubel",
	"NZD_displayName": "New Zealandsk dollar",
	"IQD_displayName": "Irakisk dinar",
	"TMT_displayName": "Turkmensk manat",
	"ZWL_displayName": "Zimbabwisk dollar (2009)",
	"INR_symbol": "₹",
	"KGS_displayName": "Kirgisisk som",
	"KWD_displayName": "Kuwaitisk dinar",
	"AFN_displayName": "Afghansk afghani",
	"ARS_displayName": "Argentinsk peso",
	"MAD_displayName": "Marokkansk dirham",
	"BAM_displayName": "Bosnien-Hercegovinsk konvertibel mark",
	"BOB_displayName": "Boliviansk boliviano",
	"BND_displayName": "Bruneisk dollar",
	"SGD_displayName": "Singaporeansk dollar",
	"MVR_displayName": "Maldivisk rufiyaa",
	"MXN_displayName": "Mexicansk peso",
	"DZD_displayName": "Algerisk dinar",
	"MXN_symbol": "MX$",
	"JOD_displayName": "Jordansk dinar",
	"PEN_displayName": "Peruviansk nuevo sol",
	"GTQ_displayName": "Guatemalansk quetzal",
	"BYR_displayName": "Hviderussisk rubel",
	"CAD_displayName": "Canadisk dollar",
	"BZD_displayName": "Belizisk dollar",
	"CLP_displayName": "Chilensk peso",
	"XOF_displayName": "CFA-franc BCEAO",
	"NOK_displayName": "Norsk krone",
	"DOP_displayName": "Dominikansk peso",
	"JPY_symbol": "JP¥",
	"KRW_displayName": "Sydkoreansk won",
	"USD_displayName": "Amerikansk dollar",
	"UYU_displayName": "Uruguayansk peso",
	"UZS_displayName": "Usbekisk sum",
	"XOF_symbol": "CFA",
	"QAR_displayName": "Qatarsk rial",
	"SAR_displayName": "Saudiarabisk riyal",
	"SYP_displayName": "Syrisk pund",
	"NZD_symbol": "NZ$",
	"DKK_symbol": "kr",
	"EGP_displayName": "Egyptisk pund",
	"AMD_displayName": "Armensk dram",
	"GBP_displayName": "Britisk pund",
	"HUF_displayName": "Ungarsk forint",
	"CSD_displayName": "Serbisk dinar (2002–2006)",
	"ISK_displayName": "Islansk krone",
	"IRR_displayName": "Iransk rial",
	"OMR_displayName": "Omansk rial",
	"TWD_displayName": "Ny taiwansk dollar",
	"PAB_displayName": "Panamansk balboa",
	"UAH_displayName": "Ukrainsk grynia",
	"ETB_displayName": "Etiopisk birr",
	"PLN_displayName": "Polsk zloty",
	"VEF_displayName": "Venezuelansk bolivar",
	"ILS_symbol": "₪",
	"AUD_symbol": "AU$",
	"BRL_displayName": "Brasiliansk real",
	"HKD_symbol": "HK$",
	"HKD_displayName": "Hongkong dollar",
	"NIO_displayName": "Nicaraguansk cordoba",
	"THB_symbol": "฿",
	"NPR_displayName": "Nepalesisk rupee",
	"PKR_displayName": "Pakistansk rupee",
	"TWD_symbol": "NT$",
	"GEL_displayName": "Georgisk lari",
	"AZN_displayName": "Aserbajdsjansk manat",
	"GBP_symbol": "£",
	"MYR_displayName": "Malaysisk ringgit",
	"DKK_displayName": "Dansk krone",
	"THB_displayName": "Thailandsk baht",
	"BRL_symbol": "R$",
	"JPY_displayName": "Japansk yen",
	"KES_displayName": "Kenyansk shilling",
	"KHR_displayName": "Cambodjansk riel",
	"PYG_displayName": "Paraguaysk guarani",
	"VND_symbol": "₫",
	"LKR_displayName": "Srilankansk rupee",
	"BGN_displayName": "Bulgarsk lev",
	"BDT_displayName": "Bangladeshisk taka",
	"HNL_displayName": "Honduransk lempira",
	"MOP_displayName": "Macaosk pataca",
	"RWF_displayName": "Rwandisk franc",
	"CHF_displayName": "Schweizisk franc",
	"CRC_displayName": "Costaricansk colón",
	"INR_displayName": "Indisk rupee",
	"KRW_symbol": "₩",
	"ZAR_displayName": "Sydafrikansk rand",
	"AUD_displayName": "Australsk dollar",
	"LAK_displayName": "Laotisk kip",
	"MNT_displayName": "Mongolsk tugrik",
	"RSD_displayName": "Serbisk dinar",
	"HRK_displayName": "Kroatisk kuna"
}
//end v1.x content
);