define("Sage/UI/Controls/nls/fr/PropertyStore", {
    "text": "Texte",
    "memo": "Mémo",
    "unicodeText": "Texte Unicode",
    "unicodeMemo": "Mémo Unicode",
    "integer": "Entier",
    "double": "Double",
    "single": "Unique",
    "decimal": "Décimal",
    "short": "Court",
    "standardId": "ID standard",
    "trueFalse": "Vrai / Faux",
    "yesNo": "Oui/Non",
    "boolean": "Booléen",
    "dateTime": "Date/Heure",
    "email": "E-mail",
    "phone": "Téléphone",
    "pickList": "Liste de sélection",
    "owner": "Propriétaire",
    "lookup": "Recherche",
    "dependencyLookup": "Recherche de dépendance",
    "char": "Caractère",
    "enum_": "Enum",
    "guid": "Guid",
    "byte": "Octet",
    "binary": "Binaire",
    "url": "URL",
    "string": "Chaîne",
    "number": "Nombre",
    "calc": "Champ calculé",
    "calcSF": "Chaîne calculée",
    "calcNF": "Nombre calculé"
});