define("Sage/UI/Alarms/nls/zh-tw/AlarmPane", {
    "dismissAllText": "全部關閉",
    "dismissText": "關閉",
    "fiveMinText": "5 分鐘",
    "tenMinText": "10 分鐘",
    "fifteenMinText": "15 分鐘",
    "thirtyMinText": "30 分鐘",
    "oneHourText": "1 小時",
    "twoHourText": "2 小時",
    "fourHourText": "4 小時",
    "eightHourText": "8 小時",
    "oneDayText": "1 天",
    "twoDayText": "2 天",
    "threeDayText": "3 天",
    "oneWeekText": "1 週",
    "twoWeekText": "2 週",
    "snoozeText": "延期",
    "snoozeByText": "延期:",
    "snoozeAllText": "全部延期",
    "showCalendarText": "顯示行事曆"
});