define("Sage/MainView/EntityMgr/AddEditEntityDetail/nls/ru/AddEditDialog", {
    "dialogTitleAddField": "Добавить поле в сущность \"${0}\"",
    "dialogTitleAddFilter": "Добавить фильтр в сущность \"${0}\"",
    "dialogTitleAddMetric": "Добавить метрику в сущность \"${0}\"",
    "dialogTitleAddRelationship": "Добавить отношение в сущность \"${0}\"",
    "editDialogTitle": "Редактировать \"${0}\" в сущности \"${1}\"",
    "lblFilter": "Фильтр",
    "lblMetric": "Метрика",
    "lblFilters": "Фильтры",
    "lblMetrics": "Метрики",
    "lblDistinct": "Уникальный",
    "lblRange": "Диапазон",
    "lblUserLookup": "Поиск пользователя",
    "lblAdd": "Добавить",
    "lblEdit": "Редактировать",
    "lblRemove": "Удалить",
    "lblHelp": "Справка",
    "lblFilterName": "Имя фильтра",
    "lblMetricName": "Имя метрики",
    "lblDisplayName": "Отображаемое имя",
    "lblName": "Имя",
    "lblDisplay": "Отображение",
    "lblCalculated": "Рассчитано",
    "lblCalculation": "Вычисление",
    "lblDescription": "Описание",
    "lblFieldsName": "Имя поля",
    "lblCalculatedFieldsName": "Имя вычисляемого поля",
    "lblFilterDp": "Поля",
    "lblTypeDp": "Тип",
    "lblCharacter": "Символы",
    "lblFrom": "От",
    "lblTo": "Для",
    "lblOperators": "Операторы",
    "lblAggregation": "Агрегации",
    "lblTypeSpecificContentBox": "Поле данных с учетом типа",
    "lblSaveButton": "OК",
    "lblCancelButton": "Отмена",
    "DateDiffCheckerValue": "Разность между датами метрики",
    "InvalidFilterName": "Неправильное название фильтра",
    "InvalidRangeName": "Неверное имя диапазона",
    "RequiredFilterName": "Требуется имя фильтра",
    "RequiredRangeName": "Требуется имя диапазона",
    "FieldMustBeANumber": "Поле символа должно иметь целочисленное значение",
    "SelectAnItem": "Выберите элемент",
    "ItemRequired": "Требуется элемент",
    "ItemInvalid": "Неверный элемент",
    "LowerMustBeLessThanUpper": "Нижнее значение должно быть меньше верхнего значения.",
    "defaultRangeRowValue": "Введите значение",
    "totalRecordCountLabel": "Всего записей: ${0}",
    "lblNew": "Новый",
    "lblExisting": "Существующий",
    "lblExistingCalc": "Сущ. вычисляемое поле",
    "validNameMsg": "Допустимая запись должна начинаться с заглавной буквы и <br> может содержать буквы, цифры и символы подчеркивания.",
    "propertyName": "Имя",
    "displayName": "Отображение",
    "dataTypeId": "Тип",
    "dataTypeData": "Атрибуты типа",
    "length": "Длина",
    "scale": "Шкала",
    "precision": "Точность",
    "isIncluded": "Включено",
    "isReadOnly": "Только для чтения",
    "displayCategory": "Показать категорию",
    "sdata": "Sdata",
    "bulkAction": "Массовое действие",
    "canBulkUpdate": "Разрешено массовое обновление",
    "canImport": "Импорт",
    "canMatch": "Соответствие",
    "generate": "Сгенерировать",
    "audited": "Аудит выполнен",
    "notUniqueFor": "не уникально для",
    "notUnique": "не является уникальным",
    "nlsCode": "Код NLS",
    "nlsName": "Имя NLS",
    "showTranslations": "Показать переводы",
    "hideTranslations": "Скрыть переводы",
    "standardIds": "Стандартные ИД",
    "others": "Другие",
    "SelectField": "Выберите поле!",
    "SelectOneField": "Выберите только одно поле!",
    "parent": "Родительская сущность и связываемое поле",
    "child": "Дочерняя сущность и связываемое поле",
    "cardinality": "Отношение",
    "cascade": "Каскад",
    "includeParent": "Включить свойство родительского отношения в дочернюю сущность",
    "includeChild": "Включить свойство дочернего отношения в родительскую сущность",
    "existingRelaton": "Это отношение уже существует!"
});