define(
"dojo/cldr/nls/fa/currency", //begin v1.x content
{
	"COP_displayName": "پزوی کلمبیا",
	"CZK_displayName": "کورونای جمهوری چک",
	"TND_displayName": "دینار تونس",
	"EUR_symbol": "€",
	"CAD_symbol": "$CA",
	"JMD_displayName": "دلار جامائیکا",
	"PHP_displayName": "پزوی فیلیپین",
	"ALL_displayName": "لک آلبانی",
	"USD_symbol": "$",
	"LBP_displayName": "لیرهٔ لبنان",
	"VND_displayName": "دانگ ویتنام",
	"LYD_displayName": "دینار لیبی",
	"AFN_symbol": "؋",
	"RON_displayName": "لئوی رومانی",
	"MKD_displayName": "دینار مقدونیه",
	"SEK_displayName": "کرون سوئد",
	"CNY_displayName": "یوآن چین",
	"IDR_displayName": "روپیهٔ اندونزی",
	"ILS_displayName": "شقل جدید اسرائیل",
	"YER_displayName": "ریال یمن",
	"TJS_displayName": "سامانی تاجیکستان",
	"TTD_displayName": "دلار ترینیداد و توباگو",
	"CNY_symbol": "¥CN",
	"TRY_displayName": "لیرهٔ ترکیه",
	"EUR_displayName": "یورو",
	"AED_displayName": "درهم امارات متحدهٔ عربی",
	"KZT_displayName": "تنگهٔ قزاقستان",
	"BHD_displayName": "دینار بحرین",
	"RUB_displayName": "روبل روسیه",
	"NZD_displayName": "دلار زلاند نو",
	"IQD_displayName": "دینار عراق",
	"TMT_displayName": "منات ترکمنستان",
	"ZWL_displayName": "دلار زیمبابوه (۲۰۰۹)",
	"INR_symbol": "₹",
	"KGS_displayName": "سوم قرقیزستان",
	"KWD_displayName": "دینار کویت",
	"AFN_displayName": "افغانی افغانستان",
	"ARS_displayName": "پزوی آرژانتین",
	"MAD_displayName": "درهم مراکش",
	"BAM_displayName": "مارک تبدیلپذیر بوسنی و هرزگوین",
	"BOB_displayName": "بولیویانوی بولیوی",
	"BND_displayName": "دلار برونئی",
	"SGD_displayName": "دلار سنگاپور",
	"MVR_displayName": "روپیهٔ مالدیو",
	"MXN_displayName": "پزوی مکزیک",
	"IRR_symbol": "ریال",
	"DZD_displayName": "دینار الجزایر",
	"MXN_symbol": "$MX",
	"JOD_displayName": "دینار اردن",
	"PEN_displayName": "نوئووسول پرو",
	"GTQ_displayName": "کتزال گواتمالا",
	"BYR_displayName": "روبل بیلوروسی",
	"CAD_displayName": "دلار کانادا",
	"BZD_displayName": "دلار بلیز",
	"CLP_displayName": "پزوی شیلی",
	"XOF_displayName": "فرانک CFA غرب آفریقا",
	"NOK_displayName": "کرون نروژ",
	"DOP_displayName": "پزوی جمهوری دومینیکن",
	"JPY_symbol": "¥",
	"KRW_displayName": "وون کرهٔ جنوبی",
	"USD_displayName": "دلار امریکا",
	"UYU_displayName": "پزوی اوروگوئه",
	"UZS_displayName": "سوم ازبکستان",
	"XOF_symbol": "CFA",
	"QAR_displayName": "ریال قطر",
	"SAR_displayName": "ریال سعودی",
	"SYP_displayName": "لیرهٔ سوریه",
	"NZD_symbol": "$NZ",
	"EGP_displayName": "لیرهٔ مصر",
	"AMD_displayName": "درم ارمنستان",
	"GBP_displayName": "پوند بریتانیا",
	"HUF_displayName": "فورینت مجارستان",
	"CSD_displayName": "دینار صربستان (۲۰۰۲ تا ۲۰۰۶)",
	"ISK_displayName": "کرونای ایسلند",
	"IRR_displayName": "ریال ایران",
	"OMR_displayName": "ریال عمان",
	"TWD_displayName": "دلار جدید تایوان",
	"PAB_displayName": "بالبوای پاناما",
	"UAH_displayName": "هریونیای اوکراین",
	"ETB_displayName": "بیر اتیوپی",
	"PLN_displayName": "زواتی لهستان",
	"VEF_displayName": "بولیوار ونزوئلا",
	"ILS_symbol": "₪",
	"BRL_displayName": "رئال برزیل",
	"HKD_symbol": "$HK",
	"HKD_displayName": "دلار هنگکنگ",
	"NIO_displayName": "کوردوبای نیکاراگوئه",
	"THB_symbol": "฿",
	"NPR_displayName": "روپیهٔ نپال",
	"PKR_displayName": "روپیهٔ پاکستان",
	"GEL_displayName": "لاری گرجستان",
	"AZN_displayName": "منات جمهوری آذربایجان",
	"GBP_symbol": "£",
	"MYR_displayName": "رینگیت مالزی",
	"DKK_displayName": "کرون دانمارک",
	"THB_displayName": "بات تایلند",
	"JPY_displayName": "ین ژاپن",
	"KES_displayName": "شیلینگ کنیا",
	"KHR_displayName": "رییل کامبوج",
	"PYG_displayName": "گوارانی پاراگوئه",
	"VND_symbol": "₫",
	"LKR_displayName": "روپیهٔ سریلانکا",
	"BGN_displayName": "لف بلغارستان",
	"BDT_displayName": "تاکای بنگلادش",
	"MOP_displayName": "پاتاکای ماکائو",
	"HNL_displayName": "لمپیرای هندوراس",
	"RWF_displayName": "فرانک رواندا",
	"CHF_displayName": "فرانک سوئیس",
	"CRC_displayName": "کولون کاستاریکا",
	"INR_displayName": "روپیهٔ هند",
	"KRW_symbol": "₩",
	"ZAR_displayName": "راند افریقای جنوبی",
	"AUD_displayName": "دلار استرالیا",
	"LAK_displayName": "کیپ لائوس",
	"MNT_displayName": "توگریک مغولستان",
	"RSD_displayName": "دینار صربستان",
	"HRK_displayName": "کونای کرواسی"
}
//end v1.x content
);