define("Sage/UI/Controls/nls/it/FieldAttributeControlFactory", {
    "IsEncrypted": "Crittografato",
    "Length": "Lunghezza",
    "Precision": "Precisione",
    "Scale": "Scala",
    "LookupEntityName": "Ricerca nome entità",
    "LookupGroup": "Gruppo di ricerca",
    "IsPercentage": "Percentuale",
    "Items": "Elementi",
    "MultiSelect": "Selezione multipla",
    "OverriddenName": "Nome sovrascritto",
    "Storage": "Archiviazione",
    "EnableHyperLinking": "Attiva collegamento ipertestuale",
    "LookupPreFilters": "Filtri ricerca",
    "EqualTo": "Uguale a",
    "NotEqualTo": "Diverso da",
    "GreaterThanOrEqual": "Maggiore di o uguale",
    "GreaterThan": "Maggiore di",
    "LessThanOrEqual": "Minore o uguale a",
    "LessThan": "Minore di",
    "CondOperator": "Operatore condizionale",
    "FilterValue": "Valore filtro",
    "PropertyName": "Nome proprietà",
    "LookupProperties": "Proprietà ricerca",
    "ExcludeFromFilters": "Escludi dai filtri",
    "HideCondition": "Nascondi condizione",
    "IsSortable": "Ordinabile",
    "PropertyFormat": "Formato proprietà",
    "None": "Nessuno",
    "Phone": "Telefono",
    "User": "Utente",
    "PickList": "Elenco di selezione",
    "DateTime": "Data e ora",
    "PropertyFormatString": "Stringa di formato proprietà",
    "PropertyHeader": "Intestazione proprietà",
    "PropertyType": "Tipo proprietà",
    "UseAsResult": "Usa come risultato",
    "ReturnPrimaryKey": "Chiave primaria risultati",
    "AllowMultiples": "Consenti multipli",
    "AlphaSort": "In ordine alfabetico",
    "MustExistInList": "Deve esistere nell'elenco",
    "NoneEditable": "Nessuna voce modificabile",
    "PickListFilter": "Filtro elenco di selezione",
    "ValueStoredAsText": "Valore memorizzato come testo",
    "Value": "Valore",
    "Display": "Visualizza",
    "Code": "Codice",
    "Name": "Nome",
    "DisplayName": "Nome visualizzato",
    "Template": "Calcolo",
    "Description": "Descrizione",
    "SortOrder": "Criterio di ordinamento",
    "lblNoFieldsInTemplate": "Aggiungere una proprietà entità al modello prima di applicare un ordinamento.",
    "AddField": "Aggiungi campo",
    "InUse": "In uso",
    "NotInUse": "Non in uso",
    "CalculatedNumberInputError": "<p>Le immissioni sono limitate ai nomi di campo selezionati dal menu a discesa<br/>e ai seguenti caratteri:<br/>&nbsp;&nbsp;&nbsp;&nbsp;'+','-','*','/','(', oppure ')’.<br/>&nbsp;&nbsp;&nbsp;&nbsp;Tali caratteri corrispondono ai valori dei pulsanti al di sopra dell'area di testo.</p>",
    "newPickList": "Nuovo elenco di selezione",
    "add": "aggiungi",
    "substract": "sottrai",
    "multiply": "moltiplica",
    "divide": "dividi",
    "openParens": "parentesi di apertura",
    "closeParens": "parentesi di chiusura"
});