define("Sage/UI/Controls/nls/it/PropertyStore", {
    "text": "Testo",
    "memo": "Memo",
    "unicodeText": "Testo Unicode",
    "unicodeMemo": "Memo Unicode",
    "integer": "Intero",
    "double": "Doppio",
    "single": "Singolo",
    "decimal": "Decimale",
    "short": "Breve",
    "standardId": "ID standard",
    "trueFalse": "Vero/Falso",
    "yesNo": "Sì/No",
    "boolean": "Booleano",
    "dateTime": "Data/ora",
    "email": "E-mail",
    "phone": "Telefono",
    "pickList": "Elenco di selezione",
    "owner": "Proprietario",
    "lookup": "Ricerca",
    "dependencyLookup": "Ricerca dipendenze",
    "char": "Carattere",
    "enum_": "Enumerazione",
    "guid": "Guid",
    "byte": "Byte",
    "binary": "Binario",
    "url": "URL",
    "string": "Stringa",
    "number": "Numero",
    "calc": "Campo calcolato",
    "calcSF": "Stringa calcolata",
    "calcNF": "Numero calcolato"
});