define("Sage/UI/Forms/nls/de/FormFromSData", {
    "addText": "Hinzufügen",
    "deleteText": "Löschen",
    "saveText": "Speichern",
    "cancelText": "Abbrechen",
    "editText": "Bearbeiten",
    "helpText": "Hilfe",
    "yesText": "Ja",
    "noText": "Nein",
    "okText": "OK",
    "newPickList": "Neue Auswahlliste",
    "items": "Auswahllistenelemente",
    "number": "Reihenfolge",
    "enterValue": "Wert eingeben",
    "lblMore": "Weitere",
    "picklistAlreadyExists": "Picklist '${0}' ist bereits vorhanden.",
    "messageOnSave": "Auswahlliste ${0} wurde gespeichert. Fahren Sie mit dem Hinzufügen oder Bearbeiten der Feldinformationen fort.",
    "permissionsToView": "Sie haben nicht die erforderlichen Berechtigungen zur Anzeige.",
    "required": "Erforderlicher Eintrag",
    "allowMultiples": "Mehrfachauswahl zulassen",
    "valueMustExist": "Text muss mit einem Listenelement übereinstimmen",
    "alphaSorted": "Alphabetisch sortiert",
    "noneEditable": "Benutzer können Einträge nicht bearbeiten"
});