define("Sage/MainView/ActivityMgr/nls/fr/RecurringEditor", {
    "activityOccurrsText": "Cette activité se produit…",
    "onceText": "Une fois",
    "dailyText": "Chaque jour",
    "weeklyText": "Chaque semaine",
    "monthlyText": "Chaque mois",
    "yearlyText": "Chaque année",
    "occursOnceText": "Cette activité ne se produit qu'une seule fois",
    "everyText": "Chaque",
    "daysText": "Jour(s)",
    "daysAfterText": "Jour(s) après la fin",
    "startRecurringText": "Démarrer la périodicité : ",
    "endAfterText": "Terminer après",
    "endOnText": "Terminer la périodicité",
    "occurrencesText": "occurrences",
    "weeksOnText": "Semaine(s) le",
    "monText": "Lundi",
    "tueText": "Mardi",
    "wedText": "Mercredi",
    "thurText": "Jeudi",
    "friText": "Vendredi",
    "satText": "Samedi",
    "sunText": "Dimanche",
    "weeksAfterText": "Semaine(s) après la fin",
    "monthsOnText": "Mois le",
    "monthsOnTheText": "Mois le",
    "monthsAfterText": "Moi(s) après la fin",
    "firstText": "1er",
    "secondText": "2e",
    "thirdText": "3e",
    "fourthText": "4e",
    "lastText": "Dernier",
    "yearsOnText": "Année(s) le",
    "yearsAfterText": "Année(s) après la fin",
    "janText": "Janvier",
    "febText": "Février",
    "marText": "Mars",
    "aprText": "Avril",
    "mayText": "Mai",
    "junText": "Juin",
    "julText": "Juillet",
    "augText": "Août",
    "sepText": "Septembre",
    "octText": "Octobre",
    "novText": "Novembre",
    "decText": "Décembre",
    "theText": "Le",
    "inText": "de"
});