define("Sage/UI/Controls/nls/zh-cn/PropertyStore", {
    "text": "文本",
    "memo": "备忘录",
    "unicodeText": "Unicode 文本",
    "unicodeMemo": "Unicode 备忘录",
    "integer": "整数",
    "double": "双精度",
    "single": "单精度",
    "decimal": "小数",
    "short": "短",
    "standardId": "标准 ID",
    "trueFalse": "真/假",
    "yesNo": "是/否",
    "boolean": "布尔值",
    "dateTime": "日期/时间",
    "email": "电子邮件",
    "phone": "电话",
    "pickList": "选择列表",
    "owner": "所有者",
    "lookup": "查找",
    "dependencyLookup": "依赖关系查找",
    "char": "字符",
    "enum_": "枚举",
    "guid": "Guid",
    "byte": "字节",
    "binary": "二进制",
    "url": "URL",
    "string": "字符串",
    "number": "数字",
    "calc": "已计算字段",
    "calcSF": "含计算的字符串",
    "calcNF": "已计算数字"
});