define("Sage/TaskPane/nls/_BaseTaskPaneTasklet", {
    root: {
        selectRecordsTitle: 'Invalid Selection',
        selectRecords: 'Please select a record before continuing.',
        selectSingleRecord: 'Please select a single record before continuing.',
        noRecordsSelectedProcessAll: 'No records selected. The full group will be processed up to the limit (if any) set by your system administrator.  Proceed?',
        invalidSelectionTitle: 'Invalid Selection',
        errorSelectionInfo: 'There was an error retrieving information about the selected records.',
        errorNoData: 'No data available.',
        yesButtonText: 'Yes',
        noButtonText: 'No',
        salesLogixPageTitle: 'Infor CRM',
        okButtonText: 'OK',
        cancelButtonText: 'Cancel',
        confirmBulkDeleteJob: 'Are you sure you want to delete the selected records?',
        deleteSelectedRecords: 'Delete ${0}',
        deleteJobError: 'Sorry an error occurred during the delete ${0} job: ${1}',
        deleteBulkJobTitle: 'Delete ${0}',
        promoteTitle: 'Promote',
        getOrderTotalTitle: 'Get Order Total',
        integrationNotEnabled: 'Back Office Extension is not enabled',
        error_PricingRequest: 'An error occured requesting pricing service: ${0}',
		workflowIntegrationNotEnabled: 'ION Workflow Integration is not enabled',
        requestWorkflowSuccess: "Workflow has been requested.",
        cancelWorkflowSuccess: "Workflow has been cancelled.",
        requestWorkflowLog: "Unable to request workflow. Please refer to the error log for more details.",
        cancelWorkflowLog: "Unable to cancel workflow. Please refer to the error log for more details.",
        errorRequestWorkflow: "An error occurred when ${0} requests workflow: ${1}.",
        errorCancelWorkflow: "An error occurred when ${0} cancels workflow: ${1}."
    },
    "de": true,
    "en": true,
    "fr": true,
    "it": true,
    "ru": true
});
