define(
"dojo/cldr/nls/hr/currency", //begin v1.x content
{
	"COP_displayName": "kolumbijski pezo",
	"CZK_displayName": "češka kruna",
	"TND_displayName": "tuniski dinar",
	"CAD_symbol": "CAD",
	"JMD_displayName": "jamajčanski dolar",
	"PHP_displayName": "filipinski pezo",
	"ALL_displayName": "albanski lek",
	"USD_symbol": "USD",
	"LBP_displayName": "libanonska funta",
	"VND_displayName": "vijetnamski dong",
	"LYD_displayName": "libijski dinar",
	"RON_displayName": "rumunjski leu",
	"MKD_displayName": "makedonski denar",
	"SEK_displayName": "švedska kruna",
	"CNY_displayName": "kineski yuan",
	"IDR_displayName": "indonezijska rupija",
	"ILS_displayName": "novi izraelski šekel",
	"YER_displayName": "jemenski rial",
	"TJS_displayName": "tadžikistanski somoni",
	"TTD_displayName": "trininadtobaški dolar",
	"CNY_symbol": "CNY",
	"TRY_displayName": "turska lira",
	"EUR_displayName": "euro",
	"AED_displayName": "UAE dirham",
	"KZT_displayName": "kazahstanski tenge",
	"HRK_symbol": "kn",
	"BHD_displayName": "bahreinski dinar",
	"RUB_displayName": "ruska rublja",
	"NZD_displayName": "novozelandski dolar",
	"IQD_displayName": "irački dinar",
	"TMT_displayName": "turkmenistanski manat",
	"ZWL_displayName": "zimbabveanski dolar (2009)",
	"INR_symbol": "INR",
	"KGS_displayName": "kirgiski som",
	"KWD_displayName": "kuvajtski dinar",
	"AFN_displayName": "afganistanski afgani",
	"ARS_displayName": "argentinski pezo",
	"MAD_displayName": "marokanski dirham",
	"BAM_displayName": "konvertibilna marka",
	"BOB_displayName": "bolivijski bolivijano",
	"BND_displayName": "brunejski dolar",
	"SGD_displayName": "singapurski dolar",
	"MVR_displayName": "maldivijska rufija",
	"MXN_displayName": "meksički pezo",
	"DZD_displayName": "alžirski dinar",
	"MXN_symbol": "MXN",
	"JOD_displayName": "jordanski dinar",
	"PEN_displayName": "peruanski novi sol",
	"GTQ_displayName": "gvatemalski kvecal",
	"BYR_displayName": "bjeloruska rublja",
	"CAD_displayName": "kanadski dolar",
	"BZD_displayName": "belizeanski dolar",
	"CLP_displayName": "čileanski pezo",
	"XOF_displayName": "CFA franak BCEAO",
	"NOK_displayName": "norveška kruna",
	"DOP_displayName": "dominikanski pezo",
	"JPY_symbol": "¥",
	"KRW_displayName": "južnokorejski won",
	"USD_displayName": "američki dolar",
	"UYU_displayName": "urugvajski pezo",
	"UZS_displayName": "uzbekistanski som",
	"XOF_symbol": "CFA",
	"QAR_displayName": "katarski rial",
	"SAR_displayName": "saudijski rial",
	"SYP_displayName": "sirijska funta",
	"NZD_symbol": "NZD",
	"EGP_displayName": "egipatska funta",
	"AMD_displayName": "armenski dram",
	"GBP_displayName": "britanska funta",
	"HUF_displayName": "mađarska forinta",
	"CSD_displayName": "stari srpski dinar",
	"ISK_displayName": "islandska kruna",
	"IRR_displayName": "iranski rijal",
	"OMR_displayName": "omanski rijal",
	"TWD_displayName": "novotajvanski dolar",
	"PAB_displayName": "panamska balboa",
	"UAH_displayName": "ukrajinska hrivnja",
	"ETB_displayName": "etiopski bir",
	"PLN_displayName": "poljska zlota",
	"VEF_displayName": "venezuelanski bolivar",
	"ILS_symbol": "ILS",
	"AUD_symbol": "AUD",
	"BRL_displayName": "brazilski real",
	"HKD_symbol": "HKD",
	"HKD_displayName": "hongkonški dolar",
	"NIO_displayName": "nikaragvanska zlatna kordoba",
	"THB_symbol": "THB",
	"NPR_displayName": "nepalska rupija",
	"PKR_displayName": "pakistanska rupija",
	"TWD_symbol": "TWD",
	"GEL_displayName": "gruzijski lari",
	"AZN_displayName": "azerbajdžanski manat",
	"GBP_symbol": "GBP",
	"MYR_displayName": "malezijski ringit",
	"DKK_displayName": "danska kruna",
	"THB_displayName": "tajlandski bat",
	"BRL_symbol": "BRL",
	"JPY_displayName": "japanski jen",
	"KES_displayName": "kenijski šiling",
	"KHR_displayName": "kambođanski rijal",
	"PYG_displayName": "gvarani",
	"VND_symbol": "VND",
	"LKR_displayName": "šrilanska rupija",
	"BGN_displayName": "bugarski lev",
	"BDT_displayName": "bangladeška taka",
	"MOP_displayName": "makaoška pataka",
	"HNL_displayName": "honduraška lempira",
	"RWF_displayName": "ruandski franak",
	"CHF_displayName": "švicarski franak",
	"CRC_displayName": "kostarikanski kolon",
	"INR_displayName": "indijska rupija",
	"KRW_symbol": "KRW",
	"ZAR_displayName": "južnoafrički rand",
	"AUD_displayName": "australski dolar",
	"LAK_displayName": "laoski kip",
	"MNT_displayName": "mongolski tugrik",
	"RSD_displayName": "srpski dinar",
	"HRK_displayName": "hrvatska kuna"
}
//end v1.x content
);