define("Sage/MainView/CopyUserProfile/nls/de/CopyUserProfile", {
    "dlg_Title": "Profil kopieren",
    "dlg_Instructions": "Wählen Sie ein Benutzerprofil oder eine Vorlage aus, das/die zu anderen Benutzern kopiert werden soll. Durch das Kopieren des Profils werden die aktuellen Einstellungen überschrieben.",
    "rad_SelectionLabel": "Profil kopieren von:",
    "rad_UserBtn": "Vorhandener Benutzer",
    "rad_TemplateBtn": "Vorlage",
    "user_LookupLabel": "Benutzer",
    "template_LookupLabel": "Vorlage",
    "lookupUserNameColText": "Benutzername",
    "lookupTitleColText": "Titel",
    "lookupDepartmentColText": "Abteilung",
    "lookupRegionColText": "Region",
    "lookupUser_Caption": "Benutzer, dessen Profil kopiert werden soll",
    "lookupUserNameTemplateColText": "Vorlage",
    "chkGeneralLabel": "Allgemein",
    "chkCalendarLabel": "Kalender",
    "chkEmployeeLabel": "Mitarbeiter",
    "chkClientLabel": "Clientoptionen (Clientsystem)",
    "chkSecurityLabel": "Sicherheit",
    "chkServiceLabel": "Service/Support",
    "chkTeamsLabel": "Teams",
    "txtJobDescriptor": "Benutzerprofil kopieren",
    "jobFailer": "Kritischer Fehler"
});