define("Sage/TaskPane/nls/zh-cn/ActivityTaskConfigurationProvider", {
    "scheduleText": "日程安排",
    "eventText": "事件",
    "phoneCallText": "电话呼叫",
    "toDoText": "待办事项",
    "meetingText": "会议",
    "personalActivityText": "个人活动",
    "deleteConfirmationText": "删除确认",
    "acceptConfirmationText": "接受确认",
    "declineConfirmationText": "拒绝确认",
    "completeActivityText": "完成活动",
    "deleteActivityText": "删除活动",
    "deleteEventText": "删除事件",
    "scheduleEventText": "安排事件",
    "scheduleRequestText": "安排申请",
    "deleteRequestText": "删除申请",
    "recordsSelectedText": "个选中的记录",
    "clearText": "清除"
});