define("Sage/TaskPane/nls/zh-cn/CommonTasksTasklet", {
    "okButtonText": "确定",
    "loadingText": "正在加载...",
    "noPrimaryEmail": "没有可用的主电子邮件",
    "selectFileFormat": "选择文件格式:",
    "exportToFile_OptionCSV": "标准 CSV",
    "exportToFile_OptionTab": "制表符分隔(建议用于 Microsoft Excel)",
    "exportToFile_OptionSaveFormat": "记住我的选择，不再询问。",
    "exportToFile_OK": "确定",
    "exportToFile_Cancel": "取消",
    "exportToFile_DialogTitle": "导出",
    "exportToExcel_Caption": "正在导出",
    "errorRequestingJobMgr": "申请作业管理器时出现错误: ${0}",
    "errorExecutionAction": "执行操作“${0}”时出现错误",
    "exportProcessingJobMsg": "正在处理导出，您可以继续等待完成，或者转至报表视图以打开文件。",
    "errorBulkActionNotSupported": "${0} 不支持批量操作更新，请联系系统管理员。",
    "errorBulkActionRequest": "请求批量更新选项时出现错误，请联系系统管理员。",
    "copyProfileNoneSelected": "必须至少选择一个用户!",
    "deleteJob_Description": "出现批量删除错误",
    "errorRequestEntityImportable": "获取实体属性时出现错误。${0}",
    "entityNotImportable": "${0} 不支持导入，请联系系统管理员。"
});