define("Sage/Services/nls/ru/ActivityService", {
    "txtErrorActionMsg": "Не удалось выполнить действие, возникла ошибка.",
    "txtActivity": "действие",
    "txtActivities": "действия",
    "txtActionDeleteActivites": "Удалить действия",
    "txtActionDeleteActivitiesQuestion": "Будут удалены только те действия на которые у вас есть права на удаление. <P> Действительно удалить выбранные \"{1}\" ({0})?",
    "txtAlarm": "оповещение",
    "txtAlarms": "оповещения",
    "txtActionSnoozeAlarm": "Отложить оповещение",
    "txtActionSnoozeQuestion": "Действительно отложить выбранные \"{1}\" ({0}) для \"{2}\"?",
    "txtActionSnoozeAllQuestion": "Действительно отложить все \"{0}\" для \"{1}\"?",
    "txtActionDismissAlarms": "Отклонение оповещений",
    "txtActionDismissAlarmsQuestion": "Действительно отклонить выбранные \"{1}\" ({0})?",
    "txtEvent": "событие",
    "txtEvents": "события",
    "txtActionDeleteEvents": "Удаление событий",
    "txtActionDeleteEventsQuestion": "Будут удалены только те события на которые у вас есть права на удаление. <P> Действительно удалить выбранные \"{1}\" ({0})?",
    "txtConfirmation": "подтверждение",
    "txtConfirmations": "подтверждения",
    "txtActionAcceptConfirmations": "Принять подтверждения",
    "txtActionAcceptConfirmQuestion": "Действительно принять выбранные \"{1}\" ({0})? Это действие распространяется только на новые или измененные подтверждения. Все остальные будут игнорироваться.",
    "txtDeclineConfirmations": "Отклонение подтверждений",
    "txtActionDeclineConfrimQuestion": "Действительно отклонить выбранные \"{1}\" ({0})? Это действие распространяется только на новые или измененные подтверждения. Все остальные будут игнорироваться.",
    "txtActionRemoveConfirmations": "Удалить подтверждения",
    "txtActionRemoveConfirmationsQuestion": "Действительно удалить выбранные \"{1}\" ({0})? Это действие распространяется на ведущие, отклоненные и удаленные подтверждения. Все остальные будут игнорироваться.",
    "txtLiteratureRequest": "запрос литературы",
    "txtLiteratureRequests": "запросы литературы",
    "txtActionDeleteLiteratureRequests": "Удаление запросов литературы",
    "txtActionDeleteLiteratureRequestsQuestion": "Будут удалены только запросы литературы, для которых имеется право на удаление. <P> Действительно удалить выбранные \"{1}\" ({0})?"
});