define("Sage/TaskPane/nls/it/_BaseTaskPaneTasklet", {
    "selectRecordsTitle": "Selezione non valida",
    "selectRecords": "Selezionare un record prima di continuare.",
    "selectSingleRecord": "Selezionare un singolo record prima di continuare.",
    "noRecordsSelectedProcessAll": "Nessun record selezionato. Verrà elaborato l’intero gruppo fino all’eventuale limite impostato dall’amministratore di sistema. Continuare?",
    "invalidSelectionTitle": "Selezione non valida",
    "errorSelectionInfo": "Si è verificato un errore nel recupero delle informazioni sui record selezionati.",
    "errorNoData": "Nessun dato disponibile.",
    "yesButtonText": "Sì",
    "noButtonText": "No",
    "salesLogixPageTitle": "Infor CRM",
    "okButtonText": "OK",
    "cancelButtonText": "Annulla",
    "confirmBulkDeleteJob": "Eliminare i record selezionati?",
    "deleteSelectedRecords": "Elimina ${0}",
    "deleteJobError": "Si è verificato un errore durante l’eliminazione del processo ${0}: ${1}",
    "deleteBulkJobTitle": "Elimina ${0}",
    "promoteTitle": "Integra",
    "getOrderTotalTitle": "Calcola totale ordine",
    "integrationNotEnabled": "Back Office Extension non abilitata",
    "error_PricingRequest": "Si è verificato un errore nella richiesta del servizio prezzi: ${0}"
});